### ISSUE TITLE
`apt-get install telegraf` fails on raspbian

### ISSUE THREAD

**Issue by danxmoran** [influxdata/telegraf#10117]
See original community report at https://github.com/influxdata/influxdb/issues/22889.

It looks like our repo server doesn't have a `Release` file for the `raspbian` OS.

**Comment by powersj** [comment]
Because raspbian is based on Debian, and the fact that the deb packages are literally, all the same, I would encourage users to use `debian` in place of `raspbian`. We had a similar request around Amazon Linux, which is a RHEL-like release. 

There are lots of other Red Hat (e.g. AlmaLinux, Rocky Linux, Amazon Linux, Oracle Linux) and Debian derivatives (e.g. Raspbian, PopOS, Tails, Purism, Kali) that are not in the repo, but I do not think it makes sense to add them all. It results in greater complexity, trying to keep up with each distro release, more time on releases, and leads to the allusion that we are making special packages for each distribution, when we are not.

I would prefer if we tackled https://github.com/influxdata/repos/issues/72 to create more simple repo URLs that are generic and apply to all derivatives.

**Comment by codeByKochs** [comment]
@danxmoran 
For me it worked downloading and installing https://repos.influxdata.com/debian/pool/stable/t/telegraf/telegraf_1.20.4-1_armhf.deb using a RPi 4 with raspbian lite.

@powersj 
Shouldn't the documentation be updated then? As someone new to this it took me a good amount of time to figure this out.

**Comment by powersj** [comment]
@codeByKochs yeah we could tell folks to use the generic `debian`. Which specific docs were you looking at? I only ask since this is in at least 3 different places and I want to be sure I hit them all.

**Comment by codeByKochs** [comment]
I was trying to follow [this guide](https://docs.influxdata.com/telegraf/v1.20/introduction/installation/#ubuntu--debian).

**Comment by powersj** [comment]
Following up on this, we are working on a more generic structure to the repo. When that is released these docs will get updated to that to prevent the need to have every single possible distro and release.

Thanks!

**Comment by mikeblas** [comment]
@powersj   Any time soon?

**Comment by powersj** [comment]
> @powersj Any time soon?

If you look at the README there is a generic set of instructions already there
