### ISSUE TITLE
[inputs.prometheus] is rewriting GET query options

### ISSUE THREAD

**Issue by osd42** [influxdata/telegraf#10118]
### Relevent telegraf.conf

```toml
[[inputs.prometheus]]
  ## An array of urls to scrape metrics from.
  urls = ["http://127.0.0.1:9115/probe?debug=false&module=ssh_banner&target=sftp.mydomain.com:22"]
```

### System info

Telegraf 1.20.2, debian 10.10

### Steps to reproduce

1. launch a blackbox_exporter exporter on localhost
2. curl query it on the endpoint you need to scrape prometheus formated data from
`curl "http://127.0.0.1:9115/probe?debug=false&module=ssh_banner&target=sftp.mydomain.com:22"`
* replace "mydomain" with any ssh server you know"
returns : 
![image](https://user-images.githubusercontent.com/49947845/142234317-0f468ff7-1483-44bd-ad16-7105ed62f159.png)

3. Test the collection via telegraf
`telegraf --config telegraf.conf --test`

...

### Expected behavior

Data should be read by telegraf (like any other prometheus like exporter)

### Actual behavior

The "urls" are rewritten and telegraf cannot hit my API : 

`2021-11-17T15:43:40Z I! Starting Telegraf 1.20.2
> probe_ip_addr_hash,host=frvspltn3-10117,url=http://127.0.0.1:9115/probe?debug\=false&module\=ssh_banner&target\=sftp.mydomain.com:22 gauge=3115204225 1637163821000000000
> probe_ip_protocol,host=frvspltn3-10117,url=http://127.0.0.1:9115/probe?debug\=false&module\=ssh_banner&target\=sftp.mydomain.com:22 gauge=4 1637163821000000000
> probe_success,host=frvspltn3-10117,url=http://127.0.0.1:9115/probe?debug\=false&module\=ssh_banner&target\=sftp.mydomain.com:22 gauge=1 1637163821000000000
> probe_dns_lookup_time_seconds,host=frvspltn3-10117,url=http://127.0.0.1:9115/probe?debug\=false&module\=ssh_banner&target\=sftp.mydomain.com:22 gauge=0.002586587 1637163821000000000
> probe_duration_seconds,host=frvspltn3-10117,url=http://127.0.0.1:9115/probe?debug\=false&module\=ssh_banner&target\=sftp.mydomain.com:22 gauge=0.036449695 1637163821000000000
> probe_failed_due_to_regex,host=frvspltn3-10117,url=http://127.0.0.1:9115/probe?debug\=false&module\=ssh_banner&target\=sftp.mydomain.com:22 gauge=0 1637163821000000000
`

"=" is replaced by "\\=" + the measurement field "probe_failed_due_to_regex" seems to mean the URL is badly (re)written.

**Comment by powersj** [comment]
Hi,

`probe_failed_due_to_regex` is a valid measurement and not an error message. The measurement has the value of 0 in the screenshot and in your results from Telegraf. In fact, all your results are returning gauges with the value from the above screenshots.

The reason the URL has the `=` escaped, is because otherwise the Influx Line Protocol an `=` is used between keys and values. It needs to be escaped, similar to a `,`.

Is there some other error you are pointing out? Also if Telegraf was erroring it would produce a log message with an error message. So showing the full logs if there is an error would help.

**Comment by osd42** [comment]
Hi, thank you for the answer ! My bad, now I understand why the url changed ! Everything is good !

Thanks a lot for your work !
