### ISSUE TITLE
Adding the option to overwriting default tags and metadata with row data

### ISSUE THREAD

**Issue by etycomputer** [influxdata/telegraf#10219]
## Feature Request

The current CSV parser overwrites the row tag data when a default tag or metadata with the same tag name is defined.
This feature introduces options to choose the overwrite priority.
`rows_overwrite_default_tags` = true/false with the current behavior being the default (false). 
`rows_overwrite_metadata_tags` = true/false with the current behavior being the default (false).

**Comment by Hipska** [comment]
Wouldn't it be better to have just 1 option to enable/disable? `rows_overwrite_tags` and default being `false` (current behaviour)

**Comment by srebhan** [comment]
I agree with @Hipska. Maybe `prioritize_default_tags` (default: `true`) or similar to just give the global prio-order...

**Comment by etycomputer** [comment]
Hi @srebhan and @Hipska,
Thank you for your feedback. I am happy to only have one option.
Just to make sure we are all on the same page:
The current state of the code parses the rows and finds the tags,
1- If the tag name is the same as the metadata, the value will overwrite the data collected from the CSV row.
2- If the default tag name is the same as the metadata or the row, the default tag value will overwrite both the CSV row and metadata.
With the `prioritize_default_tags` option  (default: true) you have the option to prioritize the metadata or row data (2)
If we add the `prioritize_metadata` option (default: true) you can add the option of prioritizing row data (1)

For example, assuming we have the following:
default tag: 
Device Type: Not Connected

```
Version: 1.1
Device Type: Wired
Time Stamp,Device Type,X,Y,Z,Status
2020-09-07T14:49:53+09:30,Wireless,894.72,496.78,40.70,1
```

If we only have one option:
1- `prioritize_default_tags=true`
device_status,Device\ Type=Not\ Connected,Version=1.1 Time\ Stamp="2020-07-29T11:29:36+09:30",Status=1i,X=894.72,Y=496.78,Z=40.70 1637184018358230900
2- `prioritize_default_tags=false`
device_status,Device\ Type=Wired,Version=1.1 Time\ Stamp="2020-07-29T11:29:36+09:30",Status=1i,X=894.72,Y=496.78,Z=40.70 1637184018358230900

If we have two priority options:
1- `prioritize_default_tags=true` & `prioritize_metadata=true/false`
device_status,Device\ Type=Not\ Connected,Version=1.1 Time\ Stamp="2020-07-29T11:29:36+09:30",Status=1i,X=894.72,Y=496.78,Z=40.70 1637184018358230900
2- `prioritize_default_tags=false` & `prioritize_metadata=true`
device_status,Device\ Type=Wired,Version=1.1 Time\ Stamp="2020-07-29T11:29:36+09:30",Status=1i,X=894.72,Y=496.78,Z=40.70 1637184018358230900
3- `prioritize_default_tags=false` & `prioritize_metadata=false`
device_status,Device\ Type=Wireless,Version=1.1 Time\ Stamp="2020-07-29T11:29:36+09:30",Status=1i,X=894.72,Y=496.78,Z=40.70 1637184018358230900

Do you still recommend having the one option?
We could also have one flag but three states to choose from?

Kind regards,
Ehsan

**Comment by srebhan** [comment]
@etycomputer I think you misunderstood my proposal (maybe due to the suboptimal option naming)...
For the same tag name we currently have: `row` will be overwritten by `metadata` will be overwritten by `default`. I.e. for all three having the same tag _name_ the `default` value will eventually set the final value. With the new option (maybe `prioritize_low_level_tags = false`) this should **still be the case**.

If setting the option to the opposite value (e.g. `prioritize_low_level_tags = true`) we want the following behavior:
`default` will be overwritten by `metadata` will be overwritten by `row`.

I agree that the option naming is difficult, so maybe `tag_priority = "top-down"` and `tag_priority = "bottom-up"` is better? I want to avoid having two options and the permutations thereof.

**Comment by etycomputer** [comment]
That all sounds good to me. Let's do it. I will probably work on that after the main branch is in master.

**Comment by Hipska** [comment]
Since I'm going to need this feature, I'm going to implement this.

What is the preferred option name?

1. `csv_rows_overwrite_tags` default `false`
2. `csv_prioritize_default_tags` default `true`
3. `csv_prioritize_low_level_tags` default `false`
4. `csv_tag_priority` default `"top-down"`
5. `csv_tag_overwrite` default `false`

I'm in favour of 4 or 5 as they can then go in the docs just after the existing `csv_tag_columns`. Option 4 might be too complicated to explain which option does what.
