### ISSUE TITLE
Disk input is broken when /proc is mounted with hidepid=2 and telegraf running as non-root

### ISSUE THREAD

**Issue by rikvdh** [influxdata/telegraf#10357]
### Relevent telegraf.conf

```toml
[[inputs.disk]]
    mount_points = [ "/" ]
```

### Logs from Telegraf

telegraf[23083]: 2021-12-30T12:17:50Z E! [inputs.disk] Error in plugin: error getting disk usage info: open /proc/1/mounts: no such file or directory

### System info

Debian 11

### Steps to reproduce

1. mount -o remount,hidepid=2 /proc
2. diskinfo is gone

### Expected behavior

Diskinfo

### Actual behavior

No disk-info

### Additional info

See https://github.com/shirou/gopsutil/issues/1212

**Comment by powersj** [comment]
Per the attached bug it looks like we should update gopsutil once https://github.com/shirou/gopsutil/issues/1159 is updated?

**Comment by cbos** [comment]
@rikvdh / @powersj 
We face the same issue.
We applied the CIS Hardening rules by running https://github.com/dev-sec/ansible-collection-hardening
Due to that hidepid is now applied. Since that moment the disk info about disk usage is not available anymore.
hidepid is a common security measure, see https://linux-audit.com/linux-system-hardening-adding-hidepid-to-proc/ for more info.

In the troubleshouting section of the disk plugin (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/disk#troubleshooting) there is described to test this:
`sudo -u telegraf cat /proc/self/mounts` and that works fine.

So using /proc/self instead of /proc/1 would solve the problem.

**Comment by powersj** [comment]
@cbos my suggestion is to add these types of comments on the upstream library's issue and help push that along. Then Telegraf can consume the fix.

**Comment by powersj** [comment]
Hi,

The upstream issue was merged and closed. We have definitely updated telegraf's gopsutil since then, is this still an issue?

**Comment by cbos** [comment]
@powersj 
It is quite a while ago. I am no longer working on the project we faced this problem.
I can remember I used an unleased build of Telegraf for these type of problems and that fixed my problem at that time, but I cannot remember if that was exactly about this problem.

**Comment by powersj** [comment]
@cbos - thanks for following up, I really appreciate it.

I will let the original reporter chime as well, otherwise this will close in a couple weeks. If it is still an issue, someone should feel free to file an new issue using the latest telegraf with their logs.
