### ISSUE TITLE
Docker input incompatible with Docker engine 20.10.7 on Windows

### ISSUE THREAD

**Issue by kerams** [influxdata/telegraf#10380]
### Relevent telegraf.conf

```toml
[[inputs.docker]]
  endpoint = "tcp://localhost:2375"
```

### Logs from Telegraf

2022-01-05T08:37:20Z E! [inputs.docker] Error in plugin: Error response from daemon: client version 1.21 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

### System info

Telegraf 1.21.1, Windows Server 2019 17763.2213

### Docker

Engine version 20.10.7

### Steps to reproduce

Run the Docker engine on Windows with _Windows_ container support, and enable daemon access via TLS on 2375.
On the same machine run Telegraf with the Docker input plugin pointing to tcp://localhost:2375.

### Expected behavior

Docker metrics are collected.

### Actual behavior

Telegraf cannot connect to the engine because of minimal API version mismatch.

### Additional info

Everything works when the engine is set to the Linux container mode, but that does not really help me since it's the Windows containers I want to monitor.

**Comment by powersj** [comment]
I am a little surprised given we were only two small releases behind on the github.com/docker/docker. We were on v20.10.9 and v20.10.10 and v20.10.11 came out, both with no comments about the client.

Looking some more I found https://github.com/influxdata/telegraf/issues/4666 which looks to be identical to the issue here.

I have put up https://github.com/influxdata/telegraf/pull/10382 which updates to the latest docker and increases the stated API version used. Once artifacts are generated for this PR, can you please try one of those and let us know if it resolves the issue?

Thanks!

**Comment by kerams** [comment]
Much obliged, I'll give it a shot tomorrow. By the way, I see you updated the API version all the way to the latest 1.41. Won't that break the plugin for people who run Docker that is just more than 12 months old? Maybe 1.24 would be the safest bet, but who knows what Microsoft will be up to soon :).

**Comment by powersj** [comment]
Agreed on the version change. My understanding is Docker maintains backward API compatibility, but does deprecate and remove features over time. That might be a good reason to move it only up to 1.24, but then I wonder how much time that buys us.

I guess bumping it up from 1.21 to 1.24 isn't too big of a leap. Let me update the PR with that for now and you can let me know if that works.

**Comment by kerams** [comment]
@powersj, can confirm the metrics are now collected, no errors or warnings in the logs.

**Comment by powersj** [comment]
awesome, thank you for trying that out!
