### ISSUE TITLE
Feature Request - Add CPU count to cpu input

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/telegraf#1041]
Adding a CPU count (the number of CPU's on the system) to the `cpu` (or maybe `system`) input would be very helpful when alerting based on system load.

**Comment by sparrc** [comment]
will do 👍

**Comment by eduser25** [comment]
Guys, I think this implementation is wrong. NumCPU is, defined by go, `NumCPU returns the number of logical CPUs usable by the current process.`

This is NOT the number of CPUs a system may have.

**Comment by jdmaloney** [comment]
How hard would this be to add to the cpu input?  I'm trying to figure out how many cores are being used in a given host so I'd like to be able to do usage_user * n_cpu to get that value.  With them being in different measurements that isn't possible (without Flux).

**Comment by oserde** [comment]
Hi @eduser25 . This behavior was updated in #6214 .

**Comment by danielnelson** [comment]
@jdmaloney You may want to turn on `totalcpu = true`.

**Comment by jdmaloney** [comment]
@danielnelson I do have that enabled on the system, however if I look at top on a compute node I see the job process is using ~2600% CPU (almost 26 cores), but looking at what I see from the cpu plugin I only get percentages that add up to 100.  I don't have a way to tell how many CPU's on a node are engaged from the information in either cpu or system individually.  I can from info in both, but I can't multiply n_cpu from the system plugin with usage_user from the cpu plugin since they're in different measurements.  Maybe a config parameter that shows aggregate cpu utilization % instead of the average across the cpus?  Not sure if that's easier than adding the n_cpu value to the cpu input.
<img width="834" alt="Screen Shot 2020-05-20 at 8 18 29 PM" src="https://user-images.githubusercontent.com/16138910/82513191-e0e56e80-9ad7-11ea-94b7-dd497312eb5c.png">
<img width="1378" alt="Screen Shot 2020-05-20 at 8 18 45 PM" src="https://user-images.githubusercontent.com/16138910/82513196-e2af3200-9ad7-11ea-8c17-197cf95c6582.png">

**Comment by danielnelson** [comment]
I might still not be fully understanding, sorry about that ahead of time.  If you want something similar to what top is showing here enable `report_active = true` and then `select sum(usage_active) from cpu group by time(10s)`.
