### ISSUE TITLE
Include Field pivoting in MQTT topic parsing

### ISSUE THREAD

**Issue by samhld** [influxdata/telegraf#10712]
Say I have a list of topics like the below:
```
/sensors/CLE/v1/device5/temp
/sensors/CLE/v1/device5/rpm
/sensors/CLE/v1/device5/ph
/sensors/CLE/v1/device5/spin
```

Each of these topics contains payloads of single raw numerical values like `1.0` or `45900`. Each of these topics map to single series in InfluxDB and would create their own line of LP ("metric" in Telegraf).

Current behavior here would be to use the MQTT consumer plugin with topic parsing configured...plus the Pivot processor.

This would look like:
```
[[inputs.mqtt_consumer]]
    ....
    topics = "/sensors/#"
    [[inputs.mqtt_consumer.topic_parsing]]
        measurement = "/measurement/_/_/_/_"
        tags = "/_/site/version/device_name/_"
        fields = "/_/_/_/_/field"
[[processors.pivot]]
    tag_key = "field"
    value_key = "value"
```

Pivoting is required here because the notation "/_/_/_/_/field" tells Telegraf that the key name is actually a Tag of name of "field". This defaults to setting the value contained in the payload to a Field named "value" (name of the Field key).

This is an okay workaround but an unofficial goal of this consumer plugin was to comprehensively support MQTT topic cases, at least where possible...and that includes this fairly common case where raw values are contained in granular per-metric topics.

I propose we change the behavior of the `fields` parameter to do the pivoting. Almost all topics will have at most one field included in the topic name like the examples above.

Instead of the above configuration telling Telegraf to make a Tag that helps identify what the contained field is, creating distinct lines like:
```
sensors,site=CLE,version=v1,device_name=device5,field=temp value=390
sensors,site=CLE,version=v1,device_name=device5,field=rpm value=45.0
sensors,site=CLE,version=v1,device_name=device5,field=ph value=1.45
...
```
The notation would instead tell Telegraf what position to find fields. The text in that position would be the field key and the value contained in the payload would then be the value to that key. This would result in the below:
```
sensors,site=CLE,version=v1,device_name=device5 temp=390,rpm=45.0,ph=1.45
```

**Comment by srebhan** [comment]
TBH, you make a lot of assumptions here... The foremost is that all those topics are updated _simultaneously_, which is _never_ the case in event-based communication. So we would need to "wait" for all messages to arrive etc. Not sure if this is a good idea actually...

**Comment by fietser28** [comment]
Changing the behaviour of the `field` parameter will disrupt another functionality: values are encoded in (part) of the MQTT topic and you want this to be fields.  

Therefore I think it would be better to add a parameter 'message' or 'value' where you can specify the name of the value you want the MQTT message to be in. This would eliminate the need for a pivot processor step.
Fancy implementation/option: Allow the value to be a combination of elements (see example).

Additionally I think a 'value_parsing.type' section somewhat analog to the 'topic_parsing.types' would be very useful: In my experience not al topics are the same type, handling this in a simple format is very useful. In one of my cases I now use seperate convert processors to achieve this with several error prone pass/drop statements to achieve filtering/ordering.
In the example I showed the order of string, int, float matters: First one matches. This allows for a easy filtering of a common IOT case were (like the example) where most values are a specific type but some are different.

Example:

MQTT topics + message:
```
 Topic                       Message
 /sensors/CLE/v1/device5/temp1 21.0
 /sensors/CLE/v1/device5/temp2 21.0
 /sensors/CLE/v1/device5/rpm     100
 /sensors/CLE/v1/device5/ph       7.0
 /sensors/CLE/v1/device5/spin1   1
 /sensors/CLE/v1/device5/spin2  13
 /sensors/CLE/v1/device5/status "OK"
 /sensors/CLE/v1/device5/log      "INFO: happy"

```

Config example:
```
[[inputs.mqtt_consumer.topic_parsing]]
    topic = "/sensors/+/v1/+/+"
    measurement = "/measurement/_/_/_/_"
    tags = "_/site/version/device_name/_"
    values = "_/_/_/_/firstvalue"
    value = "firstvalue"
    [inputs.mqtt_consumer.value_parsing.types] 
      string = [ "status", "log" ]
      int = ["spin*]
      float = ["*"]         # Meaning the order of these matter: First match assigns type.

```
where:
'values' specifies the pattern to select parts of the topic
'value' specifies the name of the field where selections from values can be used.

Resulting in:
'''
sensors,site=CLE,version=v1,device_name=device5,field=temp1 value=21.0   (float)
sensors,site=CLE,version=v1,device_name=device5,field=spin2 value=100i    (int)
sensors,site=CLE,version=v1,device_name=device5,field=status value="OK"  (string)
...
'''

PS:
`    #    fields = "_/_/_/test"`   - not used in this example, topic_parsing  also left out, still possible for other use cases.

**Comment by samhld** [comment]
@srebhan I don't think I understand what you mean. Why would Telegraf have to wait for all topics? This would happen on a per-topic level for whichever topics are relevant at the time. Maybe there's something I don't understand about the topic_parsing implementation that would force this situation?  Perhaps @MyaLongmire can weigh in on that too. Also I'm happy to Slack about it offline if you want to keep the convo here more fluid.

@fietser28 yes good point about the values being encoded. Will grok your proposal and discuss with team!

**Comment by srebhan** [comment]
@samhld as far as I do understand you want to get the **field name** from an topic (part), put the content of the message in this topic as **field value** and then collect multiple topics into a measurement like
```text
sensors,site=CLE,version=v1,device_name=device5 temp=390,rpm=45.0,ph=1.45
```
Is this correct?

**Comment by samhld** [comment]
@srebhan Essentially, but it's not required that multiple Fields sit on the same line (Telegraf's "metric"). That feature is a convenience/optimization for InfluxDB and network traffic. If users need to do that, they can use the [merge aggregator](https://github.com/influxdata/telegraf/tree/master/plugins/aggregators/merge).

**Comment by srebhan** [comment]
@samhld understood. I would like to avoid aggregating in the plugin as this complicates things.

This being said, your use-case is to get the name of a field from the topic. This would only work if you have a single value in the message itself, wouldn't it? 
As usually messages contain multiple values e.g. as JSON, this is a very special use case IMO. @reimda, @powersj  what do you think?

**Comment by samhld** [comment]
@srebhan I don't believe it's a special case. I think it's fairly common. I've heard from multiple community users about it. @fietser28 (above) is one of them.

**Comment by samhld** [comment]
@srebhan @MyaLongmire FYI -- another example: https://community.influxdata.com/t/having-difficulty-setting-metric-name-from-topic-getting-value-mqtt-topic-and-value-parsing/24192/4

**Comment by srebhan** [comment]
@samhld OK, given that there is demand, how would you like this to be configured? Something like
```toml
    [[inputs.mqtt_consumer.topic_parsing]]
        measurement = "/measurement/_/_/_/_"
        tags = "/_/site/version/device_name/_"
        field_name = "/_/_/_/_/field"
```
or
```toml
    [[inputs.mqtt_consumer.topic_parsing]]
        measurement = "/measurement/_/_/_/_"
        tags = "/_/site/version/device_name/_"
        field = "/_/_/_/_/$name"
```
The first example is more explicit, but is also limited in what in can do. In the second case we could even allow more _variables_ to do something like `field = "/_/_/$name/_/$value"`. However, we then introduce another "special character" which is not so nice as the underlying parsing code will become more complex I guess.

For all examples the problem is, we need to make sure there is only _one_ name specified. This becomes very difficult if there are multiple `topic_parsing` sections which might overlap. But I guess we do have this issue already...

@MyaLongmire what do you think?

**Comment by samhld** [comment]
@srebhan I don't have a strong opinion either way. I think I lean toward the latter with additional syntax...but as long as this is documented in the README, I'm down for either.

**Comment by MyaLongmire** [comment]
Sorry, I am late to the discussion. 

IMO the input plugin is already getting too complex with parser jobs. As there is a workaround with using pivot, I am inclined to add a section in the docs about how they can use pivot instead of adding more complexity. 

I will bring it up with the team in our next planning meeting to get the direction we want to go.

Thank you for your patience!

**Comment by sjwang90** [comment]
@luck0r [this blog](https://www.influxdata.com/blog/pivot-mqtt-plugin/) was recently published that should help you with what you want if the Github readme updates weren't enough.

**Comment by luck0r** [comment]
@sjwang90 that one helped. Thanks

**Comment by jkoopmann** [comment]
> TBH, you make a lot of assumptions here... The foremost is that all those topics are updated _simultaneously_, which is _never_ the case in event-based communication. So we would need to "wait" for all messages to arrive etc. Not sure if this is a good idea actually...

I seem to be running into the very same issue with the waiting.

I have a device creating sensor readings and putting them on MQTT.

`olaranzeige/pv-garage/meter 0
solaranzeige/pv-garage/ohmpilot 0
solaranzeige/pv-garage/storage 0
solaranzeige/pv-garage/sensorcard 0
solaranzeige/pv-garage/stringcontrol 0
solaranzeige/pv-garage/inverter 0
solaranzeige/pv-garage/inverterid 0`

These are read and created every 10 seconds and then pushed out to MQTT. However "one by one". I would love to pivot those into "one measurement" with fields storage, sensor card etc. I can pivot it correctly but since the MQTT events come in with a few ms delay I get one line per incoming message.

Is there any way to "group" these? Like "group/pivot all incoming messages within one second"?

If not what is the best practice to work with this? Not pivot them and have the measurement as a tag only?

So I would love to have this in influx

`timestamp, meter, ohmpilot, inverter
timestamp1, 0,0,0
`

and the alternative would have to be

`timestamp, measurement, value
timestamp1, meter,0
timestamp1, ohmpilot,0
timestamp1,inverter,0
`

I hope this was somewhat understandable
