### ISSUE TITLE
fix consul_metrics docs

### ISSUE THREAD

**Issue by reimda** [influxdata/telegraf#10870]
### Relevant telegraf.conf

```toml
[[inputs.consul]]
```

### Logs from Telegraf

n/a

### System info

master

### Steps to reproduce

n/a

### Expected behavior

Docs and code should match

### Actual behavior

The plugin is named "consul_metrrics" internally but the docs refer to `[[inputs.consul]]`

### Additional info

"consul_metrics" doesn't make a lot of sense as a metric name. No other inputs include "metrics" in the metric name.

**Comment by sjwang90** [comment]
@efbar Could you take a look?

**Comment by efbar** [comment]
Yes, you're right @reimda . It should be:
`[[inputs.consul_metrics]]`

I'll update the readme file.

Regarding the name. It's been called liked this because there is the older consul input plugin called simply `consul` that is not meant for metrics but for getting infos of consul services. 
Since this `consul_metrics` plugin is specifically for consul metrics I supposed that it could be the right compromise to avoid name overlapping and existing input plugin renaming.
