### ISSUE TITLE
Solution to #6322

### ISSUE THREAD

**Issue by yoplin** [influxdata/telegraf#11138]
Hi, 

I found this Issue and I'm having the same problem. Can someone please offer a solution to this?

[#6322](https://github.com/influxdata/telegraf/issues/6322)

Thanks!
c.

**Comment by KPSS123** [comment]
Hello,

Just uncommented this line in telegraf.conf:

embedded_tags = [“Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/input/service-policy-names/service-policy-instance/statistics/class-stats/class-name”]

And substituted “input” for “output”, since that’s the direction we’re monitoring.

Thank you
Best Regards
Kunal Sisodia
