### ISSUE TITLE
Tigerbot labels on PR

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#11187]
## Feature Request

It would be handy if Tigerbot could be more intelligent when adding labels to PRs.

### Proposal:

Tigerbot to recognize the following conventional commits:

- `fix(inputs/*): ...`
- `chore(parsers/xpath): ...`

### Current behavior:

Tigerbot not adding respective labels.

### Desired behavior:

Tigerbot should also add the following labels:

- `plugin/input`
- `plugin/parser`, `area/xml`

### Use case: 

Needs to be done manually otherwise.

**Comment by Hipska** [comment]
Lol, the irony..

**Comment by powersj** [comment]
@sspaink my understanding is every tag is hard-coded into github first, and then the tiger bot goes and reads the original post to search for possible tags to use? Is that accurate?

**Comment by sspaink** [comment]
@powersj your right, at the moment the bot tries to give a "best guess" for a label. The bot has a list of hard-coded keywords matched to a possible tag, and then searches the title and body for the keyword. Because this mentioned "xml" it associated it with "area/xml". 

We could change this to exclusively use the scope in a conventional commit messages as I think your suggestion @Hipska ? We don't currently enforce using the conventional commit message style for issue titles though, so it would be up for discussion if that is something we would want to do. We could also update the issue template to include a section to add keywords, then the user opening the issue would be in control of what labels gets added.

**Comment by Hipska** [comment]
We don’t force the addition of topics indeed, but I see a lot of developers are already using it, so why not take advantage of it?

**Comment by Hipska** [comment]
That's a bit counter-productive, isn't it?

I wasn't in implying to enforce the commit style. I only came to the conclusion there are already some contributors that use it like this: `feat(inputs/file): ...`. So wouldn't it then be useful that the bot would also link the `plugin/input` tag?

I'm a bit bored by needing to do that on every PR while it is that plain simple to automate.. And indeed, the labels the bot adds will not always be perfect, but that's the case now as well. We then just apply the correct tags. With this addition, we would need to add these labels less situations..
