### ISSUE TITLE
Log rotation in conf file no longer supports "7d" ?

### ISSUE THREAD

**Issue by neocogent** [influxdata/telegraf#11225]
### Relevant telegraf.conf

```toml
[agent]
logfile_rotation_interval = "7d"
```

### Logs from Telegraf

```text
Starting The plugin-driven server agent for reporting metrics into InfluxDB...
May 31 16:34:25 lucy telegraf[6934]: 2022-05-31T06:34:25Z E! [telegraf] Error running agent: Error loading config 
file /etc/telegraf/telegraf.conf: error parsing [agent]: line 83: (config.AgentConfig.LogfileRotationInterval) tim
e: unknown unit "d" in duration "7d"
May 31 16:34:25 lucy systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
May 31 16:34:25 lucy systemd[1]: Failed to start The plugin-driven server agent for reporting metrics into InfluxD
B.
May 31 16:34:25 lucy systemd[1]: telegraf.service: Unit entered failed state.
May 31 16:34:25 lucy systemd[1]: telegraf.service: Failed with result 'exit-code'.
May 31 16:34:25 lucy systemd[1]: telegraf.service: Service hold-off time over, scheduling restart.
May 31 16:34:25 lucy systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
```

### System info

Telegraf 1.22.4, Raspbian GNU/Linux, Version 9 (stretch)

### Steps to reproduce

1. Use "7d" in conf file for log rotation - fails but worked fine before updating
2. Change to "168h" and now works ok.
3. Apparently the "d" is now not recognized and breaks previous conf files.
...

### Expected behavior

previous conf file continues to work

### Actual behavior

had to change conf after figuring out why not starting daemon

**Comment by sspaink** [comment]
Relevant issue: https://github.com/influxdata/telegraf/issues/10882
Pull request that changed the default: https://github.com/influxdata/telegraf/pull/10883

The unit of 'd' was never valid and was an error that was silently ignored, but since v1.22.0 the parsing became more strict so it began to fail. Therefore the above pull request changed to default to use `h` to encourage users to move away from using `d`. Sorry this caused a breaking config issue for you, but using the `168h` is the correct way of doing it and `7d` wouldn't have worked correctly.

**Comment by neocogent** [comment]
Ok. Good to know, and will not use d any more. Thx.
