### ISSUE TITLE
Docker input plugin should use context.WithTimeout

### ISSUE THREAD

**Issue by StephanZaat** [influxdata/telegraf#1133]
I have around 15 dockers on a single server, so I'd prefer to use [ ] to get the status from all dockers.
However, when a docker on one of our test servers is in status "restarting" (i.e. for some reason it is not starting) Telegraf will hang on this docker and will refuse to send any output to the influx server.

I would expect Telegraf just skips a non-functioning docker. We have consul and other tools to do service discovery and checking.

**Comment by zstyblik** [comment]
@StephanZaat which version of Telegraf do you use?

**Comment by StephanZaat** [comment]
Telegraf - Version 0.12.1

**Comment by zstyblik** [comment]
This can be fixed by using any other `context` than `context.Background()` as `context.Background()` doesn't have any timeout. Beware, though. Metric-wise, if Docker Daemon doesn't want to talk with you or is busy, it won't talk with you. This will lead to timeouts and "gaps" in metrics. But it seems this is the reality.

**Comment by sparrc** [comment]
good point @zstyblik, I've changed the issue to reflect that. We should be using context.WithTimeout.

**Comment by sparrc** [comment]
here are the instances:

```
docker.go
100:	containers, err := d.client.ContainerList(context.Background(), opts)
130:	info, err := d.client.Info(context.Background())
213:	r, err := d.client.ContainerStats(context.Background(), container.ID, false)
```
