### ISSUE TITLE
storage volume api fails 

### ISSUE THREAD

**Issue by tiny6996** [influxdata/telegraf#11473]
### Relevant telegraf.conf

```toml
[[inputs.openstack]]
  username = "redacted"
  password = "redacted"
  authentication_endpoint= "https://redacted:5000/"
  insecure_skip_verify = true
  enabled_services = ["volumes","storage_pools"]
  measure_openstack_requests = true
```

### Logs from Telegraf

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x27a9b0e]

goroutine 39 [running]:
github.com/gophercloud/gophercloud.(*ServiceClient).ResourceBaseURL(...)
	/go/pkg/mod/github.com/gophercloud/gophercloud@v0.25.0/service_client.go:39
github.com/gophercloud/gophercloud.(*ServiceClient).ServiceURL(...)
	/go/pkg/mod/github.com/gophercloud/gophercloud@v0.25.0/service_client.go:47
github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/schedulerstats.storagePoolsListURL(0x554d4b2d?)
	/go/pkg/mod/github.com/gophercloud/gophercloud@v0.25.0/openstack/blockstorage/extensions/schedulerstats/urls.go:6 +0x4e
github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/schedulerstats.List(0x0, {0x614cd40, 0xc000ce5bd8})
	/go/pkg/mod/github.com/gophercloud/gophercloud@v0.25.0/openstack/blockstorage/extensions/schedulerstats/requests.go:32 +0x65
github.com/influxdata/telegraf/plugins/inputs/openstack.(*OpenStack).gatherStoragePools(0xc00072aa00, {0x61ae5b0, 0xc000540ea0})
	/go/src/github.com/influxdata/telegraf/plugins/inputs/openstack/openstack.go:699 +0x7c
github.com/influxdata/telegraf/plugins/inputs/openstack.(*OpenStack).Gather(0xc00072aa00, {0x61ae5b0, 0xc000540ea0})
	/go/src/github.com/influxdata/telegraf/plugins/inputs/openstack/openstack.go:227 +0x942
github.com/influxdata/telegraf/agent.(*Agent).testRunInputs.func2(0xc000bbb270)
	/go/src/github.com/influxdata/telegraf/agent/agent.go:421 +0x2f8
created by github.com/influxdata/telegraf/agent.(*Agent).testRunInputs
	/go/src/github.com/influxdata/telegraf/agent/agent.go:390 +0xc8
```

### System info

Telegraf 1.23.1 on debian 11 calling the openstack xena api

### Steps to reproduce

1. install telegraf
2. add the config above to /etc/telegraf/telegraf.d/openstack.conf
3. restart telegraf service or ton telegraf --config /etc/telegraf/telegraf.d/openstack.conf --test --debug
...

### Expected behavior

storage and volume api metrics gathered and test commands complete without errors

### Actual behavior

memory address or nil depointer reference when either service is being monitored

### Additional info

it appears that this client is still using the storage v2 api which [was removed from openstack xena](https://docs.openstack.org/api-ref/block-storage/v2/index.html?highlight=v2) and the plugin needs to be updated to use the storage v3 api. it appears that gophercloud supports the storage v3 and the openstack docs say it should be a minimal change.

**Comment by powersj** [comment]
Thanks for the issue!

I believe the traceback is because you have `volumes` in your config to [collect the volumes](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/openstack/openstack.go), except we never initialize the variable unless your config contains the [service "volumev2"](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/openstack/openstack.go#L188-L192)

Can you try again with "volumev2" in your list of enabled services?

For my own notes re: v2 and v3:

Version 2 of the block storage API was deprecated in Pike (2017-08-30) and removed in Xena (2021-10-06). Pike is about to go EOL and is already in extended maintenance. 

Version 3 was introduced in Mitaka (2016-04-07). Version 3 is supposed to be backward compatible as well.

**Comment by powersj** [comment]
Ah, right, that won't work either since now "volume2" isn't a recognized service. To confirm, this has never worked, right? Can you try the artifacts on #11481 once they are there with your original `enabled_services` setting?

@singamSrikar - what was the intention with the cinder storage settings? Did you intend to have a "volumev2" and later a "volumev3"? Or only have "volumes"?

**Comment by singamSrikar** [comment]
Hi @powersj, thanks for reaching out, the intention at that time was to have "volumev2" API now and later add "volumev3" as an add-on and later remove v2. 
Coming to config, thought it's better to have generic names/strings rather than include versions in it and perform the version check(when adding volumev3) in the code depending on the data from Openstack Services endpoint used in "containsService".

The artifacts on #11481 would not work as v3 volume is present as "volumev3" in Openstack so please update `if o.containsService("volumes") ` to `if o.containsService("volumev3") `, to make it work.

nit: README update.

**Comment by singamSrikar** [comment]
@powersj intention was to remove v2 at EOL and as you have mentioned it's EOL in Openstack community so fully remove v2 and only have v3 for volume/cinder in Telegraf Openstack plugin.

**Comment by powersj** [comment]
Thanks for the response!

> @powersj intention was to remove v2 at EOL and as you have mentioned it's EOL in Openstack community so fully remove v2 and only have v3 for volume/cinder in Telegraf Openstack plugin.

While v2 is EOL in the latest release, users could be using an older release, where it is only deprecated. That said, v2 and v3 are supposed to be backward compatible, so I'm good with removing v2 entirely.

@singamSrikar can you give the PR a review?
@tiny6996 could you try the PR artifacts and let me know if it resolves the issue for you? 

Thank you both!
