### ISSUE TITLE
outputs.mysql loses connection to sql server after 24-36 hours

### ISSUE THREAD

**Issue by jaminto** [influxdata/telegraf#11498]
### Relevant telegraf.conf

```toml
[[outputs.sql]]
  driver = "mysql"

  data_source_name = "${DB_USER}:${DB_PASSWORD}@tcp(${DB_ADDRESS}:3306)/jenkins?multiStatements=true"
  table_template = "CREATE TABLE {TABLE}({COLUMNS})"
  table_exists_template = "SELECT 1 FROM {TABLE} LIMIT 1"
  init_sql = "SET sql_mode='ANSI_QUOTES';"
```

### Logs from Telegraf

```text
## Application Startup
2022-07-11T17:10:49Z I! Starting Telegraf 1.20.4
2022-07-11T17:10:49Z I! Loaded inputs: jenkins
2022-07-11T17:10:49Z I! Loaded aggregators:
2022-07-11T17:10:49Z I! Loaded processors:
2022-07-11T17:10:49Z I! Loaded outputs: sql
2022-07-11T17:10:49Z I! Tags enabled: host=ip-10-178-133-189.ec2.internal
2022-07-11T17:10:49Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"ip-10-178-133-189.ec2.internal", Flush Interval:10s
2022-07-11T17:10:49Z D! [agent] Initializing plugins
2022-07-11T17:10:49Z D! [agent] Connecting outputs
2022-07-11T17:10:49Z D! [agent] Attempting connection to [outputs.sql]
2022-07-11T17:10:49Z D! [agent] Successfully connected to outputs.sql
2022-07-11T17:10:49Z D! [agent] Starting service inputs
2022-07-11T17:10:59Z D! [outputs.sql] Wrote batch of 27 metrics in 339.444958ms

... some time later ....

[mysql] 2022/07/12 19:07:44 packets.go:123: closing bad idle connection: EOF
[mysql] 2022/07/12 19:07:44 connection.go:173: driver: bad connection
2022-07-12T19:07:44Z E! [outputs.sql] Error during insert: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"jenkins_job"("timestamp","result","source","host","name","parents","port","dura' at line 1, INSERT INTO "jenkins_job"("timestamp","result","source","host","name","parents","port","duration","result_code","number") VALUES(?,?,?,?,?,?,?,?,?,?)
```

### System info

telegraf:1.20.4-alpine docker image

### Steps to reproduce

1. start telegraf with one input and an outputs.sql type of mysql
2. let run for 24 hours or more and observe successfully inserted data in mysql

### Expected behavior

telegraf runs indefinitely (at least consistently more than 24 hours) and successfully writes output to mysql server

### Actual behavior

telegraf logs `closing bad idle connection: EOF` error message, all ensuing `INSERT` statements fail until the telegraf application is restarted

### Additional info

The go-mysql-driver clearly mentions that the ConnMaxLifetime should be set to less than 5 mins to address potential issues like we are seeing - https://github.com/go-sql-driver/mysql#important-settings.  However, it does not appear that this value can be set on the DSN as part of the connection string, and [can only be set by calling `db. SetConnMaxLifetime()`](https://github.com/go-sql-driver/mysql#usage) which we don't appear able to do without modifying the telegraf code.

Note: In our setup, mysql is running as an AWS RDS Aurora Serverless database that is presenting a mysql 5.6.10-compatible interface.

**Comment by powersj** [comment]
@reimda - as we only ever connect during the initialization, what do you think about checking for a null connection before doing a write? Or what do you think about exposing options for specific database drivers?

**Comment by reimda** [comment]
> @reimda - as we only ever connect during the initialization, what do you think about checking for a null connection before doing a write? Or what do you think about exposing options for specific database drivers?

sql.Open() doesn't actually make a connection. It just makes a new database handle. The handle manages connections whenever it needs to without help from telegraf. (see https://github.com/go-sql-driver/mysql/wiki/Examples#a-word-on-sqlopen) When this lost connection condition happens, there's no client notification or other condition the Write method can watch out for. The server just hangs up a connection, so that when telegraf tries to use it there's a failure.

When the server closes the connection I don't know if there's anything telegraf can do to recover. There is a ping method, but since it's not an idle disconnect, pings probably won't help. In this case it sounds like the server has an upper limit on how long a connection may be used. If it's open longer than that, the server hangs up.

@jaminto's suggestion that we need to call SetConnMaxLifetime() makes sense to me because it makes the go client close connections gracefully before the server has decides it has no other option than to kill the connection. Then the db handle can make new connections if it needs them.

If we add a telegraf setting for SetConnMaxLifetime, we should probably also add ones for the other golang sql DB object settings in the same PR. That way any sql drivers that need to tweak them will have a way to do so. In other words, we may be able to fix this particular mysql problem by lowering the max connection lifetime but I expect there are other problems with other databases that can be fixed by also tweaking max idle time and how many open/idle connections there are.

[func (db *DB) SetConnMaxIdleTime(d time.Duration)](https://pkg.go.dev/database/sql#DB.SetConnMaxIdleTime)
[func (db *DB) SetConnMaxLifetime(d time.Duration)](https://pkg.go.dev/database/sql#DB.SetConnMaxLifetime)
[func (db *DB) SetMaxIdleConns(n int)](https://pkg.go.dev/database/sql#DB.SetMaxIdleConns)
[func (db *DB) SetMaxOpenConns(n int)](https://pkg.go.dev/database/sql#DB.SetMaxOpenConns)

**Comment by reimda** [comment]
@jaminto Are you able to put a PR together to expose the sql handle settings (SetConnMaxLifetime, SetConnMaxLifetime, SetMaxIdleConns, SetMaxOpenConns) as telegraf sql output plugin settings?

**Comment by reimda** [comment]
@jaminto I added settings you needed. Could you retest with an alpha build from [here](https://github.com/influxdata/telegraf/pull/11551#issuecomment-1199798772) or with the next nightly build to see if setting the connection max lifetime fixes your problem? You'll have to add a line in your toml config with the limit you want. Example:

```toml
connection_max_lifetime = "12h"
```
