### ISSUE TITLE
Support opcua auto-reconnect and don't use registered reads

### ISSUE THREAD

**Issue by reimda** [influxdata/telegraf#11559]
One of the gopcua library maintainers pointed out that telegraf needs to handle auto-reconnect and that we should reconsider using registered reads. https://github.com/influxdata/telegraf/issues/9164#issuecomment-1039878729

The related upstream issue is https://github.com/gopcua/opcua/issues/557

**Comment by reimda** [comment]
I haven't found a simple example of implementing auto-reconnect, but there are some docs here https://pkg.go.dev/github.com/gopcua/opcua#AutoReconnect

**Comment by R290** [comment]
AutoReconnect is enabled by default for the client? At least this seems to be the case when running the `TestClient1Integration` test. I'm not sure how to properly test if the auto-reconnect feature actually works. Changing the registered reads to 'normal' reads should be quite straightforward...

**Comment by reimda** [comment]
Hi @R290, I think autoreconnect is enabled by default in gopcua. I also don't know how to test auto-reconnect, but if we're switching to normal reads maybe we won't need to? From @magiconair's comments that I linked above, I understand that it might be better if telegraf didn't use registered reads since they are for higher performance, as long as telegraf doesn't need that performance. If telegraf switched to normal reads, it wouldn't have to worry about registration becoming invalid on reconnect.

Are you interested in working on this issue and maybe switching the plugin to normal reads? At this point I'm not sure if there are telegraf users with use cases that need the performance of registered reads. I would hate to introduce a performance regression. I'm leaning toward adding a plugin setting that defaults to the existing code with registered reads, but lets users select normal reads if they are getting errors caused by registered reads failing after reconnects.

**Comment by reimda** [comment]
If we do end up wanting to test autoreconnect, maybe we could do it with a docker style test like this one? https://github.com/influxdata/telegraf/blob/9cfd7d185c17be7f94d01ee33306fee3b8dd8171/plugins/inputs/opcua/opcua_test.go#L28 It uses an example server from the open62541 project. Maybe we could make a similar test for autoreconnect by starting the open62541 container, then starting the plugin, then restarting the container and checking that the plugin reconnected? I'm not sure if the open62541 example server invalidates registered node ids when it shuts down.

**Comment by R290** [comment]
Let me see what I can do with respect to implementing regular reads and the associated testing. We should even be able to do some benchmarking between registered reads and regular reads using the open62541 example server.

**Comment by R290** [comment]
So the opcua client has build in connection monitoring which is started when the client is connected, see https://github.com/gopcua/opcua/blob/main/client.go#L215 and https://github.com/gopcua/opcua/blob/main/client.go#L234. Which seems to make what we are doing here redundant: https://github.com/influxdata/telegraf/blob/7bd9c91ebe830c9c5e57f7984c7849881a4c8276/plugins/inputs/opcua/opcua.go#L504

For testing the autoreconnect function the following can be used: https://github.com/R290/opcua/tree/autoreconnect/examples/read. At the moment there is no need to use all of Telegraf, the slightly modified basic read example should be sufficient. The reason for using nginx as an intermediate, is to be able to drop the connection without modifying the state of the server. Either stopping, restarting or killing the nginx container will drop the TCP connection. Wireshark is used to monitor traffic using the filters `opcua` or `tcp.port == 14840` (browser accessible via `localhost:3000`). 

Now for the interesting part. Instead of successfully recovering the connection, the opcua client falls into an endless loop, spamming the server with requests. Seems to me that this is not by design... If I can find the time, I'll create an issue at the opcua library, although this issue might be related: https://github.com/gopcua/opcua/issues/434. Telegraf possibly avoids the endless loop with the redundant connection management.

**Comment by reimda** [comment]
Thanks for your help on this!
