### ISSUE TITLE
ntpq plugin schema: remote tag combines information that should be separate

### ISSUE THREAD

**Issue by aewallin** [influxdata/telegraf#1161]
the remote tag for the ntpq plugin combines two pieces of information: ip-number/name together with a single-character prefix that contains information on how ntpd uses that server.

this isn't ideal since when the prefix for a server changes it creates a new series.
the remote tag should instead be split into two tags, for example: remote and remote_prefix

the prefix is explained e.g. here:
http://tech.kulish.com/2007/10/30/ntp-ntpq-output-explained/

**Comment by sparrc** [comment]
agreed, we should do that

**Comment by ahothan** [comment]
ok I know I come in a bit late, but this resolution does not solve the problem because the new tag "state_prefix" will also create new time series for the same remote server when its state changes!
Instead of creating a new tag, it would have been better to create a new metric all together to carry the state of the remote server.
