### ISSUE TITLE
`config` always generates config for all plugins

### ISSUE THREAD

**Issue by StephenCleary** [influxdata/telegraf#11686]
### Relevant telegraf.conf

```toml
N/A
```

### Logs from Telegraf

```text
N/A
```

### System info

Telegraf 1.23

### Steps to reproduce

1. `docker run -it --rm telegraf:1.23 /bin/bash`
2. `telegraf config --section-filter agent:inputs:outputs --input-filter cpu --output-filter influxdb > /tmp/result.conf`
3. `more /tmp/result.conf`

### Expected behavior

`/tmp/result.conf` is a `.conf` with just `input.cpu` and `output.influxdb`.

### Actual behavior

`/tmp/result.conf` is a `.conf` with everything.

### Additional info

`telegraf config --section-filter agent:inputs:outputs --input-filter cpu --output-filter influxdb` is taken from the README.

**Comment by sspaink** [comment]
So this was fixed with: https://github.com/influxdata/telegraf/pull/11282 which I don't think is included in the latest release yet. If you use the nightly artifacts you it should work as expected: https://github.com/influxdata/telegraf/blob/master/docs/NIGHTLIES.md

This fix should be available when v1.24.0 is released, in the meantime using: `telegraf --section-filter agent:inputs:outputs --input-filter cpu --output-filter influxdb config > /tmp/result.conf` does work with v1.23 but this will get deprecated in the future
