### ISSUE TITLE
Adding IEEE to inputs.modbus.request

### ISSUE THREAD

**Issue by DuZk** [influxdata/telegraf#12433]
### Use Case

As of now the options for choosing unit type is not consistent in both "configuration_types" (request and register).
This lead to major confusion when I moved from register style configuration to request style to implement aditional devices in the configuration.

### Expected behavior

I would suggest that the following should work:
```
[[inputs.modbus.request]]
    slave_id = 20
    byte_order = "ABCD"
    register = "holding"
    measurement = "heat"
    fields = [    
      { name = "Flow", type = "FLOAT32-IEEE", scale = 1.0, address = 3000, omit=false}
  ]
```
And should produce an output

### Actual behavior

IEEE's are not recognised as a correct type:
```
2022-12-21T22:37:42Z I! Starting Telegraf 1.24.4
2022-12-21T22:37:42Z I! Available plugins: 221 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2022-12-21T22:37:42Z I! Loaded inputs: modbus (2x)
2022-12-21T22:37:42Z I! Loaded aggregators:
2022-12-21T22:37:42Z I! Loaded processors:
2022-12-21T22:37:42Z W! Outputs are not used in testing mode!
2022-12-21T22:37:42Z I! Tags enabled:
2022-12-21T22:37:42Z D! [agent] Initializing plugins
2022-12-21T22:37:42Z E! [telegraf] Error running agent: could not initialize input inputs.modbus: cannot process configuraton: initializing field "Flow" failed: invalid input datatype "FLOAT32-IEEE" for determining field length
````

### Additional info

As a reference, register configuration works flawlessly:
```
configuration_type = "register"
slave_id = 13
holding_registers = [
  { name = "L1_Power", byte_order = "CDAB",   data_type = "FLOAT32-IEEE", scale=1.0,  address = [3000,3001]}
]
```

**Comment by srebhan** [comment]
@DuZk thanks for speaking up on this issue. As a background, the `FLOATxx`, `FLOATxx-IEEE` and `*FIXED` types in the register configuration scheme are quite confusing for most people and often lead to misinterpretation, therefore I made a clean-cut for the `requests` configuration type and things are what they are named, i.e. fixed-point numbers are integers that become float by applying a scale. I would love to also do this for the `register` configuration type, but that will break existing configurations using e.g. `FLOAT32` as fixed-point numbers instead of `FIXED`.
However, introducing e.g. `FLOAT32-IEEE` might mislead people that `FLOAT32` is a fixed point number (which is not the case)...

This being said, a good way forward is not that clear to me... We could catch the `FLOATxx-IEEE` cases for `requests` and output a specific message saying you should use `FLOATxx` instead. What do you think? Do you have a better idea?
