### ISSUE TITLE
Failed to apt install telegraf

### ISSUE THREAD

**Issue by ajdhamna** [influxdata/telegraf#12563]
### Relevant telegraf.conf

```toml
-
```

### Logs from Telegraf

```text
-
```

### System info

-

### Steps to reproduce

wget https://repos.influxdata.com/influxdb.key 
apt-key add influxdb.key
echo deb https://repos.influxdata.com/ubuntu bionic stable > /etc/apt/sources.list.d/influxdb.list
apt update && apt install -y  telegraf

The installation fails with the following error.

W: GPG error: https://repos.influxdata.com/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E
E: The repository 'https://repos.influxdata.com/ubuntu bionic InRelease' is not signed.

### Expected behavior

-

### Actual behavior

-

### Additional info

It appears that the influxdb.key was recently changed. Surprisingly, it works fine with the https://repos.influxdata.com/influxdata-archive.key. 
That makes me believe the keys got swapped, the package is signed with the new key and the corresponding pub key is dropped in the influnxdb_archive.key file.

**Comment by braindawg** [comment]
Check this out, they recently swapped signing keys. The provided instructions here did the trick for me on an RPM-based system (Amazon Linux 2):

https://github.com/influxdata/telegraf/issues/12542

**Comment by powersj** [comment]
> W: GPG error: https://repos.influxdata.com/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E


As mentioned above, as well as in the [pinned issue](https://github.com/influxdata/telegraf/issues/12542), the GPG key for the InfluxData repos was rotated last week.

Please check out this blog post](https://www.influxdata.com/blog/linux-package-signing-key-rotation/) or see our [readme](https://github.com/influxdata/telegraf/blob/master/README.md#package-repository) for updated instructions.

Thanks

**Comment by gm0neyl0ve** [comment]
https://docs.influxdata.com/telegraf/v1.21/introduction/installation/?t=curl

Should probably be updated.

**Comment by powersj** [comment]
> https://docs.influxdata.com/telegraf/v1.21/introduction/installation/?t=curl
> 
> Should probably be updated.

That looks updated as it is using `https://repos.influxdata.com/influxdata-archive_compat.key` which is the new key. Is there a step that is not working for you?

**Comment by ajdhamna** [comment]
I moved to influxdata-archive_compat.key, thank you.

**Comment by gm0neyl0ve** [comment]
I get the following 
When performing the steps listed here.

`curl -s https://repos.influxdata.com/influxdata-archive_compat.key | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg >/dev/null

source /etc/os-release

echo "deb https://repos.influxdata.com/${ID} ${VERSION_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
deb https://repos.influxdata.com/ubuntu jammy stable
ubuntu@mts-mediaadapter-1:~$ sudo apt-get update
Hit:1 https://download.docker.com/linux/ubuntu jammy InRelease
Get:2 https://repos.influxdata.com/ubuntu jammy InRelease [7,019 B] 
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy InRelease           
Err:2 https://repos.influxdata.com/ubuntu jammy InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E
Get:4 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 DEP-11 Metadata [101 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 c-n-f Metadata [13.1 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 DEP-11 Metadata [265 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [15.0 kB]         
Get:11 http://us.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 DEP-11 Metadata [940 B]
Get:12 http://us.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 DEP-11 Metadata [12.5 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/main amd64 DEP-11 Metadata [41.5 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 DEP-11 Metadata [13.3 kB]
Reading package lists... Done                
W: https://repos.influxdata.com/ubuntu/dists/jammy/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg are ignored as the file has an unsupported filetype.
W: GPG error: https://repos.influxdata.com/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E
E: The repository 'https://repos.influxdata.com/ubuntu jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: http://us.archive.ubuntu.com/ubuntu/dists/jammy/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg are ignored as the file has an unsupported filetype.
W: http://us.archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg are ignored as the file has an unsupported filetype.
W: http://us.archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg are ignored as the file has an unsupported filetype.
W: http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg are ignored as the file has an unsupported filetype.
`

**Comment by powersj** [comment]
@gm0neyl0ve,

Can you go file an issue on the [docs repo here](https://github.com/influxdata/docs-v2/issues/new?body=_Describe%20the%20issue%20here._%0a%0a%23%23%23%23%23%20Relevant%20URLs%0a-%20https://docs.influxdata.com/telegraf/v1.21/introduction/installation/%0a-%20_Provide%20other%20relevant%20URLs%20%28project%20issues,%20community%20threads,%20etc.%29_%0a). Looks like there are a couple issues with the updates.

In the mean time, stop using the old docs :) and use the docs found on the project readme.

Thanks

**Comment by ajdhamna** [comment]
I did not follow the document completely, just picked the correct key name and used with `apt-key add`.

**Comment by danger89** [comment]
> `apt-key add`

Better don't use `apt-key add` anymore.

Try at least this instead: `curl -fsSL https://repos.influxdata.com/influxdata-archive_compat.key | sudo apt-key --keyring /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg ad`

**Comment by maxadamo** [comment]
> > https://docs.influxdata.com/telegraf/v1.21/introduction/installation/?t=curl
> > Should probably be updated.
> 
> That looks updated as it is using `https://repos.influxdata.com/influxdata-archive_compat.key` which is the new key. Is there a step that is not working for you?

can you please add a small README in the repository, to explain which key needs to be used? 
This is extremely confusing and I could not expect the key to be called compat-archive. Archive means stale, old. Why should I use something that is referred as archive?

**Comment by powersj** [comment]
Please do not comment on closed issues. Instead open a new one or ask questions on our [forums](https://community.influxdata.com/) or [slack](https://influxdata.com/slack).

> can you please add a small README in the repository, to explain which key needs to be used?

The [README](https://github.com/influxdata/telegraf/blob/master/README.md#obtaining-telegraf)  , [official downloads page](https://portal.influxdata.com/downloads/), and [official documentation](https://docs.influxdata.com/telegraf/v1.25/install/) all show which key need to be obtained. If you are asking why a new key was used, that was documented in the [blog post announcing the change](https://www.influxdata.com/blog/linux-package-signing-key-rotation/).

> Archive means stale, old.

That is one definition of archive. Another definition is a place where packages, records, or other items are collected and contained. This key is for the InfluxData package archive. Similar to the [Ubuntu Package Archive](https://wiki.ubuntu.com/UbuntuDevelopment/PackageArchive) or other repositories/archives of other distributions.
