### ISSUE TITLE
Building .tar.gz package on macOS fails

### ISSUE THREAD

**Issue by hjuutilainen** [influxdata/telegraf#12769]
### Relevant telegraf.conf

```
Not relevant for this
```

### Logs from Telegraf

```text
Not relevant for this
```

### System info

macOS 13.2.1, latest golang

### Steps to reproduce

1. Use macOS with build prerequisites installed
2. Clone telegraf repository
3. Run `make package include_packages="darwin_arm64.tar.gz"` or `make package include_packages="darwin_amd64.tar.gz"`

### Expected behavior

Package should be successfully created

### Actual behavior

The build process fails because Makefile is using GNU tar options:

```shell
 % make package include_packages="darwin_arm64.tar.gz"
env -u GOOS -u GOARCH -u GOARM -- go build -o ./tools/custom_builder/custom_builder ./tools/custom_builder
env -u GOOS -u GOARCH -u GOARM -- go build -o ./tools/license_checker/license_checker ./tools/license_checker
env -u GOOS -u GOARCH -u GOARM -- go build -o ./tools/readme_config_includer/generator ./tools/readme_config_includer/generator.go
GOOS=linux go generate -run="readme_config_includer/generator$" ./plugins/inputs/...
GOOS=windows go generate -run="readme_config_includer/generator$" ./plugins/inputs/...
GOOS=darwin go generate -run="readme_config_includer/generator$" ./plugins/inputs/...
GOOS=linux go generate -run="readme_config_includer/generator$" ./plugins/outputs/...
GOOS=windows go generate -run="readme_config_includer/generator$" ./plugins/outputs/...
GOOS=darwin go generate -run="readme_config_includer/generator$" ./plugins/outputs/...
GOOS=linux go generate -run="readme_config_includer/generator$" ./plugins/processors/...
GOOS=windows go generate -run="readme_config_includer/generator$" ./plugins/processors/...
GOOS=darwin go generate -run="readme_config_includer/generator$" ./plugins/processors/...
GOOS=linux go generate -run="readme_config_includer/generator$" ./plugins/aggregators/...
GOOS=windows go generate -run="readme_config_includer/generator$" ./plugins/aggregators/...
GOOS=darwin go generate -run="readme_config_includer/generator$" ./plugins/aggregators/...
GOOS=linux go generate -run="readme_config_includer/generator$" ./plugins/secretstores/...
GOOS=windows go generate -run="readme_config_includer/generator$" ./plugins/secretstores/...
GOOS=darwin go generate -run="readme_config_includer/generator$" ./plugins/secretstores/...
if [ ".gz" = ".zip" ]; then go generate cmd/telegraf/telegraf_windows.go; fi
build/darwin-arm64/telegraf -> build/darwin-arm64-tar/telegraf-1.25.3/usr/bin/telegraf
etc/telegraf.conf -> build/darwin-arm64-tar/telegraf-1.25.3/etc/telegraf/telegraf.conf
etc/logrotate.d/telegraf -> build/darwin-arm64-tar/telegraf-1.25.3/etc/logrotate.d/telegraf
tar: Option --owner is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
make: *** [darwin_arm64.tar.gz] Error 1
```

### Additional info

This is because on line https://github.com/influxdata/telegraf/blob/3835522ca79f8d1278201292943da8993fae49af/Makefile#L396 is assuming all .gz packages are built using a system with GNU Tar. If I change the elif statement to

```
elif [ "$(suffix $@)" = ".gz" ] && [ "${GOOS}" = "linux" ]; then \
    tar --owner 0 --group 0 -czvf $(pkgdir)/telegraf-$(tar_version)_$@ -C $(dir $(DESTDIR)) . ;\
elif [ "$(suffix $@)" = ".gz" ] && [ "${GOOS}" = "darwin" ]; then \
    tar -czvf $(pkgdir)/telegraf-$(tar_version)_$@ -C $(dir $(DESTDIR)) . ;\
```

the package builds successfully. Could the Makefile be updated to have a check for different operating systems and tar behaviors?

Thank you for telegraf!

**Comment by powersj** [comment]
> have a check for different operating systems and tar behaviors?

Telegraf supports cross-builds by setting the GOOS environment variable. In fact, this is how the Telegraf release packages are built today. A CircleCI container based on the Go official image, which uses Debian Bullseye, builds for the various OSes.

If we ran with your patch, to build the macOS release artifacts, then Make would attempt to run with the new tar command, which omits the group and owner settings.

I know we have had previous issues come up with the Makefile around Windows as well. The Makefile was written as you have noticed for Linux systems because that is what we use to do builds and releases. Each time we talk about cross-OS support it means adding quite a bit of work to ensure all the various options work while not breaking the cross builds or release process. 

As a result I am inclined not to make that change, nor go down the path of trying to ensure cross-OS support. I would be open to seeing a macOS specific Makefile that users can use and point to though.
