### ISSUE TITLE
New metrics created by starlark do not pass to downstream processors

### ISSUE THREAD

**Issue by cruscio** [influxdata/telegraf#12849]
### Relevant telegraf.conf

```toml
[agent]
  interval = "10s"
  hostname = "testrun"

[[outputs.file]]
  files = ["stdout"]

[[inputs.mem]]
  #Generate some random measurements for input to starlark

[[processors.starlark]] 
  script = "./starlark.star"

[[processors.date]]
  #Add timestamp as a field in iso8601 format
  field_key = "timestamp_iso8601"
  date_format = "2006-01-02T15:04:05.123456Z"
  timezone = "UTC"
```

### Logs from Telegraf

```text
2023-03-13T15:02:33Z I! Starting Telegraf 1.25.1
2023-03-13T15:02:33Z I! Available plugins: 213 inputs, 9 aggregators, 26 processors, 21 parsers, 57 outputs, 2 secret-stores
2023-03-13T15:02:33Z I! Loaded inputs: mem
2023-03-13T15:02:33Z I! Loaded aggregators: 
2023-03-13T15:02:33Z I! Loaded processors: date starlark
2023-03-13T15:02:33Z I! Loaded secretstores: 
2023-03-13T15:02:33Z W! Outputs are not used in testing mode!
2023-03-13T15:02:33Z I! Tags enabled: host=testrun
2023-03-13T15:02:33Z D! [agent] Initializing plugins
2023-03-13T15:02:33Z D! [agent] Starting service inputs
2023-03-13T15:02:33Z D! [agent] Stopping service inputs
2023-03-13T15:02:33Z D! [agent] Input channel closed
2023-03-13T15:02:33Z D! [agent] Processor channel closed
2023-03-13T15:02:33Z D! [agent] Processor channel closed
2023-03-13T15:02:33Z D! [agent] Stopped Successfully
> new_metric_from_starlark,foo=bar baz=42i 1678719753686096000
> mem,host=testrun active=5272829952i,available=5325012992i,available_percent=30.995655059814453,free=89522176i,inactive=5235490816i,timestamp_iso8601="2023-03-13T15:02:34.31332346Z",total=17179869184i,used=11854856192i,used_percent=69.00434494018555,wired=1787953152i 1678719754000000000
```

### System info

Telegraf 1.25.1

### Steps to reproduce

```
cat << EOF > ./starlark.star
def apply(metric):
  metrics = []

  new_metric = Metric("new_metric_from_starlark")
  new_metric.tags["foo"] = "bar"
  new_metric.fields["baz"] = 42
  metrics.append(new_metric)
  
  metrics.append(deepcopy(metric))

  return metrics
EOF

cat << EOF > ./telegraf.conf
[agent]
  interval = "10s"
  hostname = "testrun"

[[outputs.file]]
  files = ["stdout"]

[[inputs.mem]]
  #Generate some random measurements for input to starlark

[[processors.starlark]] 
  script = "./starlark.star"

[[processors.date]]
  #Add timestamp as a field in iso8601 format
  field_key = "timestamp_iso8601"
  date_format = "2006-01-02T15:04:05.123456Z"
  timezone = "UTC"
EOF

telegraf --version
# Telegraf 1.25.1

telegraf --config ./telegraf.conf --test --debug
```

### Expected behavior

New measurements created/emitted by Starlark processor should pass downstream to the next processor

```
new_metric_from_starlark,foo=bar baz=42i,timestamp_iso8601="2023-03-13T15:02:34.31332346Z" 1678719753686096000
```

### Actual behavior

A new measurement created in Starlark is not passed to downstream processors. 
For comparison, if you deep-copy the input metric in the starlark script, it *is* passed downstream.

```
new_metric_from_starlark,foo=bar baz=42i 1678719753686096000
```

### Additional info

I am trying to convert timestamp to an iso 8601 field, for compatibility with a tertiary system. My Telegraf config has an exec input that returns a JSON array of measurements as a single string value. A Starlark processor parses the JSON into discrete measurements. Measurements emitted by Starlark are not passed to the final processor that performs the timestamp->ios8601 transform.

As a workaround, I'm running the date processor first and copying the field to each new measurement in starlark. I'd prefer to do as much work as possible natively in the telegraf config though.

**Comment by powersj** [comment]
Hi,

First, thank you for the very clear steps to reproduce. I really appreciate that.

I was able to see it reproduce and I think we advertise that processors should be run in file order. It does not seem to be the case.

As a built-in workaround, if you set `order = 1` and `order = 2` on each processor I seem to get the expected result. Can you confirm you see the expected behavior? Setting the order on processors should ensure you get what you are after.

**Comment by powersj** [comment]
> Would it be fair to say there's still a bug here, that some processors are not running in file-order when no order is specified?

Yes - I'd like to use this issue to resolve that or at least further understand what is going on. In general, I always suggest explicitly setting the order if order matters to you, but since we do advertise the order in the file is what would be used otherwise we should look into this.

It looks like the order of processors is consistent internally until we get to `runProcessors`: https://github.com/influxdata/telegraf/blob/master/agent/agent.go#L645-L658 here we launch a number of go routines and they seem to run in reverse order, unless you set order.

> I set it as a string, not an int ( order = "1"). When it changed nothing

Can you file an issue for this as well. We use the `getFieldInt64` function here https://github.com/influxdata/telegraf/blob/master/config/config.go#L1602-L1615 and because it fails to parse as an int, we move on rather than setting an error.

**Comment by redbaron** [comment]
@powersj,

> we advertise that processors should be run in file order.

Thats what the Markdown file in this Github repo says, but currently [published documentation](https://docs.influxdata.com/telegraf/v1.26/configuration/) doesn't:

<img width="989" alt="Screenshot 2023-05-29 at 07 37 48" src="https://github.com/influxdata/telegraf/assets/16624/78fabcab-dbdb-49cf-9fa3-f70b4c2bf9f9">

**Comment by redbaron** [comment]
>  I always suggest explicitly setting the order if order matters to you

How does it behave if only some plugins define order? what will be the order in these scenarios:

```
[A]
[B]
order = 1
[C]
order = 2
[D]
```

```
[A]
[B]
order = 1
[C]
[D]
order = 2
```


```
[A]
[B]
order = 2
[C]
[D]
order = 1
```

**Comment by srebhan** [comment]
@cruscio  please test the binary in #13614 once CI finished the tests successfully. Let me know if that fixes your issue!
