### ISSUE TITLE
Some troubles encountered when using the ipmi-sensor input plugin.

### ISSUE THREAD

**Issue by stone-98** [influxdata/telegraf#12985]
### Expected behavior

I can successfully use the ipmi-sensor input plugin and understand the specific meaning of each label through the help label.

### Actual behavior

I can successfully use the ipmi-sensor input plugin, but the tricky thing is that I don't know the specific meaning of each indicator, and the help label does not give any explanation.

### Additional info

![image](https://user-images.githubusercontent.com/35629966/228714903-4139bec6-93e5-40ca-9db7-8994bc80bc1e.png)

**Comment by stone-98** [comment]
Or is there any other way for me to know what each metric means?

**Comment by stone-98** [comment]
Another issue is that I configured the ipmi-sensor input plugin when using Telegraf. This plugin depends on ipmitool, but the Telegraf image does not include this tool. In such a scenario, users need to build their own image that includes ipmitool. Can the official provide relevant images for users to use out of the box?

**Comment by powersj** [comment]
Hi,

> understand the specific meaning of each label through the help label.

As you noticed the ipmitool is what is used to collect the data. This tool collects the raw data. You appear to be using the prometheus serializer to output the data in prometheus format.

There is no help data produced by the ipmitool which can be presented. I would suggest looking up the ipmi information for your device/sever and read what metrics are produced if you want additional information about the values.

> This plugin depends on ipmitool, but the Telegraf image does not include this tool. In such a scenario, users need to build their own image that includes ipmitool. Can the official provide relevant images for users to use out of the box?

Unfortunately no. The telegraf image does come with a few pieces of software, but overall it is a basic image that tries to be small. If we included every tool that is required by all the plugins, the image would be huge and would require constant security updates due to all the tools that are used.

**Comment by stone-98** [comment]
Ok, thanks for your reply.
