### ISSUE TITLE
No service account field for inputs.stackdriver:

### ISSUE THREAD

**Issue by rivolity** [influxdata/telegraf#13049]
### Relevant telegraf.conf

```toml
Hello,

I saw that no credentials_file field was specified on the configuration example, I've tried to add the credentials_file directly to my conf, but it does not work
```

### Logs from Telegraf

```text
2023-04-06T13:40:22Z E! [telegraf] Error running agent: Error loading config file ./test.conf: plugin inputs.stackdriver: line 1: configuration specified the fields ["credentials_file"], but they weren't used
```

### System info

Telegraf 1.21.1

### Steps to reproduce

[[inputs.stackdriver]]
  #project = "projectID-GCP" #mygcpproject
  credentials_file = "path/to/service/account/sa.json"
  metric_type_prefix_include = [
    "cloudsql.googleapis.com/database/postgresql/",
  ]

### Expected behavior

metrics of postgresql

### Actual behavior

no metrics

**Comment by powersj** [comment]
Hi,

> configuration specified the fields ["credentials_file"], but they weren't used

The error message occurs because this is not a valid option for this output plugin.

The stackdriver plugin call's the [google monitoring API](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/stackdriver/stackdriver.go#L408-L412) directly to create a client. As the [readme suggests](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/stackdriver/README.md#authentication) take a look at the [Google docs on authentication](https://cloud.google.com/docs/authentication/client-libraries)

**Comment by rivolity** [comment]
I was able to resolve my issues by executing the command through a GCP machine. The telegraf plug-in utilized the service account that was responsible for managing the machine. This account was associated with the compute instance, the instance should have Stackdriver API enabled to communicate with GCP logging.

However, I have a follow-up question. If I were to execute the command outside of GCP to gather metrics, how would telegraf authenticate with GCP Stackdriver (logging) in order to collect the metrics?

**Comment by powersj** [comment]
> If I were to execute the command outside of GCP to gather metrics, how would telegraf authenticate with GCP Stackdriver (logging) in order to collect the metrics?

There are other examples on that page I linked. You could use the gcloud CLI and login with that. What I do is have a credentials file in my `~/.config/gcloud/` folder.

**Comment by rivolity** [comment]
Okay I'll give it a try.
Thanks for the quick reply 👍
