### ISSUE TITLE
Add refresh_interval to configuration parameters in Elasticsearch output plugin

### ISSUE THREAD

**Issue by Kacper2k** [influxdata/telegraf#13053]
### Use Case

I am creating a service for live monitoring of some data. I need to change this value from default 10s to 1s.

### Expected behavior

Using refresh_interval parameter we could change it in elastic index template.

### Actual behavior

Currently there is no way to chenge it in telegraf.

### Additional info

[Place in code](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/elasticsearch/elasticsearch.go#L68) with this value hardcoded.

**Comment by powersj** [comment]
Hi,

Looking through the elasticsearch output plugin, you can customize this template after it was created and/or use your own template instead by providing the name.

If we were to add this, it would need to be a list of settings that the user could set, rather than just the one setting otherwise I can see us getting further requests to add more and more customization.

Something like:

```toml
## Set template index settings
# template_index_settings = {
    "refresh_interval": "10s",
    "mapping.total_fields.limit": 5000,
    "auto_expand_replicas" : "0-1",
    "codec" : "best_compression"
}
```

next steps: someone could take a swing at adding this setting, using the existing defaults when not set.

**Comment by abhi-jha** [comment]
So we are looking for the above set of setting to get overriden via the conf file?
