### ISSUE TITLE
influxdb_v2 output plugin should support time precision

### ISSUE THREAD

**Issue by vlcinsky** [influxdata/telegraf#13407]
When writing line protocol formatted data to InfluxDB using CLI, e.g. ```influx write -f data.line -b bucket -o org --precision ms``` it allows to specify non-default precision for timestamps. Default is nanoseconds, but other options exists.

Telegraf has output plugin inluxdb_v2, which allows writing data to InfluxDB, however it does not provide a parameter to specify timestamp precision.

As see at: [plugins/outputs/influxdb_v2/http.go](https://github.com/influxdata/telegraf/blob/ebe346103ebfd96b63cdbd2f3f36b2258746c160/plugins/outputs/influxdb_v2/http.go#L408), the HTTP client does specify bucket or organization, but does not support precision parameter.

Having such an option would allow to store line protocol data in InfluxDB using optional time precision as is already possible with `influx` CLI.

This issue follows [chat in Slack #Telegraf channel](https://influxcommunity.slack.com/archives/CH99HUH8V/p1686174316187719)

**Comment by Hipska** [comment]
This is in order to be able to follow the [InfluxDB write best practices](https://docs.influxdata.com/influxdb/cloud/write-data/best-practices/optimize-writes/#use-the-coarsest-time-precision-possible):

> By default, InfluxDB writes data in nanosecond precision. However if your data isn’t collected in nanoseconds, there is no need to write at that precision. For better performance, use the coarsest precision possible for timestamps.

**Comment by powersj** [comment]
> Telegraf has output plugin inluxdb_v2, which allows writing data to InfluxDB, however it does not provide a parameter to specify timestamp precision.

Your issue was not with the output plugin, rather it was with the parser. When Telegraf was reading from your input and parsing the data it is assumed that the timestamp is in nanosecond precision. The Telegraf `influx` and `influx_upstream` parsers have the ability to set a precision level, but it is not currently exposed to the user.

I have put up #13419 which adds a new `influx_timestamp_precision` config option for the `influx` and `influx_upstream` parsers. Valid options include `1ns` (default), `1ms`, `1us`, or `1s`.

Can you please download the artifacts from #13419, set the new option, and give them a try to confirm that this resolves the issue?

Thanks

**Comment by Hipska** [comment]
We know and agree to that. It is nice you now can specify precision for the parser. But this request is specifically for the output in order to be able to follow InfluxDB best practices as in my previous comment.

**Comment by powersj** [comment]
After talking to a few folks internally, the general consensus is that enabling the precision in the output is not something we will do.

The performance benefit provided by the time precision is primarily at the compression level, not in network or write-performance. And even then the benefits are only in very specific cases. A user would need to have their database precision changed to seconds and more importantly the user needs to write data with timestamps at specific intervals, not random timestamps. For example if the user had data with timestamps always spaced exactly 10 seconds apart from each other. Any variation in the timestamps would negate this performance gain. See the [timestamps doc](https://docs.influxdata.com/influxdb/v1.8/concepts/storage_engine/#timestamps) for more on the encoding. 

@vlcinsky - as you were the one who stumbled across this I would like your thoughts on the change to the influx parser. If you find it valuable, then please do test out the PR, otherwise I will close this issue as won't fix.

Thanks

**Comment by srebhan** [comment]
@kjetilmjos sorry but I'm not sure what you are trying to do. Does your timestamp arrives with second precision in Telegraf? If so, the output will send the data as nanoseconds but everything below seconds will be zero. InfluxDB will also store the timestamp in nanoseconds, so I'm not seeing the issue here...

**Comment by kjetilmjos** [comment]
Hi @srebhan .Yes, the data arrives into telegraf with seconds timestamp as Line protocol. I need to send the data with second precision to influx. I need to specify "precision=s" on the query for this to work. The only way I have found out this can be done is by using the http output plugin and not the influx2 output. 

Storing data as seconds instead of nanoseconds significantly reduces the space usage so it's a good practice to do if you don't need the nanoseconds precision. [https://docs.influxdata.com/influxdb/v2/write-data/best-practices/optimize-writes/#use-the-coarsest-time-precision-possible](https://docs.influxdata.com/influxdb/v2/write-data/best-practices/optimize-writes/#use-the-coarsest-time-precision-possible)
