### ISSUE TITLE
telegraf init script hides syntax errors

### ISSUE THREAD

**Issue by forsberg** [influxdata/telegraf#1344]
### System info:

telegraf 0.13.1 (debian package) on Debian wheezy. 
### Steps to reproduce:

1. Introduce a syntax error in /etc/telegraf/telegraf.conf
2. Start telegraf with /etc/init.d/telegraf start

### Expected behavior:

Non-OK output from init script, with info on syntax error.

### Actual behavior:

`# /etc/init.d/telegraf start`
`Starting the process telegraf [ OK ]`
`telegraf process was started [ OK ]`

### Additional info:

Nothing useful in /var/log/telegraf/telegraf.log

Switching to telegraf user, starting daemon provides useful output (line number of syntax error)

**Comment by lifeofguenter** [comment]
This way I discovered that the generated config with contained the following line that does not seem to be supported:

`write_consistency = "any"`

Log:

```
root@debian:~# sudo -u telegraf bash -c '/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d'
Error parsing /etc/telegraf/telegraf.conf, line 22: field corresponding to `write_consistency' is not defined in `*influxdb.InfluxDB'
```

**Comment by YerisAntonio** [comment]
Thanks

**Comment by sparrc** [comment]
from #1740:

## Bug report

### Relevant telegraf.conf:

Specifically broken:

```
[[outputs.influxdb]]
  database = "telegraf"
  interval = "1s"

```
### System info:

telegraf 1.0.0 on CentOS 6.

### Steps to reproduce:

Break the config with an invalid param. Attempt to start the service using the Red Hat LSB init script. 

### Expected behavior:

I should be told the service failed to start (the binary does return a non zero exit code it just gets lost in all the Bash / Su / nohup in there). At the very least I should see the config parser error in the log file.

### Actual behavior:

The service starts but dies immediately, but it tells me it started ok. No error message in the log because the init script sends STDOUT to /dev/null.

Actual error message is this:

```
[root@server ~]# /usr/bin/telegraf -pidfile /var/run/telegraf/telegraf.pid -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
Error parsing /etc/telegraf/telegraf.conf, line 24: field corresponding to `interval' is not defined in `*influxdb.InfluxDB'
```

### Proposal:

Quick fix would be to just not bury STDOUT, so you can at least see error in the log. More robust ways of handling this would be to introduce a config parser option, so you could test the config file validity first before you tried to spawn the real instance.

Another way might be to use the Red Hat daemon() function in /etc/rc.d/init.d/functions, but then you don't have a cross platform init script.
