### ISSUE TITLE
inputs.mysql Custom Queries

### ISSUE THREAD

**Issue by TrevorChan1** [influxdata/telegraf#13567]
### Use Case

Hello!

The [inputs.mysql](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mysql) input plugin currently only runs queries based on the pre-set settings provided (e.g. gather_table_schema). Although you can run custom queries on the [inputs.sql](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/sql) plugin, you can't run them on multiple servers due to the wide range of drivers supported (as mentioned in feature request #12882). Since you can't specify multiple servers in the sql input plugin, I was wondering if you could instead add the capability of specifying custom queries into the input plugins that support multiple servers (like mysql and sqlserver). 

This would allow users to gather both the custom and pre-set queries on a list of servers without having to split the input source between multiple input plugins, as well as creating a more compact configuration file as #12882 mentioned.

### Expected behavior

Being able to specify custom queries along with the pre-set queries provided by the current input plugin:

```
[[inputs.mysql]]
  servers = ["user1@tcp(exampleServer1)/", 
    "user2@tcp(exampleServer2)"]

  metric_version = 2
  gather_table_schema = true
  gather_slave_status = true

  [[inputs.mysql.query]]
    query="SELECT * FROM guests"
    measurement = "nation"
    tag_columns_include = ["name"]
    field_columns_exclude = ["name"]

  [[inputs.mysql.query]]
    query = "SELECT * FROM hosts"
```

### Actual behavior

Functionality is split so that inputs.mysql can't run custom queries and inputs.sql custom queries can not be run on a list of servers.

Thank you for your time!

**Comment by powersj** [comment]
Hi,

> Since you can't specify multiple servers in the sql input plugin

You can run mutliple plugins though. One plugin for each of the types of servers. Does that not work?

**Comment by TrevorChan1** [comment]
Thank you for the quick response! 

It would still work, but I think it would be a lot nicer to be able to grab all of the metrics from MySQL databases in one plugin. This would be a lot more convenient and compact for applications with many databases (for example, some of the AWS accounts I'm exporting RDS metrics from have up to 59 RDS instances which will currently require 59 SQL input plugins and 1 MySQL input plugin just for that one account). 

Along with making the configuration file more compact, it will also allow for the already available functionality to not be split up between multiple plugins. Since this was a feature that at least one person wanted for a similar input plugin, I wanted to see if it would be possible to implement the existing custom query functionality within the input plugins that already allow for multiple servers.

What are your thoughts on this?

**Comment by powersj** [comment]
> implement the existing custom query functionality within the input plugins that already allow for multiple servers.

You have identified a limitation of the sql plugin, I would rather fix that. My initial reaction is to instead add the ability for the sql plugin to allow for specifying multiple servers with the assumption that they all use the same driver.

This keeps the mysql plugin specific to pull metrics from an instance rather than doing custom work as well, avoids duplicating code, or needing to maintain compatibility between the two.

The two key things are:
1) new `dsns` array of DSNs
2) adding a tag to the measurements with the hostname where the data was collected

Is this something you would consider putting up a PR for?

**Comment by TrevorChan1** [comment]
> My initial reaction is to instead add the ability for the sql plugin to allow for specifying multiple servers with the assumption that they all use the same driver.

This is what feature request #12882 was asking about and Collaborator Hipska mentioned it would be difficult due to some SQL drivers not supporting lists of inputs / multiple server inputs. Either way that it's implemented (list inputs for SQL dsns or custom query on mysql input plugin) would be an enormous help! 

> Is this something you would consider putting up a PR for?

I don't have experience programming in GO so I'm not sure if I'd be able to create a PR for it. Would it require a big change?

**Comment by powersj** [comment]
He is right in that this introduces additional potential issues (e.g. timeout, delays), those issues can exist today with just a single server as well. We have plenty of other plugins where collections can occur across a variety of servers, the key will be informing the user of the risk via the readme and sample config and reporting errors as they occur.

> Would it require a big change?

I have only briefly looked at the code itself. As I mentioned above the key will be managing the config so that you add a new config option `dsns` and then ensure we loop through each of them to gather the required data.

I am inclined to close this issue and instead focus on the previous feature request in #12882.

**Comment by TrevorChan1** [comment]
> I am inclined to close this issue and instead focus on the previous feature request in #12882.

Sounds good, thank you!
