### ISSUE TITLE
Kafka-consumer cannot be stopped cleanly with regexp-topic-refresh-interval set

### ISSUE THREAD

**Issue by srebhan** [influxdata/telegraf#13595]
### Relevant telegraf.conf

```toml
[[inputs.kafka_consumer]]
  ...
  topic_refresh_interval = "10m"
  ...
```

With the addition of periodic topic refresh (`topic_refresh_interval`) Telegraf cannot be stopped cleanly, possibly leaking resources. This is due to the fact that `handleTicker` is started [in `Start()` at line 417](https://github.com/influxdata/telegraf/blob/d3c45417045c288d7c7efe8e1816180fb30ace7d/plugins/inputs/kafka_consumer/kafka_consumer.go#L417C7-L417C21) in a goroutine, but that go-routine can never complete. The cause is that the [infinite loop in `handleTicker`](https://github.com/influxdata/telegraf/blob/d3c45417045c288d7c7efe8e1816180fb30ace7d/plugins/inputs/kafka_consumer/kafka_consumer.go#L296) cannot be exited... Therefore on the plugin's `Stop()` this go-routine is left running forever not doing anything because the `ticker` is stopped [here](https://github.com/influxdata/telegraf/blob/d3c45417045c288d7c7efe8e1816180fb30ace7d/plugins/inputs/kafka_consumer/kafka_consumer.go#L452)...

Please allow canceling the go-routine to cleanly exit Telegraf on stop.

**Comment by srebhan** [comment]
@athornton can you please take a look!?

**Comment by athornton** [comment]
Will do.  Thanks for the report.

**Comment by powersj** [comment]
@athornton - @srebhan and I have chatted and due to the flaky tests that the PR introduced seen in #13615 and this issue we are going to revert the recent regex commit (#13410).

We are more than happy to get this added back in, but as it stands right now the flaky tests are slowing other PRs down and it is not something we want to keep in master as-is.

Again, happy to see the PR go back up and we can work with you on it further.

Thanks!
