### ISSUE TITLE
Please unify download urls

### ISSUE THREAD

**Issue by ricardclau** [influxdata/telegraf#1365]
At the moment, most telegraf download urls use hyphens but for some reason the .deb downloads have an underscore in front of the telegraf version. And then for instance the rpm files have an underscore before the word beta in the last 1.0.0?

Please see this list:

https://dl.influxdata.com/telegraf/releases/telegraf_1.0.0-beta1_amd64.deb
https://dl.influxdata.com/telegraf/releases/telegraf-1.0.0_beta1.x86_64.rpm
https://dl.influxdata.com/telegraf/releases/telegraf-1.0.0-beta1_linux_amd64.tar.gz
https://dl.influxdata.com/telegraf/releases/telegraf-1.0.0-beta1_windows_amd64.zip

Would it be possible to unify this to use hyphens everywhere and so that the version names are consistent for all platforms for 1.0.0? 

I assume all this is for historical reasons but if it is documented, I don´t think people would complain as this is for cohesion and it would help defining variables for tools like chef / puppet / ansible as in {{ url }}/telegraf-{{ version }}-{{ platform}}.{{ extension }}

**Comment by sparrc** [comment]
cc @rossmcdonald

**Comment by danielnelson** [comment]
I don't think this is possible since the package naming is done in the style of the distro, and they are at odds with each other.  Here are some links I dug up:

- https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_debian_package_file_names
- https://fedoraproject.org/wiki/Packaging:Versioning
