### ISSUE TITLE
agent: watch-config ignores default config file

### ISSUE THREAD

**Issue by redbaron** [influxdata/telegraf#13764]
### Relevant telegraf.conf

```toml
-
```

### Logs from Telegraf

```text
2023-08-14T21:44:58Z W! Cannot watch config : stat : no such file or directory
```

### System info

nightly

### Steps to reproduce

1. start telegraf with `--watch-config=poll` , but no `--config` or `--config-directory`
2. Telegraf loads default config file in /etc/telegraf/telegraf.conf
3. Updates to default config file are ignored 

### Expected behavior

All in-use config files should be watched, including default.

### Actual behavior

defult config file is not watched for changes

**Comment by powersj** [comment]
Hey,

I thought I had looked at this before, but this turned out to be easier than I thought. We were keeping a "fake" config file entry if no files were found, and instead of that I got rid of it and just loaded the default config files and saved them.

Can you give the artifacts in #13774 a try once up please?

Thanks!
