### ISSUE TITLE
Telegraf 

### ISSUE THREAD

**Issue by AfakTolgi** [influxdata/telegraf#13760]
### Relevant telegraf.conf

```toml
Default config
```

### Logs from Telegraf

```text
./telegraf flag redefined: v
panic: ./telegraf flag redefined: v

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc00013faa0, {0x8998f70, 0xc5ab260}, {0x89556d0, 0x1}, {0x7d8e7bd, 0x14})
        /usr/local/go/src/flag/flag.go:982 +0x2f9
flag.Var(...)
        /usr/local/go/src/flag/flag.go:997
github.com/aristanetworks/glog.init.0()
        /Users/atolgi/go/pkg/mod/github.com/aristanetworks/glog@v0.0.0-20191112221043-67e8567f59f3/glog_config.go:26 +0x4b
```

### System info

Telegraf 1.28.0, macOS 13.4.1

### Steps to reproduce

1. Add any function from the [ygot](https://pkg.go.dev/github.com/openconfig/ygot/ygot) module in any plugin, I tried with [Int8](https://pkg.go.dev/github.com/openconfig/ygot/ygot#Int8) function.
2. Do make test. 

### Expected behavior

Telegraf should run as expected 

### Actual behavior

Telegraf crashes with the error of flags getting redefined.

**Comment by powersj** [comment]
> ./telegraf flag redefined: v

I don't believe Telegraf does not have a flag of `-v` defined anywhere. This panic is saying that you now have two `-v` defined somewhere. The trace mentions `github.com/aristanetworks/glog`, which is an indirect dependency due to the lanz plugin. If I create a go project with just these two functions imported I get the same error about flag redefined:

```go
package main

import (
	_ "github.com/aristanetworks/glog"
	_ "github.com/openconfig/ygot/ygot"
)

func main() {}
```

aristanetworks/glog defines an `v` flag in an `init` function: https://github.com/aristanetworks/glog/blob/master/glog_config.go#L32 Then either ygot or one of its dependencies is also defining a `v` flag, probalby also in an `init` function.

> Add any function from the [ygot](https://pkg.go.dev/github.com/openconfig/ygot/ygot) module in any plugin, I tried with [Int8](https://pkg.go.dev/github.com/openconfig/ygot/ygot#Int8) function.

Sounds like you are maintaining your own a custom version of telegraf. If you look at the repo of ygot someone else has already field an issue a while ago about a redefined flag as well in https://github.com/openconfig/ygot/issues/314

I am going to close this as this is not an issue with telegraf, but an issue with one or both of the above libraries. I would suggest you go file issues with them and determine either a better way to import them or see if there is some other resolution.

**Comment by burnyd** [comment]
The issue that you are more than likely experiencing just by a guess is that ygot's go modules uses [glog](https://github.com/openconfig/ygot/blob/master/go.mod#L7)  and lanz in telegraf is leveraging glog with the arista module where telegraf is using the arista glog. 

I am wondering where ygot comes in the mix here and why you are using it?
