### ISSUE TITLE
output plugin to support multi-stage Telegraf architecture

### ISSUE THREAD

**Issue by beckettsean** [influxdata/telegraf#1421]
### Proposal:

In setups where there might be 100s or 1000s of Telegraf agents reporting to a single InfluxDB server, it can be very useful to batch the writes into groups of 10k or so points for maximum throughput. However, if Telegraf is sampling every 10s, it takes hours to generate 10k points for a batch. 

Ideally, the edge Telegraf instances could send their points to an intermediary Telegraf instance, which could then batch up a few thousand points multiple times per minute and send them to InfluxDB as a single batch. This greatly reduces the HTTP load on InfluxDB and allows for scaling Telegraf instances independent of the HTTP overhead to talk to InfluxDB.

### Current behavior:

For various reasons, this isn't possible right now. One Telegraf can't talk to another one in line protocol that is then output to InfluxDB.

### Desired behavior:

Telegraf can output line protocol to another Telegraf instance, which can batch and output that line protocol to yet another Telegraf instance, or to InfluxDB/Kapacitor.

### Use case:

Described in proposal.

**Comment by beckettsean** [comment]
@jackzampolin @kostasb please elaborate and correct what I've gotten wrong.

**Comment by jackzampolin** [comment]
Seems to me that the issue here is that the [`tcp_listener`](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/tcp_listener#tcp-listener-service-input-plugin) listens for tcp connections on the `/` route. The `influxdb` output plugin emits data to write to influxdb `/write?foo=bar`.

**Comment by sparrc** [comment]
I believe the only thing we need for this is a generic tcp output? is that correct?

**Comment by kostasb** [comment]
Currently the only way for Telegraf instance (A) to submit points in line protocol format to another Telegraf instance (B), is InfluxDB output with UDP configuration on A and UDP input on B.

We need a reliable protocol for data transfer so since there is already a TCP input plugin in Telegraf, the TCP output plugin is the missing link.

A Telegraf InfluxDB input plugin would work as well, plus it would allow direct integration of Telegraf and Kapacitor, correct me if I am wrong @rossmcdonald ? This requires handling HTTP response codes as well so it may be more complex.

@jackzampolin the TCP input will not work for the HTTP conversation with the InfluxDB Ouput plugin as the latter works over HTTP - e.g. the TCP input can't return HTTP 204 so instance A will never know whether the points have been accepted.

**Comment by kostasb** [comment]
@sparrc A Telegraf TCP output plugin is a good start for reliable clear text Telegraf to Telegraf communication.

I believe the second step should be an HTTP/HTTPS service input plugin that will return 204's on success as InfluxDB does.

@beckettsean thoughts?

**Comment by jackzampolin** [comment]
[This pull](https://github.com/influxdata/telegraf/pull/1407) adds the plugin to support telegraf to telegraf writing but does not support https.

Ideally this feature would have https support so that it could support writing over the open internet.  This would provide security for isolated telegraf instances as well as allowing users to offload https parsing overhead from InfluxDB to telegraf.

This would require a significant amount of authentication work on the InfluxDB output plugin as well as the proposed InfluxDB input plugin above.

**Comment by beckettsean** [comment]
I don't have a strong opinion on the setup, but we do need an authenticated connection that allows one Telegraf instance to report raw line protocol to another Telegraf instance, which then re-emits batched line protocol. I do think the 204s need to be returned since that's the expected behavior.

**Comment by sparrc** [comment]
there is now an http input listener in 1.1 that should support this feature, you can use the influxdb output to write to the http_listener: https://github.com/influxdata/telegraf/pull/1407
