### ISSUE TITLE
Telegraf not collecting data from all iscsi disks mounted on raspberry pi4

### ISSUE THREAD

**Issue by TheNighthawk99** [influxdata/telegraf#14228]
### Please direct all support questsions to slack or the forums. Thank you.

Hello,
I run Telegraf (v. 1.25.3) along with InfluxDB as docker containers on top of a Raspberry Pi4.
The host has the following devices shown by `lsblk -f` command:

```
sda         btrfs    BTRBK       <UUID>   42.5G    57% /mnt/iscsi-btrbk
sdb         btrfs    DOCKERHOST <UUID>   78.7G    20% /mnt/iscsi-docker
mmcblk0                                                                              
├─mmcblk0p1 vfat     system-boot <UUID>                             132.3M    48% /boot/firmware
├─mmcblk0p2 btrfs                <UUID> 211.8M    90% /var/lib/docker
└─mmcblk0p3 btrfs    btrfs       <UUID>  22.4G    53% /mnt/btrfs_pool
```

In InfluxDB data explorer I can only see the following devices: **mmcblk0p3** and **sdb**.
Unfortunately, the first device (sda) is not shown in the Disk stat section, while it is shown if I query the DiskIO section.

Could you address me how to fix this?
Thanks a lot.

Regards.

**Comment by powersj** [comment]
Hi,

Since it is not clear that this is actually an issue with telegraf, please use the slack or community forums. When posting please include your config and the logs from `[[outputs.file]]` as that will help identify what metrics are actually created in order to remove influxdb from the equation.

Also keep in mind that disk and diskio plugins gather data differently. Disk uses `/proc/self/mounts` and whatever is there. So if a disk is not listed there, then it won't get data from it. Gopsutil is the library used for all of these operations.

Diskio uses data from `/proc`.

Thanks
