### ISSUE TITLE
Validate the config at start, not runtime

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#1438]
### Proposal:

Telegraf should be able to validate config parameters at startup, instead of at runtime.
### Current behavior:

The only validation telegraf can do is that the config file parses correctly.
### Desired behavior:

Telegraf should also be able to validate the the config parameters are valid values (and valid combination of values).
### Use case: [Why is this important (helps with prioritizing requests)]

Instead of having to wait for runtime to pick up config errors, it would be a much better user experience prevent telegraf from starting up. This would ensure the application doesn't run with unnoticed errors.
### Proposal continuation:

The only way I can think of to do this would be to add a `Validate()` (or `Init()`) method to the `Input` interface.
The simple way of handling this in other config languages is to do the validation inside a `UnmarshalFOO()` method. But unfortunately due to the way the TOML works (the language itself), this is not possible.

---

What I mean by "_But unfortunately due to the way the TOML works (the language itself), this is not possible._":
Take the following config:

```
[[inputs.foo]]
  param1 = "123"
  [[inputs.foo.bar]]
    param2 = "456"
```

When the `UnmarshalTOML()` is called on `inputs.foo`, it's not going to contain `[[inputs.foo.bar]]`, meaning a chunk of the configuration is missing. And the parser's beahvior can't be adjusted for this as the label `[[inputs.foo.bar]]` is anchored at top scope. In the context of the `UnmarshalTOML()` method, it's going to have no clue what `inputs.foo` is. You'd have to rewrite it to `[[bar]]`, which you can't do reliably, at least not without major difficulty.

**Comment by danielnelson** [comment]
> The only way I can think of to do this would be to add a Validate() (or Init()) method to the Input interface.

I've been thinking about this as well, it would also simplify one time initialization.  Maybe instead of using init functions we could register a `New(config ???)` function?

**Comment by phemmer** [comment]
Not sure how you'd do a `New(config)`. Since the config is built using struct tags, the object has to already be created.
With the JSON parser you can do things like `{"obj1conf":foo, "obj2conf":bar}`, and define a custom unmarshaller for "obj1conf", and the json lib won't even try to parse `foo`, it'll pass the raw bytes to the unmarshaller. While this offers infinite options, it's rather heavy handed. Plus I highly doubt the TOML lib can do that.
We could do something like each plugin creates a "config struct", and this struct has a `New()` method which is supposed to return something matching the `telegraf.Input` interface. But I don't see much advantage over just having one struct with an `Init()` method.

**Comment by danielnelson** [comment]
If we can avoid two phase construction I think it would be preferred, since it avoids the state where the object is not initialized.  Of course if it can't work out with the TOML construction then Init() is the next best thing, and I haven't looked deeply into this code yet.  Yeah, I don't want to have to go with two structs, seems like overkill.  I do want to get rid of the static registration, its just not very flexible.

**Comment by PhoenixRion** [comment]
I am working on an aggregator plugin and ran into the situation where I want to validate part of the config but none of the [Aggregator](https://github.com/influxdata/telegraf/blob/1.10.2/aggregator.go) functions return an error.

**Comment by danielnelson** [comment]
I do have a prototype of loading plugins with a `New()` function, but it requires quite a few changes and I doubt I will have time to complete it soon.  With that in mind I think we should roll out an `Init()` function for all plugin types as it would be much easier, and I agree that New() vs Init() different is minor since the agent controls the initialization and so it only needs to be written correctly once for each plugin type, not on every plugin.

Currently on the aggregator issue, the only thing you will be able to do now is log on the first call to Add() or Push(), you won't be able to signal Telegraf to exit.  Not very nice I know.
