### ISSUE TITLE
/lib/systemd/system/telegraf.service:11: Unknown key name 'ImportCredential' in section 'Service', ignoring.

### ISSUE THREAD

**Issue by electrofloat** [influxdata/telegraf#14466]
### Relevant telegraf.conf

```toml
nope
```

### Logs from Telegraf

```text
nope
```

### System info

Ubuntu 22.04

### Steps to reproduce

Installed telegraf (a long time ago) according to the docs on Ubuntu 22.04: https://docs.influxdata.com/telegraf/v1/install/#install-from-the-influxdata-repository

Recently I noticed the following in the logs:
`Dec 15 21:10:09 gw systemd[1]: /lib/systemd/system/telegraf.service:11: Unknown key name 'ImportCredential' in section 'Service', ignoring.`

### Expected behavior

The above log does not get logged.

### Actual behavior

`Dec 15 21:10:09 gw systemd[1]: /lib/systemd/system/telegraf.service:11: Unknown key name 'ImportCredential' in section 'Service', ignoring.`

### Additional info

There is no 'ImportCredential' key in a systemd service definition (not that I know of)

**Comment by powersj** [comment]
> There is no 'ImportCredential' key in a systemd service definition (not that I know of)

See either of the following:

* https://systemd.io/CREDENTIALS/
* https://www.freedesktop.org/software/systemd/man/latest/systemd-creds.html

The value was added as part of the systemd secret store. This is not an error, nor does it prevent the service from starting. Can you confirm?

Thanks

**Comment by electrofloat** [comment]
There is no `systemd-creds` binary on Ubuntu 22.04. This version of Ubuntu only has `systemd 249 (249.11-0ubuntu3.11)`, and it seems this `creds` is only in from 250?

It's not an error per se, since systemd is ignoring the unknown key, but it is still logging about it which is right since that is a nonexisting key in that version of systemd.

**Comment by powersj** [comment]
> There is no systemd-creds binary on Ubuntu 22.04.
> it is still logging about it which is right since that is a nonexisting key in that version of systemd.

correct - and that is fine as the value is ignored.

**Comment by electrofloat** [comment]
I've a logcheck setup which sends me any logs that are not ignored explicitly. That is why I noticed this. I can of course ignore this log (so it does not get sent to me every time systemd reloaded) but it would much better if did not get logged in the first place.

Now I'm assuming you don't want to fix this, since there is only one .deb repo, and a lot of things needed to be changed then (like the docs, creating a repo just for Ubuntu 22.04, and/or other flavors which does not have the expected systemd version, etc.), and you already made internal changes to handle the case where `ImportCredential` is already used.

Now this is all assumptions. But if you think this does not need fixing (and telegraf still works without this key in the .service file), feel free to close this issue, and I'm going to ignore that logline then... (which I still uphold that it is not the right solution).

**Comment by powersj** [comment]
We do not build custom RPMs or DEBs for every distro and release. The packages we provide all use the same static binary and packaging. In fact it is literally the same package used for all of them with symlinks. Maintaining different service files for every different release is beyond the scope of the packages we provide.

If you want something that is packaged specifically for your own distro version, then using the in-distro version is preferred, but at the cost of using an old version.

New versions of packages will come with new log messages. While reviewing the original PR I even asked about [the new option](https://github.com/influxdata/telegraf/pull/13657/files#r1344274710), but since it does not interfere with operation it is acceptable.

**Comment by mdella-nutanix** [comment]
Just as a side comment, ever since upgrading telegraf to the lastest version within our "Ubuntu 20.04.6 LTS" based OSs, this error comes up every time we restart or reload telegraf. Yep, its a benign error, but the negative entry in the log makes it thru filtering up to the NOC. Its now the "boy who called wolf" in our monitoring system. We're trying to stamp it out but we don't have SALT on all of our servers and systems in our QA department. So we get around 500 of these a day (we run and reboot a LOT of VMs constantly in our QA department).  Since the error is generated in the "systemd" area (and not specifically telegraf), it bubbles up on the "important to check" list.

Just my $0.02, if you're going to make something create an error entry even if benign, please be aware that "automation" isn't always smart enough to separate the noise. We're writing some filters on this but its engineering hours and review to get the filters made tested, signed off, deployed, etc.

Just sayin. Not everyone runs small nimble operations, sadly on my part.

**Comment by xDR1TeK** [comment]
I imagine the ImportCredential line there can be totally removed and no implication on the usage. Please say yes. xD

**Comment by elofu17** [comment]
I too would like an answer to xDR1TeK's question. Then I can simply sed this line out as a workarond.
