### ISSUE TITLE
subscription management for clean sessions

### ISSUE THREAD

**Issue by vielleicht** [influxdata/telegraf#14825]
### Use Case

Having set `persistent_session = true`, subscriptions are not updated on a new connection. This may lead to [missing subscriptions](https://github.com/influxdata/telegraf/issues/14749) if used careless, as the broker keeps subscriptions and the client does no updates. Having a persistent session turned on to not miss QOS1 or QOS2 messages, prevents getting updates on chaging topic subscriptions.  

### Expected behavior

When changing subscription topics in the [inputs.mqtt] plugin configuration, the changes should be updated on a new connection to the broker, even with having turned on `persistend_session`. Both by unsubscribing removed topic and by adding subscriptions to new topics. This would need some caching of subscribed topics.

### Actual behavior

Subscriptions are not updated, as far as `persistent_session = true` due to the reason, that the broker keeps subscriptions after connection loss. This took me quite a while to debug.

**Comment by powersj** [comment]
> Subscriptions are not updated, as far as persistent_session = true due to the reason, that the broker keeps subscriptions after connection loss. This took me quite a while to debug.

We tried to clarify this behavior in #14366 to resolve #9703 via the docs. We had a discussion about this and decided against trying to keep track of the state of topics across usage.

The sessions are stored by the server, so if a session is present we skip subscribing. Meaning if the user does make changes they need to update the client id or drop the existing client id store from the server.

Since we weren't inclined to make any changes a few months ago I don't expect us to now.
