### ISSUE TITLE
Telegraf should do exponential backoff on gather operations when timeout occurs for input plugins

### ISSUE THREAD

**Issue by slaymaker1907** [influxdata/telegraf#14911]
### Use Case

Currently, if a timeout (such as the 5s default timeout on the sql plugin) is used by input plugin, it will repeat the gather operation continuously. This is a serious problem for a distributed system because a non-abortable operation might be going on and thus lead to a "traffic jam" with a shared resource.

### Expected behavior

When timeout or some other error occurs, the effective gather operation interval should be reduced (particularly with the sql input plugin).

### Actual behavior

Telegraf will retry the operation every at every interval.

### Additional info

This behavior should ideally be default if it needs to be configurable.

**Comment by powersj** [comment]
> the effective gather operation interval should be reduced
> > When timeout or some other error occurs, the effective gather operation interval should be reduced

The gather cycle of collection inputs (i.e. those that run gather) is set to a global ticker based on the global interval or input specific interval. Currently Telegraf does not react to errors found during gather in anyway, beyond skipping a new interval if the previous interval is still taking place.

> This is a serious problem for a distributed system because a non-abortable operation might be going on and thus lead to a "traffic jam" with a shared resource.

Since you seem most interested With the SQL plugin, what is an example of a non-abortable operation? Have you actually seen a case for this and if so could you provide the logs?
