### ISSUE TITLE
Procstat Lookup reports PID as running even though the process is dead

### ISSUE THREAD

**Issue by kb-elmo** [influxdata/telegraf#15107]
### Relevant telegraf.conf

```toml
[[inputs.procstat]]
  pid_file = "< path_to_pidfile >"
```

### Logs from Telegraf

```text
irrelevant as there is no loggin activity that shows this issue
```

### System info

Telegraf 1.30.1, Debian 11

### Steps to reproduce

1. setup procstat check with a provided PID file
2. kill the process from the PID file

### Expected behavior

The "running" metric should go to 0 indicating that the process with the PID listed in the provided file is dead

### Actual behavior

The "running" metric keeps being reported as 1 even though the PID is gone

**Comment by powersj** [comment]
Hi,

Because the pidfile continues to have the pid in it, telegraf assumes the pid is running. This behavior looks to have always existed as far back at v1.14.0.

The pidfile mechanism reads a file containing a PID and returns the numeric pid, or pids found in that file. The pidfile parsing does not look up if the PID actually exists or is running.

It looks like we keep a global map of processes `p.processes[pid]`. This map is used to store process information for deltas. Telegraf marks a process as running if it is found in this global map. The only way to remove data from this map is if the mechanism used to look up PIDs, a pidfile in this case, does not return a pid.

I would somewhat expect a process to update the PID file when it closes out. And if you do remove the PID from the file you get the expected behavior:

```
procstat_lookup,pid_finder=pgrep,pidfile=process.pid,result=success pid_count=1i,running=1i,result_code=0i 1712328160000000000
# pid ends, clears the file now get an error on lookup because no PID exists:
procstat_lookup,pid_finder=pgrep,result=lookup_error running=0i,result_code=1i,pid_count=0i 1712328170000000000
```

Let me talk to the team about this.

**Comment by kb-elmo** [comment]
> I would somewhat expect a process to update the PID file when it closes out. And if you do remove the PID from the file you get the expected behavior:

This only works if the process quits in a controlled manner.
If it crashes for any reason the PID file will usually continue to exist even though the process is gone.

Not actually checking if the process exists and just assuming it does just because the PID file is there doesn't really make much sense in a monitoring context imho.

And checking if a process for a given PID still exists should be pretty straightforward and simple I think.
Especially on Nix based systems (idk about Windows).

**Comment by powersj** [comment]
We will take a look at this. We would like to improve the situation. It is not clear if this would happen right when we read the PID file itself or at a later state when going through the reported PIDs.

**Comment by srebhan** [comment]
@kb-elmo please test the binary in PR #15260 and let me know if this fixes the issue!
