### ISSUE TITLE
SQLServer plugin shows wrong latency values

### ISSUE THREAD

**Issue by summertony15** [influxdata/telegraf#15275]
### Please direct all support questsions to slack or the forums. Thank you.

I am using SQL server plugin to monitor database latency
And here are my conf
'[agent]
  interval = "10s"
  [[inputs.sqlserver]]

  servers = [
    "Server=192.168.1.76;Port=1433;User Id=<user>;Password=<password>;app name=telegraf;log=1;",
  ]
  database_type = "SQLServer"'

But what I found from the metric is:
<img width="1096" alt="截圖 2024-05-02 11 15 16" src="https://github.com/influxdata/telegraf/assets/33056261/4a8a7a88-a9ae-4c90-8655-ed306596507a">
There are many abnormal peak values for read and write latency, which is over 10,000,000 ms.
Are these stats multiplied out correctly, or could they be out by 10^3 or 10^6
Are these figures cumulative, even though the metric says Average?If so, should we be dividing the latency by the number of reads or writes to get the average per transaction?

**Comment by srebhan** [comment]
@Trovalo any idea what is going on here? Is there a chance that those are micro- or nanoseconds?

**Comment by Trovalo** [comment]
The number is fine as it is, but it's not an average... it's the total "latency" since the beginning of time (server start).
Here are the [MsDocs](https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-io-virtual-file-stats-transact-sql?view=sql-server-ver16#table-returned), reference to `io_stall_read_ms`.

Going back to Telegraf, if you want the average latency, divide `read_latency_ms` by `reads`, and you will have the average latency per read (since the beginning of time... not so useful), do the same with the difference between samples (as that's an incremental counter) and you will have the actual latency per time interval

something like this (on InfluxDB)
```
SELECT
	 non_negative_difference(last("read_bytes")) AS "read_bytes"
	,non_negative_difference(last("read_latency_ms")) AS "read_latency_ms"
	,non_negative_difference(last("reads")) AS "reads"
	,.....
FROM ___."sqlserver_database_io"
WHERE time >= now()-5m
GROUP BY
	time(1m)
	,*
```

**Comment by powersj** [comment]
Thanks for the quick explanation Trovalo. I'm closing this as it isn't an issue.
