### ISSUE TITLE
feat(processors): Traffic shaper processor plugin to shape uneven distribution of incoming metrics

### ISSUE THREAD

**Issue by lakshmansai** [influxdata/telegraf#15353]
### Use Case

An in-memory traffic shaper processor which evens out traffic so that output traffic is uniform

We use telegraf as a proxy and we receive data that is spiky in nature, in our every 10 minute we receive a spike and this affects our downstream systems since it needs to also process at the same rate, this leads to wastage of resource since the cpu, memory needs to be provisioned for peaks 

Screenshot showing spiky nature of data
<img width="663" alt="Screenshot 2024-05-10 at 2 32 43 PM" src="https://github.com/influxdata/telegraf/assets/14791668/17aec7a0-9e1d-4c59-97f1-af4b7a6e0fb7">

### Expected behavior

-

### Actual behavior

We have implemented a traffic shaper plugin in telegraf which evens out the spike and help us maintain a steady rate.

Example post using traffic shaper plugin we can see after 00:00 the traffic became uniform

![traffic_distribution](https://github.com/influxdata/telegraf/assets/14791668/c65603fb-5b41-4940-b53d-403a580f916b)

**Comment by powersj** [comment]
Hi,

After discussing with the team, we would prefer that rate limiting like this occur in outputs instead of a processor. We have an open issue for this in: https://github.com/influxdata/telegraf/issues/14802 That is where I would want to continue this discussion.

The processor solution unfortunately adds a second buffer, which introduces another set of issues. You can see some examples of this [#802](https://github.com/influxdata/telegraf/issues/802) for a way to maintain the buffer outside of memory via a WAL and how to control the buffer itself with https://github.com/influxdata/telegraf/issues/15208 and https://github.com/influxdata/telegraf/issues/15217.

As such we do not wish to add a processor, but would take a PR to look at output rate limiting. I will close this issue and the PR.
