### ISSUE TITLE
Add back constants in the logging package

### ISSUE THREAD

**Issue by zmyzheng** [influxdata/telegraf#15513]
### Use Case

We have a project referring to Telegraf as a direct dependency. Before v1.31.0, Telegraf has some public constants inside logging package: https://github.com/influxdata/telegraf/blob/release-1.30/logger/logger.go#L20~#L23. Starting from v1.31.0, these constants are removed and hard-coded strings are used instead in the code. This seems to be a breaking change for us as our project builds on top of the Telegraf logging mechanism and referring to those constants. This change is not announced in the release announcement of v1.31.0 so we didn't realize of it until our build fails after upgrading Telegraf to 1.31.0. It would be great if we can add back those constants to Telegraf source code to have a consistent behavior as the historical code and avoid hard-coded string in the source code. 

### Expected behavior

We expect the below 2 constants existing in the logging package:

> const (
	LogTargetFile   = "file"
	LogTargetStderr = "stderr"
)

### Actual behavior

The above 2 constants are removed from v1.31.0 but was not mentioned in the release announcement.

**Comment by powersj** [comment]
Thanks for the PR as well. We'll take a look at that tomorrow.

> The above 2 constants are removed from v1.31.0 but was not mentioned in the release announcement.

We make no promises about the internals of Telegraf and reserve the right to make changes to any and all of the internals. Fundamentally, Telegraf's end product is a static-binary, CLI tool. The change log will cover user-facing changes in these situations. While the code base can be imported directly, it is not something we directly advertise or even advise doing, that is not our primary use-case.

Our primary concern with backwards compatibility is with a configuration and ensuring previous behavior of the plugins and various options. In order to do that we need some way leeway at times with other internals to be able to make enhances and resolve other feature requests. The changes to logging in this case were the start of some larger changes to enable us to support plugin-specific logging, structured logging, etc.

**Comment by zmyzheng** [comment]
> ehavior of the plugins and various options. In order to do that we need some way leeway at times with other internals to be able to make enhancements and resolve other feature requests. The changes to logging in this case w

Thanks @powersj so much for the detailed explanation of this change. Totally agree that this is not the user-facing change so it makes sense not inlcuding it in the release announcement. Glad to see the continuous enhancements of Telegraf logging with more features.
