### ISSUE TITLE
Netflow Plugin does not collect all flows

### ISSUE THREAD

**Issue by fawzy46** [influxdata/telegraf#15676]
### Relevant telegraf.conf

```toml
[[inputs.netflow]]
    service_address = "udp4://:2055"

 [[outputs.influxdb_v2]]
   urls = ["http://192.168.2.62:8086"]
   token = ""
   organization = "OpenWrt"
   bucket = "openwrt"
```

### Logs from Telegraf

```text
2024-07-28T17:20:13Z I! Loading config: /etc/telegraf/telegraf.conf
2024-07-28T17:20:13Z I! Starting Telegraf 1.31.2 brought to you by InfluxData the makers of InfluxDB
2024-07-28T17:20:13Z I! Available plugins: 234 inputs, 9 aggregators, 32 processors, 26 parsers, 60 outputs, 6 secret-stores
2024-07-28T17:20:13Z I! Loaded inputs: netflow
2024-07-28T17:20:13Z I! Loaded aggregators:
2024-07-28T17:20:13Z I! Loaded processors:
2024-07-28T17:20:13Z I! Loaded secretstores:
2024-07-28T17:20:13Z I! Loaded outputs: influxdb_v2
2024-07-28T17:20:13Z I! Tags enabled: host=OpenWrt
2024-07-28T17:20:13Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"OpenWrt", Flush Interval:10s
2024-07-28T17:20:13Z D! [agent] Initializing plugins
2024-07-28T17:20:13Z I! [inputs.netflow] Loaded 0 PEN mappings...
2024-07-28T17:20:13Z D! [agent] Connecting outputs
2024-07-28T17:20:13Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2024-07-28T17:20:13Z D! [agent] Successfully connected to outputs.influxdb_v2
2024-07-28T17:20:13Z D! [agent] Starting service inputs
2024-07-28T17:20:13Z I! [inputs.netflow] Listening on udp://0.0.0.0:2055
2024-07-28T17:20:23Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
2024-07-28T17:20:33Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
2024-07-28T17:20:43Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
2024-07-28T17:20:53Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
2024-07-28T17:21:01Z D! [inputs.netflow]  received 1364 bytes
2024-07-28T17:21:01Z D! [inputs.netflow]  received 1424 bytes
2024-07-28T17:21:01Z D! [inputs.netflow]  received 1384 bytes
2024-07-28T17:21:01Z D! [inputs.netflow]  received 1384 bytes
2024-07-28T17:21:01Z D! [inputs.netflow]  received 1384 bytes
2024-07-28T17:21:01Z D! [inputs.netflow]  received 1424 bytes
2024-07-28T17:21:01Z D! [inputs.netflow]  received 1104 bytes
2024-07-28T17:21:03Z D! [outputs.influxdb_v2]  Wrote batch of 226 metrics in 105.780238ms
2024-07-28T17:21:03Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
```

### System info

Telegraf 1.31.2 openwrt x86

### Steps to reproduce

1. enable inputs.netflow

### Expected behavior

all flows exported by softflowd should be available/collected by the netflow plugin Netflow

### Actual behavior

most of the exported flow is missing

### Additional info

I am using softflowd with the attached configuration.  I used nfdump to view the collected flows, and everything appears fine, but in the Netflow measurement some dst/src IPs do not have any flow records at all in influxdb

for example nfdump report this flow

`2024-07-28 19:37:02.764     00:00:15.187 TCP     213.158.191.18:8080  ->     192.168.2.20:51088    10476   15.5 M     1`

when I query influxdb with IP of `213.158.191.18` no entries were found

telegraf does not show any error/warning messages at all. 

config softflowd

	option enabled '1'
	option interface 'eth0'
	option max_flows '8192'
	option host_port '192.168.2.1:2055'
	option pid_file '/var/run/softflowd.pid'
	option control_socket '/var/run/softflowd.ctl'
	option export_version '9'
	option tracking_level 'full'
	option track_ipv6 '0'
	option sampling_rate '1'

**Comment by srebhan** [comment]
@fawzy46 are you _really_ sure the packets actually contain flows and not only template definitions? Usually the agent sends the templates for its data packets first and afterwards sends the _real_ flow samples. If you are sure those are flows, could you please set the (hidden) `dump_packets` setting to `true` for the plugin and post some (redacted) samples of the missing flows... Or provide a tcpdump of the whole conversation, whatever is easier for you...

**Comment by fawzy46** [comment]
I am very sorry for my late reply.
I have attached the pcap file for the flow capture and indeed the flows get exported with no issues. 

IPs with range `213.0.0.0/8` (speedtest servers) are present in the exported flows but when I query them in influx db the query returns no matches

telegraf logs also included with `dump_packets = true`

[netflow.zip](https://github.com/user-attachments/files/16418844/netflow.zip)
[telegraf.log](https://github.com/user-attachments/files/16418922/telegraf.log)

**Comment by srebhan** [comment]
@fawzy46 sorry for the late reply, I was on holidays for a few days and the investigation took longer than expected. ;-) I guess the issue you are seeing is because you are not tagging the produced metrics correctly and therefore multiple metrics with the same timestamp overwrite each other.

I used your attached pcap file and filtered the "cflows" (see [netflow_issue_15676.pcap.zip](https://github.com/user-attachments/files/16509043/netflow_issue_15676.pcap.zip)). I then replayed the packets and see 3476 metrics produced by Telegraf (see [expected.out.zip](https://github.com/user-attachments/files/16509053/expected.out.zip)) including flows in the `213.0.0.0/8` range.

To make sure you retain the metrics in InfluxDB you probably need to tag them with the `protocol`, the `src` and `src_port` as well as the `dst` and `dst_port` but be careful as this might introduce high cardinality!

**Comment by fawzy46** [comment]
@srebhan I hope you had a wonderful holiday, I will try the custom tag and see how it goes.

on a side note (as this is way out of my experience😅 ), could the plugin itself generate a random hash value and tag the metric with it by default to avoid the overwrite issue? as the probability for 2 netflows to have the same timestamp is very high.

**Comment by srebhan** [comment]
@fawzy46 the issue is the high cardinality, that's why we leave it to the user to choose suitable tags. You can easily convert fields to tags using e.g. the [converter processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/converter). In your case this would be

```toml
[[processors.converter]]
  [processors.converter.fields]
    tag = ["protocol", "src", "src_port", "dst", "dst_port"]
```

In case you can confirm that this works for you, I can add this to the README of the netflow plugin as I do agree this is maybe surprising for "newbies". ;-)

**Comment by fawzy46** [comment]
I do agree, it should be added to the README.

after adding the tags all the metrics got logged without any issue. 


Thanks for your effort and support @srebhan

**Comment by srebhan** [comment]
@fawzy46 is the comment in PR #15713 clear and understandable?

**Comment by fawzy46** [comment]
Yes, thanks again for your effort

**Comment by coda88** [comment]
Each netflow packet could contain multiple flowset with multiple flows in each flowset. 

To avoid measurements with the same timestamp from being overwritten, is it possible to add the flowset index and the flow index as tags to ensure each of the flow data is treated as unique?

> @fawzy46 sorry for the late reply, I was on holidays for a few days and the investigation took longer than expected. ;-) I guess the issue you are seeing is because you are not tagging the produced metrics correctly and therefore multiple metrics with the same timestamp overwrite each other.
> 
> I used your attached pcap file and filtered the "cflows" (see [netflow_issue_15676.pcap.zip](https://github.com/user-attachments/files/16509043/netflow_issue_15676.pcap.zip)). I then replayed the packets and see 3476 metrics produced by Telegraf (see [expected.out.zip](https://github.com/user-attachments/files/16509053/expected.out.zip)) including flows in the `213.0.0.0/8` range.
> 
> To make sure you retain the metrics in InfluxDB you probably need to tag them with the `protocol`, the `src` and `src_port` as well as the `dst` and `dst_port` but be careful as this might introduce high cardinality!

**Comment by srebhan** [comment]
> To avoid measurements with the same timestamp from being overwritten, is it possible to add the flowset index and the flow index as tags to ensure each of the flow data is treated as unique?

No, I'm strongly vetoing this! This will create an enormous cardinality issue as those flows are not ordered at all! The idea with _NOT_ adding certain tags was especially for _avoiding_ cardinality issues. You should use a processor to tag your flows to be unique such as source-destination pairs or similar. If you want to index the metrics you are free to do so using the `starlark` processor.

**Comment by coda88** [comment]
Agree that while adding the flowset index and flow index tags will increase cardinality to a certain extent, it should be limited to the 'max number of flowset' x 'max number of flows per flowset' in each netflow packet. This number is limited by the netflow packet size itself, and is not unbounded.

But I understand your concern about introducing cardinality. 

How about adding the flowset index and flow index as fields instead so that it's simpler to use a `converter` processor to convert them to tags?

Otherwise using `starlark` processor, we have to keep state of all metrics with the same timestamp, and then enumerate them to generate a unique tag values to disambiguate them.

**Comment by srebhan** [comment]
Hmmm wouldn't it be enough to just keep the timestamp and a counter? As the flows are time-stamped on reception, the timestamp should be monotonically increasing so you reset the counter if a timestamp arrives that is larger than the stored one... But if you want, you can propose a PR covered by a flag for adding the index...
