### ISSUE TITLE
[inputs.gnmi] authentication fails if password contains double dollar sign

### ISSUE THREAD

**Issue by egr3s** [influxdata/telegraf#16025]
### Relevant telegraf.conf

```toml
[[inputs.gnmi]]
       addresses = [ "address" ]
       username = "username"
       password = "test$$pass123"
       encoding = "json"
       redial = "10s"
       tls_enable = true
       tls_ca = "/ca.crt"
       insecure_skip_verify = true
```

### Logs from Telegraf

```text
2024-10-15T14:19:07Z E! [inputs.gnmi] Error in plugin: aborted gNMI subscription: rpc error: code = Unauthenticated desc = Authentication failed - invalid username or password
2024-10-15T14:19:18Z E! [inputs.gnmi] Error in plugin: aborted gNMI subscription: rpc error: code = Unauthenticated desc = Authentication failed - invalid username or password
2024-10-15T14:19:29Z E! [inputs.gnmi] Error in plugin: aborted gNMI subscription: rpc error: code = Unauthenticated desc = Authentication failed - invalid username or password
```

### System info

telegraf:1.32.0

### Steps to reproduce

1. Create gNMI subscription with a password containing double dollar sign, e.g. `test$$pass123`
...
2. Subscription fails due to authentication issue
3. Change password to `test!$pass123` - everything works fine
This is not a router (gNMI server) issue, as authentication with the same password by other means (e.g. gnmic) works fine
```
$ gnmic --skip-verify -a address -u user -p 'test$$pass123' get --path "/state/port" | head -10
[
  {
    "source": "source",
    "updates": [
      {
```

### Expected behavior

Authentication should work

### Actual behavior

Auth doesn't work

### Additional info

Seems like telegraf drops one dollar sign, as it is seen from the tcpdump
```
Configured: test$$pass123
Seen:
Header: password: test$pass123
            Name Length: 8
            Name: password
            Value Length: 12
            Value: test$pass123
```
```
Configured: *3#Y!oW#B$$#4l6
Seen in tcpdump: Value: *3#Y!oW#B$#4l6

```

**Comment by srebhan** [comment]
@egr3s the issue comes from the way we do environment substitution... As you might know you can use environment variables in settings like `password = "${MYPASS}"`. To be able to specify `${MYPASS}` as literal the underlying library allows to set `password = "$${MYPASS}"` which will not resolve `MYPASS` as environment variable but the double-dollar escapes the expression and internally results in `password` to be set to `${MYPASS}` (literally, not resolving it as env-var).

So to put a `$$` in you password `test$$pass123` you need to set it to `"test$$$$pass123"`. We cannot change this behavior without breaking all kind of configs so that's the best we can do...

**Comment by egr3s** [comment]
Thanks for the explanation, good to know that.
I think we'll then just try avoid dollar signs, since we generate passwords programmatically.
