### ISSUE TITLE
`round_interval` seems not to be used (anymore?) is still documented, and confuses me.

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#16068]
### Relevant telegraf.conf

```toml
# telegraf.conf

round_interval = true
```

### System info

1.32.0

### Expected behavior

I find `round_interval` in our config and in the docs.
I would expect a `grep -R round_interval` to find go-code using this config option.

### Actual behavior

I didn't find go-code using `round_interval` with `grep -R round_interval`. So I believe it doesn't do anything. So I think it should be removed from examples and docs.

**Comment by srebhan** [comment]
@knollet don't be afraid, it is still used! :-) The property is defined in the [`AgentConfig` structure](https://github.com/influxdata/telegraf/blob/c73559dc6c01a941cf8bcc75c64e6555a27d9947/config/config.go#L166) and is [filled during configuration loading](https://github.com/influxdata/telegraf/blob/c73559dc6c01a941cf8bcc75c64e6555a27d9947/config/config.go#L544).

The reason you cannot find `round_interval` is because we do not have explicit TOML-tag-annotations for some of the structures (I know it's bad) and so the TOML parser infers the name from the Golang name to `round_interval`...
