### ISSUE TITLE
Telegraf inputs.docker wont send metrics correctly to questdb 

### ISSUE THREAD

**Issue by mehrdad2000** [influxdata/telegraf#16126]
Hi try to send inputs.docker via telegraf to questdb but got this error in questdb:

```
2024-11-02T13:43:11.605205Z E i.q.c.l.t.LineTcpMeasurementScheduler could not create table [tableName=docker_container_status, errno=-102, ex=table is dropped [dirName=docker_container_status~42543, tableName=docker_container_status]] 
2024-11-02T13:43:11.605242Z E i.q.c.l.t.LineTcpConnectionContext [372] could not parse measurement, NONE at 430, line (may be mangled due to partial parsing): ‘docker_container_status,container_image=bfabbaf5985e,container_name=mycontainername,container_status=running,container_version=unknown,engine_host=deploy,host=deploy,io.buildah.version=1.33.8,server_version=4.9.4-rhel container_id=“d4f707e96dcefcf0066eff54d70c4b122bf6f1ed50e1f4df71cadb2cad701da7”,started_at=1730550764250914871i,uptime_ns=4216199399846i,oomkilled=false,pid=10525i,exitcode=0i,restart_count=0i 1730554980000000000’
```

Here is the plugin repo:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/docker/README.md

telegraf send output:
[[outputs.socket_writer]]
address = “tcp://192.168.1.1:9009” (edited)

Any idea?
Thanks

**Comment by srebhan** [comment]
@mehrdad2000 we do have the bug-**template** for a reason to make sure we get all relevant information. So please try to follow this next time!

Your QuestDB server rejects the valid line-protocol message, why do you think this is a problem in Telegraf?

**Comment by jerrinot** [comment]
Jaromir from QuestDB team here: This is caused by a tag with a dot in the name: `io.buildah.version=1.33.8`

QuestD translates tags to table columns and does not support column names with a dot. QuestDB official clients validate against this, but obviously a Telegraf socket plugin cannot know this :) 

Workaround: Use the [rename](https://github.com/influxdata/telegraf/tree/master/plugins/processors/rename) plugin to rename `io.buildah.version` to e.g. `io_buildah_version`.

This issue can be closed, there is nothing wrong Telegraf.

**Comment by mehrdad2000** [comment]
@jerrinot Hi, Thank you.
I remember that I had the same issue before. At that time it took a long time for me to figure out I should rename the field.
As a suggestion, it would be better if Questdb showed a more relevant error code that made troubleshooting easier.
Thanks

**Comment by jerrinot** [comment]
@mehrdad2000 I agree with this suggestion. This is because ILP over raw TCP transport - which the Socket output uses - is a legacy. We recommend using ILP over HTTP transport by default. 

There is a descriptive error when ILP over HTTP transport is used. From Telegraf, you can use ILP@HTTP with the InfluxDB output as documented here: https://questdb.io/docs/third-party-tools/telegraf/#writing-to-questdb-over-http

**Comment by mehrdad2000** [comment]
@srebhan is there any way instead of rename each field that contain special character with telegraf, set global rule that remove all special character or replace by something else?

**Comment by srebhan** [comment]
@mehrdad2000 you are probably getting a more timely answer in our Slack channel. Yes, you can use the [regexp processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/regex) for this...
