### ISSUE TITLE
Telegraf logparser plugin grok help needed

### ISSUE THREAD

**Issue by discoduck2x** [influxdata/telegraf#1649]
version 1.0.0-beta3 , windows 2012

Using tshark to gather comma separated data and parse with telegrafs logparser plugin, 

fileline example
**1471471812.246093000**,8.8.8.8,9.9.9.9,1

..where **1471471812.246093000** is the epoch time , however i cant figure out how to construct a grok pattern that gets RID of the "." , the time-epochnano will work without the dot but how to exclude it?

working grockpattern if i manually remove the dots
CUSTOM_LOG %{DATA:time:ts-epochnano},%{DATA:src:tag},%{DATA:dst:tag},%{NUMBER:value:float}

**Comment by sparrc** [comment]
@discoduck2x the problem is that your timestamps are neither unix nanosecond nor unix second timestamps. Unix timestamps are integers, and your application is outputting the timestamps as floats.

The only option would be to ignore the nanosecond digits with something like:

```
CUSTOM_LOG %{DATA:time:ts-epoch}.%{NUMBER},%{DATA:src:tag},%{DATA:dst:tag},%{NUMBER:value:float}
```

where %{NUMBER} will get discarded.
