### ISSUE TITLE
should be able to squelch "CREATE DATABASE" statements 

### ISSUE THREAD

**Issue by beckettsean** [influxdata/telegraf#1655]
## Feature Request

Opening a feature request kicks off a discussion.
### Current behavior:

Every minute, Telegraf issues a `CREATE DATABASE` command just in case.
### Desired behavior:

Add a config option to stop all `CREATE DATABASE` statements, leaving the users to manually create whatever DBs are needed.
### Use case: [Why is this important (helps with prioritizing requests)]

In a large setup with thousands of Telegraf instances, this could lead to thousands of no-op `CREATE DATABASE` queries per minute. That's a lot of network and database traffic that serves no purpose. In addition, in a multi-stage Telegraf architecture the intermediary Telegraf instances throw an error on this query, as it is not line protocol. It's not a fatal error or anything, but there's also no utility to the repeated `CREATE DATABASE` statements in a production environment.

@kostasb

**Comment by sparrc** [comment]
this definitely shouldn't be happening, Telegraf should only try to create the database on startup, what version of telegraf is this?

**Comment by beckettsean** [comment]
@kostasb has more context, but it was happening in a multi-stage Telegraf test. I assume it was 0.13

@jackzampolin have you run across this, too?

**Comment by kostasb** [comment]
@beckettsean @sparrc 

This conversation is related to the [PR](https://github.com/influxdata/telegraf/pull/1407) from bagelswitch which introduces the inputs.http_listener  .

The statement that "create database requests are sent every minute" is not accurate and was a wrong early assumption from my side. Actually, Telegraf restarts caused the generation of these requests.

After examining the code of the influxdb output plugin [here](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/influxdb/influxdb.go) I determined that there are two occasions under which a "create database" statement is submitted by Telegraf:
1) by default upon service startup
2) in case an HTTP error is returned from InfluxDB which includes `database not found` in its message content.

I believe the error handling method of submitting a CREATE DATABASE request upon "database not found" error is sufficient, so I suggest [disabling](https://github.com/influxdata/telegraf/blob/69e4e862a35b1da35c0846c35ad947b394f51f07/plugins/outputs/influxdb/influxdb.go#L131) the sending of a CREATE DATABASE statement upon service startup. It will reduce the number of unnecessary requests and will prevent flooding the destination server with messages from multiple agents.

Regarding bagelswitch's PR, CREATE DATABASE statements with the http listener plugin from that PR are not relayed, a 200 OK response code with an empty message `{"results":[]}`is returned. So only the "edge" Telegraf instance will send "create database" statements. (That PR needs a re-base before getting merged).

**Comment by sparrc** [comment]
> I believe the error handling method of submitting a CREATE DATABASE request upon "database not found" error is sufficient, so I suggest disabling the sending of a CREATE DATABASE statement upon service startup. It will reduce the number of unnecessary requests and will prevent flooding the destination server with messages from multiple agents.

There is a drawback to this, which is that I'm fairly certain that every telegraf instance would fail it's first write attempt to a new InfluxDB instance, because there would be no `telegraf` database to write to yet.

We would also need to replace the `CREATE DATABASE` query with a `/ping` request, to validate that the db is connectable, so we would still have to submit a request (although a request that is an immediate no-op from the db)

**Comment by kostasb** [comment]
My vote goes to a `/ping` connectivity check instead of a blind `CREATE DATABASE` statement.

Your concern is valid about the initial write failure but it will only be encountered only once for databases that don't have telegraf's output db created, and will be counter-acted immediately in terms of error handling without user intervention. We can document this behavior as well, to make sure users get a clarification.

I would like to get opinions from @jackzampolin and @beckettsean since they participate in this discussion.

**Comment by jackzampolin** [comment]
Yes. I have seen this a number a times. I would 👍 @kostasb's suggestion.

**Comment by beckettsean** [comment]
I disagree, and would prefer to leave the behavior as default that Telegraf issues a `CREATE DATABASE` statement on startup. It's better for the day one experience with Telegraf and InfluxDB.

I do think it makes some sense for that to be configurable, so that in production environments it would be disabled. For users with thousands of Telegraf clients, the restarts from random VM crashes could amount to dozens of extra queries per day.

**Comment by WaterByWind** [comment]
This is actually not an uncommon scenario.

The choice upon startup:  Send an explicit `CREATE DATABASE` or send a `/ping` query.  Either way it is an event to which the target server must respond, and either way it would be a single event that would be statistically lost in the volume of normal traffic.

It is fairly common practice to go with the brute-force creation method upon startup.  However doing so will always generate a logged error except for the single case of a new install.  Since the error is actually _expected_, it is not unusual to also wrap this activity with appropriate (exception) handling to ignore (not log) the error, except perhaps when debugging (or otherwise more-verbose logging) is enabled.

My vote would be to leave the brute-force creation upon startup if the exception can be caught and not normally logged unless debug is enabled.  Otherwise I would lean towards a separate query (`/ping`) as a check, and upon that failure send the `CREATE DATABASE`.

**Comment by kostasb** [comment]
A successful response from the `/ping` endpoint does not imply that the database exists though. The ping will succeed if InfluxDB is up, but the database may not be there. An additional db-ping functionality would need to be supported by InfluxDB to verify that a database name exists.

With the current state Telegraf can either

a) force-attempt to create the database (like it does now)
b) try to write to InfluxDB and if it receives `database not found` then submit a create database request and retry the write request

I would be up for option b) to reduce unnecessary requests

With the current force-create approach, since the request is being sent from my perspective it should be logged in the same way that all similar HTTP requests are being logged to avoid causing confusion (a user would see a create request in InfluxDB logs with no source agent having a log for it)

**Comment by WaterByWind** [comment]
Instead of an actual `/ping` you could do something like `/query?db=telegraf&q=SHOW%20DATABASES`  The actual query was not the important part and each would validate a different type of failure. 

1. One can perform _some form of query_ to validate the database exists upon startup.
2. One can attempt a brute-force creation upon startup, ignoring failure but still allowing failure to be logged
3. One can attempt a brute-force creation upon startup, expect a failure, and silently continue
4. One can assume the database exists upon startup and wait until an actual query or write fails, then take action.

(3) is fairly commonly used, particularly in other languages such as python which readily support this.  The actual failure is checked when handling the exception and if it is anything other than an expected value proper handling is performed, otherwise any expected modes of failure are simply silently ignored.  Not having a client-side message to match a server-side is already the case, as telegraf wouldn't write a log entry for successful creation when running 'quiet'.  When running with debug=true no log messages should be suppressed anyway, so there would be a match between client/server side logs.

(2) is the method currently used.

(1) would be perhaps more 'elegant' simply by not generating exceptions except when actually needed.

(4) would minimize db traffic during startup by deferring until the first query or write.  However a single query/write upon startup in the other options would be insignificant "noise" among the rest of the db traffic, and this would perhaps be a more complex solution.

(2) for me would be least-preferred.  I don't see a large value in (4) over the other two options ((3), (1)) but is another sometimes-used option.  It could be the best of the four choices depending on effort for the others.

There are two items, and the priority of these two also has an impact on the choice above.

1. Reduce number of unnecessary and potentially confusing logs
2. Reduce number of db queries upon collector startup

**Comment by sparrc** [comment]
My inclination is to just close this issue as it doesn't seem very important. Are there instances where telegraf starting-up causes measurable and significant load on the db?

> Reduce number of unnecessary and potentially confusing logs

doesn't  seem like a compelling reason to me

> Reduce number of db queries upon collector startup

SHOW DATABASES is also a query, so this would only be if we provided an option to completely disable it.

**Comment by kostasb** [comment]
@sparrc this is not a major issue, we have not seen significant performance challenges by synchronized nodes restarting so far

**Comment by WaterByWind** [comment]
@sparrc - I would tend to agree, hence my comments about effort to implement.

Regarding reducing number of logs - it really is just one entry per influxdb output upon startup so volume shouldn't be an issue.  I also would not expect anyone to actually be alerting on 'CREATE DATABASE' failures so the presence of these should be benign.
