### ISSUE TITLE
statsd problem

### ISSUE THREAD

**Issue by johnnyluo586** [influxdata/telegraf#1707]
When i use telegraf statsd input and influxdb output.

statsd had not send data (counter) to telegraf, and when i query data from influxdb use "select * from cmd order by time desc limit 100;"
it will get the same value every time, and with different time.

**Comment by sparrc** [comment]
You're going to need to provide more information, see the issue request template:



## Bug report

### Relevant telegraf.conf:

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:

### Actual behavior:

### Additional info:

[Include gist of relevant config, logs, etc.]


## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

### Current behavior:

### Desired behavior:

### Use case: [Why is this important (helps with prioritizing requests)]
