### ISSUE TITLE
Config with etcd

### ISSUE THREAD

**Issue by farss** [influxdata/telegraf#193]
Now config is static in file, if I need config can be change on running...So colud config with etcd

**Comment by sparrc** [comment]
@farss thank you for the suggestion, I'm not very familiar with etcd, is that a system that is specific to CoreOS?

**Comment by rvrignaud** [comment]
Hello,
@sparrc etcd is a distributed, consistent key/value store written in Go. It can be compared to zookeeper and consul. This is not specific to CoreOS. 

If I understand @farss request correctly I think he is referring to a configuration / discovery mechanism.
Instead of having a specific mechanism for etcd, would that be possible to design a generic and modular discovery mechanism like prometheus designed ? (see http://prometheus.io/docs/operating/configuration/)
Today they provide configuration with following mechanism:
  - File
  - DNS
  - Consul
  - Kubernetes
  - Marathon

This kind of discovery allow a great flexibility for configuration.
Say that that I want to get informations on dynamic (changing ip, name, size, etc...) clusters. I can have one instance of telegraph "discovering" where and how getting metric for this clusters. This would be really awesome.

**Comment by rvrignaud** [comment]
This would also be related to https://github.com/influxdb/telegraf/issues/69

**Comment by ranjib** [comment]
i think it will be harder to support different versions of etcd,. iirc etcd has fuse bindings. something like etcd-> toml config rendering system can be used to achieve this. This will allow not only telegraf, but all other toml backed system to be configured via etcd, as well as telegraf wont have any etcd specific code.

**Comment by titilambert** [comment]
Hello !
@sparrc @rvrignaud @farss @ranjib 
I made a small poc of etcd integration. You can see it here: #465

**Comment by titilambert** [comment]
New pull request here : https://github.com/influxdata/telegraf/pull/651

**Comment by sjwang90** [comment]
Closing. See issue #272
