### ISSUE TITLE
SQL Server input errors out

### ISSUE THREAD

**Issue by haf-lynx** [influxdata/telegraf#2051]
### Relevant telegraf.conf:

```
[[inputs.sqlserver]]
  servers = [
    "Server=localhost\\.;Port=1433;user id=;app name=telegraf;log=32;encrypt=true;TrustServerCertificate=true"
    ]
```

or alternatively:

```
[[inputs.sqlserver]]
  servers = [
    "Server=localhost\\.;Port=1433;user id=;app name=telegraf;log=32;"
    ]
```

Returns:

```
2016/11/16 17:07:28 D! Attempting connection to output: influxdb
2016/11/16 17:07:28 D! Successfully connected to output: influxdb
2016/11/16 17:07:28 I! Starting Telegraf (version 1.1.1)
2016/11/16 17:07:28 I! Loaded outputs: influxdb
2016/11/16 17:07:28 I! Loaded inputs: inputs.win_perf_counters inputs.sqlserver
2016/11/16 17:07:28 I! Tags enabled: dc=norrmalmstorg host=lyn-sql-srv
2016/11/16 17:07:28 I! Agent Config: Interval:10s, Quiet:false, Hostname:"lyn-sql-srv", Flush Interval:10s
2016/11/16 17:07:30 D! Input [inputs.win_perf_counters] gathered metrics, (10s interval) in 86.0053ms
2016/11/16 17:07:40 E! ERROR: input [inputs.sqlserver] took longer to collect than collection interval (10s)
...
```

### System info:

[Include Telegraf version, operating system name, and other relevant details]

Server 2012 R2, telegraf ver c4a7bb84772af4ae543b160ec345bca6 v1.1.1

### Steps to reproduce:

1. Start telegraf.exe with the above connection string and a valid influx endpoint

### Expected behavior:

No error

### Actual behavior:

Error

Any idea why this might happen? The instance is not a named instance, and I've tried `(local)`, `localhost`, `.`.

**Comment by sparrc** [comment]
no idea, and we can't debug without more information, sounds like your server isn't responding or you're not connecting to it properly. I can assure you that the plugin is working but you'll have to figure out how to connect to your server, see the config file for proper config hints:

```
# Read metrics from Microsoft SQL Server
[[inputs.sqlserver]]
  ## Specify instances to monitor with a list of connection strings.
  ## All connection parameters are optional.
  ## By default, the host is localhost, listening on default port, TCP 1433.
  ##   for Windows, the user is the currently running AD user (SSO).
  ##   See https://github.com/denisenkom/go-mssqldb for detailed connection
  ##   parameters.
  # servers = [
  #  "Server=192.168.1.10;Port=1433;User Id=<user>;Password=<pw>;app name=telegraf;log=1;",
  # ]
```

**Comment by jgerschk** [comment]
While this is closed, I'd like to make a comment that I see this a lot in our environment and it is driving me nuts.

1) There are not issues with SQL, if there were, in our environment;  we'd have a lot of issues as we highly depend on SQL.
2) What I have found is that sometimes all the SQL calls take longer than 60 seconds to complete.  When this happens, all SQL monitoring stops.
3) I've also see this happen when we have network issues locally or on our WAN.

How hard would it be to add a parameter for the SQL connection to not just be 60s/1m?  I mean in the configuration add a timeout parameter than can be longer than equal to x?  I think this might solve a lot of issues rather than defaulting to 1m @sparrc .  Thoughts?

**Comment by sparrc** [comment]
that sounds fine, please open a separate issue for a timeout parameter feature request
