### ISSUE TITLE
docker engine-api library is deprecated, we should use their official SDK

### ISSUE THREAD

**Issue by sparrc** [influxdata/telegraf#2071]
Docker's engine-api library is deprecated: https://github.com/docker/engine-api

we should switch to https://github.com/docker/docker/tree/master/client as soon as possible

**Comment by ndegory** [comment]
@sparrc The new API is in a vendored repo, this breaks the build because of types incompatibilities.
I've managed to fix it by adding the Docker API and a few other repos in a vendor folder, but that means changing the vendoring model of Telegraf (I used [Rancher Trash](https://github.com/rancher/trash) for that). I'll make a PR, but I'm aware that's maybe not the way you'd like to implement it.

**Comment by sparrc** [comment]
please don't bother PRing a new vendoring system, it won't be accepted

**Comment by ndegory** [comment]
OK, no worries, I'll try to adapt the tests to workaround the types issue then.

**Comment by mvaude** [comment]
Any news around this plugin update?
I got issues with the current version, I can help on the ongoing effort if needed.

**Comment by sparrc** [comment]
@mvaude can you be more specific? there are no known issues with the docker plugin besides #2027, which I don't think is related to the library being used.

If you are having an issue please open a separate issue unless you're sure that it is related to the client library.

**Comment by mvaude** [comment]
@sparrc Ok thanks then I will open a new issue I am not sure it is related.

**Comment by bergerx** [comment]
Still having the old docker engine-api lib seems like blocking other docker plugin PRs to be merged in. Is there any update on this one? @apognu @ndegory

**Comment by apognu** [comment]
I was planning to look into it a bit tonight to assess the quantity of work required.

I will get back to you.

**Comment by rsingh2411** [comment]
I had raised an PR for the https://github.com/influxdata/telegraf/pull/2379, and made following changes  Recieved following issue,
 `"-X main.version=dev-49-gc8cc01b -X main.commit=c8cc01b -X     main.branch=master" ./...  github.com/influxdata/telegraf/plugins/inputs/docker  plugins/inputs/docker/docker.go:103: cannot use c (type *client.Client) as     type DockerClient in assignment: *client.Client does not implement DockerClient (wrong type for  ContainerList method) have ContainerList("github.com/docker/docker/vendor/golang.org/x/net/context".Context, types.ContainerListOptions) ([]types.Container, error) want ContainerList("context".Context, types.ContainerListOptions) ([]types.Container, error) make: *** [build] Error 2  sh-4.2# vi plugins/inputs/docker/docker.go'`

PR is closed, but, issue is because of dependency referring to wrong repository/library
This will be faced by any one who implements the change for switching from Docker's engine-api library 

Summarizing the issue, import in the  file (plugins/inputs/docker/docker.go) is as follows
import "golang.org/x/net/context"
docker container listing requires "golang.org/x/net/context" which takes context object as an argument, there are two repositories which have context  in current code base,
1. golang.org/x/net/context
2. github.com/docker/docker/vendor/golang.org/x/net/context
During compilation based on length go is selecting the 2 repository. But method needs the 1st one golang.org/x/net/context. hence the type error in code snippet is recieved

Aliasing cannot be used here as libraries should not vendor other libraries.
Compilation goes through  when "github.com/docker/docker/vendor/golang.org/x/net/context" is deleted. normally there are tools like glide which strip nested vendor directories. Telegraf uses gdm, if there is a way it can filter the vendor directory of docker or delete it. Then the PR https://github.com/influxdata/telegraf/pull/2379 will run successfully on circleci. I have made all the changes related to  https://github.com/docker/docker/tree/master/client in the PR. 

If the vendor thing is taken care of then the PR can be used. Please have a look
