### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by KyleAMathews** [influxdata/telegraf#218]
Pardon me if I'm missing something documented but is there a docker image for this? That'd be a very convenient way to install it.

**Comment by sparrc** [comment]
Hi @KyleAMathews, there isn't a docker image, and I haven't tried that out yet.

I don't think it's a great use-case, I suspect that many of the system plugins would misbehave because it would be gathering stats from the OS on the docker container rather than the underlying OS.

Could you explain more why installing via docker would be useful to you? One of the goals of telegraf was for easy installation. If you just download a binary, it will run without any state beyond just the config file that you generate.

**Comment by piniondna** [comment]
It easier to deploy and update a docker image if you're already running a docker cluster. I've managed to get a docker container with telegraf working with the exception of Docker metrics. Using --net=host doesn't seem to do the trick either.

**Comment by sparrc** [comment]
@piniondna cool! could you share how you got that working?

**Comment by piniondna** [comment]
No problem...

I based my Dockerfile on the [bailey telegraph image](https://hub.docker.com/r/bbailey/telegraf/~/dockerfile/). I install 0.1.7, I create my own telegraph.toml (to include the docker plugin, and I don't include the run.sh script since I execute the command from docker-compose (see code blocks below).

In order to get Docker metrics forwarding, the trick was mapping the proper host paths into the container, so it has access to the cgroups. I did that from the docker-compose.yml, but it can easily be done on a docker run command as well.

My run settings were --net=host and -v /sys/fs/cgroup:/sys/fs/cgroup

One gotacha to look out for is that the Telegraph and InfluxDb versions for these metrics need to sync up perfectly or the values won't map to properly ([breaking changes in value types](https://github.com/influxdb/telegraf/issues/151)). I believe the versions are Telegraf 0.1.7 --> InfluxDb 0.9.3. Unfortunately, It was due to this incompatibility that I had to roll back my effort and remove the docker metrics from my setup-- I couldn't change versions.

Dockerfile:
```
FROM debian:jessie

RUN apt-get update && apt-get install -y curl
ENV TELEGRAF_VERSION 0.1.7
RUN curl -s -o /tmp/telegraf${TELEGRAF_VERSION}amd64.deb http://get.influxdb.org/telegraf/telegraf_${TELEGRAF_VERSION}_amd64.deb && \
  dpkg -i /tmp/telegraf${TELEGRAF_VERSION}amd64.deb && \
  rm /tmp/telegraf${TELEGRAF_VERSION}amd64.deb && \
  rm -rf /var/lib/apt/lists/*

RUN mkdir /config
COPY ./telegraf.toml /config/telegraf.toml

ENV INFLUXDB_HOST influxdb

CMD ["/opt/telegraf/telegraf -config /config/telegraf.toml"]
```

docker-compose.yml:
```
telegraf:
  build: .
  net: "host"
  volumes:
   - /sys/fs/cgroup:/sys/fs/cgroup
  command: /opt/telegraf/telegraf -config /config/telegraf.toml
```

**Comment by piniondna** [comment]
btw... @sparrc 's comment about this not being a good idea still might hold true. I just wanted to demonstrate that it's at least possible to deploy Telegraf as a container. However, if the telemetry streaming out of that container is bad due to assumptions about the host enviornment then obviously this method is not a good way to go.

From what I've seen so far, everything looks good, but after reading this thread I will be doing more testing to verify that the setup is providing accurate data.

**Comment by sparrc** [comment]
@piniondna I could be wrong, since many of Telegraf's metrics come directly from the kernel `/proc` filesystem. If docker containers are using the same `/proc` files as the host OS, then it's probably accurate

**Comment by tarrychk** [comment]
I deployed telegraf in a docker container and use it to monitor host and other containers. The container itself is trivial, just (a patched) telegraf with its configuration.

I mount following folders from host into telegraf container
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro

/var/run is required because of /var/run/docker.sock which allows me to use docker plugin.
/sys lets me pull statistics from host system.
I patched telegraf to use /rootfs/proc instead of /proc. Obviously this needs some refinement to make telegraf work in both modes, e.g. make path to /proc configurable, or add a configuration item for rootfs path (default: "/").

**Comment by tarrychk** [comment]
P.S. /proc on host and /proc inside containers vary significantly, even between containers on same host.

**Comment by dustinblackman** [comment]
@tarrychk Do you happen to have a repo up of what you patched?

**Comment by tarrychk** [comment]
@dustinblackman https://github.com/tarrychk/telegraf/tree/procfs
My patch expects host procfs in /rootfs/proc. Either start container with "--volume /:/rootfs:ro" or "--volume /proc:/rootfs/proc:ro". Symlinking /rootfs/proc -> /proc will allow you to test telegraf in your build/test environment.

**Comment by ebaratte** [comment]
I successfully run a docker container with @tarrychk patch. The Dockerfile contains:

```
FROM golang:1.5.1
RUN mkdir -p /opt/telegraf
RUN mkdir -p /go/src/github.com/influxdb
RUN cd /go/src/github.com/influxdb && git clone https://github.com/tarrychk/telegraf
WORKDIR /go/src/github.com/influxdb/telegraf
RUN git checkout procfs
RUN make
RUN cp telegraf /opt/telegraf/
# create a local telegraf.toml to include in the container
ADD ./telegraf.toml /opt/telegraf/
WORKDIR /opt/telegraf
CMD ["/opt/telegraf/telegraf","-config","/opt/telegraf/telegraf.toml"]
```
and can be run with `docker run -d --name telegraf --link influxdb-latest-1.dual-latest.f5e3b2d9:influxdb -v /sys:/sys:ro -v /var/run/docker.sock:/var/run/docker.sock -v /:/rootfs:ro my_telegraf_build`

**Comment by cgeoffroy** [comment]
For the use-case aspect, I can speak about `cadvisor`. You monitor the host by deploying it in a container (see https://github.com/google/cadvisor#quick-start-running-cadvisor-in-a-docker-container).


Back to `telegraf`, you can have the same feature without heavily patching the code. Because `telegraf` uses the `gopsutil` as a back-end library to deal with low level stuff. `gopsutil` has 2 environment variables to set the base `/proc` and `/sys` paths: `HOST_PROC` and `HOST_SYS` (see https://github.com/shirou/gopsutil/blob/master/internal/common/common.go#L234). A basic `docker-compose` for `telegraf` looks like:
```
telegraf:
  build: .
  net: "host"
  links:
    - influxdb
  volumes:
    - ./telegraf.toml:/config/telegraf.toml:ro
    - /sys:/rootfs/sys:ro
    - /proc:/rootfs/proc:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
  environment:
    - 'HOST_PROC=/rootfs/proc'
    - 'HOST_SYS=/rootfs/sys'
  command: /opt/telegraf/telegraf -config /config/telegraf.toml
```

Right now, this method doesn't work with the `docker` plugin due to some static path (see https://github.com/shirou/gopsutil/pull/106).

**Comment by jchauncey** [comment]
So I submitted the original PR that added that functionality. I was in the middle of writing a go client that works very similar to telegraf and needed to mount the host /proc into the container so i could generate system metrics and send them to influx. If you guys had this in telegraf I could probably deprecate my client.

**Comment by sparrc** [comment]
I recently tried to update gopsutil to HEAD of master, but there appears to be an issue with the Go 1.5.1 build toolchain and `internal` packages. I can't find the issue at the moment, but it will probably need to wait until Go 1.5.2 is released

**Comment by jchauncey** [comment]
Sounds good

**Comment by johnrengelman** [comment]
Any update on this since go 1.5.2 is released?

**Comment by sparrc** [comment]
I'm not exactly sure the status of this, but https://github.com/shirou/gopsutil/pull/106 _has_ been merged into telegraf's build dependencies

@jchauncey @cgeoffroy  any comments?

**Comment by tarrychk** [comment]
I'm running telegraf 0.10.0 in docker container and collect system statistics via HOST_PROC and HOST_SYS. Works fine for me.

**Comment by ianwalter** [comment]
I tried implementing what @cgeoffroy described (without Docker metrics and using /host/... instead of /rootfs/...) and it seems like some metrics are being sent to InfluxDB but I'm running into multiple errors like:
```
2016/02/04 05:22:00 Error adding point [mem]: NaN is an unsupported value for field used_percent
2016/02/04 05:22:00 Error in input [diskio]: error getting disk io info: open /host/
proc/diskstats: no such file or directory
2016/02/04 05:22:10 Error in input [system]: open /host/
proc/loadavg: no such file or directory
2016/02/04 05:22:10 FATAL: Input [cpu] panicked: runtime error: index out of range, Stack:
```
It's strange because if I shell into the container those files are there and I can read them. I'm using Telegraf 0.10.1 on CoreOS stable.

**Comment by cgeoffroy** [comment]
@sparrc  I tried the new v0.10.1 release in a container and it looked good to me.

My test setup is saved there: https://github.com/cgeoffroy/basic-telegraf-setup

@ianwalter I tested the previous setup in a `CoreOS beta (899.6.0)` instance on DO without any troubles. Perhaps your volumes are misconfigured.

**Comment by sparrc** [comment]
there is now an official image at https://github.com/influxdata/telegraf-docker

**Comment by mlowicki** [comment]
@sparrc how to find it on Docker Hub? (https://hub.docker.com/_/telegraf/ gives 404)

**Comment by sparrc** [comment]
here: https://github.com/influxdata/telegraf-docker

**Comment by mlowicki** [comment]
any plans to put it into Docker Hub?

**Comment by ashmckenzie** [comment]
Looks like its there now https://github.com/docker-library/official-images/blob/master/library/telegraf - so `docker pull library/telegraf`

**Comment by passcod** [comment]
Just `docker pull telegraf` — `library` is implied for short names.
