### ISSUE TITLE
Leap second breaks round_interval

### ISSUE THREAD

**Issue by artvolk** [influxdata/telegraf#2221]
## Bug report

A [leap second](https://en.wikipedia.org/wiki/Leap_second) was be added to this year's New Year's countdown. This resulted values in InfluxDB shifted by one second (note *:19*, *:29* etc):

```
2017-01-02T15:28:19Z	0.64	host-2
2017-01-02T15:28:29Z	0.62	host-2
2017-01-02T15:28:39Z	1.16	host-2
2017-01-02T15:28:49Z	0.98	host-2
2017-01-02T15:28:59Z	1.42	host-2
2017-01-02T15:29:09Z	1.2	host-2
```

Telegraf restart resolves the issue (note *:30*, *:40* etc):

```
2017-01-02T15:30:30Z	0.88	host-2
2017-01-02T15:30:40Z	0.83	host-2
```

### Relevant telegraf.conf:

```
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true
```

### System info:
* Telegraf - version 1.0.0
* Ubuntu 14.04.5 LTS 64bit

**Comment by sparrc** [comment]
unfortunately there's not a clean way of fixing this that wouldn't incur significant overhead of constantly checking the "roundness" of current timestamp (which we would have to do on every single collection for an extremely rare edge case). Going to close this as a "won't fix" since restarting the service seems like a more reasonable workaround to me than anything we could code up.
