### ISSUE TITLE
[Feature request] netns support in inputs.net section

### ISSUE THREAD

**Issue by gfrey6wind** [influxdata/telegraf#2340]
Hello,

I noticed during my last tests that interfaces which has been moved in another netns that default one are no more seen by telegraf.

For example, if you have the following in your /etc/telegraf/telegraf.conf file:
[...]
[[inputs.net]]
    interfaces = ["enp4s0f0", "enp4s0f1", "enp6s0f0", "enp6s0f1", "enp5s0f0"]
[...]

Then, put your interface enp5s0f0 in a new netns:
~# ip netns add telegraf_test
~# ip link set dev enp5s0f0 netns telegraf_test
~# ip netns exec telegraf_test ip link set dev enp5s0f0 up

Telegraf cannot get enp5s0f0 statistics anymore.

Is it the expected behavior ?

If so, it is a hard limitation for all the applications which use netns.
Is this feature planned ?

Thanks,
Gabriel

**Comment by phemmer** [comment]
I personally would recommend against telegraf implementing namespace support directly. In fact it will likely be impossible anyway (due to the way namespaces work, and having to spawn a new process to live inside the namespace).

Addressing this exact use case is why I opened #2087 
However as an alternate solution, once #2094 is merged you can use it to solve the use case as well.

**Comment by sparrc** [comment]
agreed, there are no plans to support namespaces, and as @phemmer said I don't think it's possible without creating a new process

**Comment by gfrey6wind** [comment]
Thanks @phemmer and @sparrc for your replies.

I understand the reasons for why you're against a such feature.
Thanks for your advises, I will use input.exec waiting for #2094 solution.

Thanks,
Gabriel
