### ISSUE TITLE
[BUG] Timed out scripts launched by exec plugin become zombies

### ISSUE THREAD

**Issue by smolse** [influxdata/telegraf#2476]
## Bug report

Timed out scripts launched by exec plugin become zombies.

### System info:

Linux Ubuntu 14.04.5 LTS
Telegraf 1.2

### Steps to reproduce:

Here is a simple script to facilitate issue reproduction: https://github.com/smolse/telegraf-zombies/blob/master/reproduce_zombies.sh

1. Clone the repo stated above.
2. Run `reproduce_zombies.sh` script.

### Expected behavior:

No zombie processes.

### Actual behavior:

Each timed out process turns to a zombie process.

E.g., output of the `reproduce_zombies.sh` script:
```
$ bash reproduce_zombies.sh 
Pulling telegraf docker image...
Starting telegraf container...
Container has started, zombie processes will be checked every 30 sec...
2 zombie processes have been found
5 zombie processes have been found
8 zombie processes have been found
11 zombie processes have been found
```

**Comment by sparrc** [comment]
not sure I agree that it's telegraf's responsibility to handle this.

What would you want telegraf to do? send a kill signal whenever a script times out?

cc @danielnelson

**Comment by smolse** [comment]
I have been expecting that if telegraf launched a script, it will not allow any zombie process to appear. However, I am not sure as well if it really should be telegraf's responsibility or not. If not, then at least it would be good to have it stated clearly in the exec plugin's docs.

**Comment by phemmer** [comment]
Well telegraf does currently send a kill signal: https://github.com/influxdata/telegraf/blob/master/internal/internal.go#L210
And the code would also indicate that it's performing a `wait`, which should clean up any zombies. So if it's letting zombies accumulate, this would be a bug.

What I suspect is happening is that telegraf is sending the SIGKILL to the `start.sh` script, which kills it, and telegraf collects it with `wait`. However the child of `start.sh`, which is the `sleep`, is left running and exits normally. Because `sleep`s parent was killed, telegraf inherits the PID, but telegraf isn't doing a `wait` on the sleep because it's not expecting it, so the zombies start piling up.
But this is just a theory.

**Comment by smolse** [comment]
@phemmer This sounds like a pretty valid theory. That is why the problem occurs in docker containers where telegraf is PID 1, but can not be reproduced in a normal OS where processes are controlled by init. So, I guess it is actually not a bug in telegraf, but rather some init system (e.g. [dumb-init](https://github.com/Yelp/dumb-init)) should be used to start telegraf in a container.

**Comment by tim-basic-fit** [comment]
Still seeing this issue as of version 1.37.0 (just bumped the version to the latest). DNS went down, leading to a whole lot of zombie processes spawned by telegraf after a script spawned by exec stalled.
