### ISSUE TITLE
Report network timeouts to outputs

### ISSUE THREAD

**Issue by sybrandy** [influxdata/telegraf#2517]
### Proposal:

When using plugins, such as dns or net_response, it is possible to get a network timeout trying to connect to the services they are attempting to connect to.  However, this is not passed along to the output plugin and therefore can not be used for reporting purposes.

### Current behavior:

At least for dns and net_response, I have not seen any fields noting the timeouts, though I do see error messages in stderr.

### Desired behavior:

A boolean field is present indicating that a timeout has occurred. 

### Use case: [Why is this important (helps with prioritizing requests)]

Knowing that timeouts are occurring can be useful for knowing that there are network related issues.

**Comment by danielnelson** [comment]
@sybrandy Do you think about my suggestion on #2548 would work?

**Comment by sybrandy** [comment]
Yes.  Regarding the unit of measurement, I would say that if you use the same measurement that is used when specifying the timeout to keep things consistent.

Can this solution be generic to all input plugins?  I ask because I'm now thinking that perhaps what we really want is the execution time of the plugin.  With network-related inputs, it's very obvious we want to see when things timeout.  However, let's say we're getting CPU statistics.  While this should be very fast, perhaps if the system is very busy, it is slow to get them.  Or, perhaps it's stuck waiting for a lock.  Regardless, it may be a good idea to see when inputs are not responding quickly in general as an indication that something may not be working how we expect it to.

It's just a thought.  Honestly, even a boolean field that states that we didn't get a response/value would be better than what we have now.

**Comment by danielnelson** [comment]
We have some of this functionality in the `internal` input plugin.

**Comment by sybrandy** [comment]
O.K. That's good to know.  Still, it would be nice to see when a timeout occurs specific to a given input plugin.  I do plan on checking out the internal input plugin just because I want to see how well telegraf is doing.

**Comment by danielnelson** [comment]
About the unit of measurement, I don't think we can use the unit used when specifying the timeout because then the field name/value would change between "5s" and "5000ms".  Also we don't have that information because we convert to a time.Duration (although this part could be solved).

It seems like there are two timeout categories:
- Timeout configured on a plugin is reached (timeout or read_timeout on net_response)
- Gather does not complete within an interval (logs "took longer to collect than collection interval")

For the first item, It should probably be the plugins job to emit a point.  For the second, something should probably be emitted from the internal plugin (I'll open an issue for this).

So I think after writing this that the plugin should determine units for its points, and the internal plugin should use ns.  This what is what it is currently doing and is sort of the unofficial internal unit.

**Comment by danielnelson** [comment]
#2736

**Comment by sjwang90** [comment]
See #2736
