### ISSUE TITLE
Add support for icinga2 

### ISSUE THREAD

**Issue by mlabouardy** [influxdata/telegraf#2658]
## Feature Request

Opening a feature request kicks off a discussion.

### Current behavior:
```
[[inputs.icinga2]]
        host = "https://icinga2:5665"
        username = "root"
        password = "icinga"
```

### Use case: [Why is this important (helps with prioritizing requests)]

**Comment by danielnelson** [comment]
@mlabouardy Can you fill out the remaining sections of the template?  As much information as you can provide is helpful including a short overview, links to documentation about the data you would like collected as well as proposals about what the measurements, tags, fields should looks like.

**Comment by mlabouardy** [comment]
@danielnelson I created an input plugin for icinga2 [https://github.com/influxdata/telegraf/pull/2668](url)

**Comment by pprkut** [comment]
I think rather than polling the status API, it would be handy to work with the event stream API. That way you get accurate information on when the status of a service/host actually changed.
Icinga upstream created icingabeat (https://github.com/Icinga/icingabeat) to get this information into elasticsearch. I suppose telegraf could use that as template to build similar functionality.

**Comment by mlabouardy** [comment]
@pprkut icingabeat store data into elasticsearch, in our case we use mongodb.
