### ISSUE TITLE
Telegraf - Metric name should be dynamically mapped

### ISSUE THREAD

**Issue by pckeyan** [influxdata/telegraf#2743]
Telegraf Jolokia Input Plugin accepts Name, Mbean, Attribute and path. Name of the metric is the concatenation of Name and Attribute. Metric Name generated with this format is not backward compatible with older versions of Telegraf. This can be resolved with a Global Parameter of Name Override which will store the metric in the name specified in the "Name" parameter. Secondly, if the name is not specified, then it can concatenate Attribute to each path as a metric name and should not have the Delimiter to start with as Name is empty. This is hardcoded in extractValues function. With this we can achieve the backward compatibility.

**Comment by danielnelson** [comment]
[Discussion on community](https://community.influxdata.com/t/telegraf-jolokia-metric-name/735).  This may be a regression that happened sometime back.

@pckeyan I'll have to get a jolokia environment setup in order to debug this further, hopefully I can find time for this soon.  For completeness, it is also possible to rewrite old points with new measurement names using Kapacitor.

**Comment by danielnelson** [comment]
It sounds like you found a solution for your particular problem detailed on the community site.

For version 1.4 of Telegraf we hope to roll out an updated jolokia plugin in #2278.

As a long time user of the jolokia plugin it would be great to hear any feedback you have.  If you don't want to look at the code here is the direct link to the new README https://github.com/dylanmei/telegraf/blob/c4635df04fa31822d1c436af44ad33978f616660/plugins/inputs/jolokia2/README.md

**Comment by danielnelson** [comment]
I'm going to close this issue as I think you have found a solution.  Going forward we will probably make all changes to the new jolokia plugin.
