### ISSUE TITLE
Include tag key/value in logging for verbose debugging

### ISSUE THREAD

**Issue by ghost** [influxdata/telegraf#2762]
I got this below errors in my telegraf logs and I don't know which host that is sending this data. It would be great if it included the host tag or the entire datapoint (e.g, influxdb logging have that feature) for verbose debugging. It could even be a setting in the conf file where you can turn it on and off.

2017-05-03T21:25:03Z E! Field type conflict, dropping conflicted points: {"error":"field type conflict: input field \"read_bytes\" on measurement \"procstat\" is type float, already exists as type integer dropped=1"}

**Comment by danielnelson** [comment]
We could add additional logging of the offending metric.  It will likely have the host tag in it.  At this point in the process we don't have another way of knowing where the metric was received from.

In the meantime, you could turn on the printer processor or file output to try to figure out where it is coming from.

**Comment by danielnelson** [comment]
This error originates from InfluxDB, but since we are sending metrics in batches of `metric_batch_size`, we don't actually know which point triggered the error.

Let's keep an eye on this issue https://github.com/influxdata/influxdb/issues/8332

**Comment by sspaink** [comment]
It seems https://github.com/influxdata/influxdb/issues/8332 was closed due to being stale, a lot of time has passed since this issue has been opened without any activity and lots has changed in both Telegraf and InfluxDB. ThereI am going to close this issue. I recommended trying the latest version of Telegraf and InfluxDB, and if you are then still facing this issue please re-open with as much detail as you can provide. Thank you!
