### ISSUE TITLE
Aerospike Output plugin

### ISSUE THREAD

**Issue by scippio** [influxdata/telegraf#2781]
Opening a feature request kicks off a discussion...

Am I alone who would want this plugin?

**Comment by sjwang90** [comment]
Hi @scippio, I'm going to close this for now due to the lack of conversation. If you're still interested in this plugin it may be best to write and submit this plugin as an [external plugin](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md). 

Here is some [information on external plugins](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) and using them with `execd`. Feel free to respond with any questions you may have.
