### ISSUE TITLE
[Bug report]Collection interval is not respected when Telegraf process is reloaded

### ISSUE THREAD

**Issue by haidaraM** [influxdata/telegraf#2839]
### Relevant telegraf.conf:
```ini
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10m"
  flush_jitter = "0s"
  precision = ""
```

### System info:
CentOS Linux release 7.1.1503 (Core)
Telegraf  1.2.1

### Steps to reproduce:

1. Configure a new input.exec plugin to run a command every 2m with a timeout of 1m.
```ini
[[inputs.exec]]
commands = ["/usr/local/bin/python3.5 /etc/telegraf/telegraf.d/my_script.py"]
interval = "2m"
timeout = "1m"
data_format = "influx"
```
2. Reload Telegraf to take into account the new input: ` sudo service telegraf reload`
3. Wait a few moments to collect some metrics into InfluxDB for instance. Let's say for example the last metric was collected at `2017-05-19T07:00:40Z`.
4. Reload Telegraf : ` sudo service telegraf reload`

### Expected behavior:
The next metric should be collected at  `2017-05-19T07:02:40Z`

### Actual behavior:
The next metric is collected before `2017-05-19T07:02:40Z` and the next ones are collected 2m after and so on...

**Comment by haidaraM** [comment]
Any news about this bug ?

**Comment by danielnelson** [comment]
Only that I'm planning to fix it as part of the upcoming changes to configuration loading https://github.com/influxdata/telegraf/issues/272

**Comment by haidaraM** [comment]
Thanks for your reply

**Comment by danielnelson** [comment]
@haidaraM There are some changes in the upcoming 1.9.0 release that affect this, but it is not as described above in the expected behavior.  If you were to restart at `07:00:40` the next collection for a `interval = "2m"` input would be at `07:02:00` because `round_interval` is true in the agent.  The rounding is always done based on the effective interval of the plugin.  Does this fulfill your requirements or should we consider more configurability of the rounding?
