### ISSUE TITLE
Plugin for Caddy HTTP server

### ISSUE THREAD

**Issue by olivierlambert** [influxdata/telegraf#2842]
## Feature Request

Hi there! That would be fantastic to have a plugin for Caddy HTTP server.

### Current behavior:

No Caddy plugin ;)

### Desired behavior:

Having a Caddy plugin that monitor basic HTTP metrics.

### Use case:

To goal would be to have req/s, bytes/s and maybe non-200 HTTP requests.

Good news: there is "similar" plugins already existing, so it *should* be not too complicated to make in Telegraf. Note that I'm a *Go* noob, so I could do it, but it if seems really trivial to realize, that would save me one week just to get basic principles :+1: 

"Similar" Caddy plugins:

* Datadog plugin: https://github.com/payintech/caddy-datadog
* Prometheus plugin: https://github.com/miekg/caddy-prometheus

If you can't do it/in the bottom of the TODO (which I understand completely), a little help on the general structure would be wonderful (I looked at the mock plugin, but I need a bit of time to digest the Go thing)

**Comment by danielnelson** [comment]
I'm certainly no expert on Caddy but from what I can tell it has no built in stats, only the ones produced by plugins.  What about using the caddy prometheus plugin with the telegraf prometheus input?

**Comment by olivierlambert** [comment]
Yes, it seems not directly built-in indeed, seems like the plugin is "inserted" in the middle of Caddy code and make some extra metrics by itself (calculating http response time etc.)

The prometheus thing is an option, IDK exactly if it involves too many "layers" to just gather Caddy stats. I'll investigate.

In your opinion, what would be the best "architecture" in this context? A Telegraf plugin on the Caddy side? (but then, how to send data to the local Telegraf input)

On the other hand, the datadog agent seems easy to use/write.

IMHO, the best answer is the easiest answer (from the user point of view), like the Apache or Nginx input for Telegraf. But your advice on the best way to achieve it would be awesome :)

**Comment by danielnelson** [comment]
It seems that a Caddy plugin is required to produce metrics and there is nothing built in.  So if there was a Telegraf plugin for Caddy it would probably look essentially the same as the prometheus plugin, but with influx line protocol as the encoding.  Since it would be so similar, and since Telegraf can already process prometheus endpoints, I don't know if it's worth the effort.

The datadog plugin uses statsd with datadog extensions, so it could be used with the Telegraf statsd input, but there are the usual minor statsd downsides.  The fields are structured hierarchically instead of with tags, which makes querying harder.  Also, the Caddy server needs to know the location of the Telegraf instance to push statsd metrics.

The one thing that is not great for is that everyone who wants to integrate Telegraf with Caddy needs to figure this all out.  Maybe the fix for this is to document what we did here, add it into the docs directory, and link it off the top level README?

**Comment by olivierlambert** [comment]
Okay I'll try to find time to experiment with Prometheus/Caddy/Telegraf and report my progress here!

**Comment by olivierlambert** [comment]
Okay it was a piece of cake:

1. Download Caddy with the Prometheus plugin: https://caddyserver.com/download/linux/amd64?plugins=http.prometheus
2. Add the `prometheus` directive in your `CaddyFile`
3. Restart Caddy
3. Configure Telegraf on this same machine to fetch those metrics:

```
[[inputs.prometheus]]
#   ## An array of urls to scrape metrics from.
  urls = ["http://localhost:9180/metrics"]
```

> This is the default URL where Caddy Prometheus plugin will send data.

Works like a charm!

**Comment by danielnelson** [comment]
I'm going to reopen this as a documentation task.

**Comment by olivierlambert** [comment]
Do you want me to update a doc somewhere? I can submit a PR for that :)

**Comment by danielnelson** [comment]
Maybe we add a new section to the prometheus plugin's README with your instructions, and then in the top level README we add a link to it as a bullet point under the prometheus plugin.  This way if someone searches the README for caddy they will find it and be able to jump to it.

**Comment by olivierlambert** [comment]
PR created: https://github.com/influxdata/telegraf/pull/2853

**Comment by danielnelson** [comment]
Merged
