### ISSUE TITLE
Create a native input plugin for Sphinx Search Server

### ISSUE THREAD

**Issue by bborysenko** [influxdata/telegraf#2878]
## Feature Request

Create a native input plugin for [Sphinx Search Server](http://sphinxsearch.com/).

### Current behavior:

Use `exec`  plugin to gather stats from [`SHOW STATUS`](http://sphinxsearch.com/docs/current.html#sphinxql-show-status)  or `searchd --status`. Like:

```
$ /usr/bin/mysql --host=127.0.0.1 --port=9306 --skip-column-names --execute="SHOW STATUS"
$ searchd --status
```

**Comment by sjwang90** [comment]
Hi @bborysenko, closing this due to the lack of discussion. If you're still interested in this plugin and would like to write and submit this plugin as an [external plugin](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md). 

Here is some [information on external plugins](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) and using them with `execd`. Feel free to respond with any questions you may have.
