### ISSUE TITLE
Wrong boot time in lxc containers

### ISSUE THREAD

**Issue by kirgizz** [influxdata/telegraf#2968]
Telegraf system input plugin use btime in /proc/stat to count uptime. This behavior a little wrong, because in lxc containers btime show boot hoster time, but not container.
Maybe better get uptime metric in /proc/uptime

**Comment by danielnelson** [comment]
Can you raise this with the gopsutil project and link to the issue?  Here is the function that is called for uptime: https://github.com/shirou/gopsutil/blob/master/host/host_linux.go#L93

**Comment by kirgizz** [comment]
here you are )
https://github.com/shirou/gopsutil/issues/390

**Comment by danielnelson** [comment]
This may have been fixed for a period, but doesn't seem to be working with LXC 3. 
 https://github.com/shirou/gopsutil/issues/679

**Comment by jessingrass** [comment]
seems https://github.com/shirou/gopsutil/pull/894 addresses the upstream issue.

**Comment by zeus86** [comment]
As far as i can tell - even if this issue is addressed upstream - if does not have any effect onto telegraf yet. LXC Containers still report the uptime of their hypervisor, instead of their own; at least on pxoxmox 6 and 7 (ubuntu focal guests, x86_64), where I tested this, so this should be repoenend. maybe a switch in the config-section from where to read the uptime would be suitable?
```
$ telegraf --version
Telegraf 1.20.2 (git: HEAD f721f53d)
```

**Comment by Astaoth** [comment]
Hi, I can confirm than Telegraf in a LXC on Proxmox 7 doesn't report the right uptime (Telegraf 1.22, VM and Proxmox up-to-date). The idea of @zeus86 seems fine, would it be possible to add this switch ?
