### ISSUE TITLE
bind stats plugin

### ISSUE THREAD

**Issue by samahee** [influxdata/telegraf#299]
Add bind stats

**Comment by sparrc** [comment]
dns bind? can you provide more details where that data should come from?

**Comment by samahee** [comment]
yes dns bind.
1. https://collectd.org/wiki/index.php/Plugin:BIND (using libpcap, golang - https://github.com/sungit/gopcap)
2. https://exchange.nagios.org/directory/Plugins/Network-Protocols/DNS/check_bind-2Esh/details (using bind stats file)

first is more detailed informations, seconds is simple data.

**Comment by JulienChampseix** [comment]
Any update on it ?

**Comment by sparrc** [comment]
PRs welcome :-)

**Comment by emanzx** [comment]
Hi, I am interested to provide helps on this. Currently I  have finish developing plugin for munin on the bind9 stats but I was interested to try influx stack. 
Latest bind 9 support a few method to get statistic data from. 
1. Statistic file 
2. XML 
3. JSON
Currently I am working with JSON data because it is simple and have smaller footprint.. I manage to do some simple data dumper from bind statistics service and put the data in influx DB. I hope I can be a help to develop a plugin for telegraf to get the statistic data from bind9 server.

**Comment by sparrc** [comment]
that would be great, thanks @emanzx

**Comment by emanzx** [comment]
Please email me at iman@localhost.my if I can be any helps.

**Comment by MendelGusmao** [comment]
I'd like to help.

I just began analyzing the structure and will soon have a functional plugin for some basic sections (opcodes, qtypes, nsstats, sockstats, ...).

Later we'll have to discuss about some sections like .socketmgr.sockets, .taskmgr.tasks and zones in views. I'm still not sure of what is useful to extract from them.

Regards,

**Comment by MendelGusmao** [comment]
Hey @samahee, @JulienChampseix, @emanzx. Could you please share your thoughts about the implementation in #1431? I'd be really glad to have them.

**Comment by emanzx** [comment]
Hi @MendelGusmao nice to know you are working on the BIND9 plugin, I am working on my own ruby script to dump and process the statistic data from BIND9 to influxdb.. I would be happy to learn from you.

**Comment by dswarbrick** [comment]
Since work on the original plugin seems to have stalled, I started to write a BIND9 XML stats parser, which is about 80 - 90% complete. As many service providers are quite conservative about upgrading BIND, and the JSON stats are only supported in BIND 9.10+ (and also not enabled in Debian's BIND 9.10 packages), I think supporting the XML stats is a higher priority at present.

I hope to have a PR ready in a few days, but it's lurking here in my fork for now: https://github.com/dswarbrick/telegraf/tree/master/plugins/inputs/bind

**Comment by dswarbrick** [comment]
PR created #2046 

As this is my first contribution to Telegraf, and my first Github PR, I hope I did everything "right"... Could not find the "squash commits" option when creating the PR, but read that upstream can do that if they choose.

**Comment by dswarbrick** [comment]
Updated PR, for anybody following this still: #2383

**Comment by shalstea** [comment]
Any plans to move this forward?

**Comment by danielnelson** [comment]
@shalstea We need a volunteer to finish up some final modifications on the PR, are you able to help?

**Comment by danielnelson** [comment]
It is described in the #2383 PR, but basically it is just a restructuring of the metrics.

**Comment by danielnelson** [comment]
Closed in #2383 + #5653 and included in 1.11.0.
