### ISSUE TITLE
fail2ban plugin no data is collected

### ISSUE THREAD

**Issue by xuebaba1115** [influxdata/telegraf#3165]
### System info:

- Telegraf  1.4
- debian 9.0

### Steps to reproduce:
I added fail2ban plugin after the test is ok
```
 dev@debian:/etc/telegraf$ sudo telegraf --config telegraf.conf --input-filter fail2ban --test
 Plugin: inputs.fail2ban, Collection 1
> fail2ban,jail=sshd,host=debian failed=0i,banned=0i 1503565774000000000
> fail2ban,jail=tomcat,host=debian failed=1i,banned=0i 1503565774000000000`
```

Restart telegraf service
And did not collect fail2ban data
There is no fail2ban data in my database

```
> show measurements
name: measurements
name
----
cpu
disk
diskio
kernel
mem
processes
swap
system
tomcat_connector
tomcat_jvm_memory
tomcat_jvm_memorypool
```

### Additional info:

```
telegraf.conf
 [[inputs.fail2ban]]
   use_sudo = true
```

```
sudoers add
telegraf ALL=(root) NOPASSWD: /usr/bin/fail2ban-client status *
```
```
dev@debian:~$ sudo fail2ban-client status
Status
|- Number of jail:	2
`- Jail list:	sshd, tomcat
dev@debian:~$ sudo fail2ban-client status sshd
Status for the jail: sshd
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	0
|  `- File list:	/var/log/auth.log
`- Actions
   |- Currently banned:	0
   |- Total banned:	0
   `- Banned IP list:	
dev@debian:~$ sudo fail2ban-client status tomcat
Status for the jail: tomcat
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	2668
|  `- File list:	/var/log/tomcat8/localhost_access_log.txt
`- Actions
   |- Currently banned:	2
   |- Total banned:	2
   `- Banned IP list:	127.0.0.1 192.168.1.16
```

**Comment by danielnelson** [comment]
Can you add the output of `sudo fail2ban-client status`?

**Comment by xuebaba1115** [comment]
```
dev@debian:~$ sudo fail2ban-client status
Status
|- Number of jail:	2
`- Jail list:	sshd, tomcat
dev@debian:~$ sudo fail2ban-client status sshd
Status for the jail: sshd
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	0
|  `- File list:	/var/log/auth.log
`- Actions
   |- Currently banned:	0
   |- Total banned:	0
   `- Banned IP list:	
dev@debian:~$ sudo fail2ban-client status tomcat
Status for the jail: tomcat
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	2668
|  `- File list:	/var/log/tomcat8/localhost_access_log.txt
`- Actions
   |- Currently banned:	2
   |- Total banned:	2
   `- Banned IP list:	127.0.0.1 192.168.1.16
```

**Comment by danielnelson** [comment]
I suspect it cannot run `sudo fail2ban-client status` when ran as a service.  Is there anything in the Telegraf logfile?

Try running it as the telegraf user, both: `sudo -u telegraf fail2ban-client status` and `sudo -u telegraf fail2ban-client status tomcat`

**Comment by danielnelson** [comment]
The example sudoers in the documenation is not correct, as it's not possible to run only the status command with no arguments.  I am going to update it to recommend:
```
telegraf ALL=(root) NOEXEC: NOPASSWD: /usr/bin/fail2ban-client status, /usr/bin/fail2ban-client status *
```

As an aside, my instructions for how to test fail2ban in the same way as Telegraf were wrong, actually you need to do something like this:
```
sudo -u telegraf -s /bin/bash
sudo -n fail2ban-client status
sudo -n fail2ban-client status sshd
```

**Comment by danielnelson** [comment]
58751fa4df5e090b4499a9328ad1dc18912db582

**Comment by SNariskine** [comment]
Hello,

i had the same behavior on my platform :
Debian 9.8 Stretch
Telegraf 1.10.0-1

the config test works well but no metrics are reported in database and i had errors in telegraf.log. 
I test manually and got the issue below

`sudo -u telegraf /usr/bin/fail2ban-client status sshd     
ERROR  Permission denied to socket: /var/run/fail2ban/fail2ban.sock, (you must be root)
`

i double check my sudoers file and finally the issue was in the following file /etc/systemd/system/telegraf.service.d/override.conf, i had to comment this settings

`CapabilityBoundingSet=CAP_NET_RAW CAP_NET_ADMIN
AmbientCapabilities=CAP_NET_RAW CAP_NET_ADMIN`

i reload systemctl to take the new changes
`sudo systemctl daemon-reload`

then i restart my telegraf service and the error is gone
`sudo -u telegraf sudo  /usr/bin/fail2ban-client status sshd
Status for the jail: sshd
|- Filter
|  |- Currently failed: XXXXX
|  |- Total failed:     XXXXXX
|  `- File list:        /var/log/auth.log
`- Actions
   |- Currently banned: XXXXX
   |- Total banned:     XXXXXX
   `- Banned IP list:   XXXXXXXX
`

**Comment by danielnelson** [comment]
@SNariskine I'm confused, do you mean you needed to create the file `/etc/systemd/system/telegraf.service.d/override.conf` containing:
```
CapabilityBoundingSet=CAP_NET_RAW CAP_NET_ADMIN
AmbientCapabilities=CAP_NET_RAW CAP_NET_ADMIN
```

**Comment by SNariskine** [comment]
Not exactly, i had to comment the two lines

**Comment by danielnelson** [comment]
I'm not sure where this `override.conf` came from then, as far as I know this doesn't get created by us.
