### ISSUE TITLE
Cannot resolve 'localhost' using /etc/hosts

### ISSUE THREAD

**Issue by candlerb** [influxdata/telegraf#3194]
### Relevant telegraf.conf:

Default unchanged

### System info:

Ubuntu 16.04 amd64

telegraf 1.3.5-1 installed from repos.influxdata.com

### Steps to reproduce:

Install influxdb and telegraf out-of-box.

`/etc/hosts` has the usual entries for localhost and localhost6, but the local DNS resolver is not authoritative for `localhost`

### Expected behavior:

Telegraf runs normally and starts writing system metrics to Influxdb

### Actual behavior:

~~~
Sep 02 17:57:20 tick telegraf[12331]: 2017-09-02T17:57:20Z E! InfluxDB Output Error: Post http://localhost:8086/write?consistency=any&db=telegraf: dial tcp: lookup localhost on 10.12.255.1:53: no such host
Sep 02 17:57:20 tick telegraf[12331]: 2017-09-02T17:57:20Z E! Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
~~~

(10.12.255.1 is the local DNS cache)

### Additional info:

Making my local DNS cache authoritative for `localhost` fixed the problem.

### Proposal:

EITHER: make telegraf resolve via the usual library calls (gethostbyname or newer)

OR: change the sample configs to use http://127.0.0.1/ instead of http://localhost/

**Comment by danielnelson** [comment]
This sounds like it is caused by the [go name resolver](https://golang.org/pkg/net/#hdr-Name_Resolution), you can use the cgo resolver to get the normal system behavior.

This means that when using the go name resolver, dns resolution does not always work the same especially if you are doing anything interesting.  However, most of our platforms are cross-compiled without cgo support, so we can't just always use the cgo resolver.

Here is a similar problem someone had on the community site:
https://community.influxdata.com/t/telegraf-dns-issue-with-local-address/624/6

Changing the sample config to contain ip addresses only doesn't help with the underlying problem since as soon as the user tries to use a hostname it would fail.  Maybe a better fix is to create a FAQ and add this.

**Comment by candlerb** [comment]
Thanks for the explanation.

Another option might be to put 127.0.0.1 in the sample config, plus a comment which says you can use hostnames but they must resolve in the DNS.

If someone changes the config from default and telegraf stops working, at least they're aware that the problem is something to do with the change they made.  If the out-of-the-box experience is that telegraf fails to work in the first place, that's not so good (IMO).

**Comment by danielnelson** [comment]
I set the InfluxDB output to use an ip address in the sample config, this is the only plugin that is enabled by default and uses a hostname so perhaps it will be useful. 9796d3c99d49cf0d031cc2c803bd369efb7f3426

I also added this to a new [FAQ](https://github.com/influxdata/telegraf/blob/master/docs/FAQ.md) document.

**Comment by candlerb** [comment]
> I also added this to a new FAQ document.

Cheers.  However:

"Telegraf cannot resolve hostnames that are resolvable via dig, host, nslookup, etc."

Actually, all of those are DNS-only tools, and do not go through libc/nsswitch etc.  They would also fail where Telegraf fails.  I suggest instead:

"Telegraf cannot resolve hostnames that are in `/etc/hosts`"

**Comment by danielnelson** [comment]
Oh that's a good point. It could be things other than `/etc/hosts` as well, such as mdns or other methods in the `nsswitch.conf` file.  Maybe I'll just have the question be "Hostnames are not able to be resolved" and suggest testing with `getent`?
