### ISSUE TITLE
Can't figure out why certain data fields isn't going into Grafana

### ISSUE THREAD

**Issue by scfigg** [influxdata/telegraf#3209]
Using Postman for Windows, I'm polling my API url for my Cisco Prime infrastructure to see how many clients are on a specific SSID. Postman shows the data I'm looking for (see picture below). However, I'm assuming my telegraf config is wrong since Grafana isn't showing all the data that I'm seeing in postman (only a few things such as VLAD ID, etc). Any suggestions on what I'm doing wrong?

Here is my telegraf config:
https://pastebin.com/C7BYw9uL

Here is my postman results:
https://pastebin.com/6J9BYrc5

The only info I can see in grafana is VLAN ID, association time, and update time. I'd like to be able to see "Count" and possibly other data, but I'll start out with just that one number and see if anyone can help direct me.

Thanks :)

**Comment by tocheeba** [comment]
Looks like this may be it? Because the integers are enclosed in quotes from Cisco, they aren't treated as numbers - they are treated as strings instead?

https://github.com/influxdata/telegraf/issues/2904

**Comment by danielnelson** [comment]
The [JSON input data format](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md#json) ignores all strings that are not in the `tag_keys`.  If they are in the tag keys they are collected as tags, so make sure it makes sense from a [schema design](https://docs.influxdata.com/influxdb/v1.3/concepts/schema_and_data_layout/) point of view.

**Comment by tocheeba** [comment]
So given that I want the "@count" data, which yields a number with quotes ("273"), as long as I have it setup in tags, I should be able to pull it into Grafana, right? I can't think of anything I have wrong in my config, other than telegraf not being able to read the value "273" or whatever number as an actual 'number' since it has quotes? (per #2904)

**Comment by danielnelson** [comment]
It appears that `tag_keys` are only valid for top level items, since `@count` is nested under `queryResponse` it can't be added as a tag.  Even if you could grab this item as a tag though it probably wouldn't be a very good idea, it looks like this value changes frequently and you would end up creating a large amount of series.

I think the only way to scrape this data currently would be with a custom script for the exec plugin.

**Comment by scfigg** [comment]
Thanks, that makes sense I guess. I'm still new to API usage, telegraf, etc. I've been reading up a lot, and I guess I'll have to figure something out with the exec plugin.
