### ISSUE TITLE
Wrong node status for windows 7 machine.

### ISSUE THREAD

**Issue by botzill** [influxdata/telegraf#3313]
Hi.

I installed `Telegraf` on windows 7 machine and all seems to work OK, I get the general statistics into `Cronograf`:

<img width="1267" alt="screen shot 2017-10-06 at 10 38 56 pm" src="https://user-images.githubusercontent.com/4686040/31295416-3794d54c-aae7-11e7-920c-64b9866d9bcc.png">
 
but when I go to list nodes I see the issue related to `Status`:

<img width="1192" alt="screen shot 2017-10-06 at 10 35 10 pm" src="https://user-images.githubusercontent.com/4686040/31295442-4bb303e6-aae7-11e7-802d-e49c00c646a5.png">

`Telegraf: 1.4.1`
`Chronograf: 1.3.8.3`

Any idea how can we fix this? 

Thx!

**Comment by danielnelson** [comment]
@jaredscheib What determines the status color for a host?

**Comment by jaredscheib** [comment]
I believe this is probably related to https://github.com/influxdata/chronograf/pull/2015 and thus was fixed in Chronograf 1.3.9.0.

Could you try upgrading, @botzill? And, if you're still experiencing this issue after the upgrade, file the issue under https://github.com/influxdata/chronograf/issues/?

Thanks!
