### ISSUE TITLE
Connect to InfluxDB via a Unix Domain Socket

### ISSUE THREAD

**Issue by binary0111** [influxdata/telegraf#3366]
### Proposal:

Add support for connecting to InfluxDB over a unix domain socket

### Current behavior:

We can connect to InfluxDB via UDP or HTTP(S) over TCP but not UDS. While Telegraf has support for a generic socket writer which supports UDS, InfluxDB's UDS socket listener expects HTTP.

See : https://github.com/influxdata/influxdb/pull/7135
         https://github.com/influxdata/kapacitor/issues/1628

### Desired behavior:

Be able to talk to InfluxDB on the same host via UDS.

### Use case:

1) Improved security
2) Reduce TCP overhead for hosts running the TICK stack on the same box and have limited resources

**Comment by adityacs** [comment]
@danielnelson Can we implement the same way as explained here [influxdata/influxdb#7135](https://github.com/influxdata/influxdb/pull/7135) ?

**Comment by danielnelson** [comment]
Yeah, probably just need to add a `unix_socket = "/var/run/influxdb.sock"` option that if set enabled the dial function.

**Comment by binary0111** [comment]
@danielnelson  how about something like `urls = ["uds:///var/run/influxdb.sock"]` ? Also what will be the implication for https (including self signed certs)? I guess https is not really necessary over uds given correct permissions on the socket.

**Comment by danielnelson** [comment]
That config style works for me.  You won't be able to add a path but it will work better with multiple servers which is more important.  Certificates should work the same, you can use them if you want but there is not much of a point.

**Comment by danielnelson** [comment]
We might need the option, since even with no cert options set we might need to do a https connection.  One thing to check is if InfluxDB can even use https on the unix-socket.

What if when the unix_socket option is set we use the socket for all localhost urls, then you could have https for remote and http or https for localhost.  The unix_socket format is inspired by curl which looks like this: `curl --unix-socket /var/run/docker.sock http://localhost/write`.

If we did this we would lose the ability to connect to both a tcp socket and unix socket on localhost in the same output.

If we decide to use the socket path I think we should use "unix" as the scheme too: `urls = ["unix:///var/run/influxdb.sock"]`.

**Comment by danielnelson** [comment]
The `["unix:///var/run/influxdb.sock"]` variation was added.

**Comment by binary0111** [comment]
Thanks @danielnelson ! Much appreciated :)
