### ISSUE TITLE
Allow week number to be used in the elasticsearch output index template

### ISSUE THREAD

**Issue by hemasalma** [influxdata/telegraf#3476]
Hello,

We have installed telegraf and tried to send metrics data to elasticsearch ouput and that worked properly.

In config file in
[[outputs.elasticsearch]] block we have option for daily indexing data in elasticsearch
i.e., index=index-name-%Y-%m-%d

what we need is..
can we index data for a week of year basis..
i.e., instead of indexing data in a daily index basis it should be indexed in week of year basis..

**Comment by danielnelson** [comment]
I can imagine adding more formatting symbols, I know in python they use `%U` and `%W` for week depending on what day of the week is the start of the week.  In Go, the `.ISOWeek()` function seems to be equivalent to `%W`

**Comment by lpic10** [comment]
In linux `date` it can be `%U`, `%V` or `%W` also depending on first day of the week, being `%V` the ISO week number. Since [python 3.6 ](https://docs.python.org/3.6/library/datetime.html#strftime-and-strptime-behavior) there is also `%V` for ISO week number. If you agree on using ISO week, I think it makes sense to use that as well.

**Comment by danielnelson** [comment]
That sounds perfect.
