### ISSUE TITLE
Support Kafka 0.11+ 

### ISSUE THREAD

**Issue by nrwiersma** [influxdata/telegraf#3501]
### Proposal:

Support Kafka 0.11+ 

### Current behavior:

When trying to consume from a Kafka 0.11+ (in my case 1.0) cluster an error is recieved:
```
Error in plugin [inputs.kafka_consumer]: Consumer Error: kafka: error while consuming metrics/0: kafka: error decoding packet: invalid byteslice length
```
This is due to Kafka now using Record batches instead of Messages.

### Desired behavior:

Telegraf should be able to consume from a Kafka 0.11+ cluster. This can be effectively achieved by upgrading Sarama, and providing an option to set the Kafka cluster version.

**Comment by danielnelson** [comment]
@nrwiersma I am not able to reproduce this with Telegraf 1.4.5 and Kafka 1.0.0.  I have a very simple kafka setup, using an unmodified server.properties I'm starting with:
```
/opt/kafka_2.11-1.0.0/bin/kafka-server-start.sh config/server.properties
```

Then I'm just manually publishing via:
```
bin/kafka-console-producer.sh --broker-list localhost:9092 --topic metrics
```

Do you know what else is needed to reproduce this error?

BTW, we have updated the sarama and sarama-cluster libraries in Telegraf 1.5, so it might be working now, which is why I have been trying to reproduce with 1.4.5.

**Comment by nrwiersma** [comment]
@danielnelson It was suggested to me that perhaps the issue is that you are running a single instance rather than a cluster.

At any rate our fix was to manually update sarama. I will ask our Ops team to test Telegraf 1.5 and see if this fixes the issue for them. I will let you know what happens with this.

**Comment by nrwiersma** [comment]
Our Ops team has this in their queue of things to do, but for now lets assume this fixes the issue (as this is what we did) and if we run into any issues, we will take them up in a new ticket on Telegraf 1.5.

Thanks for your time.
