### ISSUE TITLE
not able to push metric to Inbound telegraf webhooks from github server

### ISSUE THREAD

**Issue by skajagar** [influxdata/telegraf#3679]
HI,

trying to push github  metric/events to wavefront through telegraf inbound webhooks with following configs and receiving metric to wevefront
```
[[inputs.webhooks]]
#   ## Address and port to host Webhook listener on
   service_address = "IP:1619"
#
   [inputs.webhooks.github]
     path = "/github"
     measurement_name = "testing"
    # TAGS
    * 'admin' = `event.sender.site_admin` bool
# FIELDS
    * 'commit' = `event.comment.commit_id` string
```

webhooks is successfully configured in git server, please help on this.

**Comment by danielnelson** [comment]
What are you expecting to happen and what is actually happening?

**Comment by skajagar** [comment]
I have my own repository and want to get the notification for telegraf webhooks which I can post it to wavefront

Ex: For pull_ request event
I want to get metric "no of file changed", "no of file added" "no of open issues" "no of deletion" etc.

I am interested possibly to get all the notification.

I need to know how to configure telegraf.conf to get these all metrics and configure for individual if needed.

Thanks in advance

**Comment by danielnelson** [comment]
This is the minimum configuration you will need for the plugin, you will also need to make sure that this port is accessible from the internet so that github can send events:
```
[[inputs.webhooks]]
  service_address = ":1619"
  [inputs.webhooks.github]
    path = "/github"
```

Check https://github.com/influxdata/telegraf/tree/release-1.5/plugins/inputs/webhooks/github for the full documentation.  If you have more questions, your best bet is to ask at the [InfluxData Community](https://community.influxdata.com) site.
