### ISSUE TITLE
Create a math processor plugin

### ISSUE THREAD

**Issue by rakshith-b91** [influxdata/telegraf#3709]
## Bug report
As of now conversion  supports only float, can we do the same for divide and multiply the data before output.

### Steps to reproduce:

1. Run telegraf conf with snmp input plugin, the output of timestamp is given in timeticks, we need to divide it by 6000 to get in minutes, we are not able do any conversion other than float in snmp plugin.

**Comment by danielnelson** [comment]
I think the solution to this would be a processor that can do mathematical operations, this is lightly discussed in https://github.com/influxdata/telegraf/issues/2667#issuecomment-301538731.  In the meantime you should be able to do this conversion on query.

**Comment by cruscio** [comment]
Additional use case - Calculating % of total CPU utilization of a Windows process.

Windows Perfmon provides process-level CPU utilization in `Process\% Processor Time`: The sum of processor time on each processor. This needs to be multiplied by the number of logical CPU cores to get a % of total CPU used by a process. `([Process(x)\% Processor Time] * ([Logical CPU Cores] * 100)) * 100`. It'd be ideal to perform this calculation locally at time of collection.

**Comment by sslupsky** [comment]
Another use case:  Merging two fields/tags into one.  For instance, the high byte and low byte of a 16 bit integer.  ie:  result = high_byte * 256 + low_byte.

**Comment by simoelmou** [comment]
This type of mathematical processing would be very useful in the case of the use of some types of time series databases such as OpenTSDB which doesn't support a lot of aggregation expressions, and it'll help to calculate SLAs an option.

**Comment by TimurDela** [comment]
Unit conversions can be done in queries because they always use the exact same operation but mathematical operations that may change in time cannot be done after the data has been logged.
For instance, I have a device that provides analogue signals (always between 4 and 20mA).
Initially, I set it so that 4mA means 0kW and 20mA means 1000kW.
After a while, I realise that my power never drops below 10kW nor exceeds 20kW so in order to increase the precision of the measurement, I set my device so that 4mA means 10kW and 20mA means 20kW.
Logging the analogue signal in mA is meaningless, I want Telegraf to directly log the quantity I am interested, without having to change all my queries.
