### ISSUE TITLE
Input plugin for monitoring remote process

### ISSUE THREAD

**Issue by zeinababbasi** [influxdata/telegraf#3759]
# Feature Request
Request for an input like `procstat` which can monitor processes on a remote server.

## Proposal:
It can be a combination of `jolokia2` and `procstat`; like `jolokia2`, there is an agent on the remote server and like `procstat`, it collects measurements based on a process code.

## Use case: [Why is this important (helps with prioritizing requests)]
Telegraf agent is expected to be installed on ALL the machines that needs to be monitored for system performance. This may not be acceptable in some strict corporate environments. It can be made as a VM/appliance that can be deployed in one network and configured to monitor ALL machines/DBs/... from one place.

**Comment by danielnelson** [comment]
If it needs an agent on the remote server then why not just make that agent Telegraf?  If you have ssh access I think you could arrange for Telegraf to access the other machine in this manner with the procstat plugin in particular, but the method needed would be specific to the plugin.

**Comment by zeinababbasi** [comment]
@danielnelson 
An agent, for example `jolokia2`, is an internal part of an application, but `telegraf` is a completely independent application and should be ran and managed separately. BTW, as I said in the **Use Case** section, there are a lot of cases where I want to configure one single `telegraf` in order to collect data from multiple processes from remote servers.

About configuring `procstat` to use SSH access; would you please give me a resource to read? I found nothing in [its Github page](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/procstat).

**Comment by danielnelson** [comment]
Putting aside how jolokia is loaded, which isn't really possible in Go, it sounds like your request would be to have a centralized configuration of Telegraf?  Would it be okay if there was still a "dumb" Telegraf running on the remote machine as a daemon?

Regarding remote procstat: I haven't actually tried this, and it is definitely hacky, but it seems like it should be possible to run procstat remotely if you know a bit about the implementation.  The way it works is first by running `pgrep` and secondly by inspecting the files in `/proc` (In 1.6 it will be able to only use `/proc` by using `pid_finder = "native"`).  Also some of the methods don't use `pgrep` such as the `pid_file` option.

Assuming you are using options that need pgrep, you could create a wrapper script called `pgrep` and place it into Telegraf's PATH before the system pgrep.  The script would login to the remote machine and run pgrep, you would need to configure passwordless login for the user.

The other bit is getting access to `/proc`, I think you should be able to use sshfs or nfs to mount the remote `/proc` locally and then use the HOST_PROC environment variable to specify the location the directory.  One problem I see is that you can really only monitor one host since the environment variable can only be set once.

**Comment by powersj** [comment]
Going through old issues, based on the previous comments I still don't think we plan on creating a remote agent. The use of sshfs/nfs to remote mount the filesystem or using a wrapper around pgrep are the way to go here. 

Closing as won't fix.
