### ISSUE TITLE
provide some official enums of client error code

### ISSUE THREAD

**Issue by lgarithm** [influxdata/telegraf#3820]
### Proposal:
Provide some official string constants as client error code.
Originally from discussions [here](https://github.com/prometheus/prometheus/pull/3542#pullrequestreview-98503220)

### Current behavior:
The query method of influxdb [client](https://godoc.org/github.com/influxdata/influxdb/client/v2#Client) returns an error, but there is not stable way of determining its type other than string matching.

### Desired behavior:
Provide some official error code, or just some sting contants that we can use to determine the error type.

### Use case: [Why is this important (helps with prioritizing requests)]
Some monitoring clients (promethus remote storage adaptor, telegraf, etc) needs to create database in influxdb if database not exist.

**Comment by krasi-georgiev** [comment]
here is one example how this is handled in the standard os package
https://golang.org/pkg/os/#IsNotExist

**Comment by danielnelson** [comment]
If I'm understanding this correctly we would need this issue to be open against InfluxDB: https://github.com/influxdata/influxdb.  The InfluxDB HTTP API is what provides the error strings and would need to have codes added to it.  Also, the official Go client for InfluxDB is here but is not used by Telegraf due to metric conversion performance: https://github.com/influxdata/influxdb/tree/master/client
