### ISSUE TITLE
Support for Amazon Kinesis Firehose

### ISSUE THREAD

**Issue by charliezgc** [influxdata/telegraf#3897]
### Proposal:

Kinesis output plugin should support both kinesis data stream and kinesis data firehose

### Current behavior:

Kinesis plugin supports kinesis data stream

### Desired behavior:

Kinesis plugin also supports kinesis data firehose

### Use case: [Why is this important (helps with prioritizing requests)]

We currently batch upload log and metric records to aws XRay through firehose. Since telegraf does not support firehose directly, we use it to output to local files, and then let aws kinesis agent to tail the files and batch upload the records. It would be great to remove the single purpose aws kinesis agent from the pipe line, since telegraf is almost there to replace it.

**Comment by sjwang90** [comment]
If anyone is interested wants to work on this, feel free to clone @doransmestad's PR #3544. 

Due to the late activity, it may be best to have this output plugin as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md). Telegraf users would be able to start using this plugin quicker.
