### ISSUE TITLE
procstat input plugin: notifying if process is dead or not found

### ISSUE THREAD

**Issue by arindamchoudhury** [influxdata/telegraf#3936]
### Current behavior:

Error is logged in telegraf log file.

### Desired behavior:

A metric field to monitor the error using the output.

### Use case: [Why is this important (helps with prioritizing requests)]

It will be helpful for monitoring.

**Comment by russorat** [comment]
@arindamchoudhury thanks for the report. We will look into adding this. If you'd like to take a stab at it and submit a PR, that would be awesome!

**Comment by danielnelson** [comment]
We have a related pull request #2687, but we aren't sure how we would structure the metrics in all cases, let's make sure we hammer out how the output should look before we write any code.

The obvious solution of adding a new field has some limitations, one issue is that some process search methods, such as `pattern = ".*"` return a dynamic list of processes.  In this case it is probably better for the series to be removed instead of attempting to report an error, because it wouldn't be clear when the process is gone.

Another issue is that when `tag_pid = true`, the plugin outputs a line like this:
```
procstat,exe=dnsmasq,pid=44979 cpu_user=0.14,cpu_system=0.07
```
If the process is not running, there is no pid, and you wouldn't be able to output a point to this series, again this be even more strange if you have multiple processes.

Perhaps a better solution than adding a new field is to have add a new measurement that summarizes the number of processes added, something like these:
```
procstat_processes,exe=dnsmasq found=1i
procstat_processes,pattern=.* found=7i
```

**Comment by danielnelson** [comment]
Closed in https://github.com/influxdata/telegraf/pull/4307
