### ISSUE TITLE
Add ability to configure HOST_PROC, HOST_SYS, etc from config file

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#4006]
### Proposal:

It would be nice if you could set these values from the config file on a per plugin basis.

See also: https://github.com/influxdata/telegraf/issues/2527

### Current behavior:

Must set in Telegraf Environment

### Desired behavior:

Be able to set in config like:
```
host_proc = "/rootfs/proc"
```

### Use case:

This would make it possible to monitor multiple roots and keeps all config in the Telegraf config file.

**Comment by horseinthesky** [comment]
Am I right it is impossible for telegraf to get host data from container now?

**Comment by danielnelson** [comment]
No, you can get host data by bind mounting the relevant volumes from the host, based upon which plugins you are using.

https://github.com/influxdata/telegraf/blob/master/docs/FAQ.md#q-how-can-i-monitor-the-docker-engine-host-from-within-a-container

**Comment by like-inspur** [comment]
When I search HOST_ETC、HOST_PROC and HOST_SYS in telegraf code, only HOST_PROC  can be found from code. So is it truly useful  by set HOST_ETC and HOST_SYS  when I use telegraf in container? @danielnelson

**Comment by danielnelson** [comment]
These environment variables are mainly used by github.com/shirou/gopsutil, which implements the lower level calls in quite a few plugins such as system, disk, diskio, mem, cpu.  I'm not sure the exact bits that would require HOST_ETC, it is probably not required or only in an specific case.

**Comment by like-inspur** [comment]
I see, those values are useful in gopsutil, so I ready to commit pull request for this description

**Comment by reimda** [comment]
The purpose of the host_proc functionality is for a container/vm to be able to access /proc of the host. Since there's only ever one host, I don't see the need to allow multiple values of host_proc for different plugins. I think it's also appropriate for it to be an environment variable as that's a common way to pass information into a container when running it.

If there are use cases I'm missing, feel free to reopen this or open a new issue. Thanks!
