### ISSUE TITLE
procstat may need concurrency for a list of processes

### ISSUE THREAD

**Issue by xuyao18** [influxdata/telegraf#4138]
### Relevant telegraf.conf:
I am using procstat plugin to collect usage of process in windows server.

config including
[[inputs.procstat]]
pattern = '.'
pid_tag = true

### System info:

Windows 2012 
telegraf: 1.6.1

### Steps to reproduce:

1. using the config above , to start telegraf

### Expected behavior:

all processes' stat in my server can be collected as configured.

### Actual behavior:
some logs in telegraf.log
[inputs.procstat]: took longer to collect than collection interval (10s)

### Additional info:
This is what I read from telegraf code.
```
func (p *Procstat) Gather(acc telegraf.Accumulator) error {
...
for _, proc := range p.procs {
		p.addMetrics(proc, acc) 
	}
....
```
I am not expert in golang , but I think we should concurrently collect process stat not in sequence.
This is what I think about this situation
```
var wg sync.WaitGroup

func (p *Procstat) Gather(acc telegraf.Accumulator) error {
...
for _, proc := range p.procs {
                wg.Add(1)
		go p.addMetrics(proc, acc) 
	}
wg.Wait()
....
```

**Comment by danielnelson** [comment]
Couple follow up questions:
- What do you have `pid_finder` set to?
- How long does it take if you run: `telegraf --input-filter procstat --test`?

> I think we should concurrently collect process stat not in sequence

It might be required to do this in Windows, but on Linux this may end up causing additional load since it is just reading files and collection is already very fast.

You might also want to compare with the `win_perf_counters` plugin to see how performance is.

Finally, we usually recommend against collecting all processes do to the number of series it creates, at the very least keep a close eye on your series cardinality to avoid overloading your database.

**Comment by danielnelson** [comment]
> I tried using --test it costs over 10 seconds in deed.

But it is eventually completing?

**Comment by xuyao18** [comment]
no ,  it's skipped.
