### ISSUE TITLE
Allow user to completely disable logging in Telegraf

### ISSUE THREAD

**Issue by ono760** [influxdata/telegraf#4168]
Telegraf fills the logging directories, and as a user, I should be able to completely disable logging in Telegraf. In addition, Telegraf logs to `syslog` and there seems to be no ability to specify an alternative logfile.

**Comment by danielnelson** [comment]
You can set this option to to completely avoid logging:
```
[agent]
  logfile = "/dev/null"
```

Telegraf doesn't log to syslog directly, it either logs to stderr or to the file set using that option.  Are your logs going into `/var/log/syslog`?

**Comment by danielnelson** [comment]
Which distro and version?

**Comment by danielnelson** [comment]
The packages `/var/log/telegraf/telegraf.log` on sysvinit systems, and effectively to `/var/log/messages` on systemd systems, even though we create a subdirectory for the telegraf.  This behavior is shared with InfluxDB.  

I think we should adjust the systemd systems to log into `/var/log/telegraf/telegraf.log`.

**Comment by danielnelson** [comment]
Logging location is another issue though, to completely disable logs use the technique above.  I recommend using `quiet` instead if possible:
```
[agent]
  quiet = true
```

I opened the log location as #4174

**Comment by cellcoresystems** [comment]
> Telegraf fills `/var/log/messages`

@ono760 @timhallinflux 
This can be stopped by adding the following to prevent `telegraf.service` stdout writing to `/var/log/messages`.
And you will receive stderr.
[source: silent-a-systemd-service](https://serverfault.com/questions/838574/how-to-silent-a-systemd-service)
```service
# /usr/lib/systemd/system/telegraf.service
[Service]
StandardOutput=null
StandardError=journal
```
It works even if you have `outputs.file` configured for example.
```service
[[outputs.file]]
  files = ["stdout","/tmp/metrics.out"]
  rotation_max_size = "50MB"
  rotation_max_archives = 4
  data_format = "influx"
```
---
as @danielnelson stated
> You can set this option to to completely avoid logging:
> ```
> [agent]
>   logfile = "/dev/null"
> ``` 
> Telegraf doesn't log to syslog directly, it either logs to stderr or to the file set using that option. Are your logs going into `/var/log/syslog`?

and

> Logging location is another issue though, to completely disable logs use the technique above. I recommend using `quiet` instead if possible:
> 
> ```
> [agent]
>   quiet = true
> ```
> 

This only works when no `output.file` with `stdout` is defined otherwise stdout is used also for telegraf.service which writes to `/var/log/messages`

Hope that helps.

Cross reference #4174
