### ISSUE TITLE
Allow to collect performance counter from remote host(s)

### ISSUE THREAD

**Issue by DmitryMaletin** [influxdata/telegraf#4221]
## Feature Request
Allow to collect performance counter from remote host(s)

### Proposal:
Add server list into configuration & build full path for perf counter including host 
It will allow to have a dedicated host which will collect data 

### Current behavior:
Agent should be installed on the same machine 

### Desired behavior:
Agent  can be installed on any other machine
Optionally: collect counters form set of machine

### Use case: [Why is this important (helps with prioritizing requests)]
It's not always possible to install 3rd party software on host. 

Configuration might looks like that:

  [[inputs.win_perf_counters.object]]
    # Processor usage, alternative to native, reports on a per core.
    Servers = ["$COMPUTERNAME","HOST1","HOST2"]
    ObjectName = "Processor"
    Instances = ["_Total"]
    Counters = [
      "% User Time",
      "% Processor Time"
    ]
    Measurement = "win_cpu"

some draft version: https://github.com/DmitryMaletin/telegraf/tree/dma

**Comment by danielnelson** [comment]
@DmitryMaletin We have an existing issue for this feature #1899.  There is also some work in progress on this feature so I think it is coming soon.  Can you take a look at this PR to see if it looks correct, it says closed but only because we need to update the code due to a refactor of the win_perf_counters plugin.  https://github.com/influxdata/telegraf/pull/4076#issuecomment-392708595

**Comment by Vikonder** [comment]
Hi,
Is it possible to use remote Host for collection data from MSMQ VIP  (Cluster)?
I don't see in the plug list support for MSMQ
