### ISSUE TITLE
Better abstraction of serializer and parser plugins

### ISSUE THREAD

**Issue by srclosson** [influxdata/telegraf#4330]
## Feature Request
Currently, if a parser plugin or serializer plugin requires special configuration, this configuration is currently hard coded into config.go and removed from the configuration prior to adding it to an input plugin. I find this confusing, and would like to recommend a better layer of abstraction be used so that 
1) parser and serializer plugins have a clear indication of their location in the config file
2) That location, like an input/output/processor/aggregator plugin would have it's configuration parsed directly, rather than indirectly.

### Proposal:
For example, currently if a parser plugin like graphite uses a separator, you must declare it as part of your input plugin

[[input.tail]]
separator = ","

This is not documented as part of the input plugin, and therefore confusing to configure. Parsers and Serializers should be treated the same way, but perhaps as part of the input plugin itself, and you should be able to have multiple parsers.

For example:
[[input.tail]]
  [[parser.graphite]]
    separator = ","
  [[parser.filestat]]
    use_utc_time = true

In the above example, I may want to collect two different types of metrics from the tail input. Information from the contents of the file being tailed, but perhaps information about the file being tailed. This type of configuration seems much more intuitive to me.

### Current behavior:
See above. Currently parsers configuration is hard coded, and developers are required to change a common file, which I think then has the potential of having a lot of changes. 

### Desired behavior:
See above. I would like to use multiple parsers for my inputs, and be able to have that parser grab it's own config.

### Use case: [Why is this important (helps with prioritizing requests)]
Right now, if I want to write a new parser with custom options, I either have to change config.go, or I have to edit all the plugins and add the parser functionality in them. 

I also want to run multiple parsers that may collect different types of data

**Comment by danielnelson** [comment]
I agree, and the fact that parsers/serializers are not first class plugins heavily reduces the number of community contributions.  It doesn't scale up because they all share a single config and the instantiation of parsers/serializers is more time consuming and error prone.  Because they all touch config.go they are a difficult to keep up-to-date if you have custom parsers outside the Telegraf source tree.

A couple things to keep in mind though when we attempt this.  We don't want to break the config file, so we need to keep the old configuration valid, I would also be happy with a new nested format if we can work that out.

This is something I experimented with last year when I was working on a config fileupdate, which has been put on the back burner for now.  Perhaps we can port the section of that code that dealt with parsing the config seperately without the rest of the changes.

https://github.com/danielnelson/tgconfig

**Comment by srclosson** [comment]
I love the idea of the loader @danielnelson. Being able to read config from an http stream or yaml or whatever is an outstanding idea. 

I'm going over your code, and just trying to understand where you were going with it. I think I'm getting the gist. 

I'd like to play the devils advocate on the backwards compatibility notion if I may. Would providing a tool or automation to convert config from one format to another acceptable? I don't feel like a most extensible configuration mechanism is a lot to ask. Changing config with tools like ansible/puppet/salt/chef etc. is no longer a big task. I feel like trying to retain backwards compatibility will hold back the product, and takes away much of what open-source agility provides.

Is there a code review process that can be used during development that can keep things on target? I could throw out some ideas, get feedback, rinse and repeat...

**Comment by danielnelson** [comment]
Given the size of the install base of Telegraf, and the complexity of its config file, I would like to avoid breaking changes whenever possible even if we have a tool that can update the config file.  One thing we can do though is add an alternate way of specifying parsers and then in the future remove the old style.

In order to get your other changes added, first we will need to split them up into individual plugins.  I think it is best to pick the one plugin that seems easiest, and open a pull request for that first.  This should give you an idea of how much work the rest will take, and should give you some ideas for other changes that may be required.

> Perhaps after this is done?

Yes, perhaps we should put the parsers on hold until we fix this issue so we will have less work untangling them later.

**Comment by sspaink** [comment]
All of the parsers have been migrated to be first class plugins: https://github.com/influxdata/telegraf/issues/10482, serializers haven't been updated yet but I think its better to track this in a separate newer issue.
