### ISSUE TITLE
Large numbers are rounded.

### ISSUE THREAD

**Issue by glinton** [influxdata/telegraf#4331]
### Relevant telegraf.conf:
```
[[inputs.mysql]]
  servers = ["root:password@tcp(mysql:3306)/"]
  interval_slow = "30m"
```
### System info:

[Include Telegraf version, operating system name, and other relevant details]
 * Telegraf v1.7.0
 * Ubuntu 18.04
### Steps to reproduce:

1. Collect basic stats from mysql
2. Look for the field `max_join_size`

### Expected behavior:
```
mysql> SHOW GLOBAL VARIABLES;
| max_join_size | 18446744073709551615 |
...
max_join_size=18446744073709551615
```
### Actual behavior:
```
max_join_size=18446744073709552000
```
### Additional info:
```
telegraf_1  | mysql_variables,host=3549010a79d2,innodb_version=5.7.22,server=mysql:3306 max_sp_recursion_depth=0,max_prepared_stmt_count=16382,max_relay_log_size=0,max_write_lock_count=18446744073709552000,metadata_locks_cache_size=1024,myisam_data_pointer_size=6,max_points_in_geometry=65536,max_execution_time=0,max_heap_table_size=16777216,max_join_size=18446744073709552000,max_length_for_sort_data=1024,metadata_locks_hash_instances=8,multi_range_count=256,max_error_count=64,max_seeks_for_key=18446744073709552000,max_sort_length=1024,max_tmp_tables=32,max_user_connections=0,min_examined_row_limit=0,max_insert_delayed_threads=20 1529537880000000000
```

**Comment by glinton** [comment]
Influx currently only supports "double precision floating point numbers." That is as precise as a `float64` can get in this case. [See here](https://play.golang.org/p/TD_YdCaIjzx) for an example of float precision.

**Comment by kyunghoj** [comment]
So how can I deal with this issue? Shouldn't I collect this metric?

**Comment by gangseok514** [comment]
@glinton Hello, I'm facing the same issue. In this case, Should I change max setting in mysql? or are there any workaround? Thanks.

**Comment by glinton** [comment]
@kyunghoj I personally see no value in collecting a static value like this, so a non-exact value is likely fine. If you do need to collect it, you can lower the max setting in mysql as @gangseok514 mentioned.

**Comment by glinton** [comment]
I can see that, and I definitely agree that if a real value is that high, data integrity is imperative. Maybe we'll wait to merge #4430 until the next major release since it would disrupt current implementations. Perhaps @danielnelson has some thoughts.

**Comment by danielnelson** [comment]
I think this data is useful to collect, often even static values are nice to track to be used as thresholds for alerts, or just view them across all database instances.  While it could be considered wasteful to update them so frequently it is often easiest to just get them with everything else since the size of a single field is so little.

This is an unfortunate bug as we recently fixed a bunch of type errors in this plugin, which is somewhat of a chore to deal with changes as a plugin user, you can read about it under [metric_version](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mysql#metric-version).  However it would not be off the table to introduce a `metric_version = 3` with another set of type fixes.  I prefer to add support for as many v2.0 features as possible now, and then with the 2.0 release we will only remove deprecated features and update defaults.

That said, there are some issues with the implementation in #4430. I will comment over there with more details.

**Comment by srebhan** [comment]
@kyunghoj: The mysql-driver supports `ColumnTypeScanType()` to derive the actual type from the DB/scheme-definition. It includes information about signedness of the column. Instead of guessing the types, we should use this information to parse the value.
