### ISSUE TITLE
Ping module to return IP 

### ISSUE THREAD

**Issue by AsenZahariev** [influxdata/telegraf#4353]
## Feature Request

Opening a feature request kicks off a discussion.

### Current behavior: Is not showing the IP address 
ping,url=ping-what-you-want,host=ping-from-the-host
average_response_ms=54.54,standard_deviation_ms=0.593,packets_transmitted=20i,packets_received=19i,percent_packet_loss=5 1530176987000000000

### Desired behavior:
ping,url=ping-what-you-want,host=ping-from-the-host
average_response_ms=54.54,standard_deviation_ms=0.593,packets_transmitted=20i,packets_received=19i,percent_packet_loss=5 1530176987000000000,ip_address=xx.xx.xx.xx

**Comment by glinton** [comment]
Could you pair `ping` with the `exec` plugin running a `dig`/`host` or something similar?

**Comment by danielnelson** [comment]
I think we shouldn't add this in the ping plugin because the ip address is not really part of the ping data, the hostname lookup happens before any pinging occurs and is similar to any other network operation.  

You could get the address using dns_query if we add this feature: https://github.com/influxdata/telegraf/issues/2834
