### ISSUE TITLE
Could not connect to Jolokia endpoint - connection refused

### ISSUE THREAD

**Issue by andreypp** [influxdata/telegraf#4371]
I am trying to collect metrics from Jolokia using Telegraf.
My application is instrumented properly with Jolokia, and I'm able to get te response from it using curl like below:
`curl -X POST http://localhost:8092/jolokia/read -H "Content-Type:application/json" -d '  {
    "type" : "read",
    "mbean" : "java.lang:type=Memory",
    "attribute" : "HeapMemoryUsage",
    "path" : "used"
  }'
`

Response: `{"request":{"path":"used","mbean":"java.lang:type=Memory","attribute":"HeapMemoryUsage","type":"read"},"value":272254264,"timestamp":1530622794,"status":200}`

But in my telegraf output log (from docker logs) I see the following error:
`2018-07-03T12:53:10Z E! Error in plugin [inputs.jolokia2_agent]: Unable to gather metrics for http://localhost:8092/jolokia: Post http://localhost:8092/jolokia/read: dial tcp 127.0.0.1:8092: getsockopt: connection refused`

My confg file 
```
[agent]
  debug = true
  quiet = false
  interval = "10s"
  precision = "10s"

[[inputs.jolokia2_agent]]
  urls = ["http://localhost:8092/jolokia"]

  [[inputs.jolokia2_agent.metric]]
    name  = "java_runtime"
    mbean = "java.lang:type=Runtime"
    paths = ["Uptime"]

  [[inputs.jolokia2_agent.metric]]
    name  = "java_memory"
    mbean = "java.lang:type=Memory"
    paths = ["HeapMemoryUsage", "NonHeapMemoryUsage", "ObjectPendingFinalizationCount"]

  [[inputs.jolokia2_agent.metric]]
    name     = "java_garbage_collector"
    mbean    = "java.lang:name=G1*,type=GarbageCollector"
    paths    = ["CollectionTime", "CollectionCount"]
    tag_keys = ["name"]
```

I tried to use Debug mode but I am not seeing debug messages on log output (console)
Tested on 1.7.0 and 1.6.4
Any other idea on how to proceed?

**Comment by danielnelson** [comment]
Since you are running in docker you will need to make sure Telegraf can reach the container you application is in.  This depends a bit on how you are starting your containers, in some simple cases you may just need to start the Telegraf container with something like `--net=container:yourappcontainer`. I also suggest using the `docker exec` command to run a shell in your Telegraf container for debugging.

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
