### ISSUE TITLE
Add prometheus parser and serializer

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#4414]
### Proposal:

Add a parser and a serializer that support Prometheus text exposition format

### Current behavior:

No such parser/serializer

### Desired behavior:
```
data_format = `prometheus`
```

### Use case:

Would be useful for integrating with services which use this format but do not use HTTP, and for transferring prometheus specific metadata such as TYPE and HELP (#4354)

**Comment by danielarkins** [comment]
Interested in similar, would like to use http output plugin to perform a post of metrics to a custom collector in Prometheus exposition format. Do we know if anyone is considering this?

**Comment by danielnelson** [comment]
It is something we are planning to do but have not started work on.  You might also be interested in #5003.

**Comment by danielarkins** [comment]
Thanks this is not bad but I am looking to leverage the http outputs plugin to post and just put the data in prom expos format

I’m thinking it’s not to difficult

Sent from my iPhone

On Feb 6, 2019, at 4:53 PM, Daniel Nelson <notifications@github.com<mailto:notifications@github.com>> wrote:


External Email: Use caution with links and attachments


It is something we are planning to do but have not started work on. You might also be interested in #5003<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_influxdata_telegraf_pull_5003&d=DwMCaQ&c=zUO0BtkCe66yJvAZ4cAvZg&r=PX3mIUBgypJ_Ngt43z45tkt-jfL2ASCsYjTQMG7c-mU&m=qPnji9u_A_2Sar5QGVfTn39g-78wpCs_bRBBUdTzW34&s=uibJCq6Clry3YHKodncpYNS_A2ccWpuzDKSJlszQcgk&e=>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_influxdata_telegraf_issues_4414-23issuecomment-2D461202748&d=DwMCaQ&c=zUO0BtkCe66yJvAZ4cAvZg&r=PX3mIUBgypJ_Ngt43z45tkt-jfL2ASCsYjTQMG7c-mU&m=qPnji9u_A_2Sar5QGVfTn39g-78wpCs_bRBBUdTzW34&s=SruvBs3WWcFjG6DDkptlxPDJIHB8u928GGRiE-eZefQ&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AYebAmwTLYNWKqbaNBscLx25jGJA4njBks5vK07RgaJpZM4VMORI&d=DwMCaQ&c=zUO0BtkCe66yJvAZ4cAvZg&r=PX3mIUBgypJ_Ngt43z45tkt-jfL2ASCsYjTQMG7c-mU&m=qPnji9u_A_2Sar5QGVfTn39g-78wpCs_bRBBUdTzW34&s=E2049ArdQPMFB0-4rg1i0g4jkMWCASEBcdWy8VEDhQU&e=>.

This message may contain information that is confidential or privileged. If you are not the intended recipient, please advise the sender immediately and delete this message. See http://www.blackrock.com/corporate/compliance/email-disclaimers for further information.  Please refer to http://www.blackrock.com/corporate/compliance/privacy-policy for more information about BlackRock’s Privacy Policy.
For a list of BlackRock's office addresses worldwide, see http://www.blackrock.com/corporate/about-us/contacts-locations.

© 2019 BlackRock, Inc. All rights reserved.

**Comment by allangood** [comment]
I'm interested in this feature as well. My use case is because I have some systems that logs the metrics to a file and telegraf has a file plugin, but it cannot parse the Prometheus metrics. The interesting part is that Telegraf is capable to read Prometheus metrics from http requests and also can expose as client, but cannot parse it.

**Comment by Elinvention** [comment]
Also this could be useful to avoid having to install a Prometheus PushGateway, if I understand correctly. We could push prometheus metrics directly into Telegraf.

**Comment by vpedosyuk** [comment]
@elithe1 I've got the same use case, so wondering if you've managed to get it working somehow?

**Comment by debu99** [comment]
+1

**Comment by elithe1** [comment]
I actually ended up writing my own parser. Tou can still some good code
from the repo from other prometheus stuff there

**Comment by omegarus** [comment]
If I understand correctly, for now file input plugin is not supporting prometheus data format ?

**Comment by danielnelson** [comment]
Right now we have only a serializer for Prometheus data format, so it can only be used in output plugins.  Hoping to add a parser so it can be used in the file input in the future.

**Comment by lekuyuan** [comment]
Now is there a plugin that can satisfy this situation ( from telegraf to pushgateway)?
