### ISSUE TITLE
Collect Nvidia GPU metrics without nvidia-smi

### ISSUE THREAD

**Issue by pytimer** [influxdata/telegraf#4506]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Collect nvidia gpu metrics  without `nvidia-smi`.

### Current behavior:

Telegraf use input `nvidia_smi` to collect gpu metrics can not work if `nvidia-smi` not installed on host.

### Desired behavior:

Telegraf add a new input plugin to use load `NVML` library to collect nvidia gpu metrics if host not install `nvidia-smi` executable binary file.

### Use case: [Why is this important (helps with prioritizing requests)]

On my case, some host use gpu, but not install `nvidia-smi` binary file, so gpu metrics could not collect use `nvidia_smi` input plugin.

**Comment by danielnelson** [comment]
This would be great, especially for performance, but we have some requirements for working with C libraries.

It needs to be possible to compile and run Telegraf without having any external libraries present on the system.  Also, remember that since Telegraf is currently cross compiled on Linux, on other platforms CGO is not enabled.  This doesn't mean the plugin has to work without CGO or that the plugin can't be optional, but it probably wouldn't be enabled in the official builds.

**Comment by sjwang90** [comment]
Telegraf now allows plugins to be built without Go libraries with [external plugins](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) if you are still interested on getting this done with a C library.

**Comment by powersj** [comment]
As sjwang90 said above, users can use external plugins for C library. Given the [go-nvml](https://github.com/NVIDIA/go-nvml) library requires cgo, the external library would be the route to go. I'm going to go ahead and close this issue as I don't see us adding this directly.

**Comment by pytimer** [comment]
OK, i will try plugins to do it. Thanks.
