### ISSUE TITLE
Add HTTP Digest Access Authentication to the http input

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#4524]
### Proposal:

The `http` input plugin should support HTTP Digest Authentication as desribed in [rfc2617](https://tools.ietf.org/html/rfc2617).

There has been prior discussion of this feature on https://github.com/influxdata/telegraf/issues/461

### Current behavior:

No support

### Desired behavior:

Support added.

**Example**
```
curl --user aaa:bbb "http://xxx.yyy" --digest -v
Authorization: Digest username="root", realm="Forbidden", nonce="04d5b48c5e6c8b9b3dd84af4ce6b7643", uri="/", cnonce="OTEyZTZkMTExZjk1NDAxM2EyMDdlMThlNDc4MTM4MGM=", nc=00000001, qop=auth, response="a2ac73d78e199580a2c8546ac4ba7229", opaque="7a6a2abf367f778892c5db364070449f", algorithm="MD5"
```

### Use case:

Needed for interop with servers expecting digest authentication

**Comment by danielnelson** [comment]
@spidie @marianob85 @aashley This issue replaces #461

**Comment by yaazkal** [comment]
Hello, I wonder if this feature request has any chance to be implemented.
Regards !

**Comment by russorat** [comment]
@yaazkal no this issue is still pending. Could you add your use case and why this addition would be helpful for you to help us prioritize against the other work in the project? Also, if someone from the community would like to take a stab at implementing this, we would be glad to review the PR. Thanks!

**Comment by yaazkal** [comment]
@russorat Thanks for the answer.

**About Digest authentication (context)**
`The Digest authentication scheme [...] is intended as a replacement for Basic authentication and nothing more.` as seen on [rfc2617 section 3.1.4](https://tools.ietf.org/html/rfc2617#section-3.1.4)

` The protocol referred to as "HTTP/1.0" includes the specification for a Basic Access Authentication scheme[1]. That scheme is not considered to be a secure method of user authentication, as the user name and password are passed over the network in an unencrypted form. This section provides the specification for a scheme that does not send the password in cleartext,  referred to as "Digest Access Authentication".` as seen on [rfc2617 section 3.1.1](https://tools.ietf.org/html/rfc2617#section-3.1.1)

**Why is good to have it implemented**
As is the replacement of the basic auth; many companies has opted to use it as the default way of authentication in their web servers, this of course is not the safest authentication method, it has its own limitations but is the prefered method against basic auth.

**My use case**
I'm using telegraf to consume an url that will result in a csv file as [described in page 6 of this document](https://www.egauge.net/media/support/docs/egauge-xml-api.pdf).

This is to use an API that a device called [egauge](https://www.egauge.net/) has. The device dosen't support basic auth but digest authentication by default.  As every device has it's own web server and I can't change its configuration (and If I can I will not want to because of the reference above), I'm forced to use Digest for every device, now as I'm using ansible to provision many raspberry pi and then every pi will consume an egauge device, this can solve my specific use case multiplied by the devices I'll provision :)

Anyway I don't think there will be few use cases, as digest is a replacement of basic auth as cited before.

**Comment by yaazkal** [comment]
Let me add that after writing this I've checked the code to see if I can open a PR. Found that golang has no digest auth support in the http module. As there are third party modules that add support for it, I'll sugest to discuss them first before choosing one or maybe do a feature request in golang. What do you think?

Regards !

**Comment by danielnelson** [comment]
@yaazkal Doesn't appear that Go will be adding first party support for digest authentication in the near term.  Would you be able to make a list of the libraries that implement support?

**Comment by yaazkal** [comment]
@danielnelson I'm aware of the existence of:

https://github.com/bobziuchkovski/digest wich is a fork of [this](code.google.com/p/mlab-ns2/gae/ns/digest)
https://github.com/delphinus/go-digest-request
https://github.com/Soontao/goHttpDigestClient

I end up using the first of the list on a project because it was pretty straight forward but I had to change this [switch](https://github.com/bobziuchkovski/digest/blob/26857231d60c9cfee5fbe14cd873bf7633ebbd80/digest.go#L105) because if the header also has `charset` it was defaulting to an error. 

I also tried with the other libraries but found them confusing and at the end they didn't worked for me (maybe is a lack of knowledge by my side).

My general impression is that there is still work to be done in any of those and I'm not sure if they are maintained as I don't see recent activity (old commits, issues and PRs).

**PS** if anyone end up searching for a workaraound to use digest in telegraf: For my project I end up using `[[inputs.exec]]` with a curl command, something like:

```
[[inputs.exec]]
  commands = [ "curl -X GET -u USER:PASSWORD --digest 'https://URL'" ]
```

**Comment by yaazkal** [comment]
My personal opinion is to contribute or request the digest support in golang directly and use the `exec` input in telegraf

**Comment by srebhan** [comment]
Is this issue still relevant to anyone @here?

**Comment by daniel-falk** [comment]
I have to resurrect this topic again since I too am astonished that this is not part of the Telegraf `http` input. It is still very common that both internal IT systems and IoT devices do not allow BASIC auth, e.g. the [Axis Communications network cameras](https://www.axis.com/) do per default not always support BASIC auth. The reason for this is that BASIC auth never should be used without TLS since that would send the passwords in plain text. Both for company internal services and for IoT devices, it is common to not have reliable TLS infrastructure, meaning that you would want to prevent BASIC auth. To give some perspective, [curl added support for DIGEST back in 2003](https://curl.se/changes.html#7_10_6).

I do not know a lot about Golang and how their strategy is on having auxiliary features in libraries or the core language, but I am surprised to hear that the built-in HTTP module there does not support it.. It does however seem like they are handling this by allowing a [custom http.RoundTripper](https://lanre.wtf/blog/2017/07/24/roundtripper-go). The [icholy/digest](https://github.com/icholy/digest) library linked above supports this for adding DIGEST auth.

This means that it would probably be a few lines change to add DIGEST support and it could be done without affecting existing code at all. My proposal would be to add a new parameter to the plugin called `digest_auth` to enable the new feature:

```
[[inputs.http]]
  urls = ["http://example.com/metrics"]
  username = "myuser"
  password = "mypass"
  digest_auth = true  // This does not exist today
```

if this flag is set, all we need to do is to create a new transport wrapper and use that when creating the `http` module. The code would look something like this:

```go
	var client *http.Client
	var req *http.Request
	var err error

	// Build request first
	req, err = http.NewRequest("GET", url, nil)

	if useDigest {
                // Wrap the transport with digest authentication from the library
		client = &http.Client{
			Transport: digest.NewTransport(username, password),
		}
	} else {
		// Use the standard built-in Basic authentication from the http module
		client = &http.Client{}
                if h.Username != "" || h.Password != "" {
                        req.SetBasicAuth(h.Username, h.Password)
                }
       }

	// Perform the request
	resp, err := client.Do(req)
```

It's essentially one new if-statement to branch on the `digest_auth` flag, and one extra argument to the constructor.

**What's the way forward?**
Given the small size of the change, and that it does not affect existing use, I have a hard time seeing that this would be a problem? The core question then is the use of a new library? Would it be OK for you to depend in the (MIT licensed) [icholy/digest](https://github.com/icholy/digest) library? If not, what requirements do you have for libraries?

I don't know a lot about Golang and I don't have a lot of time, so I would be really happy if someone would be open to implement this. I would be happy to help with testing and code review / coming with ideas.
