### ISSUE TITLE
Telegraf throws `Illegal Instruction` on arm A9 system

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#4526]
### Relevant telegraf.conf:
N/A

### System info:
arm A9 system
telegraf 1.7.2

### Steps to reproduce:

1. try to install and run `telegraf_1.7.2-1_armel.deb` on an arm A9 system 
2. notice the illegal instruction when trying to run telegraf

### Expected behavior:
telegraf runs

### Actual behavior:
illegal instruction thrown when starting

### Additional info:
basically, you need to try to get to setting `GOARM=5` in the build script but the logic is incorrect. If you try to build with `--arch=armel`, then on line https://github.com/influxdata/telegraf/blob/master/scripts/build.py#L455 the `arch` is overwritten to be `arm` and then the logic on line https://github.com/influxdata/telegraf/blob/master/scripts/build.py#L461 is never executed.

**Comment by osingla** [comment]
The issue is that the armel.deb image currently built using build.py with this command:
./scripts/build.py --platform=linux --arch=armel --version 1.7.2 --package
generate actually an armhf image (GOARM=6) instead of the expected armel (GOARM=5), and this image will require a cpu with floating point and a kernel built with armhf support.
