### ISSUE TITLE
http_response creates two versions of http_response_result_code when result_code becomes 3

### ISSUE THREAD

**Issue by i2blind** [influxdata/telegraf#4574]
### Relevant telegraf.conf:

[[inputs.http_response]]
    name_suffix = "_TEST1"
    address = "http://somehost:9198/metrics"
    response_timeout = "10s"
    method = "GET"
    follow_redirects = true
    response_string_match = "go"

### System info:
both telegraf 1.7.0.1-1
telegraf 1.7.3-1

CentOS Linux release 7.5.1804 (Core)  Virtual Machine
[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

configure telegraf to monitor a URL
make the url unconnectable, ie stop apache etc.

### Expected behavior:
upon error I should only get one result_code metric with result code of 3
http_response_TEST1_result_code{host="somehost","bunch of tags you dont' care about",method="GET",result="connection_failed",result_type="connection_failed",server="http://somehost:9198/metrics",status_code=""} 3
### Actual behavior:

instead I get two, one showing the correct status code and one indicating that success.  
http_response_TEST1_result_code{host="somehost","bunch of tags you dont' care about",method="GET",result="connection_failed",result_type="connection_failed",server="http://somehost:9198/metrics",status_code=""} 3

http_response_TEST1_result_code{host=somehost","bunch of tags you dont' care about",method="GET",result="success",result_type="success",server="http://somehost:9198/metrics",status_code="200"} 0

### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
I think this is because the tags do not match, otherwise the new failure metric would overwrite the old one instead of creating a different metric.  Can you check if the tags are different and what tags are changing?

**Comment by i2blind** [comment]
The tags and values of those are the same except for the status_code, result and result_type.   The other tags that i removed are statically assigned to the agent as a whole.  I did a comparison of the two lines to make sure.

**Comment by i2blind** [comment]
I have a few other http_response configurations on this same telegraf instance as well and I have seen this same behavior with others.

**Comment by danielnelson** [comment]
The change is the status_code, result, result_type tags are enough to cause problems here, we don't have a way to know these are readings are for the same logical object.  I think there are two actions you can take:

1. Set `expiration_interval = "60s"` to a value appropriate based on your agent interval.  You will want it high enough that values do not disappear between collections, but low enough that stale metrics don't stick around forever.

2. Remove the offending tags so that only one metric is created.  In this example, you could tagexclude status_code, result and result_type to remove them from the output, and possible combine this with the `string_as_label = false` parameter on the prometheus output.

I'm going to close this issue, I think there is nothing that should be changed in Telegraf, but let me know if these workarounds will work out for you and if you have any follow up questions.

**Comment by i2blind** [comment]
your workaround for tagexclude partially worked.  

I had to do this.
    tagexclude = ["status_code","result"]
    fielddrop = ["result_type"]

**Comment by i2blind** [comment]
This is working, setting prometheus output a suggested resolved.
