### ISSUE TITLE
Time-based limits of metrics

### ISSUE THREAD

**Issue by ono760** [influxdata/telegraf#4578]
## Feature Request

The `metric_buffer_limit` setting in Telegraf is not very helpful when I want to control the ability to only send time-based limits of metrics.

For example, instead of a buffer_limit of `5000`, I would like my Telegraf agent(s) to keep only 30 minutes worth of data in its buffer. 

The number of metrics in the buffer is useless when I don’t know how many lines are output, pending on the number of input plugins enabled. This is especially the case with docker hosts that can have `1` to `100` docker containers, which requires a larger `metric_buffer_limit`.

**Comment by sspaink** [comment]
Is this still a relevant feature request? It has been quite sometime since this issue was opened, and I am wondering if this still needs to be investigated. If it is could you provide a use case with an example using the latest version of Telegraf to demonstrate the issue you are having with `metric_buffer_limit`?
