### ISSUE TITLE
Many processes with same name, but wanted to point out one of these.

### ISSUE THREAD

**Issue by kjedrol** [influxdata/telegraf#4590]
Hello,
First of all, many thanks for great plugin. Appreciate Your work.

I have many processes with the same name: "nssm.exe", but every of them is different program.
I would like to point out in configuration file, the path to the exactly one process.
Is it possible?
Thanks in advance for Your help.

Example:
[[inputs.win_perf_counters.object]]
    ObjectName = "Process"
	Counters = ["ID Process","% Processor Time","Handle Count","Private Bytes","Thread Count","Virtual Bytes","Working Set","Elapsed Time"]
    Instances = ["nssm"]
    Measurement = "nssm"

**Comment by danielnelson** [comment]
@kjedrol I will check into this the next time I have access to a Windows machine.

**Comment by danielnelson** [comment]
It doesn't seem like it would be possible to collect the executable path with performance counters, the best you could do is collect all of the processes separately, but you won't know which without checking the pid by hand:
```
[[inputs.win_perf_counters]]
  UseWildcardsExpansion = true
  [[inputs.win_perf_counters.object]]
    ObjectName = "Process"
    Counters = ["ID Process","% Processor Time","Handle Count","Private Bytes","Thread Count","Virtual Bytes","Working Set","Elapsed Time"]
    Instances = ["nssm*"]
    Measurement = "nssm"
```

Another hacky idea is to copy and rename the nssm executable, this seems to work for okay for me, the instance is the name of the executable.
```
[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Process"
    Counters = ["ID Process","% Processor Time","Handle Count","Private Bytes","Thread Count","Virtual Bytes","Working Set","Elapsed Time"]
    Instances = ["nssm2"]
    Measurement = "nssm"
```
 
We might be able to add something similar to procstat in the future, since we can access the executable path using gopsutil (WMI), but if this is the service manager, you probably actually want to search based on the arguments to nssm?  In that case this would probably be best done with a plugin like suggested here: https://github.com/influxdata/telegraf/issues/1857

**Comment by kjedrol** [comment]
Thank You so much!
It helped!
Glad, that there are people like You :)

niedz., 2 wrz 2018, 03:53 użytkownik Daniel Nelson <notifications@github.com>
napisał:
