### ISSUE TITLE
Get Kafka topic number of messages (count) as output value

### ISSUE THREAD

**Issue by meetchandan** [influxdata/telegraf#4600]
## Feature Request
```
[agent]
interval = "60s"
flush_interval= "60s"

[[inputs.kafka_consumer]]
topics = ["test1", "test"]
brokers = ["xx.xx.xx:9092"]
consumer_group = "telegraf-kafka-to-influxdb"
offset = "oldest"
data_format = "json"

[[outputs.influxdb]]
urls = ["http://influxdb:8086"]
database = "telegraf"
```

Now, with above, I am able to push kafka messages in above topics to my desired output (influxdb in my case)

What I wish to do is, instead of the kafka messages being pushed, I just want the message count in kafka topics during the interval to be inserted into influxdb.

I do not know if this is possible currently, or this is very vague requirement.

P.S. My use case is, I wish to track how many messages are being put into kafka topics per minute.

**Comment by danielnelson** [comment]
You can use the [jolokia2](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jolokia2) plugin to get JMX metrics from Kafka, I would start with the [example configuration](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/jolokia2/examples/kafka.conf).

Another popular input for monitoring Kafka is the [burrow input](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/burrow).

Finally, you could directly measure what you consume in the kafka_consumer by enabling the [internal input](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/internal).  I don't know if this would make sense though because if you don't need the messages you would need to filter them away.  But it might be suitable for a short performance test.

You also might be able to find out some more ideas by asking on the [InfluxData Community](https://community.influxdata.com) site.
