### ISSUE TITLE
Configurable Docker endpoint

### ISSUE THREAD

**Issue by longnguyen11288** [influxdata/telegraf#463]
Is it possible to make docker endpoint configurable and have a default if it isn't specified

**Comment by sparrc** [comment]
can you provide more details?

**Comment by zstyblik** [comment]
@sparrc my guess is Docker over TCP, resp. `DOCKER_HOST=tcp://X.X.X.X:2375/` instead of U*nix socket in `/var/lib/run/docker.sock`.

**Comment by longnguyen11288** [comment]
My unix socket isn't running at /var/lib/run/docker.sock. and would like for it to be configurable so I can use this awesome plugin for my servers.

On January 14, 2016 at 9:02:49 PM, Cameron Sparr (notifications@github.com) wrote:

can you provide more details?

**Comment by zstyblik** [comment]
@longnguyen11288 I'd say this is rather question for gopsutil which is being utilized by Telegraf.

**Comment by sparrc** [comment]
I'm not sure that I follow.....the docker plugin uses cgroup files to gather stats (such as `/sys/fs/cgroup/cpuacct/docker`). Maybe I'm missing something but I don't think it's accessing /var/run/docker.sock?

**Comment by sparrc** [comment]
@longnguyen11288 It should be fairly easy to change this: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/ps.go#L139

But does your system still have the cgroup files (such as `/sys/fs/cgroup/cpuacct/docker`) available locally? because https://github.com/shirou/gopsutil/ relies on these local files to gather stats.
