### ISSUE TITLE
Does telegraf plan to support ROS message input?

### ISSUE THREAD

**Issue by itfanr** [influxdata/telegraf#4692]
## Feature Request

 ROS is a popular platform in robotics .When dealling with performance tunning, We need a visual graph to find the bottleneck.

### Proposal:
Add a plugin to support ROS message.
You can refer to : `http://wiki.ros.org/roscpp`

### Current behavior:
Not support ROS

### Desired behavior:
Add a plugin to support ROS message.

### Use case: [Why is this important (helps with prioritizing requests)]
Do performance tunning with telegraf

**Comment by danielnelson** [comment]
@itfanr We don't currently have any plans for this, looks interesting though.

One potential problem is that we don't currently accept plugins that use non-Go code.  This is mostly because we are not setup to do cross compilation of other languages and we don't want to add C/C++ library dependencies to the build.  Do you know if there is a Go implementation of the client?

Another possible issue is that we currently have a pretty hefty backlog, and I'm not sure if this will have enough interest to where we could add it very soon.

**Comment by itfanr** [comment]
@danielnelson 

Thank you for you reply. I find that someone is writing a go client.

https://github.com/akio/rosgo

ROS1 is popular and it has many problems.
In ROS2, any launguage is supported to easily access to ROS. But there are some time to make it widely used.

**Comment by windelbouwman** [comment]
This is certainly an interesting idea. Since ROS1/ROS2 is a pretty compilated system, with many libraries, it might make most sense to create a ROS node, which is a telegraf client. Probably using the socket input plugin.

**Comment by srebhan** [comment]
Querying data from ROS nodes is certainly a bit out of scope for Telegraf and implementing a node in ROS to send the data is probably more feasible. One thing I could imagine is querying metrics from ROS itself, but that's probably not what is requested here. If you feel this feature should be implemented, please feel free to speak up and provide a pull-request.
