### ISSUE TITLE
telegraf appears to be inserting HOST and URL fields into influx input data

### ISSUE THREAD

**Issue by martinwalke** [influxdata/telegraf#4760]
Hi,
I'm sending the following string to telegraf upon a GET request using the [inputs.http] section:

 server_2 cdce_1=1i,cdce_2=1i,sams_hb_1=1i,sams_hb_2=1i,sams_vl_1=1i,sams_vl_2=1i

but when it's passed to influx, the data becomes:

server_2,host=DEV-1,url=http://xx.xxx.xxx.xx:8080/web-app/services/status/interfaceStatusTelegraf?serverId\=1 sams_hb_1=1i,sams_hb_2=1i,sams_vl_1=1i,sams_vl_2=1i,cdce_1=1i,cdce_2=1i 1538041290000000000

which causes the extra columns to be created in influx.

Am I missing a config parameter somewhere to turn the extra fields off?

TIA

**Comment by danielnelson** [comment]
You can remove the url tag using [`tagexclude`](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering).

If we were to write this plugin today, we would use `source` instead of `url`.  Since `source` is always only a hostname we might want other tags such as `scheme` or `port`.  In the future, I think we also ought not add any tags to `ParserInput`'s by default.
