### ISSUE TITLE
Record the source IP address of syslog messages

### ISSUE THREAD

**Issue by candlerb** [influxdata/telegraf#4762]
## Feature Request

As far as I can tell, the syslog receiver in telegraf 1.8.0-1 does not log the source IP address of the incoming message.  It would be helpful if it did.

### Proposal:

Add a new tag containing the source IP address, e.g. `source`

This could optionally be reverse-DNS resolved; but if so I would like an option to turn it off; I prefer the raw IP addresses for accuracy (not subject to reverse DNS spoofing) and performance.

OR: replace the current tag `host` with this information.

### Current behavior:

The [documentation](https://github.com/influxdata/telegraf/tree/release-1.8/plugins/inputs/syslog#metrics) says that a tag called `hostname` is added.

Experimentation shows that:

* telegraf adds two tags, `host` and `hostname`
* `hostname` is the hostname contained *within* the syslog message
* `host` is the host where telegraf itself is running (or possibly influxdb - I have them both running on the same host)

This can be demonstrated by sending a test message from a remote host.  Here, the tick stack is running on host 10.12.255.35.  On a different host (10.12.255.33) I do the following:

```
# echo "60 <13>1 2018-09-27T07:41:24.310199+00:00 zzzz root - - -  qux" | nc 10.12.255.35 6514
```

Querying influxdb:

```
> select * from syslog where "hostname" = 'zzzz'
name: syslog
time                           appname exampleSDID@32473_eventID exampleSDID@32473_eventSource exampleSDID@32473_iut facility facility_code host hostname message msgid procid severity severity_code timestamp           version
----                           ------- ------------------------- ----------------------------- --------------------- -------- ------------- ---- -------- ------- ----- ------ -------- ------------- ---------           -------
2018-09-27T10:57:16.712507294Z root                                                                                  user     1             tick zzzz      qux                 notice   5             1538034084310199000 1
```

So the message has been received, but the source address 10.12.255.33 (or its reverse DNS) has not been logged anywhere.

### Desired behavior:

Logging the telegraf host doesn't appear to be particularly useful, although I suppose it might be if you have multiple telegraf servers.  But knowing where the syslog message came from is much more useful.

### Use case:

Knowing with certainty where the syslog message came from is very useful:

* for certainty of provenance (the "hostname" field of syslog messages is easily spoofed)
* for machines which don't include their hostname in syslog messages

**Comment by glinton** [comment]
`host` is added by telegraf to all metrics unless disabled with the following config:
```toml
[agent]
  omit_hostname=true
```
It seems we may want to change `hostname` to `source` in our quest to unify tags (4413), or just add `source` and do as you suggested and assign it the source ip.

**Comment by danielnelson** [comment]
There are two main ways you could deploy this plugin:
- One syslog input on a central server that all syslog agents send to.
- Telegraf on every server with the syslog input running, all data is sent InfluxDB directly or to batching Telegrafs.

Granted that in the first deployment model, the host is not very useful, especially if you have only one Telegraf.  The second model works better if you also want to use other Telegraf plugins and provides a neat fan-in data flow for all of your metrics.  In this case you can assume that the `host` tag will be accurate and describe the server reporting the logs.

----

We are generally favoring a more readable hostname over IP address with the `source` tag, but I think we would only want to do a reverse DNS for TCP connections and only if some new option is set.  On UDP connections and by default we should only use the IP address.  It probably makes sense to start with the IP address in the `source` tag.

I think many may want to trust the hostname to be the source, but I'm unsure if we want to add another option just for this behavior.  For now let's require this to be done externally using processors.

I think we should keep both the `hostname` and the `source` tags since they show data obtained using different methods.  The cost of storing two tags when they are locked together is very low because they don't increase the number of series, and really only become a problem when you can have all permutations.  Using `tagexclude` is an available option as well.

**Comment by candlerb** [comment]
Thank you, I agree with all of that.  A separate processor for reverse DNS resolution makes sense.  It could put the reverse DNS name in a separate tag if you choose; it could also implement "paranoid" mode where it checks that there is matching forward DNS.

I can see one other potential problem with UDP address spoofing: if source address is stored in a *tag* rather than a *field*, and someone spoofs 2^32 different source addresses, then they could create 4 million time series (or unlimited with IPv6).  But equally they could just fill your disk with junk messages - so syslog needs to be blocked at your network border anyway.

**Comment by dpajin** [comment]
Having source IP address in the tag (not reverse DNS name) is really a necessary feature in network monitoring. Would you be able to move forward with this, I guess adding `source` tag with source IP address of UDP packet is not much complicated?

**Comment by luanhdeandrade** [comment]
Is there a plan for anybody to implement this? It would be super helpful

**Comment by reimda** [comment]
> Is there a plan for anybody to implement this? It would be super helpful

If you'd like to contribute a PR to add the source tag it would be welcome.  Since this issue was last active the reverse_dns processor was added.  It should work with a source tag from this plugin once it's added.

**Comment by thepacketgeek** [comment]
I was looking into this enhancement this while working on #8454, should be easy enough to add. I'll give it a shot this weekend :)
