### ISSUE TITLE
Kinesis Output should support aggregating messages

### ISSUE THREAD

**Issue by shanielh** [influxdata/telegraf#4795]
### Proposal:

Kinesis Output should support aggregating messages into one message, one known format is the [KPL aggregated format](https://github.com/a8m/kinesis-producer/blob/master/aggregation-format.md).

### Current behavior:

Each metric is sent as a different record in Kinesis, one shard supports up to 1000 records / second or up to 1 mb / second. Because of that behaviour, more shards are needed, but not necessarily.

### Desired behavior:

There are some well known formats (separate records in textual format with "\n") and compressions (snappy, gzip) that allows to reduce the size and number of messages sent to kinesis queue and allow users to save costs.

These behaviours (compression, aggregation) can be used also when sending data to other outputs (S3, Azure Event Hub, Kafka, etc...)

### Use case: 

Sending lots of metrics w/ Kinesis is currently not optimised and costs a lost because messages are not aggregated / compressed.

**Comment by DimaRabkin** [comment]
+1

**Comment by jregovic** [comment]
+1

**Comment by morfien101** [comment]
I have been looking into this as we have similar requirements.

So far I have the following:
- Metrics are joined together by "\n"
- Metrics can be compressed with snappy (reasonable compression and very fast)
- Metrics can be compressed with GZip (Much better compression by much slower, generally fast enough)

I'm leaning to better compression over speed as we are talking about a few milliseconds (2-3) to compress most of our batches.

However the issue seems to come in when we need to sort the metrics via a partition key. From the ideas that I have come up with I can only really aggregate and compress them when using the random partition key. Which leaves the sorting to the consumer. In my case I care very little about this and am more interested in getting the data rather than what shard it comes in on.

I'm interested to hear what others think of the partition keys and if anyone actually uses it or than random.

**Comment by sjwang90** [comment]
Added as an [external plugin](https://github.com/influxdata/telegraf/blob/master/EXTERNAL_PLUGINS.md#outputs)
