### ISSUE TITLE
Reduce data collection space

### ISSUE THREAD

**Issue by AlexStreaming** [influxdata/telegraf#4861]
I need to reduce my / data directory of influxdb. My idea is to increase the parameter "interval" to i.e 1 minute in the telegraph agents, could that help? I do not see differences. Do the flush_interval and flush_jitter parameters affect the size of data stored by influxdb ?. If the answer is yes, what would be the best values to reduce the size of data? What is the function of these two parameters?

**Comment by danielnelson** [comment]
The interval controls the rate that standard inputs poll for metrics, and doubling it will generally half the amount of data you send.  This setting usually does not affect service inputs which are event driven and produce as many metrics as are sent to them.

Flush interval controls the **longest** amount of time between writing to the outputs, but since all metrics are always written changing it will not reduce the amount of data.  Flush jitter just adds an amount of random time to each flush interval to reduce the thundering herd problem when you have many Telegraf's reporting.

Closing, but feel free to ask follow up questions or you can also ask over on the [InfluxData Community](https://community.influxdata.com) site.
