### ISSUE TITLE
Try to update "telegraf.conf" every time (at least) debian package is upgraded

### ISSUE THREAD

**Issue by nervo** [influxdata/telegraf#4966]
As `/etc/telegraf/telegraf.conf` is included in debian "conffile" package control, if modified locally, every time an `apt-get update/upgrade` is launched, dpkg warns us that "Package distributor has shipped an updated version" and asks for which action to take (install the package maintainer's version, keep your currently-installed version, ...).
This is a bit annoying in a full automated environment :)

From now:
* Yes, there are some dpkg options like `--force-confold` and `--force-confdef` to work around this "issue", but most of the time, they are globally used, and what is relevant for telegraf debian package, is not necessary relevant for other packages
* One could say "ok, keep the upstream `/etc/telegraf/telegraf.conf`, and use the `/etc/telegraf/telegraf.d` directory" but there are some already enabled plugins in the `/etc/telegraf/telegraf.conf`; some of them you don't want, or some of them you want to overrides

I don't really know if `rpm` packages suffers from the same problem..

Anyway, i see - at least - two solutions:
* Provide an upstream `/etc/telegraf/telegraf.conf` where *all* plugins are commented/disabled. Using `/etc/telegraf/telegraf.d` directory could become the more-or-less official way, and the package init scripts could provide separated config files for input/ouput plugins currently enabled by default.
* Provide `/etc/telegraf/telegraf.conf` in an install script, only if absent, which is a traditional debian way to handle this.

Thanks for reading, and wonder what your feelings are on that.

**Comment by danielnelson** [comment]
I think we could potentially only have the `[agent]` section in the telegraf.conf, and add the default plugins under telegraf.d.  On first install we could generate the default plugins into telegraf.d, but otherwise take a hands off approach.

**Comment by nervo** [comment]
@danielnelson that's a good solution. `[agent]` section (and maybe `[global_tags]` too) can be overwritten in "telegraf.d", unlike plugins sections, defined in array of tables.
This way, `telegraf.conf` could remain unchanged, and package upgrades as sweet as possible :)

I can initiate a pull request if you want.

**Comment by danielnelson** [comment]
That would be great if you can put together a pull request.  I will mention that while I think my suggestion above would be a good place to be, we need to take special care getting there.  It should probably only be done if we are doing a fresh install and there is no /etc/telegraf directory.  We will need to also implement this for the rpm package as well.

Being able to overwrite the agent/global_tag sections is probably behavior I would classify as a bug, I'm not sure it will be allowed forever as the ordering of config file loading is undefined and it seems confusing to understand what the final config would be.  I think you would only be prompted if the config changes though, and the agent section is fairly stable, but it might be worth checking.

**Comment by kir4h** [comment]
Trying out telegraf and reached the same concern on my first upgrade. I was thinking of moving everything to `telegraf.d` but reading this I realized this wouldn't work since there are things enabled by default. 

The current proposed approach if I understood it correctly would be:

1. Modify `telegraf.conf` so that only agent section remains active.
    * Question: By doing so, would we be able to override properties? (say `agent.interval` defaults to 10s but I want to specify a different value, this wouldn't be possible since we don't want to enable overriding right?)

1. Modify packages so that if no `/etc/telegraf/` (or maybe `/etc/telegraf/telegraf.conf`?) is found, default plugins are added onto `/etc/telegraf/telegraf.d`

Just a thought: What if we just modify the packages so that if `/etc/telegraf/telegraf.conf` is not found, the package installs it but if it already exists the package writes it to a different file? This is for instance what dpkg does when we say to keep our current version, or with `--force-confold` (it saves it as `telegraf.conf.dpkg-dist`).

I agree with my suggestion one could think 

> but this is exactly what `--force-confold` is for!

and I could configure it this way under my settings but as @nervo was saying this is a global configuration, I might not want this for all my packages. Being practical, I think the most common use case is to keep current Telegraf settings during an upgrade, rather than wanting to replace it.

**Comment by danielnelson** [comment]
> Just a thought: What if we just modify the packages so that if /etc/telegraf/telegraf.conf is not found, the package installs it but if it already exists the package writes it to a different file?

I think this could be easier to roll out.  We could write to a new file `/etc/telegraf.conf.sample` as a non-conffile and if `/etc/telegraf.conf` is not found we copy it there.  This seems safe for now and in the future we can revisit providing an empty configuration.

Debian suggests this[[1]] as the second method for quieting dpkg:

> If the program you're packaging requires every user to modify the configuration files in the /etc directory, there are two popular ways to arrange for them to not be conffiles, keeping dpkg quiet:
>
> - Create a symlink under the /etc directory pointing to a file under the /var directory generated by the maintainer scripts.
>
> - Create a file generated by the maintainer scripts under the /etc directory.

[1]: https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles
