### ISSUE TITLE
improve doc for input plugin vsphere

### ISSUE THREAD

**Issue by bgjoseluis** [influxdata/telegraf#4981]
Hello all,

thanks for your great job.

I would like to suggest to improve the doc for vsphere input plugin. I would like to be clarified the bellow sections/points:

01.- Could be added an example for parameters "collect_concurrency" and "discover_concurrency" in a large vCenter?, will be helpful to "define" in some way what is a "large" vCenter and the value for the parameters depending on how large is the vCenter (i now that is difficult but some example will help).

02.- Please could be specified which parameters must be lower than 8, each parameter individually ("collect_concurrency" and "discover_concurrency") or both added?

03.- Credentials for telegraf user to connect vCenter (or role).

Thanks for your time, anyway we are working with vsphere input plugins, if we get some know about these parameters i will share it.

Regards.
JLBG

**Comment by danielnelson** [comment]
Thanks for the feedback, @prydin do you know the answer to these questions?

**Comment by Peteyboo** [comment]
I'd also like to see documented what type of security level is needed for #3 (Credentials for telegraf to connect to Vcenter)?

**Comment by sspaink** [comment]
It looks like there has been improvements to the vsphere docs since this issue was made, I don't see the security level mentioned but there is more info about "collect_concurrency" and "discover_concurrency".

@Peteyboo or @bgjoseluis have either you found the answers you were looking for? If you did would you be interested in updating the README with what you discovered?
