### ISSUE TITLE
vsphere plugin: count vm in host or datacenter

### ISSUE THREAD

**Issue by solune** [influxdata/telegraf#4993]
I just want to graph the number of VM in my datacenter or on a particular host over the time.
How can I do this  ?

**Comment by prydin** [comment]
Which visualization tool are you using? Most of them have some kind of query construct that allows you to do that. It would only show powered on VMs, though, since they are the only ones reporting metrics.

We are currently discussing exposing some metrics for powered off VMs as well, but that's a pretty big code change, since they don't report metrics the usual way.

**Comment by solune** [comment]
I'm using grafana and I want to graph the number of VM

**Comment by danielnelson** [comment]
You should be able to do a query like this with InfluxDB, in Grafana you will need to "toggle edit mode" to the textbox:
```
select count(count) from (select count(usage_average) from vsphere_vm_cpu group by esxhostname) where $timeFilter group by time($__interval)
```

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.

**Comment by solune** [comment]
It works, thanks a lot
