### ISSUE TITLE
Select tags in vSphere plugin

### ISSUE THREAD

**Issue by AdamJohnson100** [influxdata/telegraf#5124]
## Feature Request
Be able to select which tags/keys should be imported from vSphere
### Proposal:
Be able to select custom labels in vSphere to bring over as tags (including other metadata like ip)
### Current behavior:
custom labels are not brought in as tags
### Desired behavior:
Custom labels can be selectively added in the conf file
### Use case: [Why is this important (helps with prioritizing requests)]
Increase data quality and allow better linking/unification of systems.  Difficult to compare systems in vSphere to workloads running inside it without any metadata linking or better way to unite the data.

**Comment by GeckoZero** [comment]
Nice one! 

I noted down some ideas with some relevance to that in another issue: https://github.com/influxdata/telegraf/issues/4955#issue-377098286

**Comment by GeckoZero** [comment]
Since the custom attribute feature works pretty well, the tag thing is on our focus again too. It has to do with internal billing, governance, reporting and so on.

I have to revise my opinion from the last post. Both feature requests are not the same and need to be handled differently. The result will be the same though.

That means that all "custom" tags of a vSphere asset should be added to the tag set of a metric.
Perhaps it would be wise to be able to filter the amount of "custom" tags that will be added.

**Comment by reimda** [comment]
Hi @GeckoZero were you able to find a solution to your problem?
