### ISSUE TITLE
Confusing/inconsistent use of `telegraf.Metric` fields?

### ISSUE THREAD

**Issue by amoghe** [influxdata/telegraf#5166]
### Additional info:

IIUC, the `telegraf.Metric` interface is organized so that many related measurements are reported as a single metric. So, for example, when reporting measurements of CPU related metrics, we can do something like this:

```
fieldsC := map[string]interface{}{
	"time_user":       cts.User,
	"time_system":     cts.System,
	"time_idle":       cts.Idle,
	"time_nice":       cts.Nice,
	"time_iowait":     cts.Iowait,
	"time_irq":        cts.Irq,
	"time_softirq":    cts.Softirq,
	"time_steal":      cts.Steal,
	"time_guest":      cts.Guest,
	"time_guest_nice": cts.GuestNice,
}
if s.ReportActive {
	fieldsC["time_active"] = activeCpuTime(cts)
}
acc.AddCounter("cpu", fieldsC, tags, now)
```
This single call to `AddCounter` means that a single `telegraf.Metric` is added to the accumulator  and it contains multiple measurements (metrics, really) that are all of type `Counter`. So the metric name itself serves as a namespace (and a typespace?) and the `fields` are the actual measurements in that namespace.

However, in the MySQL input plugin, I also see behavior like this:

```
dlTags["component"] = "data_length"
acc.AddFields(newNamespace("info_schema", "table_size", "data_length"),
	map[string]interface{}{"value": dataLength}, dlTags)

ilTags := copyTags(tags)
ilTags["component"] = "index_length"
acc.AddFields(newNamespace("info_schema", "table_size", "index_length"),
	map[string]interface{}{"value": indexLength}, ilTags)

dfTags := copyTags(tags)
dfTags["component"] = "data_free"
acc.AddFields(newNamespace("info_schema", "table_size", "data_free"),
	map[string]interface{}{"value": dataFree}, dfTags)
```

This seems like it is adding a set of individual `Metrics` , each similar to the other, except that it is using `component` to identify what the measurement actually is and `value` to hold the numeric value. Could this have instead been written like so:

```
fields := map[string]interface{}{
	"data_length":       data_length,
	"index_length":     index_length,
	"data_free":       data_free,
}

acc.AddGauge("info_schema.table_size", fields, tags, now)
```

Am I missing something? Or maybe I've misunderstood the telegraf.Metrics data model altogether.

Some documentation clarifying how `Metrics` are organized would be super useful. Particularly since this way of organizing multiple metrics into a single `telegraf.Metric` causes:
1. a mismatch between what `metric` means in other systems (a single thing being measured)
2. some friction/confusion when contributing input/output plugins

If such documentation exists, please point me in the right direction

**Comment by danielnelson** [comment]
Telegraf Metrics are highly influenced by InfluxDB's data model as well as [Line Protocol](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/), but has deviated in a few details.  I suggest you also read the InfluxDB documentation for more details, but I'll try to summarize and answer your questions.

> This single call to AddCounter means that a single telegraf.Metric is added to the accumulator and it contains multiple measurements (metrics, really) that are all of type Counter. So the metric name itself serves as a namespace (and a typespace?) and the fields are the actual measurements in that namespace.

Unfortunately, the code does mark all the fields as counters today, though there is desire to change this to be field specific.  The `telegraf.Metric` name (sometimes this is referred to as the measurement) does provide a namespace of sorts, though the details of what this means depends on the output.

> This seems like it is adding a set of individual Metrics , each similar to the other, except that it is using component to identify what the measurement actually is and value to hold the numeric value. Could this have instead been written like so:

Tags and fields are closely designed after the InfluxDB model.  In InfluxDB tags are indexed for fast lookup and allow a different set of queries (notably you can `group by`).  The name and tags also identify the time series, similar to a primary key in a relational database, each field can have one value at any given timestamp for each series.  Fields, on the other hand, can be one of several types (int/float/string/bool) and make up the data for the time series.

It can be tricky to design the data schema, because many decisions need to be made up front.  There are some [official recommendations for schema design](https://docs.influxdata.com/influxdb/v1.7/concepts/schema_and_data_layout/) that may be helpful.

When using InfluxDB, the Metrics have a very simple encoding from `telegraf.Metric` to a line of line protocol.  The name becomes the measurement, tags are tags, fields are fields.  However, generally speaking it is up to the individual output to decide how the `telegraf.Metric` are encoded for the output, some outputs have limitations or are even more rich with respect to how they handle the `telegraf.Metric` metadata compared to the influxdb output.

We do have some existing documentation about Telegraf [metrics](https://github.com/influxdata/telegraf/blob/master/docs/METRICS.md).

I hope this helps, let me know if you have more questions or ideas on what would be the best information to add to the documentation.

**Comment by amoghe** [comment]
Thanks for the info (and the pointer to the schema guidelines doc). With that as a background, it seems as though the MySQL code snippet (above) should be reworked to resemble the CPU metrics (`cpu` is a namespace, and other `fields` under there are the actual measurements). If I'm mistaken - what am I missing?

**Comment by danielnelson** [comment]
In fact that particular code has been reworked when using `metric_version = 2`, which is the recommended setting, and they are structured like this:
https://github.com/influxdata/telegraf/blob/675178f91569c19e78648593c33470817bcdb68f/plugins/inputs/mysql/mysql.go#L1604-L1614

As an aside, although mostly equivalent, this really should be written like this:
```
acc.AddFields(
	"mysql_table_schema",
	map[string]interface{}{
		"rows": tableRows,
		"data_length": dataLength,
		"index_length": indexLength,
		"data_free": dataFree,
	},
	tags)
```

I avoid the use of measurement in the discussion since it is heavily overloaded and generally refers to the `Name()`, but yes the fields are the "values" of the time series.  Often it makes sense to vary the `Name()` when the series has a different set of tags or groups of fields and the mysql plugin creates several values for the telegraf.Metric `Name()`.

I am sure there are many improvements that could be made in the mysql plugin and other plugins to bring it closer to the recommended schema, but changes to the schema can be quite disruptive so we try to limit the frequency of breaking changes.
