### ISSUE TITLE
Inconsistency/uncertainty about whether telegraf.d files override telegraf.conf

### ISSUE THREAD

**Issue by James00001** [influxdata/telegraf#5187]
I am using an almost-default telegraf.conf

My default config was created by using the output of created by capturing the output of telegraf -sample-config  -input-filter system:cpu:disk:diskio:kernel:linux_sysctl_fs:mem:net:netstat:processes:swap  -output-filter influxdb

I am using Telegraf 1.9.1 installed by rpm on Centos 7

I am only editing 3 lines of this default config.

in [agent] I set  logfile = "/alternate/log/location/telegraf.log"
in [[outputs.influxdb]] I set urls = ["http://10.0.2.72:8086"]
in [[inputs.cpu]] I set report_active = true

If I edit the three config lines in telegraf.conf then everything behaves exactly as I expect. The logfile location changes, my data is saved to the correct influxdb instance, and that data includes the "active" CPU measurement.

However, if instead of editing the default telegraf.conf file, I instead add my changes to telegraf.d/local.conf and leave telegraf.conf unmodified

```
[agent]
  logfile = "/bigdisk0/telegraf/logs/telegraf.log"

[[outputs.influxdb]]
  urls = ["http://10.0.2.72:8086"]

[[inputs.cpu]]
  report_active = true
```

Two of those config options behave exactly the same (agent logfile and inputs.cpu report_active) but outputs.influxdb urls behaves differently.

Instead of just sending influxdb data to http://10.0.2.72:8086 it also sends to http://localhost:8086 so my log file is full of failures, since no influxdb instance exists on localhost.

Note that the default [[outputs.influxdb]] section in the default telegraf.conf file does not contain urls = http://localhost:8086

I don't know if this is an actual bug, or just a documentation-bug where the interaction between telegraf.conf and telegraf.d/*.conf is just not adequately explained anywhere.

**Comment by glinton** [comment]
How do you think the docs could be improved to more clearly explain that the `--config-directory` flag joins the config files. It is found in the docs [here](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#configuration-file-locations):
> When the --config-directory command line flag is used files ending with .conf in the specified directory will also be included in the Telegraf configuration.
>

Were you able to find which config file contains the `localhost:8086` url?

**Comment by James00001** [comment]
Hello, glinton!

Yes, I did read that line in the docs, but what it does not tell me is exactly how the telegraf.d/*.conf files are included in the configuration.

If a single value appears in two different conf files, which one takes prioriry?

If a section appears in two different .conf files, Does it use the entire section from one conf file and ignore the other? or does it merge them?

The behavior of the logfile option in the [agent] section would suggest to me that values in config files in the config-directory override values in the main telegraf.conf file, but the behavior of the urls option in the [[outputs.influxdb]] section suggests that something more complicated is happening.

> Were you able to find which config file contains the localhost:8086 url?

No, I do not see the localhost:8086 address anywhere in any of my config files.

My best guess as to what *might* be happening is since there is a [[outputs.influxdb]] section in both telegraf.conf and telegraf.d/local.conf then _maybe_ rather than merging those two sections it is treating them as two separate sections, one with a default value for urls= and another with an actual value for urls, and then I am getting the end result of both the default and the manual options-- but I am just guessing here, I really have absolutely no idea what is really happening under the hood.

**Comment by glinton** [comment]
The docs, if there are multiple input/output tables defined, each one is it's own plugin.

**Comment by danielnelson** [comment]
I would describe it conceptually as if the multiple files are concatenated.

To understand how the configuration loading works it helps to be familiar with [TOML].  The config has two main components, the `agent` and `global_tags` are [tables], and the various plugins are defined as an [array of tables].

Since `agent` and `global_tags` are tables, they should only be defined once.  Normally in TOML defining a table twice is an error, but unfortunately due to the way the files it is not reported as an error by Telegraf if the sections are found more than once.  Don't try to figure out what Telegraf does if they are defined more than once, the behavior is unreliable, only have one of each table.

All other tables are defined as an [array of tables] and independent of each other, and TOML dictates how these work, it might be helpful to think of the conversion of TOML to JSON:
```toml
[[inputs.mem]]
  name_override = "a"

[[inputs.mem]]
  name_override = "b"
```

The equivalent configuration in JSON would be:
```json
{
    "inputs": {
        "mem": [
            {
                "name_override": "a"
            },
            {
                "name_override": "b"
            }
        ]
    }
}
```

As you add more tables, they will be appended to the list of plugins, there is no way to merge them.  This allows you to define each plugin as many times as needed.  For instance, you may want to have multiple `influxdb` output plugins to send the data to two databases.

[toml]: https://github.com/toml-lang/toml
[tables]: https://github.com/toml-lang/toml#table
[array of tables]: https://github.com/toml-lang/toml#array-of-tables

**Comment by James00001** [comment]
Thank you glinton and danielnelson!

That explanation is helpful.

I think in terms of making the documentation clearer, it would probably be good enough to add a line saying something like: 

> "Multiple configuration files behave as if they are concatenated. You should not include more than one copy of the same configuration section in more than one different *.conf file, since doing so may produce undefined results"

That would have been plenty of information to let me know that my approach was not a good fit for the way the Telegraf conf files actually work.
