### ISSUE TITLE
Documentation for DATA_FORMATS_INPUT doesn't list statsd/dogstatsd

### ISSUE THREAD

**Issue by jeffwidman** [influxdata/telegraf#5229]
Docs bug:

Shouldn't https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md include `statsd` / `dogstatsd` as an acceptable input format?

Or am I misunderstanding how this works?

**Comment by danielnelson** [comment]
The statsd and dogstatsd functionality is all contained within the [statsd input](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd).

Generally we use an input data format when it is common for the format to be stored/transferred in multiple ways which would require it to be used from multiple input plugins.  When the transport is more standardized we generally use a dedicated plugin since this is simpler to configure.  The distinction is often somewhat of a gray area.

**Comment by jeffwidman** [comment]
To provide a little more context, I am porting over a script that already emits `statsd`, and I was assuming that since `telegraf` supports `statsd`, that I could use the `exec` plugin and specify `data_format = 'statsd'`.

But are you saying that's not actually possible since `statsd` is a dedicated plugin?

**Comment by danielnelson** [comment]
It's not currently possible, perhaps you could alter the script to send on a socket instead of stdout, or write a wrapper script for your script to do the same?  I wouldn't be opposed to a PR adding the statsd format as a data_format either.

**Comment by jeffwidman** [comment]
Thanks for the fast reply. I can workaround this fine using the socket or directly modifying it to emit `json`, just wanted to make sure I clearly understood how `telegraf` worked.  Again, thank you.
