### ISSUE TITLE
HOST_VAR not respected in docker.inputs

### ISSUE THREAD

**Issue by rantoniuk** [influxdata/telegraf#5283]
Looking at #5031 we should be configuring `[[inputs.docker]]` plugin with HOST_VAR for monitoring host system. One can obviously override `#  endpoint = "unix:///var/run/docker.sock"` to include `/host` but I guess that is inconsistency in configuration?

**Comment by danielnelson** [comment]
This is an interesting point that I haven't considered.  The `HOST_VAR`, `HOST_PROC` variables are only used by plugins that don't expose the locations of the files they parse, while the docker plugin doesn't know where the socket is and just uses the given path.  I also think the environment variables are not very ideal, I would rather if these locations were set in the config file.

I understand how this would be confusing but I think we shouldn't fix this in the docker input, and instead work on making the host prefix more configurable from the config file.

**Comment by echtelerp** [comment]
some informations to #5283 and the older issue #5031: 

### Relevant telegraf.conf:
used the standard, did no changes. just ran the two commands provided in the readme of Dockerhub:
`$ docker run -d --name influxdb -p 8083:8083 -p 8086:8086 influxdb`
`$ docker run --net=container:influxdb telegraf:alpine`

### System info:
Host MacOs, Docker Version 2.0.0.2

[Include Telegraf version, operating system name, and other relevant details]

```
DockerEnvironment$ docker run --net=container:influxdb telegraf:alpine
2019-02-08T21:54:40Z I! Starting Telegraf 1.9.4
2019-02-08T21:54:40Z I! Using config file: /etc/telegraf/telegraf.conf
2019-02-08T21:54:40Z I! Loaded inputs: inputs.mem inputs.processes inputs.swap inputs.system inputs.cpu inputs.disk inputs.diskio inpu
ts.kernel
2019-02-08T21:54:40Z I! Loaded aggregators: 
2019-02-08T21:54:40Z I! Loaded processors: 
2019-02-08T21:54:40Z I! Loaded outputs: influxdb
2019-02-08T21:54:40Z I! Tags enabled: host=9ab66945f415
2019-02-08T21:54:40Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"9ab66945f415", Flush Interval:10s
2019-02-08T21:54:50Z E! [inputs.system]: Error in plugin: open /var/run/utmp: no such file or directory
...
...
```

### Steps to reproduce:

1. ...`$ docker run -d --name influxdb -p 8083:8083 -p 8086:8086 influxdb`
2. ...`$ docker run --net=container:influxdb telegraf:alpine`
watch the command line output. 

### Expected behavior:
run without errors

### Actual behavior:
`2019-02-08T21:54:50Z E! [inputs.system]: Error in plugin: open /var/run/utmp: no such file or directory`

### Additional info:

I did dig deeper in this problem. 
Alpine as being such a minimal image somehow does not provide the file, that [[inputs.system]] is looking for. 
The command uptime is working. 
```
bash-4.4# uptime
 22:11:56 up  6:36,  0 users,  load average: 0.44, 0.43, 0.30
```
I did not find a solution how to load the utmp corresponding program via apk. 

So the workaround provided in other bugs #5031 has some deeper issue behind. 
In my specific case I would like to use the container with alpine, without having to bind anything to the host. this behavior makes the container somehow dependent, what I would like to avoid. 


[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
@echtelerp Can you open this as a new issue?
