### ISSUE TITLE
http_listener_v2 config different database

### ISSUE THREAD

**Issue by meez14** [influxdata/telegraf#5356]
It would be great to have the possiblility to define a different database in this input plugin, so we are able to seperate data per input.

**Comment by danielnelson** [comment]
It's not possible to do this, by design the inputs and outputs are fully independent.  If you look at the [configuration](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md) documentation though the very last example on the page shows a technique for how to do this type of routing.
