### ISSUE TITLE
Kafka output attempting to write to influxdb on localhost

### ISSUE THREAD

**Issue by sjafferali** [influxdata/telegraf#5369]
### Relevant telegraf.conf:
```
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 10000
  metric_buffer_limit = 50000
  collection_jitter = "5s"
  flush_interval = "10s"
  flush_jitter = "5s"
  precision = "1ns"
  debug = true
  quiet = false
  logfile = "/var/log/telegraf/telegraf.log"
  hostname = ""
  omit_hostname = false

[[outputs.kafka]]
  brokers = ['XXXXXXXX']
  topic = "MY_TOPIC"
  routing_tag = "host"
```
### System info:

Ubuntu 16.04.2 LTS
Telegraf 1.9.3-1

### Steps to reproduce:
1. Add this configuration file with my Kafka topic.
2. Restart telegraf.

### Expected behavior:
Debug lines should show it writing to kafka. No output should indicate writing to outputs.influxdb .

### Actual behavior:
The below entries start getting logged. 
```
2019-02-03T03:45:01Z E! [outputs.influxdb] when writing to [http://localhost:8086]: Post http://localhost:8086/write?db=telegraf: dial tcp 127.0.0.1:8086: connect: connection refused
```

Not sure why adding a kafka output would also make telegraf start attempting to write to influxdb. Removing the ```outputs.kafka``` config, makes this error go away. 

### Additional info:
Checking my kafka topic, the plugin appears to be working, just also somehow enabling outputs.influxdb plugin as well.

**Comment by danielnelson** [comment]
In the .deb package, the `/etc/telegraf/telegraf.conf` and all files in `/etc/telegraf.d` are loaded, one of them must have the influxdb output enabled (in the default config it is enabled).  There must be more to the configuration since at least one input is also required.  Perhaps Telegraf did not restart and is still running with the default configuration?

**Comment by sjafferali** [comment]
Hey @danielnelson . This is what I originally assumed as well, however, I can reproduce this without any other configurations apart from inputs. Additionally, if I remove the kafka.conf file, this error disappears. Attached is a tar.gz file with a full copy of the /etc/telegraf directory. 

[telegraf.tar.gz](https://github.com/influxdata/telegraf/files/2826567/telegraf.tar.gz)

The endpoints of the kafka brokers and tags have been filtered out of these files. 

I also have an enterprise ticket open about this with the log file, as well as un-redacted configuration directory in ticket #40309, if you have access to this.

**Comment by danielnelson** [comment]
I think these just need to be adjusted to `outputs.kafka.tagpass`, otherwise they will create the parent table.
```
$ ack outputs.influxdb
telegraf.d/kafka.conf
99:  [outputs.influxdb.tagpass]
101:  [outputs.influxdb.tagdrop]
```

**Comment by sjafferali** [comment]
Excellent. Great catch. Seems that was it!

**Comment by raghav29061999** [comment]
I also faced the same issue then i changed the telegraf.conf file like this
urls = ["http://<ipv4 address>:8086/"]

Reasons for the Issue:
Docker Networking:

Localhost (127.0.0.1) in Containers: When you use 127.0.0.1 inside a Docker container, it refers to the container itself, not the host machine. This is because each container has its own network namespace, and 127.0.0.1 points to the loopback interface of that namespace.
Bridge Network: By default, Docker containers are connected to a bridge network, allowing them to communicate with each other using container names as hostnames.
Host Network:

Host vs. Bridge Network: When you use the host's IPv4 address, you are explicitly addressing the host machine from within the container. This tells Docker to route the traffic to the host's IP, allowing proper communication between the container and the InfluxDB instance running on the host.
