### ISSUE TITLE
Telegraf SNMP Load agent list from an external file 

### ISSUE THREAD

**Issue by salmansamie** [influxdata/telegraf#5440]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

To load telegraf inputs.snmp agents list from a different file

### Current behavior:

Telegraf inputs.snmp agents list loads from the same telegraf snmp configuration file. 

### Desired behavior:

Telegraf inputs.snmp agents list to load from a different files in telegraf.d/ for example: waf_hosts.yml, bigswitch_hosts.yml that defines the list of particular agent hosts. Here the file path to host is defined in the particular telegraf configs for a particular appliance.

### Use case: [Why is this important (helps with prioritizing requests)]
1) In production environments, it is difficult to track and list the inputs.snmp agents in the same telegraf.conf file, especially when there is a very large list of hosts.
2) Because the agent list changes almost frequently during new enrolments and decomms. 
3) Although ansible jobs can directly alter the conf, this would be a neat idea to have the agent host/IPs load from an external file.

**Comment by js-mode** [comment]
Hi Salman - I have be wondering this same thing and am curious how you are using Ansible jobs to alter the conf file?  

Right now I have a docker container that is deployed and it runs this init.sh script that populates the environment variables in the different conf files for that container: 
```
#!/bin/bash
if [ "$SNMP_LIST" ]; then
  SNMP_AGENTS=""
  COUNT=0
  for ITEM in $SNMP_LIST; do
    if [ $COUNT -gt 0 ]; then
      SNMP_AGENTS="${SNMP_AGENTS},"
    fi
    SNMP_AGENTS="${SNMP_AGENTS}\"${ITEM}\""
    COUNT=$((COUNT + 1))
  done
  echo "$SNMP_AGENTS"
fi

if [ "$DEVICE" ] && [ "$WF_PROXY" ] && [ "$WF_PORT" ] && [ "$SNMP_AGENTS" ] && [ "$TELEGRAF_SNMP_TOKEN" ]; then
  cp /setup/$DEVICE.conf /etc/telegraf/telegraf.conf
  sed -i "s|WF_PROXY|${WF_PROXY}|;\
          s|WF_PORT|${WF_PORT}|;\
          s|AGENTS|${SNMP_AGENTS}|;\
          s|TELEGRAF_SNMP_TOKEN|${TELEGRAF_SNMP_TOKEN}|g" \
    /etc/telegraf/telegraf.conf
  /usr/bin/telegraf
else
  echo "Telegraf configuration aborting due to missing ENV VARS."
  exit 2
fi
```
Problem is then we end up with 3 separate docker containers running based on the same image, and it would be a lot cleaner if I could maybe do something in ansible or make it so that the single container could run all 3 configuration files at the same time. 

One of the issues was the time out it takes to poll all of the different switches we are testing against it in the lab. Wondering if you have an example of any of the *_hosts.yml files that you would be willing to share so I can clean up some of the process I am testing out.

**Comment by Hipska** [comment]
Hi, I'm using Ansible to generate a config file for each agent I want to collect so it does not interfere with the global `telegraf.conf` file. Is this a workable alternative to your request?

**Comment by Hipska** [comment]
It is also possible to load configurations from an external source via http.
