### ISSUE TITLE
vSphere Plugin VM DNS Name

### ISSUE THREAD

**Issue by bchris999** [influxdata/telegraf#5481]
## Feature Request

VM DNS name on vCenter input plugin

### Proposal:

To add a tag of fqdn to vsphere_vm_* metrics. This should be acompanied by a similar tag to the win_* metrics.

### Current behavior:

Doesn't exist.
(win_ host tag is the VM name, which doesn't match anything in vSphere, so having a seperate fqdn or dnsname tag would be better)

### Desired behavior:

To have these exist

### Use case: [Why is this important (helps with prioritizing requests)]

It would be useful to be able to combine metrics from Windows side and VMware side into one graph (/ area).
E.g. Single graph with CPU usage from both a Windows and ESX point of view

**Comment by danielnelson** [comment]
> This should be acompanied by a similar tag to the win_* metrics.

Are you referring to the `win_perf_counters` metrics here?  The `host` tag uses [GetComputerNameEx](https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-getcomputernameexa) with the `ComputerNamePhysicalDnsHostname` parameter.  It seems we would need to use `ComputerNamePhysicalDnsFullyQualified` if we wanted it to be fully qualified.  Changing it would be a pretty big change, I would want to think about it a bit, though maybe it would make sense to allow the host tag to be generated in one of several styles.

I'm not sure it would be possible to pull the DNS name without doing a lookup for each VM, which would be unwanted due to the cost of the lookup, but I'll let @prydin respond since he knows better than I do.

**Comment by bchris999** [comment]
@danielnelson All the win_ metrics, so win_perf_counters and well as win_cpu, win_mem, win_disk, etc. I think use a different tag for FQDN to not break the current host tag.

With regards to the VM DNS name, it may require a separate lookup, in which case have it as optional for those who want it? The results returned by the second lookup however, along with DNS name, may return other useful metrics that could be sent too.

**Comment by danielnelson** [comment]
I think for some of these optional items we should experiment with creating a processor type that can do async tasks, this would allow us to lookup additional tags and add them to metrics.  In your case, could the DNS name for the virtual machines be determined based on the information from the vsphere plugin?

**Comment by bchris999** [comment]
The vsphere plugin seems to use VIM so it will be accessible through the GuestInfo of the virtual machine.

https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.vm.GuestInfo.html

I'll have to do some digging into exactly how this can be achieved from where the existing plugin is getting data.

**Comment by prydin** [comment]
We are currently working on exposing DNS names and IP addresses of VMs. I have the code running in my lab and it will be part of a larger PR we are planning on issuing shortly.

**Comment by powersj** [comment]
@prydin was this something that ever happened?
