### ISSUE TITLE
win_services state values to be better for grafana

### ISSUE THREAD

**Issue by bchris999** [influxdata/telegraf#5493]
## Feature Request

win_services state values to be better for grafana

### Proposal:

Create a second state field for better usage for Grafana Singlestat.

### Current behavior:

The state field can have the following values:

1 - stopped
2 - start pending
3 - stop pending
4 - running
5 - continue pending
6 - pause pending
7 - paused

This does not work well with the Singlestat thresholds and colors.

### Desired behavior:

state_code field:

1 - running
2 - start pending
3 - continue pending
4 - pause pending
5 - pause
6 - stop pending
7 - stopped

This will allow thresholds of green = 1, yellow = 2 - 4, red = 5 - 7

### Use case: [Why is this important (helps with prioritizing requests)]

This will allow for nicer dashboard based on service status.

**Comment by danielnelson** [comment]
We will need to evaluate this in the context of #4532 and #4823, since I would like these to play well together for common items.  The ordering makes sense but I'm not sure it warrants a new field, and could be problematic if, for example, one wanted stop pending to be yellow or some other ordering.  This makes me think we should possibly provide state as a string tag/field and make sure it is possible to use the enum processor to generate custom codes, something which doesn't seem to be possible today.

It looks like Chronograf/InfluxDBv2 thresholds can handle this case, but it might also be worth opening a feature request with Grafana for more control since from what I can tell it seems to have a max of 3 cases.

**Comment by powersj** [comment]
Hi,

Going through old bugs currently to see if further action is required.

While it might be nice to have some sort of order, as Daniel points out the ordering could entirely be different from one use case to another. Our suggestion, for now, would be to use a processor to either modify these values or add another field/tag that you can use based on the reported value.

Given the above, I am going to close this as something we won't be doing.
