### ISSUE TITLE
Telegraf agent - Windows 201x Hyper-V cluster

### ISSUE THREAD

**Issue by nacabuta** [influxdata/telegraf#5559]
Hello

Was wondering if there exist any documentation on how to monitor a Window Server 201x Hyper-V cluster.
It is the cluster part that is of interest. Monitoring CSV (Cluster shared volumes), clustered VMs, networks etc.
Monitoring a standalone Hyper-V server works fine.

**Comment by danielnelson** [comment]
Not that I am aware of, how are you going about monitoring the standalone server?

**Comment by nacabuta** [comment]
Well thats the standard Telegraf agent (windows) feeding the InfluxDB data db running on a Linux server presentented in Chronograf.

**Comment by danielnelson** [comment]
Are you already using the Hyper-V performance counters?

**Comment by nacabuta** [comment]
Yes in a lab I have it up and running on a standalone Hyper-V server with a couple of Hyper-V performance counters and it is working fine. Now I want to test in a clustered environment with 2-3-4 nodes. Installing the agent locally will obviously not be a good idea in case of failure. Monitoring the clustered resources from the cluster I should think would be the way to go. Virtual Machines, Cluster Shared Volumes/Storage Spaces Direct etc.

> |-- Node1 - Telegraf Agent
|-- Node2 - Telegraf Agent
|-- Node3 - Telegraf Agent
|
|---Clustered resources - Telegraf Agent

**Comment by danielnelson** [comment]
Unfortunately, I don't have a Hyper-V cluster so it is hard to advise.  In general though there are a few patterns I see for monitoring clustered services:
1. Telegraf is on each node and monitors only the local resources.  When put together with the rest of the cluster you have a full view of all metrics.
2. Telegraf is on each node and collects metrics for the entire clusters resources from the local service.  Reported data is duplicated 2-3-4-n times across the cluster but is treated only as a local view.  The data can coexist in InfluxDB due to the host tag but you can really only view one hosts view at a time.
3. Telegraf is outside the cluster on a single node, it collects metrics for the entire cluster.  This pattern doesn't provide high availability.
