### ISSUE TITLE
InfluxDB V2 Output add bucket name into error message

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#5600]
### Relevant telegraf.conf:

```
# Configuration for sending metrics to InfluxDB 2.0
[[outputs.influxdb_v2]]
  ## The URLs of the InfluxDB cluster nodes.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  urls = ["http://127.0.0.1:9999"]

  ## Token for authentication.
  token = "$INFLUX_TOKEN"

  ## Organization is the name of the organization you wish to write to.
  organization = "influxdata"

  ## Bucket to the name fo the bucketwrite into; must exist.
  bucket = "telegraf"
```

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. start writing data to influxdb_v2 with a particular bucket name
2. change the name of the bucket in influxdb_v2
3. notice the error in the telegraf doesn't contain a reference to the bucket name

### Expected behavior:
the error message should include the bucket name

### Actual behavior:
`2019-03-16T20:48:40Z E! [outputs.influxdb] when writing to [https://url]: 404 Not Found: not found: bucket not found`

**Comment by glinton** [comment]
I wonder if it would make more sense for influx to return that information? `bucket 'notabucket' not found`?

**Comment by danielnelson** [comment]
The error returned by InfluxDB does not give us enough information to react to this particular error.  I know it says `bucket not found` but this is an opaque string that we don't want to have special handling on since it isn't specified in the API documentation.

We could consider if we want this error to be one of the InfluxDB error code's but I don't think we want to get in the business of printing all configuration values when an error occurs.  You can check your config file of course to find the bucket name, but sometimes it is difficult to tell which plugin to look at.  Printing the base URL is our standard compromise currently for #1815.

**Comment by russorat** [comment]
let's wait until https://github.com/influxdata/influxdb/issues/12713 is addressed

**Comment by kelwang** [comment]
https://github.com/influxdata/influxdb/issues/12713 is merged

**Comment by danielnelson** [comment]
@russorat Can you retest and post the log message?
