### ISSUE TITLE
Ability to specify the keys for timestamp for logfmt parser plugin

### ISSUE THREAD

**Issue by sslupsky** [influxdata/telegraf#5605]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Ability to specify the keys for timestamp for logfmt parser plugin.

### Current behavior:
The current logfmt parser does not allow you to specify which key/value pair is the timestamp.  All data parsed using the logfmt processor is timestamped by telegraf when it is processed instead of using the actual timestamps from the log.  

### Desired behavior:
It is preferred that the key/value pair that represents the timestamp can be specified in the configuration of the processor.

### Use case: [Why is this important (helps with prioritizing requests)]
This feature was part of the original specification requested by @russorat in issue #4427

This feature appears to have been overlooked when the plugin was released.  The use case is all logs that are timestamped that use logfmt.

**Comment by sslupsky** [comment]
Also, the ability to specify the type (bool, int, float, string) of the value for a key/value pair would be useful as well.

**Comment by St3f1n** [comment]
One can keep this issue closed. The solution could be using both **processors.timestamp** combined with **processors.converter** plugins to finally change an "arbitrary" timestamp field to the real timestamp in the line protocol.

**telegraf config example for a timestamp field in ISO 8601:**

Allows converting timestamp fields to other formats. It exists since 1.31 on.
```
[[processors.timestamp]]
  field = "ts"
  source_timestamp_format = "2006-01-02T15:04:05.999Z"
  destination_timestamp_format = "unix_ms"
```

Allows changing timestamp fields to actual timestamp. But it does not work with 1.25 as not yet implemented. It exists since 1.26 on. The fields needs to be in unix time.
```
[[processors.converter]]
  [processors.converter.fields]
    timestamp = ["ts"]
    timestamp_format = "unix_ms"
```

**logfmt file:**
ts=2025-07-17T07:52:32.015Z message="A"
ts=2025-07-17T07:53:09.078Z message="B"
ts=2025-07-17T08:06:37.527Z message="C"

**Old output (not using the log entries timestamps):**
Measurment ts="2025-07-17T07:52:32.015Z",message="A" 1753811165210106500
Measurment ts="2025-07-17T07:53:09.078Z",message="B" 1753811165210106500
Measurment ts="2025-07-17T08:06:37.527Z",message="C" 1753811165210106500

**New output (using the log entries timestamps):**
Measurment message="A" 1752738752015000000
Measurment  message="B" 1752738789078000000
Measurment  message="C" 1752739597527000000
