### ISSUE TITLE
Add pivot processor to "rotate" metrics

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#5629]
## Feature Request

Often data is received or, in some cases, created by Telegraf in a form where all points are on a single "value" field with the name of the field stored in a tag.  It would be nice to be able to pivot the metric into a format that would work more nicely with InfluxQL, Kapacitor, and uses the same organization style as the rest of Telegraf.

### Proposal:

```toml
[[processors.pivot]]
  key_tag = "name"
  value_field = "value"
```

Outstanding Questions:
- Processor or Aggregator?
- Is pivot the right word?
- Do we need reverse pivot?
- Move measurement into field name?

### Current behavior:

Cannot pivot data.

### Desired behavior:

```
- foo,name=bar value=42
+ foo bar=42
```

### Use case:

Would be helpful for prometheus and statsd metrics, among others.

**Comment by samhld** [comment]
This could be a fantastic improvement to the on-boarding process of those who are using Prometheus, StatsD, Graphite, and any other data format that implements a long string descriptor of a "value" or "gauge" or "counter" metric.

In my experience, our users that have metrics in this format experience much slower write performance.  How much this processor would help that, I'm not sure....but a more tangible benefit would be data exploration in a tool like Chronograf.

This change in data shape would reduce the total number of tags making `SHOW` commands much more effective/usable as more information would be contained in the field set rather than the tag set.  I've seen many users have issues with simply resolving `SHOW TAG KEYS` / `SHOW TAG VALUES WITH KEY` queries...and because of this, tools like Chronograf's data explorer/query builder can't populate data.

The below screenshot is an example of the desired end goal, as opposed to their being only one field called "value", etc., and having to toggle between multiple tags to discover the metric you want to query:
![Screen Shot 2019-03-25 at 4 14 54 PM](https://user-images.githubusercontent.com/4852912/54963440-13bcc280-4f26-11e9-89b8-3a0cd64e05ba.png)
