### ISSUE TITLE
plugins/inputs/win_services: use "DisplayName" as well as "name" for service selection

### ISSUE THREAD

**Issue by AlmightyOatmeal** [influxdata/telegraf#5675]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

plugins/inputs/win_services: use "DisplayName" as well as "name" for service selection.

Example service data entry on Windows Server 2018R2:
```
Name                : LanmanServer
RequiredServices    : {SamSS, Srv2}
CanPauseAndContinue : False
CanShutdown         : False
CanStop             : True
DisplayName         : Server
DependentServices   : {Browser}
MachineName         : .
ServiceName         : LanmanServer
ServicesDependedOn  : {SamSS, Srv2}
ServiceHandle       : 
Status              : Running
ServiceType         : Win32ShareProcess
StartType           : Automatic
Site                : 
Container           : 
```

### Current behavior:

Service selection is based on service name only.

### Desired behavior:

Service selection to try a service by name then try by DisplayName.

OR

Add an additional configuration parameter.

### Use case: [Why is this important (helps with prioritizing requests)]

This would add value at a minimal amount of cost -- adding try by name then try by displayname is trivial and wouldn't require a lot of dev time. Although it would be advantageous to do some kind of string checking and make sure unicode characters aren't in play which would look legitimate but cause a problem when selecting a service.

This would make it that much easier for a whole group of users and administrators alike to make such a solution that much more approachable. We all know that the knowledgeable of users can be quite diverse and adding flexibility to address all levels of experience (or interns) would only be beneficial in the end.

I'm not that familiar with Go otherwise I would give it a... go!... :)

**Comment by danielnelson** [comment]
It's a good idea but it doesn't seem possible to get a service by display name in the Windows API winsvc.h.

- https://docs.microsoft.com/en-us/windows/desktop/api/winsvc/nf-winsvc-enumservicesstatusexa
- https://docs.microsoft.com/en-us/windows/desktop/api/winsvc/nf-winsvc-openservicew

If we could find a way to lookup by display name where it would reduce the underlying API calls then we would add an option, but since the best we could do here is filter the services once they have all been retrieved, we generally instead recommend using [metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering) options.  

In this case you could add:
```
[[inputs.win_services]]
  [inputs.win_services.tagpass]
    display_name = ["Remote Desktop Services"]
