### ISSUE TITLE
Temperature input plugin stops working when WiFi is turned off

### ISSUE THREAD

**Issue by marcv81** [influxdata/telegraf#5692]
### Relevant telegraf.conf:

[[inputs.temp]]

### System info:

- Telegraf 1.10.1-1 installed from .deb package / Ubuntu 16.04 + Kernel 5.0
- Intel Wireless LAN hardware, iwlwifi module

### Steps to reproduce:

1. Enable WiFi, connect to a network
2. Enable the `inputs.temp` plugin
3. Observe that the plugin is working correctly: various `temp` metrics should exist, including one called `temp,sensor=iwlwifi_input`
4. Disconnect from the network, turn off WiFi

### Expected behavior:

No new metrics should be produced for `temp,sensor=iwlwifi_input`. New metrics should still be produced for everything else in `temp`.

### Actual behavior:

**No** new metric is produced for anything in `temp`.

### Additional info:

    Apr 08 14:36:50 telegraf[6305]: 2019-04-08T06:36:50Z E! [inputs.temp]: Error in plugin: error getting temperatures info: read /sys/class/hwmon/hwmon4/temp1_input: no data available

**Comment by glinton** [comment]
We could add to [the check here](https://github.com/influxdata/telegraf/blob/release-1.10/plugins/inputs/temp/temp.go#L28) to return only if `len(temps) == 0`, but you could still potentially see partial or missing data. This is due to the [upstream gopsutil library returning on file read errors](https://github.com/shirou/gopsutil/blob/master/host/host_linux.go#L663-L669).

This seems like an upstream issue, as implementing the `len` workaround would create a new issue for incomplete data.

**Comment by danielnelson** [comment]
@glinton Could you create a new issue on the gopsutil project and link to it here.  I agree the upstream code should probably skip errors.

**Comment by marcv81** [comment]
Related PR: https://github.com/influxdata/telegraf/pull/5941.
