### ISSUE TITLE
Plugins should emit metric unit as a tag

### ISSUE THREAD

**Issue by zstyblik** [influxdata/telegraf#574]
You collect all these cool metrics about everything and nothing, but what unit is this metric in? Is it MB or B or potatoes? Do you remember? Do you know?

Now, that we have support for tags aka meta-data, it'd be cool if tag `unit` was emitted as well to better describe the metric.

**Comment by mark-rushakoff** [comment]
I wonder if units are something that are a better fit as a first-class InfluxDB feature. (I did a cursory search through InfluxDB issues and didn't see anything – perhaps you'd like to open an issue @zstyblik ?) It's something we've internally talked about once or twice in Chronograf development as well.

I'm not sure that tags are a proper fit for this problem. For example, the system plugin's disk stats record fields for total/used/free bytes in the same measurement as total/free/used inodes, so a single tag is insufficient to distinguish which unit belongs to which field.

Perhaps an interim workaround is to name the fields to include the unit – e.g. `total_bytes` instead of just `total`.

**Comment by sparrc** [comment]
As Mark said, there isn't a solution for this that telegraf can solve, because tags cannot be applied per-field.

**Comment by zstyblik** [comment]
@mark-rushakoff, @sparrc I see that as a rather short-sighted (design) decision. My $0.02USD.

> Perhaps an interim workaround is to name the fields to include the unit – e.g. total_bytes instead of just total.

Yes, but let me counter with ``back to the Graphite land''.

**Comment by sparrc** [comment]
@zstyblik That requires renaming every single field that telegraf emits, which requires users to re-tool all their queries. Please remember that you're not the only user we need to satisfy ;-)

**Comment by zstyblik** [comment]
@sparrc what do you mean by renaming? Do you mean `total_bytes`? I'm sorry, but that was irony, if you didn't get it. It's a no way for us and it should be a no way for anybody else. Don't you feel it's going backwards, thus the remark of Graphite?

**Comment by mark-rushakoff** [comment]
@zstyblik It sounds like you have some strong opinions about how this should work. Please either open an issue on the influxdb repo regarding first-class unit support, or create a new thread on the mailing list to invite a larger discussion on how to solve the problem you're facing.

**Comment by zstyblik** [comment]
@mark-rushakoff we've just had discussion with opinions about this and that. And I'm sorry, but I'm not knowledgeable enough to see how this is InfluxDB's problem.

**Comment by sparrc** [comment]
Mark has suggested that InfluxDB have built-in support for tracking the `unit` of each field. This would be a better solution because using tags requires separating measurements by unit, which sometimes isn't ideal.

There are many plugins which combine fields in a single measurement that have different units, and all of these would need to be reworked to support unit tags (this would also be a breaking change for all users)

@zstyblik I would suggest softening your tone in general, being rude and sarcastic usually doesn't endear yourself to open-source maintainers :-1:

**Comment by zstyblik** [comment]
> Mark has suggested that InfluxDB have built-in support for tracking the unit of each field.

@sparrc What @mark-rushakoff has suggested is to open ticket with influxdb and a work-around. Work-around which I didn't agree with. You've added to that:

> That requires renaming every single field that telegraf emits, which requires users to re-tool all their queries.

... which stated the obvious.
I don't see any (obvious) suggestion there is internal support of `units` in InfluxDB that you're referencing to.

> I would suggest softening your tone in general, being rude and sarcastic usually doesn't endear yourself to open-source maintainers

@sparrc please, can you show where I was sarcastic or rude? btw  what you're suggesting goes both ways.

> It sounds like you have some strong opinions about how this should work.

@mark-rushakoff Yes, but I also understand the limitation of design decisions that have been made. What gave me hope was some other Telegraf's GH issue or whatever.

> Please either open an issue on the influxdb repo regarding first-class unit support, or create a new thread on the mailing list to invite a larger discussion on how to solve the problem you're facing.

No thank you. If it wasn't obvious from my previous comment, I really don't feel like I want to discuss this issue further after all the comments and propositions here.

Have a nice day, gentlemen.

**Comment by beckettsean** [comment]
@zstyblik 

>> please, can you show where I was sarcastic or rude?

Be careful what you wish for:

> Is it MB or B or potatoes? Do you remember? Do you know?
> Do you mean total_bytes? I'm sorry, but that was irony, if you didn't get it.

Not sarcastic but pretty flippant:

> Yes, but let me counter with ``back to the Graphite land''.

So I would agree that your tone has not been constructive, and I thank @mark-rushakoff and @sparrc for keeping it cool through your continued attempts to get a rise out of them.

> And I'm sorry, but I'm not knowledgeable enough to see how this is InfluxDB's problem.

@mark-rushakoff and @sparrc are knowledgeable enough to say that this is best fixed by an alteration to InfluxDB, not to Telegraf. You may continue to disagree, but we will not continue to debate unless there's new information or significantly improved tone.

**Comment by zstyblik** [comment]
@beckettsean thank you for twisting and taking things out of context. This kind of puts nice end to it all.

> are knowledgeable enough to say that this is best fixed by an alteration to InfluxDB, not to Telegraf.

Then I'd expect such knowledgeable people to open such issue since they have knowledge to write up exactly what's necessary to move things in right direction and at the right place. Obviously, I don't.

> You may continue to disagree

I'm glad this is allowed. I got the feeling that such thing, different opinion, isn't welcome and actually is forbidden.

> but we will not continue to debate unless there's new information or significantly improved tone.

I've never said this debate should continue. I was fine with the resolution. Yet it seems to me this is the fact you, for whatever reason, are unwilling to accept.

**Comment by sparrc** [comment]
https://en.wikipedia.org/wiki/Wikipedia:You_can%27t_squeeze_blood_from_a_turnip
