### ISSUE TITLE
Remove exponential/scientific notation from metric value

### ISSUE THREAD

**Issue by danielarkins** [influxdata/telegraf#5747]
using telegraf for windows metrics collection, some values return exponential notation:

System_Driver_Resident_Bytes{_category="host",objectname="win_mem",objectname="Memory"} 2.1917696e+07 (this is the value)

I would like to remove the e+07 from the value as my destination does not support exponential. Is there a way to do this for all metric values?

**Comment by danielnelson** [comment]
So you want it in decimal notation: `21917696.0`?  There isn't a way currently, but maybe it would display in this format if we had a processor that could round values to fewer decimal points.  Similar to this pull request https://github.com/influxdata/telegraf/pull/3738.

That said, with the library we use to output prometheus format, I think we have very little control over this in the end.  Even with high levels of rounding it may display as `2.1e+07`.  I'm curious, what program are you using to read prometheus output that can't handle scientific notation?

**Comment by danielarkins** [comment]
in reality, I don't want any decimal. when I look at an example through perfmon, I see a count such as 731,131,904 that telegraf returns as 7.31131904e+08. I'm unsure as to why it does this, why does it not just return the value as is?

**Comment by danielarkins** [comment]
alternately I am trying to figure out how to simply drop the metrics I know will produce an exponential value until I figure this out. its seems fielddrop or tagdrop should work but unable to get this to work, I want to do "*" for counters to collect in windows but then drop them by counter name if I know they produce exponential values.

**Comment by danielnelson** [comment]
It looks like the prometheus library uses this function to convert the values: https://github.com/prometheus/common/blob/master/expfmt/text_create.go#L436

Strictly speaking we are using an older version of their library that just uses `%v` formatting, but it should produce a similar result.

There has been some talk about adding a theshhold processor that could remove values larger than a number, it might be able to help.  https://github.com/influxdata/telegraf/pull/4592

Ultimately though this is a question for the https://github.com/prometheus/common project, you could ask there but I wouldn't expect them to want to make changes to the formatting.  Any program that can parse prometheus output should be able to handle this, maybe it makes more sense to update the program that is scraping the prometheus data to handle prometheus data more fully.

I'm going to close this issue, we won't be able to change the behavior since we want to use the upstream prometheus formatter.
