### ISSUE TITLE
Support binding to a specific local address for `http_response`

### ISSUE THREAD

**Issue by zoonage** [influxdata/telegraf#5856]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add a bind interface/IP address to the `http_response` plugin to force the request to egress via a specific interface

```
[[inputs.http_response]]
  address = "http://google.com"
  bind = "eth0"
```

### Current behavior:
The request uses the default `net.Dialer` which selects an interface for the request.

### Desired behavior:
To be able to specify an interface or IP address as the address to bind the `http.Client` to.

### Use case: 
For hosts that have VPN tunnels for a specific interface's traffic it is useful to check that you can send a request via this interface

**Comment by danielnelson** [comment]
Sounds good, I think we should name the option `interface` since bind is something the server usually does.  It seems like this is implemented with the `LocalAddr` field on the dialer?  I guess we would use the first address assigned to the interface?

Is this something you could put together a pull request for?

**Comment by zoonage** [comment]
@danielnelson I'm unsure due to work commitments, but I'll give it a go
