### ISSUE TITLE
environment variables for Azure Monitor does not work 

### ISSUE THREAD

**Issue by gutzeit1106** [influxdata/telegraf#5890]
The following environment variables does not work. 
https://github.com/influxdata/telegraf/tree/master/plugins/outputs/azure_monitor

Client Credentials: Azure AD Application ID and Secret.
Set the following environment variables:
**AZURE_TENANT_ID: Specifies the Tenant to which to authenticate.
AZURE_CLIENT_ID: Specifies the app client ID to use.
AZURE_CLIENT_SECRET: Specifies the app secret to use.**

syslog outputs auth error.
May 22 07:37:50 ub18sea telegraf[3870]: 2019-05-22T07:37:50Z E! Error writing to output [azure_monitor]: unable to fetch authentication credentials: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://southeastasia.monitoring.azure.com/subscriptions/xxxxx/resourceGroups/TelegrafTest/providers/Microsoft.Compute/virtualMachines/ub18sea/metrics: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}

On the other hand, Managed Service Identity (MSI) is working correctly. 

 I found the following commit for go-autorest. Now these environment variables are supportable?  
https://github.com/Azure/go-autorest/commit/f4369d4c79bf40df5e86def1e0f54c7ef261a51c#diff-8328c637821ec7d676a3d287e6ffed85

**Comment by danielnelson** [comment]
I don't have a setup to test this authentication method easily, but I don't see a reason to suspect the environment variable are not working.  The commit just looks like it gives better control over the authentication.

Here is a full set of the environment variables that can be set, perhaps our documentation is lacking and another one needs set (`AZURE_AD_RESOURCE` maybe?):
```
tenantID:            os.Getenv("AZURE_TENANT_ID"),
clientID:            os.Getenv("AZURE_CLIENT_ID"),
clientSecret:        os.Getenv("AZURE_CLIENT_SECRET"),
certificatePath:     os.Getenv("AZURE_CERTIFICATE_PATH"),
certificatePassword: os.Getenv("AZURE_CERTIFICATE_PASSWORD"),
username:            os.Getenv("AZURE_USERNAME"),
password:            os.Getenv("AZURE_PASSWORD"),
envName:             os.Getenv("AZURE_ENVIRONMENT"),
resource:            os.Getenv("AZURE_AD_RESOURCE"),
```

If you still can't get it to work, can you try one of these builds which include the latest go-autorest version, then we'll know if it has been fixed in a newer release:

- [telegraf-1.11.0~ac2ff0d5-0.x86_64.rpm](https://33416-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf-1.11.0~ac2ff0d5-0.x86_64.rpm)
- [telegraf_1.11.0~ac2ff0d5-0_amd64.deb](https://33416-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.11.0~ac2ff0d5-0_amd64.deb)
- [telegraf-1.11.0~ac2ff0d5_windows_amd64.zip](https://33416-33258973-gh.circle-artifacts.com/0/build/windows/amd64/telegraf-1.11.0~ac2ff0d5_windows_amd64.zip)
