### ISSUE TITLE
Statsd delete_counters not working with sum over time

### ISSUE THREAD

**Issue by tccod** [influxdata/telegraf#5892]
### Relevant telegraf.conf:
```
[agent]
  interval = "15s"
  round_interval = true
  metric_buffer_limit = 10000
  metric_batch_size = [1000]
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = true
  quiet = false

[[inputs.statsd]]
  protocol = "udp"
  max_tcp_connections = 250
  tcp_keep_alive = false
  service_address = ":8130"
  delete_gauges = true
  delete_counters = true
  delete_sets = true
  delete_timings = true
  percentiles = [95,99]
  metric_separator = "_"
  parse_data_dog_tags = true
  allowed_pending_messages = 10000
  percentile_limit = 1000

[[outputs.prometheus_client]]
  listen = ":9273"
```

### System info:
Telegraf 1.10.3
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
Prometheus Version: 2.8.0

### Steps to reproduce:

1. Send metrics from CLI  5 times``` echo "abc.count:1|c" | nc -u -w0 127.0.0.1 8130```

### Expected behavior:

Over the time sum should be equal to 5.

### Actual behavior:

Over grafana, the total is 20.

![Screenshot 2019-05-22 at 3 43 55 PM](https://user-images.githubusercontent.com/42868615/58167001-a8366d80-7ca8-11e9-9dc5-985786afbd66.png)

### Additional info:

Prometeheus scrape_interval: 15s
Prometheus query: ``` sum(abc_count) ```

**Comment by danielnelson** [comment]
I think this is a prometheus query issue, I'm no expert but I think you need to use the rate function before sum.

From the Telegraf side I expect the metric to be set to 5 and not change unless another point is received.  After the the expiration interval (default is 60s) is reached with no update then the value is removed.  This appears to match your screenshot.

**Comment by tccod** [comment]
Thanks, @danielnelson  for clarification.

Though from the [documentation](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd), the statsd metric should be cleared it's cache of previous value after each interval but here I'm receiveing this until expiration interval.

```
  ## Reset gauges every interval (default=true)
  delete_gauges = true
  ## Reset counters every interval (default=true)
  delete_counters = true
```
So is there any setting that I'm missing?

Another thing, can we change expiration interval so it doesn't send duplicate value?

**Comment by danielnelson** [comment]
It is cleared from the statsd cache, for example if you were to enable the `file` output it would only be written once.  Without `delete_counters` it would be emitted again each interval.  However, all items written to the prometheus output are not cleared until they receive a new value or expire.

> Another thing, can we change expiration interval so it doesn't send duplicate value?

No, its not possible to send the data on only one http response and then delete.  Theoretically this could be possible but I think it would be rather unexpected behavior.

The data you have collected is good, but since this value is a `TYPE counter`, I believe the proper way to query this data is like:
```
sum(rate(abc_count[10s]))
```

You will run into many non-resetting counters like this working with Prometheus/Telegraf/InfluxDB and other monitoring software, in fact I prefer these style counters over resetting counters as they behave very nicely if you have downtime for any reason, and are very flexible with changes in interval and aggregation windows.  You won't want to try to avoid them, instead its just a matter of learning to work with them.
