### ISSUE TITLE
influx telegraf connectivity issue

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#5910]
Telegraf agents are unable to connect with InfluxDB. we are getting below error in Influx log and telegraf log

1. Influx log :- [httpd] 10.14.153.252 - - [25/May/2019:14:06:31 +0530] "POST /write?db=telegraf HTTP/1.1" 500 20 "-" "Telegraf/1.9.0" 327d6a3e-7ec8-11e9-a5d9-00155dc8485c 15448669
ts=2019-05-25T08:36:47.163773Z lvl=error msg="[500] - \"timeout\"" log_id=0FcWM9lG000 service=httpd

2. Telegraf log :-  2019-05-25T08:37:25Z E! [outputs.influxdb] when writing to [http://10.14.153.4:8086]: Post http://10.14.153.4:8086/write?db=telegraf: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

3. Also We are not able to see few day back data in inlfux.

version :- InfluxDB v1.7.1 
OS :- Red Hat Enterprise Linux Server release 6.6
CPU Core 4
Memory : 32 GB

Also Port connectivity is working from all end servers and space are also available on influx server. Please let me know if any other details required

**Comment by danielnelson** [comment]
I believe this is an InfluxDB issue, does restarting InfluxDB help?  I know there was a bug in InfluxDB 1.7.5 that is similar but I did not think 1.7.1 was affected.  Here are some potentially related issues:

https://github.com/influxdata/influxdb/issues/8036
https://github.com/influxdata/influxdb/issues/8533

I'm going to close this issue since I don't think it is a Telegraf issue, but I suggest updating to the latest version 1.7.6 and if the error occurs again to open an issue on the InfluxDB repo.
