### ISSUE TITLE
Make the TLS listening version configurable.

### ISSUE THREAD

**Issue by jackdown** [influxdata/telegraf#5914]
## Feature Request

Configure the TLS listening at the moment its not possible to listing only on TLS 1.2 or TLS 1.3.
Also it would be great to configure the cipher suites.

### Proposal:

Make the TLS listening version configurable.

### Current behavior:

Not possible to disable unwanted TLS versions.

### Desired behavior:

Default as current, but possible to enable only wanted TLS versions.

### Use case: 

Realy needed for security concerns, we want to disable old and maybe broken TLS versions.

**Comment by danielnelson** [comment]
This would be nice, we could add optional setting `tls_versions = []` and `tls_cipher_suites = []` to the [tls.ClientConfig][clientconfig].  I think since they are more advanced features we wouldn't document them in the `telegraf.conf`.

[clientconfig]: https://github.com/influxdata/telegraf/blob/master/internal/tls/config.go#L11
