### ISSUE TITLE
Telegraf window blank after [Agent] Config.

### ISSUE THREAD

**Issue by Varjotiger** [influxdata/telegraf#5924]
Hi all,

I am brand new to Tick Stack and have been setting it up for my work environment as a proof of concept.  I have the vsphere input plugin for Telegraf.conf and am retrieving metrics from the VM environment but the metrics are only showing up extremely slowly and the Telegraf window does not contain any information after the [Agent] config: line as per the picture below.  I have searched for quite a while to see if anyone else has experienced this issue but unfortunately have not found anything on it (or my search query is incorrect).  I believe that this issue is due to either Server performance or my parameters in the config file.

![Telegraf stuck](https://user-images.githubusercontent.com/51191434/58621995-8ea5af00-82c2-11e9-88a0-65d768db7427.png)

Unfortunately my current VM environment is still 5.5 and am running the TickStack from Windows Server 2012 (i know, this environment is ancient).  The VM environment has 16 hosts, 300 VM's and around 50 Datastores (poor I know).

.conf main settings:
interval = "10s" (This has now been changed to 20s)
Gathering all metrics e.g. vm_metric_include = []
max_query_objects = 256 (edited vSphere config to allow 256)
collect_concurrency = 5 (This has now been changed to 4)
discover_concurrency = 5 (This has now been changed to 4)
object_discovery_interval = "300s"
timeout = "1800s" (This has now been changed to 30s)

Thanks for your help.

Varjo

p.s. please ignore the win perf counters on the loaded inputs, I had added it as a test and will be creating a separate .conf file for win perf as soon as I figure out whether I need to have a second database instance and how to configure Telegraf to use two .conf's.

Update:
Debug = True now shows all the Telegraf activity so that one is cleared up.  Does anybody know if the screenshot above shows Telegraf working as it should do?

**Comment by glinton** [comment]
This seems like a great question for [our community page](https://community.influxdata.com/)

From the above screenshot, it seems telegraf is functioning properly. It looks like it is outputting data to a running influxdb server, which is why you are not getting more output. Turning on `debug` will just show that telegraf is writing (you could also view incoming data in the influxdb instance it's writing to.

Using a [`config directory`](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#configuration-loading) is how you'd use multiple config files.

The [`interval`](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent) you are configuring is how frequently telegraf runs each plugin, the `flush_interval` is how often that data gets sent to the configured outputs. Both can contribute to telegraf seeming "slow", but as "slow" wasn't quantified, it's difficult to tell.

There may be some limits to collection frequency for the [vsphere plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/vsphere#vmware-vsphere-input-plugin) (iirc, there is an aws input that only allow requesting data every 60 seconds, making collection seem "slow").

If you have follow up questions, please ask on the [community forum](https://community.influxdata.com/) and link to this issue.
