### ISSUE TITLE
Add support for basic auth to elasticsearch plugins

### ISSUE THREAD

**Issue by florent26** [influxdata/telegraf#5967]
Hi,
Is it possible to add http auth params on the elasticsearch plugin ?
For example it doesn't work when Xpack Security is enable.

Thanks,

**Comment by florent26** [comment]
I have tried in /etc/telegraf/telegraf.d :
<code>
servers = ["http://elastic:XXXXXX@10.24.0.15:9200"]
</code>

But it doesn't work.

**Comment by florent26** [comment]
Sorry, finally it works with http://USERNAME:PASS@.....

**Comment by florent26** [comment]
Maybe you just can update the readme ?
Thanks

**Comment by danielnelson** [comment]
I think we should add support for HTTP Basic auth which uses the Authentication header instead of the userinfo section of the URL.  The reason being that the URL can be printed in a number of circumstances, and many don't want to log credentials.  I can add this if you could help test it out, are you working with the Elasticsearch input or output?

**Comment by xiaoyanghapi** [comment]
I also want to ask this qustion、
我也想问这个问题。
