### ISSUE TITLE
statsd input and field name

### ISSUE THREAD

**Issue by lassizci** [influxdata/telegraf#602]
I've been trying to template my metrics so that I could have multiple fields with my measurement. According to https://github.com/influxdata/influxdb/tree/master/services/graphite#templates (which is linked from statsd readme page).

it should be possible to make a template like:

```
templates = [
    "mybycket.* measurement.measurement.field"
]
```

so this:
```
echo "mybucket.appstats.foo_count_testing:1|c" | nc -C -w 1 -u localhost 8125
```

would turn in to:
```
> select * from mybucket_appstats;
name: mybucket_appstats
------------------------
time			host		metric_type	metricgroup	foo_count_testing
1453985830000000000	metricstest	counter		metrics		1
```

However, there's only field called "value" and no tag field. So at least with statsd this doesn't seem to work. I'd like to be able to send multiple fields to same measurement.

**Comment by tstm** [comment]
+1

**Comment by sparrc** [comment]
thanks for pointing this out :+1:, I have a PR up to fix this.

I'm not exactly sure how this would look for timings though, and I'm thinking of simply not supporting fields for timings. This is because (as of 0.10.2) timings will have their actual metrics that are sent in their own fields.

ie, my_timing_metric will be the measurement, with mean,stddev,90_percentile, etc. as fields
