### ISSUE TITLE
Add support for TLS1.2 for Cisco MDT Plugins

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/telegraf#6045]
## Feature Request
TLS 1.2 support for Cisco MDT

### Proposal:
Trying to advance all of the plug-ins such that they have options for secure communication for data collection.  Proposal is to add support for optional TLS 1.2 configuration.

### Current behavior:
Provide configuration option to provide support for TLS 1.2

### Desired behavior:
Allow collection of metrics using TLS 1.2

**Comment by danielnelson** [comment]
The gRPC transport already has support for TLS, it also ought to be quite easy to extent TLS to the tcp socket transport, but the [documentation][] I have seen seems to indicate that TLS is only supported for gRPC.

@sbyx Do you know if devices would support using TLS along with the TCP socket?

[documentation]: https://www.cisco.com/c/en/us/td/docs/iosxr/asr9000/telemetry/b-telemetry-cg-asr9000-61x/b-telemetry-cg-asr9000-61x_chapter_010.html

**Comment by sbyx** [comment]
Yeah the legacy plain TCP transport doesn't support TLS on the device side so it would be a fruitless effort. TLS for GRPC should be completely covered.

**Comment by littlespace** [comment]
@danielnelson @timhallinflux I am not sure if you can add recommendations to each plugins or not. For example for all gNMI plugins the TLS and read only user authentication  should be mandatory because gNMI also has the capability to do configuration change on the device so if the user/pass in the telegraf.conf is not a read only account it will be major security risk!

**Comment by danielnelson** [comment]
I can add a note to the configuration further clarifying that the TCP transport is not encrypted.  Luckily with MDT it listens like a server, and no secrets are sent to the device.
