### ISSUE TITLE
docker_log plugin crash

### ISSUE THREAD

**Issue by prashanthjbabu** [influxdata/telegraf#6146]
### Relevant telegraf.conf:

```toml
[[inputs.docker_log]]
```

### Steps to reproduce:

1. Enable docker_log plugin
2. Have docker containers which throw out logs

### Expected behavior:
No crash
### Actual behavior:
docker_log plugin crashes randomly . Trigger unknown!
```
panic: send on closed channel

goroutine 145 [running]:
github.com/influxdata/telegraf/agent.(*accumulator).addFields(0xc000592340, 0xe61afd, 0xa, 0xc0003d03c0, 0xc00044c270, 0x3, 0x0, 0x0, 0x0)
	/home/prash/go/src/github.com/influxdata/telegraf/agent/accumulator.go:103 +0x184
github.com/influxdata/telegraf/agent.(*accumulator).AddFields(0xc000592340, 0xe61afd, 0xa, 0xc00044c270, 0xc0003d03c0, 0x0, 0x0, 0x0)
	/home/prash/go/src/github.com/influxdata/telegraf/agent/accumulator.go:45 +0x83
github.com/influxdata/telegraf/plugins/inputs/docker_log.tailStream(0xfaadc0, 0xc000592340, 0xc00057ff80, 0xc0002920c0, 0x40, 0xf96480, 0xc00000e008, 0xe5da8e, 0x6, 0x0, ...)
	/home/prash/go/src/github.com/influxdata/telegraf/plugins/inputs/docker_log/docker_log.go:332 +0x4ed
github.com/influxdata/telegraf/plugins/inputs/docker_log.tailMultiplexed.func1(0xc00038e450, 0xfaadc0, 0xc000592340, 0xc00057ff80, 0xc0002920c0, 0x40, 0xc00000e008)
	/home/prash/go/src/github.com/influxdata/telegraf/plugins/inputs/docker_log/docker_log.go:360 +0xb8
created by github.com/influxdata/telegraf/plugins/inputs/docker_log.tailMultiplexed
	/home/prash/go/src/github.com/influxdata/telegraf/plugins/inputs/docker_log/docker_log.go:358 +0x306

```

**Comment by prashanthjbabu** [comment]
@danielnelson  Looks like tailStream() goroutine is trying to flush out data even after the telegraf accumulator channel is closed . Probably during a shutdown of telegraf?

**Comment by GeorgeMac** [comment]
Thanks @prashanthjbabu 

This is definitely a bug and it is to do with the fact that the docker log Gather() function currently doesn't guarantee it won't attempt to call AddFields after exit.
Note: https://github.com/influxdata/telegraf/blob/877c42362d9d3c8264add86a727af7b10f01c571/plugins/inputs/docker_log/docker_log.go#L222-L233

A global wait group is incremented which is to support calls to `plugin.Stop()`. However, no wait groups track that these docker log following routines have ended before Gather exits.

I also notice that this plugin uses the `follow: true` option which suggests to me that the expectation was to block and consume these logs in long running streaming fashion. However, my understand of Gather is that it should process a single batch and be called multiple times by telegraf. Correct me if I am wrong @danielnelson or @glinton ?

I assume this because as soon as the agent finishes calling Gather on all input plugins it closes the metrics chanel used by the accumulator.

We may want to reconsider `follow: true` here at the very least. I have implemented a fix locally to ensure the follow calls have exited before Gather can exit. Otherwise these gather routines will constantly run up against the plugin timeout (which defaults to 5 seconds).
Ommitting follow: true may require we also remember the last timestamp of messages between calls as to avoid collisions. Though from experience the timestamp feature with docker logs is still a little fuzzy.

**Comment by danielnelson** [comment]
A plugin is allowed to use the accumulator until the Stop function returns, after this function is called on all plugins the channel is closed.

**Comment by GeorgeMac** [comment]
@danielnelson that appears to be true only if the input plugin implements `telegraf.ServiceInput`:

https://github.com/influxdata/telegraf/blob/877c42362d9d3c8264add86a727af7b10f01c571/agent/agent.go#L711-L715

I appears that the docker login plugin doesn't implement Start(accumulator). Unless I am not finding that definition. It does have stop though.

**Comment by danielnelson** [comment]
That makes sense then, the Stop wouldn't even be called.  Let's add an empty Start function.
