### ISSUE TITLE
Add use_sudo option in x509_cert input

### ISSUE THREAD

**Issue by ichasco** [influxdata/telegraf#6178]
## Feature Request

I can't check the certificate, because:

E! [telegraf] Error running agent: cannot get SSL cert 'cert.crt': open cert.crt: permission denied

If I execute it with root user with --test it works

### Proposal:

Add sudo option to execute it. Like in iptables input

### Current behavior:

Fail when execute non permitted certificate

### Desired behavior:

Execute with sudo and work

### Use case: 

When Telegraf has not permissions to red a certificate

**Comment by glinton** [comment]
This behavior wouldn't work because the `x509` plugin doesn't shell out (call a system binary) like the `iptables` plugin does. In order for the `x509` plugin to read private files is for it to be given permissions to access that file, added to a group allowed to access that file, or to be run as the user who owns the file.

**Comment by danielnelson** [comment]
@ichasco On Linux you could use a Posix ACL to give the `telegraf` user read access to the Certificate:
```
sudo apt-get install acl # might need this
sudo setfacl -m u:telegraf:r /etc/nginx/cert.crt
```
