### ISSUE TITLE
Improvements in fails2ban plugin

### ISSUE THREAD

**Issue by jlsam** [influxdata/telegraf#6197]
### Relevant telegraf.conf:

```toml
# # Read metrics from fail2ban.
[[inputs.fail2ban]]
#   ## Use sudo to run fail2ban-client
    use_sudo = false
    interval = 550
```

### System info:
VPS running Ubuntu 18.04.2 LTS, Telegraf 1.11.3 (git: HEAD d6024fd2)

### Steps to reproduce:

1. Follow 'You will also need to update your sudoers file' section in 
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/fail2ban/README.md

2. Reboot VPS to be sure

### Expected behavior:
Telegraf would successfully collect fail2ban metrics
### Actual behavior:
$sudo journalctl -f -u telegraf.service
E! [inputs.fail2ban]: Error in plugin: failed to run command /usr/bin/fail2ban-client status: exit status 255 -

I can confirm from querying InfluxDB in console that other metrics collected with the same .conf are being recorded.
### Additional info:
A few suggestions too:
- add a default interval=550 or similar to the example code, so it's adjusted to the default bantime = 600. Otherwise people by default would be overpolling this input.

- recommend placing the sudoers edits in a separate file under /etc/sudoers.d/. See for example https://askubuntu.com/questions/930768/adding-local-content-in-etc-sudoers-d-instead-of-directly-modifying-sodoers-fi for a discussion

- clarify in telegraf/plugins/inputs/fail2ban/README.md that we are actually adding 3 lines and not one (the comment '# Add the following line:'). The commands may be split in 3 lines but someone reading the instructions literally may think they're just line breaks or an error in the page formatting. Editing sudoers is a serious business and some people may not be familiar with its syntax. Pasting everything in one line would result in a visudo warning, but someone unware doing a direct edit could get into a really thorny trouble.

My sudoers file after the edit:
https://pastebin.com/5x2vKfqb

**Comment by danielnelson** [comment]
I updated the README with most your ideas, but didn't include the recommendation for altering the interval.  Even if fail2ban bans for 600s, I think it could be valuable to have the poll interval faster since not all bans would be applied on a rounded time period, and you might want to have a faster update.

364bf38b4ae9a86555dac22306c41c9d6320a9be

**Comment by jlsam** [comment]
Ok... but now I'm confused - the page now indicates the default config as `use_sudo = false` and two lines below it recommends `use_sudo = true`. So `use_sudo = false` is the correct setting when running telegraf as root, which is not recommended? I think the text as currently is, although correct lends itself to confusion when read quickly. If you don't recommend running as root, why display that config instead of the recommended one? That way people would copy/paste the code set to work with the recommended mode.

And to access fail2ban as the user telegraf, one must change the setting to `use_sudo = true` _and_ also add the 3 lines to sudoers? I thought the point of the sudoers edits were to allow the telegraf user access to a restricted set of fail2ban commands without having to raise the privilege level? Sorry, maybe I'm just not understanding correctly what the sudoers edits are supposed to do.

And on a side note, would you say interval=300 (half the ban period) would be a good compromise between capturing all events and not filling the database with too many unnecessary, repeated entries?

**Comment by danielnelson** [comment]
> So use_sudo = false is the correct setting when running telegraf as root, which is not recommended?

I didn't change the default, false here has always been the default, but I did move the sudoers config into the configuration section.  I think having this option default off is okay, because it indicates that you must take some action to enable sudo, perhaps a better comment would be helpful:

```
  ## Use sudo to run fail2ban-client, when enabling this option you should first 
  ## properly setup your sudoers file.
  use_sudo = false
```

I do expect sudo to be the most common way to configure the plugin on a Debian/Fedora system, but there are other methods that could be used other than the 2 listed.  I think the documentation tries to hint that it's up to the admin to figure this out, while nudging in the right direction if you aren't sure about a way to do it.

> And to access fail2ban as the user telegraf, one must change the setting to use_sudo = true and also add the 3 lines to sudoers? I thought the point of the sudoers edits were to allow the telegraf user access to a restricted set of fail2ban commands without having to raise the privilege level?

Yes, you need to do both most likely, the sudoers commands lets you use sudo to raise privilege and run a few specific commands without a password.  The 3rd line turns off logging in /var/log/auth.log, which would otherwise be a bit annoying since it would log a message every interval without it.

> would you say interval=300 (half the ban period) would be a good compromise 

I think 300s would be a reasonable, but it really comes down to how much latency you want between when a ban occurs and when it gets reported.

**Comment by jlsam** [comment]
Ok, I don't entirely agree with some of your points, but now I understand things a bit better. I just want to point out that most plugins are much better documented and don't need to mess with stuff as delicate as the sudoers file.

I take your point about the interval. I hadn't thought about low latency use cases, specially because the measurement is not that detailed. For a low latency wouldn't also be useful to report the banned IP?

**Comment by danielnelson** [comment]
> For a low latency wouldn't also be useful to report the banned IP?

This could be interesting, though it is also quite difficult to model lists of items in most time series databases.  The naive approach of using a tag would be high cardinality and I don't know of any TSDB that supports string sets.
