### ISSUE TITLE
how to parse special time type use grok

### ISSUE THREAD

**Issue by SloanChang** [influxdata/telegraf#6251]
### I have the following time data:
```toml
{"StartTime":"2019-08-14 15:30:45:532"}
```
I want to use grok parsing, but it doesn't support, how should I handle it?

**Comment by danielnelson** [comment]
@SloanChang It's not clear to me how you want this to be parsed, this is why it is so important to fill out the expected behavior section from the issue template.  If you are trying to parse the time string as the timestamp the only way to have it work is to exclude the section after the `:`.  It won't be possible to keep the sub second precision.

I haven't tested this but it ought to be something like this:
```
%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02 15:04:05"}:\d{3}
```

If you have follow up questions about how to create patterns please ask at the [InfluxData Community](https://community.influxdata.com) site.
