### ISSUE TITLE
cpu input: cpu_time_active includes iowait time

### ISSUE THREAD

**Issue by fillest** [influxdata/telegraf#6306]
### Relevant telegraf.conf:

```toml
[[inputs.cpu]]
  percpu = true
  report_active = true
```

### System info:

* Telegraf - master
* Linux

### Steps to reproduce:

1. `telegraf --input-filter cpu --test`

### Expected behavior:
Active time should not include iowait because iowait [is essentially idle](https://github.com/torvalds/linux/blob/9c7db5004280767566e91a33445bf93aa479ef02/kernel/sched/cputime.c#L218). From #2943 it seems it was intentionally made to match collectd, but why? It is wrong. At least it should be documented in cpu/README.md to avoid confusion.

### Actual behavior:
Active time includes iowait (t.Iowait not subtracted in activeCpuTime()).

### Additional info:
Also why activeCpuTime uses totalCpuTime and not just 100? Probably more rounding errors are introduced that way and individual kernel counters may introduce individual inaccuracies.

**Comment by danielnelson** [comment]
We can change this but given that active time is essentially made up, I want it to match other programs.  This avoids questions about why Telegraf does not match with X.  Could you take a survey of how top/htop/ps calculate cpu use?

> At least it should be documented in cpu/README.md to avoid confusion.

Agreed, no matter what we decide on active.

> Also why activeCpuTime uses totalCpuTime and not just 100? Probably more rounding errors are introduced that way and individual kernel counters may introduce individual inaccuracies.

The totalCpuTime is the number of jiffies, but it's not necessarily 100.

**Comment by phemmer** [comment]
Was just about to file a bug about this very issue and found one already exists :-)

I agree with @fillest's idea of making active time subtract iowait.  
Though I don't agree with the documentation update as acceptable. People aren't going to go crawling through the documentation looking for [little surprises](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) about each of the metrics they have available. There are likely hundreds or thousands of metrics in their environments. 

While I can somewhat understand the desire to be inline with other apps in the space, in this case I disagree.

The iowait number is usually pretty significant, and thus screws up the calculation significantly. People are likely trusting telegraf to give them accurate information, and if the numbers are telling them that their CPU is 100% used, they're likely going to respond to that and take inappropriate action.

I also don't understand the point of wanting to match other monitoring systems to this degree. People aren't going to be running 2 systems side by side and trying to find differences. I also don't think trying to make it easy for people to transition between them is a valid argument, as minutiae like this don't really make that any easier or harder. And at the end, just because some other app has a bug isn't a good reason to copy that bug.

Sorry, I'll stand down from my soap box now :-)

**Comment by phemmer** [comment]
Another thing I just noticed. The active time does not include guest times. 
Given how wrong this value is, maybe the best option is to deprecate it and create a "total" field instead. Then if people want active, they can just do `total - idle - iowait`.

**Comment by danielnelson** [comment]
Hey @phemmer, good to hear from you again.

I'm not particularly invested in the definition of "active", it's not a thing really and it seemed we should follow existing definitions at the time.  I agree we want to avoid surprises, and that's why I'm hoping to keep the plugin in line with existing tools.  If collectd is wrong we can do it different, but if everyone else agrees on what "active" is I don't think we should redefine.  It shouldn't take too long to document a few cases before switching the code, and it will help us remember why we differ vs collectd.

Documentation is just something we should do anyway, it's not a substitute for any fixing code but in theory you should be able to use Telegraf without constantly referencing the code.

We can add `time_total`, its a calculated field but I think it is helpful enough to be worth it.  It sounds like there is a bug in the total time calculation so we should fix that too.
