### ISSUE TITLE
Docker input plugin does not show the same container on many hosts well

### ISSUE THREAD

**Issue by morfien101** [influxdata/telegraf#6472]
## Feature Request

When starting the same container on many hosts, and collecting the metrics of said container via telegraf running on the docker host, user are not able to differentiate between the containers.
This is because the container_id is written to a field. Which makes it unselectable in the query to InfluxDB.
We do have the container name, but these can be the same if the user is setting them.

Telegraf also writes its own hostname as the `host` tag, so the best you can really do is know which telegraf instance wrote it.

Opening a feature request kicks off a discussion.

### Proposal:

Telegraf should write the common container hostname derived from the container_id (the first 12 chars of the id) as the `host` tag. This allows the measurements to be attributed directly to a single container easily.

### Current behavior:

We only have the name available which can be set to the same thing on many hosts.
We have engine_host which can also be set to the same thing in rare cases but is hard to use to identify containers individually.

### Desired behavior:

Use the host tag to directly link measurements to a container based on a common naming format.

### Use case: 

Situation: You have 3 docker instances, each with a local telegraf instance. The containers are deployed with a name and tag of "amazing_app" (--name amazing_app). Telegraf will pick up the measurements for cpu, mem, disk ect... and tag them with the same name making it impossible to figure out which container produced the metrics.

Telegraf will however set the `host` tag to be itself. Which means you can find the telegraf instance then link that to the container running on the same host and then finally know which container made the metrics. Which is really a pain in a failure situation.

**Comment by danielnelson** [comment]
To add a little history, the `container_id` was originally added as a field to prevent cardinality issues,  since the cardinality could add up very quickly especially on system with many short lived containers.   In a perfect world it always would have been a tag.  Since its addition, InfluxDB has gotten quite a bit better at handling cardinality, and so long as you have the right retention policy in place it should be okay to tag this.  I know there are quite a few who are converting the `container_id` to a tag with the `converter` processor.

There is a second issue around how we use the `host` tag.  There are two concepts: where were the metrics collected and what/who does the metrics describe.  What we have decided on is that we should have two "standard" tags for these, named `host` and `source` respectively.  There is more background in #4413, but ideally with this scheme we would store this tag as `source`.

If one wanted to add this now, it would be possible, but you would need to use 3 processors to convert to tag, rename to `source`, and trim the length.

So, minor tweak to your PR, how about we add it as the `source` tag and since it will add some cardinality in a sensative plugin, we can default it off.  The option can be similar to the `pid_tag` option on the `procstat` plugin:
```
source_tag = true
```

Would it be possible for you to do the same on the `docker_log` input?

**Comment by morfien101** [comment]
I am happy to make these changes and I like the standard tag name for source.

I will also make the same option available in the `docker_log` plugin and add it to this PR.

**Comment by danielnelson** [comment]
I merged your changes in, thank you!
