### ISSUE TITLE
Time interval in influxdb not matching with the interval set in telegraf config

### ISSUE THREAD

**Issue by aftabquraishi** [influxdata/telegraf#6480]
In the telegraf agent I have set the interval as 5s. But in influxdb sometimes I am seeing long intervals between timestamps, for example 40s to 50s. Because of this, the graph in grafana showing blank spots which is giving a wrong impression to user.

Below are the timestamps. Please notice the third row where the time difference is 49 seconds. So, between 11:52:08 AM and 11:52:57 AM grafana will plot a blank spot, that's the problem. But, I monitored CPU metrics using Performance Monitor, counters like "Privileged Time" and "User Time" do have data during that blank period.

Any idea, what am I doing wrong?

```
Wednesday, October 2, 2019 04:52:02 AM .... +2s
Wednesday, October 2, 2019 04:52:08 AM .... +6s
Wednesday, October 2, 2019 04:52:57 AM .... +49s
Wednesday, October 2, 2019 04:53:01 AM .... +4s
Wednesday, October 2, 2019 04:53:05 AM .... +4s
Wednesday, October 2, 2019 04:53:22 AM .... +17s
Wednesday, October 2, 2019 04:53:26 AM .... +4s
Wednesday, October 2, 2019 04:53:51 AM .... +25s
Wednesday, October 2, 2019 04:53:55 AM .... +4s
Wednesday, October 2, 2019 04:54:06 AM .... +11s
Wednesday, October 2, 2019 04:54:12 AM .... +6s
Wednesday, October 2, 2019 04:54:16 AM .... +4s
```
![Capture 1 - Grafana](https://user-images.githubusercontent.com/6789674/66182935-ae961680-e698-11e9-9b8a-f3667b3b40a2.PNG)

### Relevant telegraf.conf:
```
[global_tags]
  domain = "$USERDOMAIN"
  username = "$USERNAME"
  hostname = "$COMPUTERNAME"


[agent]
  interval = "5s"
  round_interval = true
  metric_buffer_limit = 2000
  flush_buffer_when_full = true
  collection_jitter = "3s"
  flush_interval = "10s"
  flush_jitter = "3s"
  precision = "s"
  debug = false
  quiet = true
  hostname = "$COMPUTERNAME"
  # logfile = "C:\\Program Files\\Monitor.log"

[[outputs.influxdb]]
  urls = ["http://primary.xxxxx.com:8686", "http://secondary.xxxxx.com:8686"]
  database = "xxxx"
  timeout = "5s"
  user_agent = "monitor"

[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = ["% Idle Time", "% Interrupt Time", "% Privileged Time", "% User Time", "% Processor Time", "% DPC Time",]
    Measurement = "win_cpu"
    IncludeTotal=true
  [[inputs.win_perf_counters.object]]
    ObjectName = "LogicalDisk"
    Instances = ["*"]
    Counters = [ "% Idle Time", "% Disk Time", "% Disk Read Time", "% Disk Write Time", "Current Disk Queue Length", "% Free Space", "Free Megabytes",]
    Measurement = "win_disk"
  [[inputs.win_perf_counters.object]]
    ObjectName = "PhysicalDisk"
    Instances = ["*"]
    Counters = [ "Disk Read Bytes/sec", "Disk Write Bytes/sec", "Disk Reads/sec", "Disk Writes/sec", "% Disk Time", "% Disk Read Time", "% Disk Write Time",]
    Measurement = "win_diskio"
  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = [ "Bytes Received/sec", "Bytes Sent/sec", "Packets Received/sec", "Packets Sent/sec", "Packets Received Errors", "Packets Outbound Errors",]
    Measurement = "win_net"
  [[inputs.win_perf_counters.object]]
    ObjectName = "System"
    Counters = [ "Context Switches/sec", "System Calls/sec", "System Up Time",]
    Instances = ["------"]
    Measurement = "win_system"
  [[inputs.win_perf_counters.object]]
    ObjectName = "Memory"
    Counters = [ "Available Bytes", "Pages/sec",]
     Instances = ["------"]
    Measurement = "win_mem"
  [[inputs.win_perf_counters.object]]
    ObjectName = "Paging File"
    Counters = [ "% Usage",]
    Instances = ["_Total"]
    Measurement = "win_swap"

  [[inputs.ping]]
    urls = ["ping.xxxx.com"]
    count = 1
```

### System info:

Telegraf 1.3.6
Windows 10 (64 bit)

**Comment by Theoooooo** [comment]
From what i've read in the documentation of the agent configuration and the influxDB plugin configuration, it can be a normal behavior with how you configured your influxDB behind and the way you configured your telegraf.

There is what i think:
Playing with jitter first will gather metric in a non-constant period of time. With some jitter options, the values are being gathered at a random interval each time. And it's the same with the flush interval because you configured a jitter.
And after that, the documentation for the influxdb output plugin say this :

```
 ## Multiple URLs can be specified for a single cluster, only ONE of the
 ## urls will be written to each interval.
```
This way, the data are being gathered from your system with random intervals and send out to only ONE of your both influxDB service with also random intervals, each time.
This can possibly cause some irregularity in your data collection especially in grafana because you can only request from 1 URL per datasource.

If you have the possibility, setup a replication in the influxDB or add another datasource with your secondary server to retreive the other missing informations and add another query to your panel to display the missings datas.

**Comment by danielnelson** [comment]
I think the gaps are too large to be explained as normal behavior.  Since you have `round_interval = true` and a 5s interval, the collection times should be (mm:ss):
- 00:00 + 0-3s
- 00:05 + 0-3s
- 00:10 + 0-3s
- 00:15 + 0-3s

All timestamps are set on collection, so the `flush_interval` and `flush_jitter` won't effect the times.

I would guess the most likely cause is either an issue with the collection, or since your `metric_buffer_limit` is so small, it could also easily be dropped metrics.  If you check the logs you should be able to see if either of these is happening.

**Comment by aftabquraishi** [comment]
@Theoooooo & @danielnelson thanks a lot for your valuable feedback!

@Theoooooo what you said do perfectly makes sense. I will check with the other InfluxDB instance and co-relate the timestamps from both instances, should be able to figure out that way. If that is the case then I will have to find a way to query and merge data from both instances into a single graph in grafana.

@danielnelson I agree with you that there may be a possibility of data loss due to the `metric_buffer_limit`. I will check the logs and see if that's happening.

Unfortunately, I am sick today and unable to check this. I will provide an update once I have my findings ready. Thanks again!

**Comment by aftabquraishi** [comment]
@Theoooooo you guessed it right! Metrics are actually getting splitted among the 2 instances of InfluxDB. Thanks a lot for your help!

As a resolution we may use `--Mixed--` data source in Grafana to aggregate data from both the instances, or eliminate 1 instance, or replicate among the instances.
