### ISSUE TITLE
telegraf warning

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#6481]
Hi Team,

I am getting Warning in telegraf status, can you please help me to understand it's meaning 

Redirecting to /bin/systemctl status telegraf.service
● telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
   Loaded: loaded (/usr/lib/systemd/system/telegraf.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2019-09-14 19:47:23 IST; 2 weeks 5 days ago
     Docs: https://github.com/influxdata/telegraf
 Main PID: 1787 (telegraf)
   CGroup: /system.slice/telegraf.service
           └─1787 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

**Comment by Theoooooo** [comment]
This message mean that the log file containing the local logs of the service telegraf has been rotated due to it's big weight or his timestamp being too old. This as nothing to do with telegraf and should not be opened has an issue.

https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs
Go to "Limiting Journal Expansion" at this link
