### ISSUE TITLE
Question: What are best practises for scalability

### ISSUE THREAD

**Issue by darox** [influxdata/telegraf#6493]
I just asked my self, what are the best practises for scalability of telegraf. My plan:
A host which runs telegraf and pings a lot of hosts every 60 minutes. Do you have any tricks, for example to handle the configuration in a efficient way?

Many thanks.

**Comment by fifedrum** [comment]
Integrate your configurations into some sort of code repository and automation so that you can keep configurations separate from the host. Check-in the ping targets into a live list that represents the last word in authority for what should be pinged. Run a script every automation run that detects changes to that list and rebuilds the configuration files and reloads the service only if there are changes.

Crank up the open file handle limits using that system so when you upgrade you don't lose your configs and have to remember later what needed to change possibly use the same script that rebuilds the configurations to automatically tune the open file handle limits.

Centralize logging so you can see the log data all in one spot.

Slap a web page in front of it.

**Comment by reimda** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.

Thanks!
