### ISSUE TITLE
Windows Service Fails to Start

### ISSUE THREAD

**Issue by r4yfx** [influxdata/telegraf#6503]
### System info:

telegraf 1.12.2
windows 2012 also tried on windows 2016

### Steps to reproduce:

Following installation documentation on telegraf
Attempt to start service of telegraf and fails - Error 1067 

### Expected behavior:
Should just run
### Actual behavior:
Fails to start, however running the command from the powershell or cmd prompt and it runs fine. However cannot terminate the window as this stops the process.

**Comment by reimda** [comment]
Could you send related logs from event viewer and the log file configured in telegraf?  It's possible something simple is going on, like a syntax error in your telegraf.conf.

Thanks!

**Comment by r4yfx** [comment]
There isn't much on the event log

The Telegraf Service service failed to start due to the following error: 
The system cannot find the file specified.

I have uninstalled the program and attempted to reinstall on windows 2016 and this happens

C:\Users\Administrator>C:\"Program Files"\Telegraf\telegraf.exe --service install
2019-10-10T07:30:00Z I! Starting Telegraf 1.12.3
2019-10-10T07:30:00Z I! Using config file: C:\Program Files\Telegraf\telegraf.conf
2019-10-10T07:30:00Z I! Loaded inputs: win_perf_counters
2019-10-10T07:30:00Z I! Loaded aggregators:
2019-10-10T07:30:00Z I! Loaded processors:
2019-10-10T07:30:00Z I! Loaded outputs: influxdb
2019-10-10T07:30:00Z I! Tags enabled: host=<hostname>
2019-10-10T07:30:00Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"<hostname>t", Flush Interval:10s

**Comment by r4yfx** [comment]
I have also done the same with windows 2012, and this appears to be working now.

**Comment by r4yfx** [comment]
the path  within services is 
C:\'Program Files'\Telegraf\telegraf.exe --config C:\'Program Files'\Telegraf\telegraf.conf

**Comment by reimda** [comment]
Glad it's working now.  Closing the issue

**Comment by r4yfx** [comment]
Hi, sorry for the confusion.

This isn’t fixed. The windows 2012 issue I also experienced is resolved but the 2016 issue very much live

**Comment by glinton** [comment]
Sorry for the confusion. In the event log on 2016, are you still getting the `system cannot find the file specified error`? If so, add a `logfile` to the agent portion of the telegraf config (`C:'Program Files'\Telegraf\telegraf.conf`) and send the contents of that, it should contain what file is missing, whether it be the telegraf binary, the config file, or something a configured plugin depends on (be sure to install using the absolute path, rather than simply relative)

**Comment by r4yfx** [comment]
Hi Thanks for reopening the case for me

I added the logfile and syntax into the command, but it appears to still fail without writing the log file. However, running this within cmd prompt it doesn't appear to recognise the "logfile" flag. Is it possible you could give me an example to what the output is supposed to look like?

**Comment by reimda** [comment]
Sorry for jumping the gun closing the issue yesterday. :)

I was able to get an eval Windows Server 2016 VM up and running with telegraf as a service today.

The logfile should look just like the output of telegraf when you don't run it as a service.  Here's mine:

c:\Windows\System32>type logfile.txt
2019-10-11T22:27:12Z I! Loaded inputs: win_perf_counters
2019-10-11T22:27:12Z I! Loaded aggregators:
2019-10-11T22:27:12Z I! Loaded processors:
2019-10-11T22:27:12Z I! Loaded outputs: influxdb_v2
2019-10-11T22:27:12Z I! Tags enabled: host=WIN-MQQQTJ3UI48
2019-10-11T22:27:12Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"WIN-MQQQTJ3UI48", Flush Interval:10s

Initially I couldn't find my logfile either.  If you don't specify a full path for the logfile in telegraf.conf, Windows Server 2016 puts it in c:\windows\system32.  Check there first if you can't find it.

As to your original problem of telegraf not running as a service, it may be because telegraf can't find telegraf.conf.  If that's the case, adding the logfile flag won't do anything anyway.  When running as a service on windows, telegraf expects to find telegraf.conf in c:\program files\telegraf.

Your earlier comment has working directory of C:\Users\Administrator.  Is that where your telegraf.conf is?  If it's there or anywhere other than c:\program files\telegraf, stop and uninstall your existing telegraf service, move telegraf.conf there, then install and start the telegraf service again.

**Comment by r4yfx** [comment]
Hi 
Dont worry about the premature closure. Its all good :) 

I have amended the configuration file to have the log file which it generate when you run the following command from powershell or cmd

However when attempting to start the service. It fails, but no logs are generated. It feels like its not even getting that far. Which would suggest that its not finding the configuration file. The executable path though is 
C:\'Program Files'\Telegraf\telegraf.exe --config C:\'Program Files'\Telegraf\telegraf.conf

You are right in saying that the command prompt starts at C:\Users\Administrator, but I always put in the full path for it to work. 

C:\'Program Files'\Telegraf\telegraf.exe --config C:\'Program Files'\Telegraf\telegraf.conf

Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\Administrator> C:\'Program Files'\Telegraf\telegraf.exe --config C:\'Program Files'\Telegraf\telegraf.conf
2019-10-14T09:28:46Z I! Starting Telegraf 1.12.3

**Comment by reimda** [comment]
Could you retry with a nightly build then recheck windows event log?  Nightlies should have #4291 which improves logging to event log when running as a service.  With that new functionality hopefully the event log will be more useful in debugging the issue you're experiencing.

https://dl.influxdata.com/telegraf/nightlies/telegraf-nightly_windows_amd64.zip

**Comment by r4yfx** [comment]
well, this is interesting. The uninstall of the previous version failed stating that it couldn't find the telegraf.exe file even though I put in the full path and then attempt to do it from the directory. But got passed that speed bump as it appeared to remove the service. 

Downloaded the nightly one as you suggested. Installed without any issues and the service is also now running without any issues either and data coming into influxdb. So it looks like that update is working. 

So the question is. What is the difference between the nightly build and the latest stable version?

**Comment by reimda** [comment]
I reviewed the differences between the nightly and 1.12.3 and the only windows-related change I found was #4291. I don't think it has any changes that affect installing the service or running as a service.

At this point you could keep using the nightly or if you'd like to dig deeper and find out what was wrong before, you could downgrade back to last release and see if the error comes back.

**Comment by danielnelson** [comment]
I'm going to close this issue since it seems that it was addressed with the new logging.
