### ISSUE TITLE
Telegraf logged using container's id instead of name

### ISSUE THREAD

**Issue by hatamiarash7** [influxdata/telegraf#6516]
My telegraf logged to Influxdb using container's id .... so after each `down` or `reboot` container's id will changed

![Screenshot_2019-10-12 Chronograf](https://user-images.githubusercontent.com/16325641/66698577-f85fac00-eceb-11e9-90ce-d8a65b9c50ef.png)

And there is many useless hosts

![Screenshot_2019-10-12 Chronograf(1)](https://user-images.githubusercontent.com/16325641/66698591-175e3e00-ecec-11e9-9619-08c0f0defe5e.png)

What should i do ? Is there any bug ? Or my configs are wrong ?  
It's better to log using container's name instead of id

**Comment by danielnelson** [comment]
This is normal, since docker sets the hostname to the container id, but it's not always very nice.  You have a few options I can think of:
- Use the `--hostname` option to `docker run` and set the container name as the hostname
- Use the `hostname` option in the `agent` section of the telegraf configuration to set the hostname.
