### ISSUE TITLE
telegraf on ubuntu 18.04 output apparmor error

### ISSUE THREAD

**Issue by like-inspur** [influxdata/telegraf#6574]
I run telegraf on ubuntu 18.04 in the way of kubernetes daemonset, now I found some nodes always output error like this about telegraf, even if I have stoped apparmor.service:

[1218209.608134] audit: type=1400 audit(1571921370.172:7045): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=6327 comm="telegraf" requested_mask="trace" denied_mask="trace" peer="unconfined"

**Comment by danielnelson** [comment]
Does this occur with only a `mem` input and a `file` output enabled?  If not can you enable your plugins one at a time to find which is triggering the message?

**Comment by like-inspur** [comment]
processes input meet this error, I found @danielnelson

**Comment by danielnelson** [comment]
Thanks for the update, this plugin looks at all the `/proc/<pid>/stat` files on the system.  We will need to investigate the best way to address this issue, I'm not familar enough with apparmor enough to know right now, perhaps someone from the community can help suggest a course of action.

**Comment by like-inspur** [comment]
I config securityContext as privileged: true, and pod don't output error any more

**Comment by crazy-canux** [comment]
got the same issue when running with docker swarm on ubuntu16.04.
error comes from syslog and kernel.log.

```
    image: telegraf:latest
    hostname: "{{.Node.Hostname}}"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    depends_on:
      - influxdb-service
    networks:
      - ol0
    volumes:
      - /:/hostfs:ro
      - /run/udev:/run/udev:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/var/run/utmp:ro
    environment:
      - HOST_MOUNT_PREFIX=/hostfs
      - HOST_PROC=/hostfs/proc
```

kernel: [4301938.597476] audit: type=1400 audit(1578546880.065:1455110): 
apparmor="DENIED" operation="ptrace" profile="docker-default" pid=12293 
comm="telegraf" requested_mask="read" denied_mask="read" peer="unconfined"

**Comment by brunokc** [comment]
Started hitting this out of nowhere today. Not sure what changed. I run telegraf in a docker container running as root with various volumes mapped as read-only to allow it to look into the currently running processes and other things.

I'm not getting flooded by these logs:

```
May 07 18:34:30 sun kernel: audit_log_start: 80 callbacks suppressed
May 07 18:34:30 sun kernel: audit: audit_backlog=65 > audit_backlog_limit=64
May 07 18:34:30 sun kernel: audit: audit_lost=39793 audit_rate_limit=0 audit_backlog_limit=64
May 07 18:34:30 sun kernel: audit: backlog limit exceeded
May 07 18:34:30 sun kernel: audit: audit_backlog=65 > audit_backlog_limit=64
May 07 18:34:30 sun kernel: audit: audit_lost=39794 audit_rate_limit=0 audit_backlog_limit=64
May 07 18:34:30 sun kernel: audit: backlog limit exceeded
May 07 18:34:30 sun kernel: audit: audit_backlog=65 > audit_backlog_limit=64
May 07 18:34:30 sun kernel: audit: audit_lost=39795 audit_rate_limit=0 audit_backlog_limit=64
May 07 18:34:30 sun kernel: audit: backlog limit exceeded
May 07 18:34:30 sun kernel: audit: audit_backlog=65 > audit_backlog_limit=64
```
And from /var/log/audit/audit.log:
```
type=AVC msg=audit(1588901740.036:2457789): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=9030 comm="telegraf" requested_mask="read" denied_mask="read" peer="dovecot"
```
It's always dovecot for some reason. Trying to learn apparmor to see what can be done.

**Comment by P4sca1** [comment]
Also getting those messages every 10 seconds:
```
May 20 07:34:40 ****** kernel: [1770415.693029] audit: type=1400 audit(1589952880.010:177062): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=1722 comm="telegraf" requested_mask="trace" denied_mask
="trace" peer="unconfined"
May 20 07:34:50 ****** kernel: [1770425.693304] audit: type=1400 audit(1589952890.010:177063): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=1722 comm="telegraf" requested_mask="trace" denied_mask
="trace" peer="unconfined"
May 20 07:35:00 ****** kernel: [1770435.696746] audit: type=1400 audit(1589952900.014:177064): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=1722 comm="telegraf" requested_mask="trace" denied_mask
="trace" peer="unconfined"
```

Using telegraf in a docker container via docker-compose:
```yaml
telegraf:
    image: "telegraf"
    command: "--config https://eu-central-1-1.aws.cloud2.influxdata.com/api/v2/telegrafs/******"
    restart: "always"
    labels:
      - "autoheal=true"
    hostname: "*****"
    environment:
      HOST_PROC: "/host/proc"
      INFLUX_TOKEN: "*******"
    volumes:
      - "/proc:/host/proc:ro"
```

**Comment by danielnelson** [comment]
I think we need to write an apparmor profile and install it with the rpm/deb.

**Comment by P4sca1** [comment]
Does the apparmor profile need to be installed on the host system when running Telegraf in a Docker container?

**Comment by endersonmaia** [comment]
@P4sca1 did you tried `--cap-add SYS_PTRACE` and `--security-opt apparmor:unconfined` ?

see : https://github.com/moby/moby/issues/7276#issuecomment-68812214

I'm using `docker swarm` and those options are not supported via `docker stack`

- https://docs.docker.com/compose/compose-file/#cap_add-cap_drop
- https://docs.docker.com/compose/compose-file/#security_opt

**Comment by crazy-canux** [comment]
can't fix this for docker swarm?

**Comment by rdxmb** [comment]
same here with ubuntu 20.04. telegraf is running as a DaemonSet (so it is running in the official telegraf-image)

`--input-filter processes` seems to be the problem here. 

the inputs `cpu, disk, diskio, mem, kernel, swap, system, docker` are running without errors.

**Comment by P4sca1** [comment]
`--security_opt apparmor:unconfined` solved the issue for me. `--cap-add SYS_PTRACE` alone did not work and seems to not be required when using `apparmor:unconfined`.

`docker-compose.yml`:
```yaml
    security_opt:
      - apparmor:unconfined
```

**Comment by phantomski77** [comment]
I can confirm `--security-opt apparmor:unconfined` sorted out the issue for me. The processes plugin needs `ptrace` allowed to work apparently. Question is - for what exactly? As `unconfined` is probably too permissive, I’d suggest a security profile created specifically for telegraf. At the moment, modifying `docker-default` by allowing `ptrace` would _probably_ suffice, but one provided by InfluxData would be preferred.

**Comment by effitient** [comment]
For Pods in Kubernetes the following annotation must be added to solve this issue:

`container.apparmor.security.beta.kubernetes.io/<container-name>: unconfined`

Replace `<container-name>` accordingly.

**Comment by wosiu** [comment]
Same on ubuntu 20.04 and running telegraf as docker container using docker-compose

**Comment by jdstrand** [comment]
Note there are two significantly different apparmor denials being discussed here:
* ptrace read ala: `type=AVC msg=audit(1588901740.036:2457789): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=9030 comm="telegraf" requested_mask="read" denied_mask="read" peer="dovecot"`
* ptrace trace ala: `
audit: type=1400 audit(1589952900.014:177064): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=1722 comm="telegraf" requested_mask="trace" denied_mask="trace" peer="unconfined"`

Mediation of ptrace in the kernel is pretty coarse with a concept of `read` and `trace` by the calling process and `readby` and `tracedby` for the target. `read` is for things like `ps` and `trace` is for things like actually taking control of the process (can read https://blog.strandboge.com/2014/06/06/application-isolation-with-apparmor-part-iv/ for a little more info). Unfortunately, 'read' and 'trace' cannot be made more fine-grained and you'll find that several things can cause a denial.

If you are going to run telegraf under apparmor (whether on its own, in a pod, under docker, etc), then you need to understand the environment that telegraf is operating in and what it is intended to do so that you can adjust the profile appropriately. I suspect typical plugins are going to need a `ptrace (read),` rule (eg, to read various files in `/proc`) and specialized plugins will need some sort of `ptrace (trace)...` rule (personally, I wouldn't start with a `ptrace (trace),` rule since that gives telegraf a lot of control and is in the neighborhood of defeating the purpose of having the apparmor profile enabled, especially if telegraf is running as root). Once you add these rules to telegraf's apparmor profile, you'll probably find new `readby` and `tracedby` denials popping up for any confined target processes. This is where understanding the environment that telegraf is operating in is important: you may want to add `ptrace (readby) peer=<your telegraf profile name>,` to the target process profile, or you might not. This is a site-specific administrative decision.

Importantly, these apparmor denials are typically not going to be addressable by telegraf developers because telegraf plugins are written to do something and the apparmor profile that is being applied to telegraf needs to account for the intended use of telegraf and any enabled plugins[1]. The apparmor profile is not something that telegraf has any control over: this is a site-specific adminstrative decision to run telegraf in k8s with an apparmor profile, under docker with an apparmor profile or on the system with an added apparmor profile and it is expected that the administrator will always have to fine-tune it (similar to Linux capabilities or seccomp policies).

[1] of course, if a set of plugins has only ever needed `ptrace (read)` and a commit to one of those plugins causes it to all of a sudden need `ptrace (trace)`, this is something a developer could explore to get rid of that denial, but even then, sometimes it is outside the control of the telegraf developers since changes in kernel mediation could cause this as well.
