### ISSUE TITLE
FR: Keep outputs/influxdb HTTPConnection open

### ISSUE THREAD

**Issue by jamesshannon** [influxdata/telegraf#6607]
## Feature Request

I'd like a choice to somehow cache the HTTPConnection in outputs/influxdb and keep it open from from upload to upload. 

### Proposal:

`outputs.influxdb` option for something like `http_keep_open`. 

### Current behavior:
A new HTTPConnection is created for every upload. https://github.com/influxdata/telegraf/blob/9efc37606f7eae0d72b801ba0be68d4561eee915/plugins/outputs/influxdb/influxdb.go#L176

### Desired behavior:

Connection is opened once and kept open.

### Use case:
I'm switching to a 3G network and realize that telegraf is responsible for a lot of data usage.

I could use UDP, but:
* I'd  prefer the guaranteed aspect of TCP
* I really want authentication and encryption (via TLS client side certs).

Using HTTP adds a lot of overhead, and that's multiplied 3 - 6 times per minute. Using HTTPS adds even more overhead. I think I was seeing about 10k per push (so ~3.6mb / hour or 86mb per day).

Keeping the connection open and/or TLS session resumption will solve the connection overhead.

**Comment by glinton** [comment]
The code you linked gets called only once. There is a new connection each call to write, which ends up here: https://github.com/influxdata/telegraf/blob/9efc37606f7eae0d72b801ba0be68d4561eee915/plugins/outputs/influxdb/http.go#L297

I'm not certain influxdb utilizes streaming via an open connection (http2.0, websockets, etc...) so it would have to be implemented there before we can do anything about this. 

Have you tried using the [merge aggregator](https://github.com/influxdata/telegraf/tree/master/plugins/aggregators/merge) to see if that helps limit connections the payloads? Otherwise you can modify the [`metric_batch_size`](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent) and `flush_interval` to group more metrics together before sending them off to influx (higher batch size means more metrics sent to influx per http call).

**Comment by jamesshannon** [comment]
Regarding influxdb: Good point. I use nginx in front of influxdb (to handle client certs and some other stuff). Nginx supports Http2, but that's obviously not the baseline. It's been quite successful in slimming down other repeating connections to the server.

No. I haven't. I'll play with merge  aggregator.

I had seen `metric_batch_size` and `flush_interval` but I think I got confused by the documentation. E.g., `of at most metric_batch_size metrics` didn't suggest that it'd actually batch up multiple intervals. Instead I thought that for any given interval it might create smaller batches (in the same way as the `udp_payload` config setting). But I'll play with these too.

**Comment by danielnelson** [comment]
Telegraf will reuse the connection to InfluxDB, so long as it isn't closed by InfluxDB or any proxies in the path.

I'm going to close this issue since the feature should already be implemented.

> I had seen metric_batch_size and flush_interval but I think I got confused by the documentation. 

The outputs write (in this case do a HTTP POST) if `metric_batch_size` worth of new metrics are produced, or after the `flush_interval`, whichever comes first.  This is independent of the `interval` which only governs input plugins that are polling sources.  If this Telegraf produces only a small amount of data, increasing the `flush_interval` should help at the cost of more latency before your data is viewable in the database.

You will also definitely want to set `content_encoding = "gzip"` in the InfluxDB output plugins, so that the body is compressed.
