### ISSUE TITLE
[[inputs.file]] multiple csv, only second being displayed in /metrics

### ISSUE THREAD

**Issue by andrew1381** [influxdata/telegraf#6692]
### Relevant telegraf.conf:

[[inputs.file]]
  files = ["C:/temp/*.csv"]
  data_format = "csv"
  csv_header_row_count = 1
  name_override = "machine_role"

### System info:

Server 2012 R2 
Telegraf 1.12.1
Prometheus output

### Steps to reproduce:

1. Have input get any csv in path.
2. Test config and see both csv's are represented by their own row "machine_role"

### Expected behavior:

Both "machine_role" metrics should appear in the metrics page "/metrics" for Prometheus to read.

### Actual behavior:

Both metrics show up in test, but are missing in prometheus /metrics page.

### Additional info:

Both csvs have the same headers.

**Comment by danielnelson** [comment]
Can you add the output of `telegraf --input-filter file --test`?

**Comment by andrew1381** [comment]
> machine_role,host=hostname env="dev",os="windows",role="domain_controller",value=1i 1574364903000000000
> machine_role,host=hostname env="dev",os="windows",role="dns",value=1i 1574364903000000000

**Comment by danielnelson** [comment]
Since the prometheus format does not support string values, they are normally dropped, this effectively leaves you with just:
```
machine_role,host=hostname value=1i 1574364903000000000
machine_role,host=hostname value=1i 1574364903000000000
```
Since they measurement+tags+timestamp are identical, these collapse onto each other.

The fix is easy though, the string fields should be parsed as tags:
```
[[inputs.file]]
  csv_tag_columns = ["env", "os", "role"]
```

It is also possible to set `strings_as_labels` in the `prometheus_client` output, but the parse fix is more appropriate in this case, and will work if you ever change outputs.

**Comment by andrew1381** [comment]
That did it! Thanks!
