### ISSUE TITLE
Add []byte data_type for value parser

### ISSUE THREAD

**Issue by ppff** [influxdata/telegraf#6717]
For some reason, you might want to get raw data from your inputs (to process various binary payloads through a custom processor for example). The closest solution right now is to use the `value` parser with the `string` type. But this already changes the value, as it removes spaces and null bytes.

I would like to add the `bytes` data type which would simply copy `buf []byte` to the output.

I can open a small PR if you agree with this feature. If there's a better solution for this use case, please share it.

**Comment by danielnelson** [comment]
I'm not sure, in general I would advise against binary payloads unless we are going to encode them first with a text safe encoding such as base64.  Although it mostly works, most of our output formats assume text data.  The `[]byte` type is not currently allowed by the telegraf.Metric type, although it does convert this type into a string and functionaly there is no difference.

If we added a parser for this type of data how would we handle delimiting, say if it were used with the tail input or socket_listener?

> If there's a better solution for this use case, please share it.

Can you share your use case?  Include if this data bound for InfluxDB.

**Comment by ppff** [comment]
Thanks for the quick answer.

To answer your question, I'm currently setting up IoT data collection. The "things" have a pretty basic firmware (no OS) and a low data rate internet connection. They use MQTT but data usage is reduced to the minimum with very short topics and binary payloads (it makes no sense to transfer "1684567" using 7 (ascii) bytes when 3 bytes hold the same information).

So here is the pipeline I thought of: mqtt input with "bytes" value parser -> custom processor -> influx

Maybe the best way to do this is simply to rewrite the MQTT input plugin. However I thought we could provide a more generic solution since IoT is a big market of Influx and because these constraints are quite standard with embedded programming.

**Comment by danielnelson** [comment]
The custom processor would be interpreting the bytes as an integer?

I think we wouldn't want to allow binary data into the internal metric type (`telegraf.Metric`), it would be too limiting in what we could do with this form and we wouldn't want to add it only with the idea that a processor would fix it.  To me it makes the most sense to do the intepretation of the data fully in the parser, from binary to integer.

Are you encoding your value using a standard encoding?  Maybe we could have a `int64_le` `data_type` for example.

**Comment by ppff** [comment]
It's more complicated than that. The MQTT topic defines the measurement and the field, and the payload contains the data. However, the data isn't always formatted the same way depending on the field. There are strings, but also int16, int32, uint8, uint16... That's why 1) it's not possible to use a parser only (the mqtt plugin only gives the payload to the parser, but I need the topic) and 2) I can't juste have a single conversion type.

I'm not sure what you mean by "encoding", it's pure binary. Here is what my processor would look like : 
```
if topic == "measurementA" { 
  value = binary.BigEndian.Uint16(mqtt_payload)
}
else if topic == "measurementB" {
  value = binary.BigEndian.Uint32(mqtt_payload)
}
etc...
```

**Comment by cliffordvandyk** [comment]
This topic relates to my request to reopen the base64 decoder class. I agree that since IOT is an important market for Influx, it would be nice to support it well. It seems that one of the standard methods of storing IOT values is to pack the "raw" values (ints, floats, etc) into a byte array, and then either base64 encode them, or simply use a HEX string, before including this in a JSON key/value pair, like the "data" key/value in this example: "{"applicationID":"1","applicationName":"eDartSensors","devEUI":"393032357a377e05","deviceName":"dev-393032357a377e05","timestamp":1574112721,"fCnt":49,"fPort":2,"data":"VQP0DQwCiv7Qf28M5kkAqg==","data_encode":"base64","adr":true,"rxInfo":[{"gatewayID":"60c5a8fffe760ef8","loRaSNR":9.5,"rssi":-54,"location":{"latitude":-34.077960,"longitude":18.448570,"altitude":107},"time":"2019-11-18T21:32:01.166093Z"}],"txInfo":{"frequency":868300000,"dr":6}}"
The field ("data_encode") is used to identify the encoding (typically either hex or base64). 

The decoded string (assuming base64 encoding was used) then needs to be split into the values, and for this to happen the byte array needs to include more than just the values, but delimiters and type identification. 

A reasonable (although frustratingly incomplete/poorly generalised) method for packing multiple value fields into the byte array is CayenneLPP (myDevices.com) that allows the fields to be automatically identified through parsing the byte array alone. See https://github.com/myDevicesIoT/CayenneLPP
My problem with CayenneLPP is that it has proprietary sensor type field (e.g. temperature), but no understanding of the data types, scale or resolution of the sensed value. 

I think it would be more useful to include in each sensed value some bare minimum metadata necessary for value delimiting and type interpretation (particularly if different types may appear arbitrarily in the same byte array). Maybe also a termination character to tell the parser when to stop. Perhaps some of the field interpretation rules could be brought into the telegraf input configuration.

I am happy to propose/document a generalised method for consideration.

**Comment by cliffordvandyk** [comment]
I should point out that the above example is transported using MQTT, where the entire JSON message is the MQTT payload. The MQTT topic could never hope to provide sufficient information for a multi-value data payload embedded in JSON, I think this metadata would need to be included in the payload ("data") or input plugin config.

**Comment by ppff** [comment]
Hello Clifford, I think this is unrelated to my question. I don't use multi-value data payload because it would break the advantage of being able to route single values efficiently using MQTT topic filtering, and my network constraints are such that I can't transfer payloads that are so big.

I mean look at ZigBee, a popular M2M protocol, the maximum payload size for a message is 80 bytes or so. And this for the entire MQTT packet, including its header, topic and payload. In the embedded world, data can't be wasted, and that's why we need binary support.

I'll just write my own input plugin, but if you want to discuss this further don't hesitate to contact me!

**Comment by cliffordvandyk** [comment]
Yes, not exactly the same, since your payload is single valued as opposed to multivalued. I was trying to show you an example of the base64 encoding that is used in IOT applications. I have also had to write my own pre-processor (Python, since I'm not too familiar with Go) to reform these strings into something that Telegraf will interpret usefully, but it feels like this partially defeats the purpose Telegraf. It's unfortunate that neither simple  MQTT binary payloads, nor JSON formatted payloads that include binary are supported.
