### ISSUE TITLE
Not able to get all data of Json

### ISSUE THREAD

**Issue by wolvriene** [influxdata/telegraf#6758]
Hi Team,
i have input.file as json below

{"Performance":0.96,"first-contentful-paint":"0.9 s","speed-index":"1.0 s","first-cpu-idle":"1.0 s","Time to Interactive":"0.9 s","Max Potential First Input Delay":"30 ms","First Meaningful Paint":"1.0 s"}

But telegrapf providing only first data point i.e. "**Performance**"
Please help me to get other data as well

**Comment by danielnelson** [comment]
The other items are skipped because they are strings.  You could add them to the `json_string_fields` option but you may find it to be limiting for these to be strings so you may want to try to send the data in as an integer.

If you need more help, please ask usage questions at the [InfluxData Community](https://community.influxdata.com) site.
