### ISSUE TITLE
Add input plugin for PSI (Pressure Stall Information)

### ISSUE THREAD

**Issue by bbartsch** [influxdata/telegraf#6760]
## Feature Request

Facebook implemented PSI (Pressure Stall Information) for Linux 4.20 and higher. PSI presents high quality information about the pressure the IO, memory and CPU is under. More information here:

https://facebookmicrosites.github.io/psi/

### Proposal:
Input plugin for PSI
### Current behavior:
None
### Desired behavior:
Support/Input plugin for PSI 
### Use case: 
Good indicator if a system is overloaded

**Comment by lpic10** [comment]
I'd be interested in this.

Should it be implemented on [gopsutil](https://github.com/shirou/gopsutil) ?

**Comment by danielnelson** [comment]
I suspect the information might be too Linux specific to be included in gopsutil.

@shirou @Lomanic Do you have any thoughts on adding this?

**Comment by Lomanic** [comment]
Too much Linux specific for gopsutil I would say yes.

**Comment by shirou** [comment]
Agree. Too specific and if you want, creating other package would better I think.

**Comment by vans163** [comment]
+1 for this, this is pretty much 'THE' CPU metric worth monitoring.

**Comment by niasar** [comment]
I made input plugin, that collects pressure stall information by raw parsing files in /proc/psi. [Here is my PR](url)

**Comment by ajfriesen** [comment]
If someone searches for PSI and Influx/telegraf:

Since we were in need for psi metrics as well I have created a plugin as well: [gridscale/linux-psi-telegraf-plugin](https://github.com/gridscale/linux-psi-telegraf-plugin)
It is using the [procfs](https://pkg.go.dev/github.com/prometheus/procfs) package from the prometheus folks to get/parse the metrics.

You can run this as an external plugin without getting it merged into the telegraf core.

**Comment by powersj** [comment]
@ajfriesen any reason not to put it up as a PR as well?

**Comment by ajfriesen** [comment]
> @ajfriesen any reason not to put it up as a PR as well?

I thought this is stale since Dec 5, 2019 for a reason.
Just wanted to have an external plugin and use it as fast as possible without any dependencies. Did not want to wait for the telegraf core.

**Comment by powersj** [comment]
> I thought this is stale since Dec 5, 2019 for a reason. Just wanted to have an external plugin and use it as fast as possible without any dependencies. Did not want to wait for the telegraf core.

We have a huge backlog of PRs and issues that are we actively working our way through. My hope is to get this back down in the coming months so we can be even more responsive with fixing issues and merging PRs.

If you feel we should review the existing PR or if yours should supersede it. Thanks!

**Comment by ajfriesen** [comment]
@powersj 

> We have a huge backlog of PRs and issues that are we actively working our way through. My hope is to get this back down in the coming months so we can be even more responsive with fixing issues and merging PRs.

You maintain a huge open source project and I understand the amount of work and appreciate it. 🙃 
Therefore I just have gone with the external plugin way. I think this is the reason to have external plugins. Not everything needs to be in the core of telegraf.
Otherwise, you will end up as a bottleneck just from the perspective of amount of work.

If PSI makes sense in the core is up to the telegraf maintainers. I think it makes sense for Linux machines but could be wrong here.

> If you feel we should review the existing PR or if yours should supersede it. Thanks!

My plugin setup is a little different from the perspective of tags and kind of metric I am adding.

Not sure what would be the better approach. It is my first plugin and also first go code I have written which is somewhat useful.

**Comment by pikrzysztof** [comment]
Would be cool to have it support docker as well.

**Comment by famz** [comment]
How come PSI is listed in https://docs.influxdata.com/telegraf/v1.26/plugins/ but nowhere in the repo?

**Comment by powersj** [comment]
> How come PSI is listed in https://docs.influxdata.com/telegraf/v1.26/plugins/ but nowhere in the repo?

Looks like someone saw we added it as an external plugin and accidently added as a plugin. [I'll get it removed](https://github.com/influxdata/docs-v2/pull/4811).

**Comment by vipinvkmenon** [comment]
This plugin would be of great help if it was incorporated

**Comment by iBug** [comment]
As of Telegraf 1.30 (released 2024-03-11) the built-in `inputs.kernel` plugin supports PSI with `collect = ["psi"]`.

See the [README](https://github.com/influxdata/telegraf/blob/release-1.30/plugins/inputs/kernel/README.md) for details and example metrics.
