### ISSUE TITLE
Monitor number of connected users on a Windows host

### ISSUE THREAD

**Issue by ArthurBodom** [influxdata/telegraf#6762]
## Feature Request

The idea is to have the same metric as on Linux hosts "n_users" but on Windows hosts. I have searched on the Internet but couldn't find anyone who had done this. Maybe I'm wrong, maybe it is possible.
Please take in consideration that I'm new to telegraf and I might have not seen the solution to my request.

### Use case: 
I am monitoring several RDS 2016 Windows servers, and I would like to monitor the number of connected users on each server. This isn't a huge priority as I might be the only person who wants to monitor this metric.

**Comment by Trovalo** [comment]
You should be able to achieve that using the **exec** plugin.
You will need a cmd/Powershell script to get the data you need and then serialize them in a valid format (csv, json, influx and others, see the [docs](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md)) so Telegraf can send them to InfluxDB.
I'm using Powershell to gather some custom data and the ["Influx" Powershell module](https://github.com/markwragg/PowerShell-Influx) to serialize them in influx format.

I made a script to get the disk space on current/remote machine, I will put it below as an example
The exec plugin configuration looks like this one:
`
[[inputs.exec]]
  ## Commands array
  commands = [
    'powershell.exe -Command "C:\Monitoring\telegraf\Configuration\telegraf.d\custom_input_scripts\Get_DiskSpace.ps1 -HostList SQLCSRV04"'
  ]

  ## Timeout for each command to complete.
  timeout = "2m"

  ## data format options:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "influx"
  
  ## Override default gathering interval
  interval = "6h"
`

And this is the Powershell script:
`
# ===================================================
# Script Requirements
# ===================================================
# 1. Powershell remoting enabled, even on local machine. run as admin -> Enable-PSRemoting
# 2. Influx Powershell Module, run as admin -> Install-Module Influx

param(
    [String[]] $HostList = [Environment]::MachineName
)

# only DriveType = 3 â†’ Local hard disk
$VolumeData = Get-CimInstance CIM_LogicalDisk -ComputerName $HostList | Where-Object {$_.DriveType -eq 3}

# ===================================================
# Set calculated/renamed Fields
# ===================================================

$Server = @{label="Server";expression={$_.SystemName}}
$Volume = @{label="VolumeId";expression={$_.DeviceID}}

$TotalSize = @{label="TotalSpace(MB)";expression={[math]::Round($_.Size/1MB, 2)}}
$FreeSpace = @{label="FreeSpace(MB)";expression={[math]::Round($_.FreeSpace/1MB, 2)}}
$FreeSpacePerc = @{label="FreeSpace(%)";expression={[math]::Round(1-($_.Size - $_.FreeSpace)/$_.Size , 4)}}

# $_.Description may contain the same value
$VolumeTypeC = @{label="VolumeType";expression={
    switch ($_.DriveType) {
        1 {"No root directory"; break}
        2 {"Removable drive"; break}
        3 {"Local hard disk"; break}
        4 {"Network disk"; break}
        5 {"Compact disk"; break}
        6 {"RAM disk"; break}
        default {"Unknown"; break}
    }
}}

# ===================================================
# Define Tags and Metrics property mapping
# ===================================================
$Measurement = "ServerDisk"
$TagList = "Server","VolumeId","VolumeName"
$MetricList = "TotalSpace(MB)","FreeSpace(MB)","FreeSpace(%)"

# ===================================================
# Output
# ===================================================
# Warnings can't be sent to the output therefore "-WarningAction SilentlyContinue" is used
$VolumeData | Select-Object $Server,$Volume,VolumeName,$VolumeTypeC,$TotalSize,$FreeSpace,$FreeSpacePerc | ConvertTo-Metric -Measure $Measurement -MetricProperty $MetricList -TagProperty $TagList | ConvertTo-InfluxLineString -WarningAction SilentlyContinue
`

This approach has some cons, especially for logging/managing exceptions, because when you run a Powershell file/command from the cmd (the exec plugin on windows uses cmd to run commands) the error output of Powershell is not sent to stderr of the cmd, and therefore is not logged by Telegraf. 
I have not yet found a way to manage this, the only option might be to manage and log exceptions from the Powershell script itself.

**Comment by danielnelson** [comment]
@Trovalo Thanks for sharing you solution, this seems like a good solution and is very extensible.  I didn't know about the Influx module, that will be handy.

Another idea that comes to mind is to use the `win_perf_counters` input plugin to read a Windows Performance Counters with this info.  [This page](https://support.microsoft.com/en-us/help/186536/terminal-server-performance-monitor-objects-and-counters) seems to indicate that there is a counter for "Active Sessions".

I use `perfmon` to poke around a bit for the right names and found what I think might work for you, translated into the plugin configuration:
```toml
[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Terminal Services"
    Counters = [
      "Active Sessions",
      "Inactive Sessions",
    ]
    Instances = ["------"] # this counter has no instances
    Measurement = "terminal_services"
```

**Comment by ArthurBodom** [comment]
@danielnelson The solution you gave me is very simple and works just fine. I modified the configuration files on all my servers, restarted the services and voilà, I can now display the number of active sessions! 

Thank you very much
