### ISSUE TITLE
No way to create alerts for counters in Azure Monitor

### ISSUE THREAD

**Issue by futurexpe** [influxdata/telegraf#6771]
Currently there is no way in Azure monitor to create alerts on top of counter metrics that are increasing values. For example if I have an 'error' metric which is counting errors, and I want to set up alerts every time there is a error, which increases the reported metric by 1.

Azure monitor does not support dynamic thresholds so one way to do this would be to implement custom logic in the telegraf module to send only the delta rather than the increasing value. 

Is there another recommendation here to set up alerts on Counters in Azure Monitor?

**Comment by danielnelson** [comment]
I don't have a good recommendation for you right now, it doesn't seem to me that Azure Monitor has a difference aggregation.

In general, we don't know if a value is a counter or what type of counter it is, so it would be a problem to send deltas automatically.  We do have a few items in progress for calculating derivative or differences on select fields, so perhaps these will be the ultimate answer: https://github.com/influxdata/telegraf/pull/3762

**Comment by sjwang90** [comment]
@futurexpe I'd suggest you checking out if any of the [Starlark processor examples](https://github.com/influxdata/telegraf/tree/master/plugins/processors/starlark#examples) can help you to get what you're looking for. It can calculate deltas and do logic functions. 

Closing this for now due to the lack of discussion. If you have any questions please reach out to us in our [Community Slack](influxdata.com/slack).
