### ISSUE TITLE
Deleted VM is still showing on the influxDB

### ISSUE THREAD

**Issue by kssanthosh** [influxdata/telegraf#6833]
### Relevant telegraf.conf:

```toml

```

### System info:
Telegraf 1.11.4
VMware vSphere Input Plugin

### Steps to reproduce:

1. Delete a vm in VMware vsphere cluster
2. It is still showing on the influxdb
3. You can check it on the Tag values

### Actual behavior:
Hope it should be removed from influx also if we remove a vm or a datastore from the vsphere cluster

**Comment by danielnelson** [comment]
So long as vSphere is still reporting on the VM then Telegraf should continue to forward the info.  Nothing should ever be removed from InfluxDB after it has been reported, usually you handle removal with an appropiate retention policy.

**Comment by kssanthosh** [comment]
Can you please suggest me a best solution for this.

**Comment by danielnelson** [comment]
@prydin Do you have any advice on how to debug this issue?

**Comment by prydin** [comment]
There will be no metrics reported on a deleted VM. The vSphere plugin has no way of deleting objects in InfluxDB.

As far as I can tell from the problem description, Telegraf behaves as designed.

**Comment by danielnelson** [comment]
@kssanthosh I'm not sure if your expectation was that the old data would be deleted once the VM stopped, but if so that definitely won't happen.  The best solution for this is to write to a database and retention policy with a suitable duration.  This way old data will be removed once it reaches a certain age.
