### ISSUE TITLE
perfEventsStatementsQuery cannot collect data when schema_name is null.

### ISSUE THREAD

**Issue by ChoiJoonho** [influxdata/telegraf#6855]
Hi,

This query cannot collect digest queries text when schema_name is null,

SELECT
            ifnull(SCHEMA_NAME, 'NONE') as SCHEMA_NAME,
            DIGEST,
            LEFT(DIGEST_TEXT, %d) as DIGEST_TEXT,
            COUNT_STAR,
            SUM_TIMER_WAIT,
            SUM_ERRORS,
            SUM_WARNINGS,
            SUM_ROWS_AFFECTED,
            SUM_ROWS_SENT,
            SUM_ROWS_EXAMINED,
            SUM_CREATED_TMP_DISK_TABLES,
            SUM_CREATED_TMP_TABLES,
            SUM_SORT_MERGE_PASSES,
            SUM_SORT_ROWS,
            SUM_NO_INDEX_USED
        FROM performance_schema.events_statements_summary_by_digest
        WHERE SCHEMA_NAME NOT IN ('mysql', 'performance_schema', 'information_schema')
            AND last_seen > DATE_SUB(NOW(), INTERVAL %d SECOND)
        ORDER BY SUM_TIMER_WAIT DESC
        LIMIT %d

**Comment by sspaink** [comment]
Hello sorry you haven't received a response yet, but I am going to close this because the MySQL plugin has received a lot of updates since you created this issue and we now also have a generic sql plugin that you might find useful. If you are still having the issue please re-open or leave a comment and we can investigate further.
