### ISSUE TITLE
input.socket or collectd parser issue

### ISSUE THREAD

**Issue by mroe1234** [influxdata/telegraf#6920]
I'm using radsniff (https://wiki.freeradius.org/guide/stats-with-radsniff) to collect freeradius statistics and forward to a collectd listener.  Using collectd it seems to work.  I use socat to sniff the unix socket and it looks good.  collectd also is populating RRDs.

When I redirect radsniff to telegraf with the below configuration, telegraf logs an error:

telegraf[1522]: 2020-01-17T18:47:27Z E! [inputs.socket_listener] Unable to parse incoming line: Collectd parser error: invalid length 21590

I also have the socat capture from this communication upon request.  

### Relevant telegraf.conf:
     cat /etc/telegraf/telegraf.d/collectd.conf
      [[inputs.socket_listener]]
        service_address = "unix:///var/run/telegraf/telegraf.sock"
        data_format = "collectd"
        collectd_typesdb = ["/usr/local/share/freeradius/radsniff_types.db"]
        collectd_parse_multivalue = "split"
        socket_mode = "777"

### System info:

    # uname -a
    Linux ccc 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux
    # cat /etc/debian_version 
    10.2
    # telegraf --version
    Telegraf 1.13.1 (git: HEAD 0c175724)

### Additional info:

    # radsniff -v
    radsniff version 3.0.20, built on Jan 16 2020 at 08:54:33, libpcap version 1.9.0 (with TPACKET_V3), collectdclient version 5.8.1

**Comment by danielnelson** [comment]
This is a bit of a guess, but I suspect this may be because the socket_listener plugin always performs newline delimiting when reading from a stream, so it doesn't know how to properly split the collectd binary format, which uses a length in the message header to frame messages.  That would make this essentially the same core issue as #6025.

I see in the linked site they were unable to get radsniff working over UDP to collectd, but could you try sending to socket_listener using a udp socket?

**Comment by nward** [comment]
Hi @danielnelson - I don't believe that libcollectdclient supports sending via UDP - only TCP, and radsniff uses libcollectdclient.

An easy way make this work in the short term is run a copy of collectd relaying from TCP to UDP.. but it's a bit of a pain.

**Comment by srebhan** [comment]
@mroe1234 can you please check if #12187 with the correct `splitting` setting fixes the issue?
