### ISSUE TITLE
Name can not be set after setting sometimes

### ISSUE THREAD

**Issue by daviddotzhang** [influxdata/telegraf#7032]
### Relevant telegraf.conf:

>  [[inputs.cisco_telemetry_gnmi.subscription]]
        name ="hw-resources-datas"
        origin = "Cisco-IOS-XR-platforms-ofa-oper"
        path = "/ofa/stats/nodes/node/Cisco-IOS-XR-NCS-BDplatforms-npu-resources-oper:hw-resources-datas"
        subscription_mode = "sample"
        sample_interval = "10s"

### Steps to reproduce:

1. set the telemetry as the config
2. output the result to a file.
3. check the file and tail -f /tmp/metircs.out

### Expected behavior:
Name can be outputted  correctly

### Actual behavior:

Name can not be outputted correctly
![image](https://user-images.githubusercontent.com/7136961/74629669-ba8bfc00-5193-11ea-8be7-d64c6eb36692.png)

**Comment by danielnelson** [comment]
@sbyx Can you take a look at this one?  Any chance it is a similar to #7035?

**Comment by sbyx** [comment]
Hmm, interesting. Cannot really say what is happening there. The screenshot seems to show some other weird behavior as well, e.g. "isco_IOS_XR_...".

Unfortunately I cannot query this model from a virtual router to verify or get the raw data since it seems to be platform specific.

Could you check what happens if you ask for the path "/ofa/stats/nodes/node/hw-resources-datas" instead (skipping the qualifier).
Can you let me know which platform and version that is? I can try to get ahold of one to verify this.

**Comment by sjwang90** [comment]
@daviddotzhang Can you provide the platform and version that you were running into this issue so we can get this verified?

**Comment by MyaLongmire** [comment]
Due to inactivity, I am going to close this. Feel free to ping me to reopen if needed.
