### ISSUE TITLE
Build ARM pacakge (.deb / .rpm)

### ISSUE THREAD

**Issue by PierreF** [influxdata/telegraf#708]
Telegraf is already built for ARM, but only available as "Standalone".

It would be great to also built them as .deb and have them in your repository (https://repos.influxdata.com/). This would simplify installing (and keep up-to-date) telegraf on RasberryPi (or other ARMish board).

Thanks

**Comment by TotallyInformation** [comment]
The ARM deb that is listed on the github README does not work on the Raspberry Pi 2 which is an armhf architecture. Would it be possible to adjust your auto-builds to include armhf versions and add them to the repos?

**Comment by s1m0** [comment]
there is a work-around (credit to  @rossmcdonald)
As root run:-
dpkg --add-architecture arm
dpkg -i <package>

The nightly influxdb builds install as armhf.

**Comment by lukeroge** [comment]
Agreed. Not sure why the current arm builds are "arm" and not "armhf" or "armel". Debian really does not want to install them because of that fact.

**Comment by PierreF** [comment]
Building with
```
./scripts/build.py --package --version="0.10.4.1-22-gb2a4d4a" --platform=linux --arch=arm --pkgarch=armhf
```
creates package that works on RaspberryPi 2 (with Ubuntu)

I don't known what pkgarch expect RPM based distro.

If armhf works on them, Maybe it should be the default pkgarch for ARM build ?

**Comment by TotallyInformation** [comment]
Thanks for listing the command @PierreF but my point was that this is VERY unfriendly to users who are often not that familiar with Linux development. It is even more unfriendly as compilation on a Pi will take AGES.

If there is a build process that populates the repo's, is it that hard to fix it to also include a working set of ARM binaries?

@s1m0 many thanks for the workaround, I will give that a go.

I'm new to Influx and I would have to comment that the lack of friendliness for non-dev installers is a real put-off and will continue to hamper your otherwise excellent set of projects. I sincerely hope that Influx won't languish as another "also-ran" like so many other open source projects for lack of some thought for people who don't want to or haven't the time to learn the arcane arts of C programming.

If it were not for [Matthias's blog post with precompiled versions](http://padcom13.blogspot.co.uk/2015/12/influxdb-telegraf-and-grafana-on.html), I would have certainly passed over InfluxDB alltogether. As it is Telegraf didn't work properly so I'm not currently using it. I will try again with the information here but life is far too precious to be wasting it on working out how to compile something I'm afraid.

All the best for the future. Julian.

**Comment by rossmcdonald** [comment]
@TotallyInformation the reason why this issue was closed is because we just added support for `armhf`, `armel`, and `arm64` builds to the nightly releases with #779. If you need an `armhf` binary as badly as it sounds, you can find the links to the nightlies below:

- [Debian/Raspbian](https://s3-us-west-1.amazonaws.com/telegraf-nightly/telegraf_nightly_armhf.deb)
- [Fedora](https://s3-us-west-1.amazonaws.com/telegraf-nightly/telegraf-nightly.armhf.rpm)

I don't have the means to test the new builds myself since I don't have a Pi, but let me know if anyone runs into any other issues and I'd be happy to help.

**Comment by TotallyInformation** [comment]
Thanks Ross, can we assume this will eventually make it across to the stable builds too? 

I'll give it a go when I get a chance.

**Comment by sparrc** [comment]
@TotallyInformation Yes the armhf packages will be available in stable builds with the next release.

Please keep in mind that we're trying our best to support all users and platforms. We usually do not know about issues with a smaller platform until someone opens an issue. As you can see, this issue was only opened 3 weeks ago. Ross has been doing a great job with our build process and repositories, and I think it's understandable to overlook the difference between "arm" and "armhf" :)

We don't expect users to build our code from source....so if there's somewhere else you find this, you should let us know as soon as possible.

**Comment by TotallyInformation** [comment]
@sparrc - sorry if I came across a little aggressively - a professional danger. I can get a little carried away with trying to encourage people about things I'm passionate about. :-}  I recognise that there are far too many options to be able to pick up on everything and I really do appreciate your efforts to bring something new and good. I'm happy to spread the word - as long as I can get it to work :-/

Thanks for clarifying. I'm looking forward to trying Telegraf again. I also gave some feedback on InfluxDB as I got an email having registered. It was along much the same lines so I hope that the DB will follow a similar route.
