### ISSUE TITLE
sqlserver: add wait_duration_ms to WaitStatsCategorizedV2 counters

### ISSUE THREAD

**Issue by Erik-Horn** [influxdata/telegraf#7090]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Update the WaitStatsCategorized counters to include wait_duration_ms from the sys.dm_os_waiting_tasks system view

### Current behavior:

The current wait stats metrics use the sys.dm_os_wait_stats view which only includes completed waits.

### Desired behavior:

Add a metric for the wait_duration_ms column of the sys.dm_os_waiting_tasks system view. This view includes statistics for tasks that are currently waiting.

### Use case: 

We primarily monitor the performance of our sql servers using wait statistics under the simple premise that if nothing is waiting, then everything is generally ok.

The current wait metrics gathered by the sqlserver plugin only cover completed waits. For short waits, this is fine. For long running waits, such as locks, this delays reporting the wait until is has completed. Lock waits can last for minutes, hours, or even longer. This will be represented on a graph of resource_wait_ms as a short lived, but potentially large spike when the wait completes.

Adding a counter that covers ongoing waits allows long running waits to be immediately gathered/graphed. 

I've implemented the change locally and we are graphing derivative( resource_wait_ms  ) + derivative ( wait_duration_ms ). This is how sql management studio's activity monitor works. The wait_duration_ms is a count of how long tasks have been waiting for a specific wait. When a wait completes, this count goes to zero which creates a negative derivative value that matches the positive value added to the resource_wait_ms. 

This isn't perfect. Occasionally, SQL server is in the middle of updating the data when it's gathered and one counter change doesn't get logged until the next polling interval. This will cause a negative spike in the graph with an adjacent positive spike. There may be a way to deal with this in the graphing engine, but for us it doesn't happen often enough to worry about it.

The change is an easy modification to the existing query that gathers the wait statistics. It does not have any impact on the existing metrics.

I have attached a diff to show how I did it. It only covers on-prem sql server. I don't have azure resources to test with.

[sqlserver.go.diff.txt](https://github.com/influxdata/telegraf/files/4263603/sqlserver.go.diff.txt)

**Comment by danielnelson** [comment]
@denzilribeiro Can you review this change?

**Comment by denzilribeiro** [comment]
In my opinion it is a more expensive query , you can at some points have a LOT of waiting tasks and so that can be a large DMV have seen that have a ton of rows.. Remember for parallel plans each EC is tracked in waiting tasks. The  idea is to keep this very light weight. Yes you can miss an in flight wait ( of a single request) but that will show up in perfmon counters ( also being captured) such as LOCK WAITS/sec. If multiple requests are waiting on a lock of course any one of them finishing/timing out will appear.

A big concern would be adding the time from dm_os_waiting_tasks will then pollute the signal wait type and other columns from sys.dm_os_wait_stats and will make them potentially incorrect as those will only be added at the end of a wait. Signal wait time is a great way to know how much of a wait is due to the wait itself or CPU/scheduler pressure on the box and this would be lost.


Another aspect as you mentioned are negative spikes, account type issues as the 2 different DMV's accountn at different intervals.I personally wouldn't mix the 2. Waiting_tasks are a great addition to anything like a per request monitoring or a "whats in flight" view.
Have been a lot of docs on waits and queues one of the later ones is  - https://www.sqlskills.com/wp-content/uploads/2014/04/sql-server-performance-tuning-using-wait-statistics-whitepaper.pdf

**Comment by sspaink** [comment]
@Erik-Horn are you still interested in this feature request? It seems this change has some downsides from the above response. If you are still interested, would you have the time to implement this potential change?
