### ISSUE TITLE
Telegraf .RPM Fails Verification 

### ISSUE THREAD

**Issue by mprintz** [influxdata/telegraf#7139]
## Feature Request
The RPM package fails verification.

### Proposal:
Change the default permissions of /var/log/telegraf & /etc/telegraf/telegraf.conf

### Current behavior:
`rpm -v telegraf `-> fails.

### Desired behavior:
`rpm -v telegraf` -> No fails

### Use case: 
Customer audit system does not allow packages that fails.

```
nldakapctr-1{root}-> rpm -V telegraf

S.5....T.  c /etc/telegraf/telegraf.conf

.....UG..    /var/log/telegraf

nldakapctr-1{root}->
```

Where:

·         S is the file size.
·         M is the file's mode.
·         5 is the MD5 checksum of the file.
·         D is the file's major and minor numbers.
·         L is the file's symbolic link contents.
·         U is owner of the file.
·         G is the file's group.
·         T is the modification time of the file.
·         c appears only if the file is a configuration file. This is handy for quickly identifying config files, as they are very likely to change, and therefore, very unlikely to verify successfully.
·         <file> is the file that failed verification. The complete path is listed to make it easy to find.

**Comment by danielnelson** [comment]
I believe this verification failures are due to changes on the local system.  From a clean install the verification shows no issues:
```
[:][dbn@centos-8 ~]$ sudo rpm -i telegraf-1.14.0-1.x86_64.rpm
        package telegraf-1.14.0-1.x86_64 is already installed
[:][dbn@centos-8 ~]$ rpm -V telegraf-1.14.0-1.x86_64.rpm
```

If `telegraf.conf` is modified, it will then show up in the output:
```
[+][dbn@centos-8 ~]$ sudoedit /etc/telegraf/telegraf.conf
[:][dbn@centos-8 ~]$ rpm -V telegraf-1.14.0-1.x86_64.rpm
S.5....T.  c /etc/telegraf/telegraf.conf
```

You can use `rpm --noconfig -V` to skip checking the config file.

I believe the `/var/log/telegraf` directory must have been modified manually on your system.

Closing, but let me know if you have any follow questions/concerns.
