### ISSUE TITLE
cisco_telemetry_mdt: GPB Compact support

### ISSUE THREAD

**Issue by neeles83** [influxdata/telegraf#7172]
## Feature Request

Please add support for GPB-Compact next to the GPB-KV (self-describing-gpb) to the cisco_telemetry_mdt plug-in. As this is quicker in collecting and the bandwidth needed for metric collection is about 5x smaller. 

### Proposal:
Add support for GPB-Compact to the MDT plugin. We currently have some python code which already decodes this but would like it to be integrated with the MDT plug-in to have a single source for collecting metrics.

### Current behavior:
Not supported

### Desired behavior:
Support for MDT xpath decoding of GPB-Compact mode. 

### Use case: 
Allows us to minimize traffic for collecting metrics from MDT. Instead of receiving 40-80Mb on metrics per collection/push it will be more like 5-20Mb.

**Comment by danielnelson** [comment]
cc @sbyx

I don't know much about how this is implemented, but would we need to include device specific data into Telegraf to decode the compact format?  One concern I have is that this could significantly increase the binary size.

**Comment by sbyx** [comment]
Yes, it would mean we would need one protobuf file / generated go module per device data model. A device can regularly have 500 or so different models. Also these do change with newer software versions. I guess the overhead would be quite hefty both administratively also in terms of code and binary sizes.

**Comment by neeles83** [comment]
Well I don't want to put in the models. The user still needs to find his own xpath to export through the Yang explorer. The format you will receive is the only difference instead of getting a gpb-kv pair you now get an binary. 

To my understand GPB sends a encoded messages, which holds the encoding path. In addition it should hold a version so you can use multiple versions of the decoder. 

The GPB indeed uses decompiling files, but these can be placed in a directory just like SNMP MIBs. 
https://github.com/cisco/bigmuddy-network-telemetry-pipeline works in a similar fashion., to my understanding. 

Let me have a look at the code we have and how we do this. Hope we can make it a bit simpler and make it work like the SNMP plug-in as soon as you want GPB-Compact support. 

I will get back to you. Thanks for looking into it already.

**Comment by neeles83** [comment]
> Yes, it would mean we would need one protobuf file / generated go module per device data model. A device can regularly have 500 or so different models. Also these do change with newer software versions. I guess the overhead would be quite hefty both administratively also in terms of code and binary sizes.

I checked how Cisco did this in the bigmuddy-pipeline. You are correct in the fact that we need to compile this in the code and thus the Telegraf code will grow rapidly something Telegraf does not want. Especially if Telegraf wants to supporting multiple vendors. 

What we can do is fork of MDT and build our own plugin with support for GPB-Compact. That would mean that users need to compile their own Telegraf instance with MDT GPB-Compact proto files included, to get GBP-compact support working.

**Comment by danielnelson** [comment]
> What we can do is fork of MDT and build our own plugin with support for GPB-Compact.

Yeah, I think this is how it will have to be done.  I'd be interested in seeing the forked code even if we can't merge it though, if you can add a link here once you have it working?

**Comment by neeles83** [comment]
Hi Daniel, 
It may take a while as I have tons of other stuff to do and limit knowledge on programming and GO, I will study up this weekend on the later and have a chat with some off my colleagues to see if they are interested in a hobby project to fix this and have it working for others as well. 

We will post the fork here, for you to review and see what can be done.

**Comment by deanasheehan** [comment]
@neeles83 and @danielnelson - Having finally taken a look at Cisco Compact GPB (and I had unknowingly already come across it when looking at some Huawei telemetry collection) it resonates with some other work I have looked at for dynamic GPB decoding and I think one solution might sit with such a scheme.


Rather than statically compiling the protobuf unmarshallers for each required path it is possible (in theory and with some non telemetry but other GPB work I've done) to interpret the .proto definition (actually its File Descriptor version which is a protobuf encoded definition of a .proto file) and dynamically decode the wire data on the fly.

**Comment by neeles83** [comment]
@deanasheehan that would mean it works like Telegraf is working with SNMP. Meaning you have a directory if descriptors instead of MIB's now .proto files which will be loaded when Telegraf starts. 

GBP-Compact mode would then be an case in the MDT plugin. You can even split up this function from the MDT plugin and make it more generic as multiple vendors support Google ProtoBuff metrics. It will allow Telegraf to consume Telemetry in a compact manor for multiple vendors which would be awsome for a lot of people in the community. It think there are some examples on how to do this with Go in the bigmuddypipeline from Cisco which we can work with.

**Comment by deanasheehan** [comment]
Something like that @neeles83 
I'm unclear how strong the adherence is to the Open Telemetry standards between Cisco / Juniper and Huawei and it might mean there are some other nuances that cause some vendor specific code paths. However, for the Key Value piece versus Dynamic Protobuf {field index, value}  unmarshalling it (theoretically) should be very generic and driven by .proto files place and reference from a generic streaming telemetry plugin.

**Comment by danielnelson** [comment]
I'd love to add support for loading the descriptors from file, but is this something that the Go protobuf library supports doing at runtime?

**Comment by deanasheehan** [comment]
@danielnelson - the approach is to (and you can do this on the fly from within GoLang, receive a .proo file and then to protobuf compiler to convert the .proto to a GPB definition of the .proto - called a filedescriptor, you can then (and I have done this) write code that walks the file descriptor definition of the message format and unpacks the wire format data dynamically. You can, if wanted, convert the .proto to filedescriptor outside of the Telegraf/Go binary and present the preconverted .proto->filedescriptor file.

This is also (relates to anyway) how Google themselves propose people make use of GPB to self-describe GPB https://developers.google.com/protocol-buffers/docs/techniques#self-description

In situations where you are effectively transcoding from one format to another - rather than making technical use of the data through prior knowledge or expectations of the data - then a dynamic approach that walks the wire format as driven by the file descriptor to then apply standard rules for conversion to the output format works.

For Compact GPB the Compact Protobufs are replacements for what is otherwise {name,value} pairs where name is replaced by field index on the wire (varint). Walking this dynamically and turning it into LineProtocol 'tag|field'=value is relatively trivial.

**Comment by neeles83** [comment]
@danielnelson and  @deanasheehan, I concure with Deanasheehan in that it works just like a descriptor in a sense just like MIB's are used for SNMP. The Cisco MDT you have now should also work for other products which used the uncompiled versions of Google Proto Buffers. 

So in a sense it not a Cisco Model Driven Telemetry but just Model Driven Telemetry with self desribing kv-pairs or through JSON. Both have a bigger overhead than the Compact mode which uses the .proto files as descriptor to decode the messages. 

But then again that is my understanding and I'm not a programmer.

**Comment by powersj** [comment]
@neeles83 sounds like the request seems reasonable, however if we were to look into this, where could we find sample protobuf Cisco files that we could use for development? Would these be possible with the Cisco simulator as well? The big concern with taking on changes to the cisco plugin is our lack of access and knowledge to hardware and this ecosystem.
