### ISSUE TITLE
Execd Aggregators

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#7217]
Request for aggregator capabilities of the [execD](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/execd) plugin.

**Comment by opengamer29** [comment]
Why this feature request has been closed? I can be helpful.

**Comment by sjwang90** [comment]
We recently added [starlark aggregator](https://github.com/influxdata/telegraf/tree/master/plugins/aggregators/starlark) capabilities in 1.21 that could cover your use case of using Execd.

**Comment by opengamer29** [comment]
Thanks, it really can solve my issue. But I've slightly modified telegraf histogram plugin and with starlark aggregator, I need totally rewrite it :(

**Comment by sjwang90** [comment]
@opengamer29 Can you provide more information about your use case? We haven't had that many requests for an execd aggregator. We were wondering if it was possible to achieve what you're trying to do with the Execd input possibly.

**Comment by opengamer29** [comment]
We use telegraf to collect mobile performance metrics. In details, we use inputs.socket_listener to collect data from devices, aggregators.histogram to create histograms (there are a lot of data and it's expensive save all of them without aggregations) and outputs.prometheus_client to scrap all metrics by VictoriaMetrics.

**Comment by opengamer29** [comment]
We use telegraf to collect mobile performance metrics. In detail, we use `inputs.socket_listener` to collect data from devices, `aggregators.histogram` to create histograms (there are a lot of data and it's expensive to save them all without aggregations) and `outputs.prometheus_client` to scrap all metrics by VictoriaMetrics.

And we have more than 80 000 lines in `prometheus_client` `/metrics` url (and will be more). It happens because of this issue https://github.com/influxdata/telegraf/issues/10043 (`aggregators.histogram` always push all metrics to output and output `expiration_interval` doesn't work, it calculates all metrics as new).

So, to try to fix this issue I've added an `expiration_interval` to aggregators.histogram and want to test this approach and understand if this approach will work and should I create PR to your repository, or maybe it will be only our local approach.
With Execd and Shim and can be much easier.

**Comment by opengamer29** [comment]
@sjwang90 That's what I'm talking about - https://github.com/influxdata/telegraf/pull/10515 Adding such capabilities to the already existing codebase with execd is simpler rather than rewriting it in starlark.
