### ISSUE TITLE
telegraf hang state issue. 

### ISSUE THREAD

**Issue by rguptarg** [influxdata/telegraf#7252]
Hi Team,

We have faced Server hang/slowness issue on Linux server, after troubleshooting and we got below log :-

$ cat var/log/messages-20200329 | grep blocked
Mar 29 04:12:40 CMPGN_SRVR_02 kernel: INFO: task telegraf:3993 blocked for more than 120 seconds.
Mar 29 04:14:40 CMPGN_SRVR_02 kernel: INFO: task telegraf:3993 blocked for more than 120 seconds.

OS version Red Hat Enterprise Linux server release 6.6
Telegraf version  telegraf 1.9

Also I have upgraded the telegraf version from 1.9 to 1.12

**Comment by ssoroka** [comment]
[looks](https://helpful.knobs-dials.com/index.php/INFO:_task_blocked_for_more_than_120_seconds.) like [this](https://www.blackmoreops.com/2014/09/22/linux-kernel-panic-issue-fix-hung_task_timeout_secs-blocked-120-seconds-problem/) issue is [related](https://access.redhat.com/solutions/31453) to the system consuming all available memory and writing to swap, and that IO consumes everything. I think the typical scenario here is to disable the swap so you instead get out of memory errors rather than punting the issue to disk, which is not equipped to handle it.

**Comment by danielnelson** [comment]
I've seen this myself when dealing with bad hardware and kernel bugs.  Would be interesting to see the stack trace though, while Telegraf is blocked if you kill it with SIGQUIT it should print out the stack trace to its log.
