### ISSUE TITLE
Feature Request: Allow collecting and sending metrics immediately on start

### ISSUE THREAD

**Issue by concreted** [influxdata/telegraf#7293]
### Proposal:

Add a configuration option to perform one round of metrics collection + flush to InfluxDB immediately on start. 

### Current behavior:

Current observed behavior is that on startup, Telegraf will wait for the full flush interval before sending metrics. 

### Desired behavior:

If configured to do so, Telegraf will collect metrics from all enabled plugins and flush metrics immediately on start.

### Use case: 
This is useful when wanting to ensure that hosts will quickly send metrics when they come online and have a longer flush interval set. For our use case we are working with a network provider that will not certify devices for use on the network that communicate more than once every ~30m while idle, but is OK with an initial burst of communication on startup. With the current behavior we will not see metrics for those devices until ~30m after they are first powered on.

**Comment by ssoroka** [comment]
I just wanted to confirm that you're using a low `interval` and a high `flush_interval`? With this setup you're expecting only the additional flush, and that the metrics will already have been collected.

**Comment by ssoroka** [comment]
I'm also curious if you use the round_interval setting, as that has some effect on when the first flush is.

**Comment by concreted** [comment]
@ssoroka In my current setup I'm using an `interval` of 10m and `flush_interval` of 28m. I don't mind lowering the `interval`, but for my use case it would be best if it actually collected metrics immediately on start also, and then flushed. That way we can get a fresh set of metrics immediately on boot.

**Comment by concreted** [comment]
Also we're not using the `round_interval` setting for this use case. To clarify though, if we had `round_interval` turned on and `interval` set to `12m` for example, would it do the colleciton at `X:00, X:12, X:24, X:36, X:48`? What would happen if 60 is not divisible by `interval`?

**Comment by ssoroka** [comment]
Correct, if you used it with 12m you'd get metrics every 12m on minute 0, 12, 24, 36, 48. If it's not divisible by 60 it would still collect on the round_interval requested, it just wouldn't be cyclic for one hour. eg 24m would be:
```00:00
00:24
00:48
01:12
01:36
02:00```

**Comment by ssoroka** [comment]
Ok so I found out that metrics are _collected_ right away on start (as long as you're not using the round_interval, then it's on the round interval exactly). It's the _flushing_ that doesn't happen until the flush interval (30m in your case). There's another issue open that–if resolved–might solve this for you. [Option to flush buffer on request #5120](https://github.com/influxdata/telegraf/issues/5120). What do you think?

**Comment by concreted** [comment]
Gotcha, that looks like it could work - would the idea be that we would have to send a signal from our code -> Telegraf to trigger a flush? Or that Telegraf could use the 'flush-buffer-on-request' hook internally to cause a flush after first collection? 

Ideally we'd like Telegraf to handle figuring out when the first set of metrics is collected and flush automatically then - if that aligns with the general use case.

**Comment by ssoroka** [comment]
Yeah, correct, the idea is you would start Telegraf, give it enough time to collect the metrics (say 1 minute or whatever is appropriate), and then send a flush signal to the app, probably SIGUSR1 or something. Part of the problem is that we don't know when the first round of metrics are collected successfully, either. Definitely the output plugins don't know, but even the agent–which has an overview of everything–would have a hard time figuring this out for a couple of reasons:
- Service inputs can have their own metric reporting schedules
- Gather inputs can take a long time to respond, and maybe not respond right away
- it's not clear how many metrics is "all of them", since inputs can return [0..n] metrics.

I think potentially this could be improved in the future, but at the moment I think Telegraf has less context about how long it needs to wait for inputs than you would. That might seem slightly pedantic, because I would expect 99% of inputs to finish within 1-2 seconds of the collection being requested, but that's definitely not always the case, and it feels like putting this into Telegraf would be offering some sort of guarantee that this would or should not miss any metrics being collected after the flush.

**Comment by ssoroka** [comment]
FYI https://github.com/influxdata/telegraf/issues/5120 has been merged now, so in master it'll respond to SIGUSR1 with a flush.

**Comment by ssoroka** [comment]
Hey @concreted, I'm going to close this for now since you can approximate the solution you want with SIGUSR1 signals in master now. Let us know if you need anything else or run into any issues.

Thanks!

**Comment by lucassardois** [comment]
I'm also looking for this feature. My use case is fetching an API every 3 hours because of limit rate. But I also want Telegraf to fetch it at the start because other services need the data *right away*.

**Comment by pkolmann** [comment]
@lucassardois have you found a solution to this problem? I am facing this right now as well....

I have posted also a question in the forum as suggested above: https://community.influxdata.com/t/trigger-input-on-startup-as-well-as-long-interval/58335

**Comment by pkolmann** [comment]
Setting `round_interval = false` as suggested in  https://github.com/influxdata/telegraf/issues/15414#issuecomment-2137769582 solved the issue for me.
