### ISSUE TITLE
CentOS 5 repo checksum error

### ISSUE THREAD

**Issue by cheribral** [influxdata/telegraf#734]
Our centos 5 boxes are complaining about the yum repo database checksums.  If I had to guess, I'd say that createrepo was run without '-s sha'.

The exact error is:

https://repos.influxdata.com/rhel/5/x86_64/stable/repodata/d06009220803dc69930a83938da0ca0f83a8e55dd8171d83bcea80bb82e11b84-primary.sqlite.bz2: [Errno -3] Error performing checksum
Trying other mirror.
influx_repo/primary_db                                  | 7.3 kB     00:00     
https://repos.influxdata.com/rhel/5/x86_64/stable/repodata/d06009220803dc69930a83938da0ca0f83a8e55dd8171d83bcea80bb82e11b84-primary.sqlite.bz2: [Errno -3] Error performing checksum
Trying other mirror.
Error: failure: repodata/d06009220803dc69930a83938da0ca0f83a8e55dd8171d83bcea80bb82e11b84-primary.sqlite.bz2 from influx_repo: [Errno 256] No more mirrors to try.

**Comment by rossmcdonald** [comment]
@cheribral Do you get the same error if you use the `nightly` branch of the repository? The link is: `https://repos.influxdata.com/rhel/5/x86_64/nightly`

**Comment by cheribral** [comment]
The error seems to have changed.  I tried both the old and the new URL, and I am now getting:
error: rpmts_HdrFromFdno: Header V4 RSA/SHA1 signature: BAD, key ID 2582e0c5

**Comment by rossmcdonald** [comment]
@cheribral Sorry for the delay. Can you retry the repo? I have changed the GPG settings when signing the packages, so I believe this should be resolved.

**Comment by rossmcdonald** [comment]
@cheribral After researching this issue a bit more, it turns out that the version of RPM used in CentOS 5 cannot accept signing keys larger than 2048 bits. We are using a 4096 bit key, so I'm not sure we'll ever be able to support CentOS/RHEL 5. 

Sorry for the inconvenience. I have gone ahead and removed the `5` and `5server` directories from repository to avoid any further confusion. If you absolutely need to have packages installed on CentOS 5, I would recommend verifying the package signatures on another machine, and then installing the RPM's manually.

**Comment by cheribral** [comment]
@rossmcdonald sorry I missed those last couple of updates.  Thanks for looking into it!
