### ISSUE TITLE
[inputs/statsd] Make timing fields not mandatory

### ISSUE THREAD

**Issue by kedare** [influxdata/telegraf#7361]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:

Currently, there are no way to disable the metrics to be pulled with predefined fields like sttdev, upper, lower, which are I think useless as InfluxDB can generate this data on the fly (and they may not be needed anyway).
There should be a configuration flag to disable those and only push the desired data to the output

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/statsd/statsd.go#L257

### Current behavior:
Instead of just pushing the value, many fields like sttdev, mean, sum, etc.. are always pushed to the outputs, no way to disable them

### Desired behavior:
A configured option to be able to just push the "value" (or other fields defined in the templates)

### Use case: 

To avoid pushing data we don't need to the outputs.

**Comment by danielnelson** [comment]
Statsd values are always aggregated, if you want to send an individual value it isn't possible but a gauge instead of a timer would be the closest metric type.  You could use [metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering), in particular fieldpass/fielddrop, to remove the unwanted fields.

If you are really interested in getting every timing event, I recommend switching the application over to line protocol or another format more suitable for events.
