### ISSUE TITLE
[Feature Request] prometheus input to scrape not only kubernetes pods but also kubernetes services

### ISSUE THREAD

**Issue by nsteinmetz** [influxdata/telegraf#7368]
### Proposal:

prometheus input plugin should also watch for prometheus annotation on service side and not only pod side.

### Current behavior:

As of now, prometheus input in a kubernetes context has some autodiscovery features on pods only if there are prometheus annotations.

### Use case: 

If you deploy some components like [bitnami/postgresql](https://github.com/bitnami/charts/tree/master/bitnami/postgresql#parameters), you will notice that prometheus annotations are on service side and not on pod side - see `metrics.service.annotations` property.

As of now, I have to maintain a list of `urls` or `kubernetes_services` which are not dynamic and so not a really cloud native way to get metrics.

**Comment by powersj** [comment]
@wojciechka is this something that the helm charts could do? Or is this something that also needs to get implemented in Telegraf's prometheus plugin first as well?

**Comment by wojciechka** [comment]
As for the original request, the annotations must be at a PodSpec level specifically and most helm charts provide a way to add such annotations - they must be provided as values for the template. If a template does not provide such functionality, I recommend you request it from the author of the template.

I believe bitnami templates all provide a way to add pod level annotations. This specific allows doing this via `primary.podAnnotations` and `readReplicas.podAnnotations`.

ps. I believe this should be an issue for [influxdata/telegraf-operator](https://github.com/influxdata/telegraf-operator) rather than telegraf - telegraf itself does not provide a way to scrape Kubernetes workloads.

**Comment by powersj** [comment]
Thanks for taking a look wojciechka! I am going to go ahead and close this and encourage the reporter to file this under https://github.com/influxdata/telegraf-operator
