### ISSUE TITLE
influxdb output (v1) should gzip by default

### ISSUE THREAD

**Issue by ssoroka** [influxdata/telegraf#7397]
should default to `content_encoding = "gzip"` for influxdb

### Relevant telegraf.conf:

```toml
[[outputs.influxdb]]
  ## HTTP Content-Encoding for write request body, can be set to "gzip" to
  ## compress body or "identity" to apply no encoding.
  # content_encoding = "identity"
```

### System info:

Telegraf 1.14

### Expected behavior:

gzip compression by default

### Actual behavior:

no data compression

### Additional info:

Need to make sure this won't break any old InfluxDB servers; but as far as I can tell it's not going to be an issue for any version of InfluxDB.

**Comment by timhallinflux** [comment]
any reason this wouldn't be the default for v2 as well?

**Comment by danielnelson** [comment]
On v2 gzip is the default.  If we make this change, with the default settings network bandwidth will be reduced substantially but it will most likely increase CPU requirements for the database.

**Comment by ssoroka** [comment]
I suspect the cpu cost of uncompressing a gzip body is so minimal that it won't have a measurable impact, yet it has a huge impact on the throughput rate of metrics; a highly visible negative performance when it is disabled.

**Comment by e-dard** [comment]
I don't have a good feeling on whether this would be a good idea from a Cloud 1 perspective, but that is something to think about.

My initial feeling on this is that regardless of whether this is enabled or not InfluxDB is processing the same amount of metrics. 

With it enabled InfluxDB has to do more work to decompress the payload, but the client can send metrics in a smaller payload and more quickly. If metrics are arriving more quickly after a sampling interval, and they're now more expensive to process I wonder if that could have some impact in some cases..

If you put to one side the reduction in network, what real benefit is there to a user in pushing their (let's say) 10 second interval metrics slightly quicker to the DB? 

> I suspect the cpu cost of uncompressing a gzip body is so minimal that it won't have a measurable impact

I have seen InfluxDB profiles where gzip is showing up quite heavily in the profiles.  I can't recall whether that was due to the Go implementation of the gzip decoder, or the volume of writes on those clusters in those cases.

**Comment by ssoroka** [comment]
> If you put to one side the reduction in network, what real benefit is there to a user in pushing their (let's say) 10 second interval metrics slightly quicker to the DB?

Zero, but it's not latency we're trying to improve, it's throughput. This came out of a real case from a user who moved from a local influx server to a cloud server and couldn't handle the same workload. When investigating if the server was overloaded, it was found to be effectively near zero cpu utilization. The bottleneck was the network pipe. Enabled gzip and (if my memory serves) we saw something like a 30x reduction in size.

**Comment by asgs** [comment]
@ssoroka is the compression talked about here applicable to responses generated and sent by InfluxDB to the client?
