### ISSUE TITLE
invalid escape sequence '\'' in inputs.prometheus

### ISSUE THREAD

**Issue by browcio** [influxdata/telegraf#7423]
### Relevant telegraf.conf:
```
[[inputs.prometheus]]
    urls = ["http://localhost:9363/metrics"]
```

### System info:
ubuntu 18.04
telegraf 1.12.6 and 1.14.1

### Steps to reproduce:
Scrape metrics containing 
```
\'
```

### Expected behavior:
Endpoint is scraped without error

### Actual behavior:
```
E! [inputs.prometheus] Error in plugin: error reading metrics for http://localhost:9363/metrics: reading text format failed: text format parsing error in line 13: invalid escape sequence '\''
```

### Additional info:
I am trying to scrape metrics from Clickhouse prometheus endpoint. line that breaks telegraf:
```
# HELP ClickHouseProfileEvents_Seek Number of times the \'lseek\' function was called.
```

**Comment by danielnelson** [comment]
I believe this error is coming from the official Prometheus parser which we use for parsing:
https://github.com/prometheus/common/blob/master/expfmt/text_parse.go#L561.  This seems to indicate that the character sequence is indeed not allowed.

I would report this to the author of the Clickhouse Prometheus exporter so that it can be fixed in the right spot.

You may be able to use our [clickhouse](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/clickhouse#clickhouse-input-plugin) input plugin in the meantime.

I'm going to close this issue since I don't think we need to schedule any work in Telegraf, but it would be great if you could link the upstream issue you open here for others to reference.
