### ISSUE TITLE
Centralized Telegraf Manager

### ISSUE THREAD

**Issue by raider111111** [influxdata/telegraf#7478]
## Feature Request
A centralized way to monitor the health of the agents as well as deploy new configuration files to a server or groups of servers remotely. 
Opening a feature request kicks off a discussion.

### Proposal:
A centralized way to monitor the health of the agents as well as deploy new configuration files to a server or groups of servers remotely. 
### Current behavior:
Telegraf appears to need to be monitored using a separate tool, like Wavefront and the configurations have to deployed using a desired state tool like Puppet.
### Desired behavior:
A centralized way to monitor the health of the agents as well as deploy new configuration files to a server or groups of servers remotely. 
### Use case: 
The ability to monitor the health of the Telegraf agents is important.
The ability to deploy new configuration files to thousands of servers would be extremely useful in our environment.

**Comment by ssoroka** [comment]
Hey @raider111111, I appreciate you raising the issue as it mirrors some discussions we've been having on the team.

I might like to split off the "monitoring health of agents" conversation to something separate, as Telegraf agents already have an `inputs.internal` plugin that Telegraf can use to self-report health statistics. Also check out the [Telegraf community template](https://github.com/influxdata/community-templates/tree/master/telegraf) in that regard. 

For the config server, we're thinking something like a Telegraf-config service that can store and manage a central config repository, storing config templates for certain types of machines, then maybe the machines would pull the config type they want, using local environment variables for some settings, and start Telegraf.
some questions that come from this:
- are there any other services out there that already provide a similar service that we should consider using, integrating with, or building on?
- Would agents periodically check for or subscribe to new configs?

I'd love to hear your thoughts on what you think and what you currently use for configuration management.

**Comment by M0rdecay** [comment]
@ssoroka, how about integration with zookeeper?

**Comment by danielnelson** [comment]
I've been thinking there are two separate pieces: key/value stores for service-discovery/secrets and full config storage.  With zookeeper/consul/etcd you may want to pull certain variable and use them in an existing configuration.  There is also configuration storage where you store the full configs, plugin configs, or configuration templates.  These two sources of information need to be combined in order to produce the final configuration.

Right now we have analogues of these two information sources: full config is local only now and can be split in the config-directory.  For key/value lookups we have the environment variable support in the config file.  I think we would probably keep it as a two step process, this way you can mix and match where the configuration is kept and where the variables are kept.

So for zookeeper, may support a way of grabbing variables and using them in the configuration.  Maybe something along the lines of:
```toml
[[variables.zookeeper]]
  # zookeeper connection settings

[[inputs.http]]
  urls = ["$zookeeper{some_key}"]
```

Not sure how we would do advanced tasks such as producing multiple plugins from a list of keys.  I'm not sold on introducing an official template format built-in to Telegraf.  It may make more sense to layer this on the outside.

**Comment by M0rdecay** [comment]
@raider111111 I would like to share the solution for monitoring the status of agents that we use in our environment.
We did this:
Each telegraph in its configuration has sections:
```toml
[[inputs.internal]]

[[inputs.procstat]]
  systemd_unit = "telegraf.service"
  namepass = [ "procstat_lookup" ]
  [inputs.procstat.tags]
    appl = "telegraf"
```

Thanks to them, each agent marks itself in the **procstat_lookup** measurement, which reports its status and the host where it is located. Then, we display their status on the Grafana dashboard, where the lack of data is interpreted as a problem with the agent.
Query: `SELECT mean("running") FROM "$ret_policy"."procstat_lookup" WHERE "host" =~ /^$hosts$/ AND "appl" = 'telegraf' AND $timeFilter GROUP BY "host", time($coll_interval) fill(0)`

This is not an ideal solution for a number of reasons, but it works. Hope you find this helpful.
![Example](https://user-images.githubusercontent.com/50422107/81338779-d5e11600-90b5-11ea-92aa-449278cfa5cb.png)

**Comment by M0rdecay** [comment]
@danielnelson, didn’t you think about downloading configurations to a directory defined through `--config-directory`, and then sending SIGHUP to yourself? Some of our colleagues use a telegraf fork with this behavior and this seems to work well.

**Comment by danielnelson** [comment]
Whats different in the fork?  Does it add a new plugin that downloads files and sends SIGHUP?  You could definitely do this without a fork using the execd input.  Another popular tool for doing this is [confd](https://github.com/kelseyhightower/confd).

**Comment by M0rdecay** [comment]
Thanks for the idea, I'll try to do it the way you suggest!

**Comment by raider111111** [comment]
Thanks @M0rdecay  and @danielnelson !!

**Comment by pberlowski** [comment]
@raider111111 What we do is use a repo with config setup and an ansible playbook to install the agents to our inventory. We utilize Ansible AWX to maintain the state of all the agents by running the playbook multiple times a day. We provide sane defaults to what should be monitored, but also allow "extras" in our inventory. When a target is configured with an extra - then it is deployed with an additional conf.d fragment. We have several thousand of agents deployed in this manner.

With regards to state monitoring, we only care if an agent is not submitting as it should. We have gloabl alerts on `internal.write.metrics_written` which alerts both at drops and at "no data" events to let us know that an agent is out (happens extremely rarely). We don't care for seeing all the agents as greeen otherwise. No news is good news.

Does that help?

**Comment by ssoroka** [comment]
This is a great way to do it, and I would follow @pberlowski 's practice of monitoring `internal.write.metrics_written` as a best practice. Some other things to watch: metrics_dropped, errors, and the write buffer size. You can see an example of this in my [Telegraf dashboard template](https://github.com/influxdata/community-templates/tree/master/telegraf).

**Comment by sjwang90** [comment]
Closing. See discussion in #272

**Comment by raider111111** [comment]
Thanks @ssoroka, @pberlowski! 

Yes, this is what we're currently doing.
The thing we wanted the most was a way to deploy configurations centrally.
I spoke to InfluxData and they suggest using Ansible, though we don't currently have that available in our enterprise.

**Comment by pberlowski** [comment]
@raider111111 I can walk you through what we have for the centralized Telegraf management if you want to connect. I'll put a blog post on the topic down on my todo list as well, so I can share this knowledge and start a discussion.

**Comment by ssoroka** [comment]
Ansible is a push model, and I'd be interested in more of a central config repository for Telegraf itself, though as far as individual solutions it's just whatever fits your organization the best. 

I'm curious if anyone is using Kubernetes to deploy Telegraf configured along side other service pods?

**Comment by pberlowski** [comment]
We're just finalizing an operator for Kubernetes to install "metrics" custom resources for our internal customers. Our main driver is that we're looking to maintain the control over the agent (to allow version and config updates) but we want to shard it across namespaces.

**Comment by 00willo** [comment]
@pberlowski Did you end up writing up a blog post on this?  I wasn't able to track down a blog from your github profile. I would be very much interested in what you were able to get done in that space.  Thanks.
