### ISSUE TITLE
Feature request for cloudwatch metrics collection with time_range

### ISSUE THREAD

**Issue by s009255** [influxdata/telegraf#7544]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
In cloudwatch input, i can set only period, delay and interval in configuration
So, the Starttime is determined by period.
But I want to change Starttime with another option.
So, I want to add time_range option.

### Current behavior:
[[inputs.cloudwatch]]
period  = '1m'
delay = '2m'

If I set like this, Endtime is "now-2m" and Starttime is "now-3m"

### Desired behavior:
[[inputs.cloudwatch]]
period  = '1m'
delay = '2m'
time_range= '10m'

If I set like this, Endtime is "now-2m" and Starttime is "now-12m"

### Use case: 
I want to get short period, but long term data points with one batch job.
So, I have to change Starttime regardless of the period option.

**Comment by danielnelson** [comment]
While the first time the cloudwatch input runs it grabs a single period, on subsequent calls it should grab all periods since the previous collection.  This means that you can set `interval` just like the `time_range` option and it should work in the desired manner.
```toml
[[inputs.cloudwatch]]
  period = '1m'
  delay = '2m'
  interval= '10m'
```

It has been awhile since I tested this, so let us know if you run into any issues.
