### ISSUE TITLE
Kafka consumer input (and others?) cannot specify timestamp precision

### ISSUE THREAD

**Issue by hackery** [influxdata/telegraf#7625]
@ssoroka per Slack

In [Influx line protocol](https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_reference) the default timestamp precision is nanoseconds. The [Influx write API](https://docs.influxdata.com/influxdb/v1.8/tools/api/#write-http-endpoint) includes a `precision` parameter to declare the precision of incoming metrics (and the docs specifically say that "using the least precise precision possible as this can result in significant improvements in compression").

In Telegraf's [Influxdb_listener input](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/influxdb_listener), the precision parameter is honoured as expected, [calling](https://github.com/influxdata/telegraf/blob/702946b5cfba8f91b3f8fb6602922bd26a4cd5b9/plugins/inputs/influxdb_listener/influxdb_listener.go#L282-L285) into SetTimePrecision in parsers/influx.

The Kafka consumer input does not appear to have any way to declare the precision of incoming metrics, and the parser does not handle precision units in the input either (in at least 1.13).

This probably affects other inputs - UDP for example?

**Comment by ssoroka** [comment]
cc @danielnelson for thoughts on how to address this

**Comment by danielnelson** [comment]
The `precision` option to the InfluxDB HTTP API is a special feature of that API, I don't consider it to be a part of Line Protocol proper.  While we do take pains to support this feature in the `influxdb_listener`, since this input attempts to be a drop in replacement for the InfluxDB API, we don't support it in any other plugins I don't recommend using it ever.

The primary advantage of line protocol is that all information needed to parse is included on each line.  When you use the `precision` option, it is no longer possible to interpret the data from the line protocol alone, you must always keep track of and communicate the timestamp precision along with it.  If, on the other hand, you always use nanosecond precision it will ensure that line protocol can be read from any source without needing additional information, and you will minimize issues writing data with the wrong timestamp.

> using the least precise precision possible as this can result in significant improvements in compression

While it is faster to send points at times rounded to precision larger than nanoseconds, it is not true that using the `precision` option to the HTTP API is helpful.  The speed/storage improvement with InfluxDB have to do with having even timestamps and not the length of the timestamp in line protocol.  It is virtual the same speed to write a timestamp like `1591205949000000000` vs `1591205949` thanks to compression.  When using a format without compression supported, the difference is very small.

So, I highly recommend ignoring this option to the InfluxDB API and just always using nanosecond precision in all plugins.  I'm going to close the issue since I don't think we would add support in other plugins, but if you have follow up questions I'll still see your comments.
