### ISSUE TITLE
Freeze dates & release dates

### ISSUE THREAD

**Issue by sunkuranganath** [influxdata/telegraf#7635]
Hello Maintainers,
Being new to this community, our team is looking to contribute few plugins to the codebase to be considered for upcoming releases. Going through wiki & milestones, there isnt clarity on release process. 
Few questions to better help us plan our work:
- based on past releases, would it be right to assume 1.15 be in June while 1.16 be sometime end of september/early October?
- Is there a code freeze/feature freeze date that one should be aware of to ensure new feature requests are submitted adequately ahead of time

Your feedback will be helpful. Thanks

**Comment by danielnelson** [comment]
> 1.15 be in June while 1.16 be sometime end of september/early October

Yes, we release approximately every 3 months, so yes I expect 1.15 will be near the end of June/early July.  Expect the milestone to be updated with a more concrete data in the next few weeks.

> Is there a code freeze/feature freeze date that one should be aware of to ensure new feature requests are submitted adequately ahead of time

Due to the number of pull requests we receive it isn't possible for us to process all of them.  Because of this pull requests are processed on based on the amount of effort needed and the perceived importance/value of the change.  This means that some pull requests that we would like to incorporate have to wait indefinitely.

The pull request backlog is one of the reasons we recently added the [execd](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/execd) input.  Most plugins can be written to use it, perhaps utilizing the [shim](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/execd/shim), to ease running plugins that are not yet merged into the official release.

**Comment by sunkuranganath** [comment]
Great, thanks for the fast feedback. Will assume releases will be every 3 months approx.

Since there is no code freeze date as such, is it a right assumption that whatever makes into master would be considered to be in next release?
That means we have to try contributing a PR as early as possible to a release and work towards getting it merged.

**Comment by danielnelson** [comment]
> Since there is no code freeze date as such, is it a right assumption that whatever makes into master would be considered to be in next release?

We will create a release branch, `release-1.15`, approximately 2 weeks before the release and tag a release candidate.  Everything in master up until then will be included in the release.

Sooner never hurts on a pull request.

**Comment by sunkuranganath** [comment]
Great, thanks. Will watch out for release branch.
