### ISSUE TITLE
How do I select from InfluxDB 2.0 the list of hosts??

### ISSUE THREAD

**Issue by dummy-andra** [influxdata/telegraf#7813]
I want to create a variable in grafana that displays a list with all the hosts. What should I put in the Query caset?
I am using telegraf+influxdb 2.0 + grafana.

![IMG_20200710_154853](https://user-images.githubusercontent.com/37038210/87159031-547e4d80-c2c9-11ea-808c-b068b92d3abc.jpg)

Influxdb 2.0
Telegraf
Grafana

Thanks

**Comment by danielnelson** [comment]
The [Flux query to list tag values](https://v2.docs.influxdata.com/v2.0/query-data/flux/explore-schema/#list-tag-values) is:
```js
import "influxdata/influxdb/v1"

v1.tagValues(bucket: "example-bucket", tag: "example-tag")
```

I gave this a shot in the new Grafana 7.1.0 beta2, but no matter the query I received an `unauthorized access` error.  This seems like an issue with the Grafana beta, as I can otherwise query without issue.  Would you be able to ask this question at the [Grafana community site](https://community.grafana.com/)?

I'm going to close this issue since it is not something we would address on Telegraf, but once you are able to get an answer it could probably be added to our [Grafana documentation](https://v2.docs.influxdata.com/v2.0/visualize-data/other-tools/grafana/).  Instructions for opening new issues are at the bottom of the page.

**Comment by dummy-andra** [comment]
I used the following flux: 
import "influxdata/influxdb/v1"

```
v1.tagValues(
  bucket: "bucket",
  tag: "host"
)

```
But with no results.

Thanks for replying, I was wondering if it is something with Grafana.

Have a wonderful weekend 🌞

**Comment by dummy-andra** [comment]
I used the following flux query, but with no results:

![IMG-20200711-WA0003](https://user-images.githubusercontent.com/37038210/87218809-db313a00-c35e-11ea-8dd0-2f40adccd1b8.jpg)


Additional info: if I put the same query in a Grafana panel, it displays the output:
![IMG-20200711-WA0002](https://user-images.githubusercontent.com/37038210/87218824-f9973580-c35e-11ea-8c41-ca7a1e3b1d9a.jpg)

I am using:
Influxdb version 2.0 beta
Telegraf version 1.14
Grafana version 7.05

**Comment by sjwang90** [comment]
Hey @dummy-andra, as we mentioned this isn't a Telegraf problem so won't be addressed here.  Feel free to drop into our [Community Slack](www.influxdata.com/slack) and post your issue in the #flux channel.
