### ISSUE TITLE
input-redis, used_memory_dataset_perc or used_memory_peak_perc should be an independent monitoring metric_name rather than a dimension label

### ISSUE THREAD

**Issue by fcddk** [influxdata/telegraf#7827]
## Feature Request

input-redis, used_memory_dataset_perc or used_memory_peak_perc should be an independent monitoring metric_name rather than a dimension label
input redis:

### Proposal:
add metric for used_memory_dataset_perc and used_memory_peak_perc
### Current behavior:
eg:  redis_uptime

redis_uptime{aof_last_bgrewrite_status="ok",aof_last_write_status="ok",controller="harbor-redis-redis4-ha-server",exported_host="harbor-redis-redis4-ha-server-0",host="mgt06",instance="harbor-redis-redis4-ha-server-0:9126",job="sidecar",kubernetes_namespace="harbor",maxmemory_policy="noeviction",port="6379",rdb_last_bgsave_status="ok",redis_version="4.0.14",replication_role="master",server="127.0.0.1",used_memory_dataset_perc="71.99%",used_memory_peak_perc="92.13%"}
### Desired behavior:
redis_uptime{aof_last_bgrewrite_status="ok",aof_last_write_status="ok",controller="harbor-redis-redis4-ha-server",exported_host="harbor-redis-redis4-ha-server-0",host="mgt06",instance="harbor-redis-redis4-ha-server-0:9126",job="sidecar",kubernetes_namespace="harbor",maxmemory_policy="noeviction",port="6379",rdb_last_bgsave_status="ok",redis_version="4.0.14",replication_role="master",server="127.0.0.1"}
redis_used_memory_dataset_perc{aof_last_bgrewrite_status="ok",aof_last_write_status="ok",controller="harbor-redis-redis4-ha-server",exported_host="harbor-redis-redis4-ha-server-0",host="mgt06",instance="harbor-redis-redis4-ha-server-0:9126",job="sidecar",kubernetes_namespace="harbor",maxmemory_policy="noeviction",port="6379",rdb_last_bgsave_status="ok",redis_version="4.0.14",replication_role="master",server="127.0.0.1"}
redis_used_memory_peak_perc{aof_last_bgrewrite_status="ok",aof_last_write_status="ok",controller="harbor-redis-redis4-ha-server",exported_host="harbor-redis-redis4-ha-server-0",host="mgt06",instance="harbor-redis-redis4-ha-server-0:9126",job="sidecar",kubernetes_namespace="harbor",maxmemory_policy="noeviction",port="6379",rdb_last_bgsave_status="ok",redis_version="4.0.14",replication_role="master",server="127.0.0.1"}
### Use case: 
I don’t know what considerations were based on the design of the redis plug-in, but for me, all metric and labels in the world (prometheus) of k8s cluster monitoring should be positioning a monitoring object (or resource) Instead of using the monitored value as a label(used_memory_dataset_perc,used_memory_peak_perc)

**Comment by ssoroka** [comment]
I don't understand your _Desired behavior_ example. You don't actually list the % used values anywhere, and list `redis_used_memory_dataset_perc` twice. I assume you mean the second one is redis_used_memory_peak_perc.

I'm not inclined to think that following prometheus's example is the best practice here, and it would definitely be a lot of duplication in storage and transmission costs to do this. Typically properties of the same _resource_ end up in the same metric, with much better performance characteristics all around.

**Comment by fcddk** [comment]
Understand, but in prometheus monitoring practice such data is very unsuitable.

**Comment by danielnelson** [comment]
I'm guessing you have `string_as_label = true` (the default) on the prometheus output.  This causes string fields to be added to the labels, when this option is false the value is dropped instead since prometheus doesn't have a way to report a series of strings.  I recommend disabling this option and using processors to convert fields to tags if needed for some reason.  We may want to consider changing this default in 1.16 since it is a continual source of confusion.

The other bug here is that we are reporting this value as a string when it is numeric data, something is not working right in the parsing of the redis info data.  This input plugin ought to be changed to be more specific in what it gathers instead of attempting to guess what the data types.   Can you add the output of the `info all` command in redis?

In the future, it would be helpful if you also include the output in InfluxDB line protocol using the `file` output and `data_format = "influx"`.  I think this will make it much easier to understand the issue/request without clouding the issue with the quirks of the prometheus output.  It will probably be easier for you to debug as well if you check the output in it's native format.

**Comment by fcddk** [comment]
thanks!
 I haven't paid attention to this configuration before.
