### ISSUE TITLE
Enhancements to TopK processor

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#7925]
### Proposal:
Enhance the `processors.topk` for large scale performance improvements. 

### Current behavior:
Currently using plugin in combination with `inputs.tail` for aggregation
1. Cache all data into an interval
2. Do a sort
3. Take top K for each field
Time: O(nlogn)
Space: O(no)

### Desired behavior:
1. Use a heap (min heap)
2. Store the Top K in the min heap
3. Push the next metric into the heap if it's larger than the head
Time: O(nlogk) => O(n)
Space: O(k) => O(1)

### Use case: 
Works for current use case but concern on how it effectively it will scale in a large enterprise environment

**Comment by essobedo** [comment]
@sjwang90 Since this processor takes the top K of the buckets of metrics and not the top K of the metrics, unless I miss something obvious, I don't see how it is possible to get rid of the internal cache of metrics. The best we can do, is to use a heap when we sort the buckets of metrics which should not have a real impact on the overall scalability of the processor as the real scalability issue is more the internal cache of metrics. WDYT?

**Comment by sjwang90** [comment]
@essobedo Scalability is the main concern for the enhancements - the process you laid out is good with me. Since you mentioned the internal cache of metrics is the root problem of scalability and it is not possible to get rid of these this all sounds good. 

Not sure if @ssoroka had any feedback.

**Comment by powersj** [comment]
Haven't seen any actual direct issues or concerns with this processor any more. Going to close and we can revisit if someone has a detailed example.
