### ISSUE TITLE
Add flag to Telegraf run command to pass a token for retrieving configuration from separate Influx host

### ISSUE THREAD

**Issue by samhld** [influxdata/telegraf#8027]
## Feature Request

Add a flag to the Telegraf run command to pass a token for the InfluxDB instance hosting the Telegraf configuration.  This would allow for Telegraf to get its token from a different instance than to which it is writing data.

Could look like `--config-host-token` or `--config-fetch-token` or `--config-token` (because it may be implicit that it's specific to fetching that config).  All together might look like:
```
telegraf -config <url/to/config> --config-fetch-token <fetch_token>
```

## Motivation

1) Could offer flexibility to use a token through another means than an environment variable or hard-coding it into the configuration file.
2) It's possible that some Telegraf instances may want to pull configuration from a local (or "on-site", in IoT and other "fog" model use cases) instance of InfluxDB but still write out to another instance, say Cloud.

**Comment by stephanie-engel** [comment]
After doing the initial research and attempting to create a proof of concept for this, it looks like this potential implementation should be part of a larger discussion.

Currently, it appears that `telegraf.go`(which contains the supported telegraf command line arguments) **doesn't** include commands that would overwrite values within `telegraf.conf`. This proposed feature seems to stray from how we currently use t`telegraf.go`. If we want to support setting the fetch token via the command line, we may want to consider other config settings that could also be set via the command line and then come up with an overall architectural solution.

At the moment, the use of environment variables seems like a great workaround - especially because the fetch token could just have a different name from "${INFLUX_TOKEN}" - such as "${INFLUX_FETCH_TOKEN}".

**Comment by samhld** [comment]
@stephanie-engel Thanks for looking into this!  The environment variable workaround would still not be available today though, correct?  Unless I'm misunderstanding?

How would Telegraf use `INFLUX_FETCH_TOKEN` to instantiate its configuration if not from the configuration file?  To be extra clear, the proposal is to allow for Telegraf to use a separate token to fetch its configuration.  The current support for environment variables (AFAIK) requires an instantiation of a configuration to begin with.  This token would, by definition, have to be used / called from outside of configuration, itself.

**Comment by stephanie-engel** [comment]
@samhld Ah ok, you're right. I was misunderstanding your request.

**Comment by reimda** [comment]
Closing since it's already possible to use separate tokens for fetching config and writing: https://github.com/influxdata/telegraf/pull/9290#issuecomment-1163580655
