### ISSUE TITLE
Unable to connect to SQL Server named instance

### ISSUE THREAD

**Issue by SQLPRODDBA** [influxdata/telegraf#8037]
Hi all,

I have few servers where hide instance is enabled on SQL Server named instances with non default SQL Server ports for security reasons. Those instances are not getting detected by telegraf. Below is the error I get in telegraf logs:

Error in plugin [inputs.sqlserver]: No instance matching 'INST1' returned from host 'svr1'

Below is how my telegraf config file looks like:

"Server=svr1;Port=1433;User Id=test;Password=1234;app name=telegraf;log=1;",
"Server=svr1\\INST1;Port=55555;User Id=test;Password=1234;app name=telegraf;log=1;"

Hide instance is enabled for only svr1\INST1 SQL Server instance. My browser service is working fine. Also, I am able to connect SQL Server using SSMS with the credentials specified in telegraf config. It looks like when hide instance is enabled SQL Server can't be connected through a browser service and explicit port should be specified to connect to SQL Server like svr1\INST1,55555. I tried that but it didn't work in telegraf. Is there a way to fix this issue?

**Comment by win32nipuh** [comment]
What about  "\\"? 

"Server=**svr1\\INST1**;Port=55555;User Id=test;Password=1234;app name=telegraf;log=1;"

**Comment by Trovalo** [comment]
Are you still having issues?

In general when using connection strings I sue the single quote in order to avoid character escaping, which is what you wrote in the previous comment.
ie:
```
'Server=svr1\INST1;Port=55555;User Id=test;Password=1234;app name=telegraf;log=1;'
```

Note that this does not allow to use environment variables inside the connection string.

About the issue itself, It's probably related to the library used to connect to SQL Server, [go-mssqldb](https://github.com/denisenkom/go-mssqldb), you can try to open the issue there and see if someone can answer to this problem.

**Comment by Trovalo** [comment]
@SQLPRODDBA did you solve this?

**Comment by sjwang90** [comment]
Closing this issue. @SQLPRODDBA feel free to re-open if you are still seeing issues that isn't resolved the above guidance.

**Comment by davidblackmx** [comment]
> What about ` "\\"`?
> 
> `"Server=**svr1\\INST1**;Port=55555;User Id=test;Password=1234;app name=telegraf;log=1;"`

This works! Use 2 backslashes.
