### ISSUE TITLE
SQL Server - new On-Prem query refactoring (discussion)

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#8143]
Now that #7713 has been merged, I can start some query refactoring for the (new) SQL server on-prem section.

To be more specific I plan to:
1. remove the "database_name" tag when not useful, most of the time is just DB_NAME(), and was there for compatibility with Azure editions
2. Remove some useless variables/logic, needed just to correctly manage the switch between Azure and on-prem versions
3. Apply some code formatting (like adding square brackets on column names, SQL code indentation and similar)
4. Maybe add some null management logic (if appropriate and needed) for some queries, at least for the main tags. As an example, the [session_db_name] for the "sqlserver_requests" measurement could be NULL (at least in the old version of the query). but it's not easy to select such a value in InfluxDB, therefore replacing NULL with '<n/d>' might actually be helpful.

Also I'd like your opinion on the check performed on the SQL Engine edition before executing the query, in fact, it should not be needed anymore as it was used to choose the appropriate version of the query.

- is it still worth checking for the SQL Engine edition before executing the query?
  - if yes, should we return an error in case the engine edition does not match with the one configured in telegraf?

sample:
```SQL
IF @EngineEdition IN (2,3,4) /*Standard,Enterpris,Express*/
BEGIN
  {build and execute query}
END
ELSE 
  THROW 66666, 'Telegraf - This is not the on-prem version of SQL Server, check your configuration.', 1;
```

@denzilribeiro I'd like to hear you opinion about those ideas, also propose other ideas for the refactoring if you feel like something is missing

**Comment by denzilribeiro** [comment]
I thought I removed the DB_NAME() for new queries for on-prem. I didn't remove it for "backward compat" from V2 queries . Edition check is still a good thing in my opinion just because someone could put a wrong type of connection string and without that you would get otherwise one of many errors. When error is thrown should give context of what connection string ( atleast @@servername)  else will never know. Note you can't just optimize for influx though that is primarily being used only as other sink could be used as well.

Still improvements can be made to error handling/logging ( have made some already), once you have many connection strings hard to identify which one is throwing certain errors like login failed.
Also test cases could be beefed up :)
We should also  going forward should try to restrict PR's to one database_type if possible (unless is something very minor) so as to contain them?

**Comment by Trovalo** [comment]
The DB_NAME() has been removed in some queries but I still found it in queries like sqlServerRequests, that's not a problem.
About the null management (influx optimization) that's the last thing I want to make, still, I think it could make sense in some cases (not only for influx)

I agree on keeping the PR's to just one database_type with one more exception
- minor changes (as you said)
- implementing plugin wide logic (like adding the THROW ERROR in every query) - we just need to use separate commits to make identification easier

For every other changes (adding columns, queries, etc) there is no problem in creating multiple PRs, one for each database_type

**Comment by Trovalo** [comment]
@denzilribeiro I've added the THROW error in several queries as below and I'm trying to test them (by using a wrong config)
```
IF SERVERPROPERTY('EngineEdition') NOT IN (2,3,4) BEGIN /*NOT IN Standard,Enterpris,Express*/
	DECLARE @ErrorMessage AS nvarchar(500) = 'Telegraf - '+ @@SERVERNAME +' is not a SQL Server Standard, Enterprise or Express, check the database_type parameter in the telegraf configuration.';
	THROW 50000, @ErrorMessage, 1
END

{query}
```

looks like in the new version the error is not outputted by telegraf tho, no error message is written in the telegraf log. I will have a better look at this during the week

https://github.com/influxdata/telegraf/blob/689b4639982bb5cec12b45654f57a6816007532c/plugins/inputs/sqlserver/sqlserver.go#L257

**Comment by Trovalo** [comment]
The refactoring has been merged some time ago, I think this can be closed
