### ISSUE TITLE
Common plugin TLS module allows for insecure ciphers 

### ISSUE THREAD

**Issue by darinfisher** [influxdata/telegraf#8171]
The TLS module included for plugins allows insecure versions 1.0 and 1.1.

See the plugins common file: `plugins/common/tls/common.go`

**Comment by ssoroka** [comment]
So I guess the question is should we allow users to use insecure versions if they really want to? I'd love to say "you must use secure settings", but I'm thinking that's going to cause a problem with some old client somewhere. Maybe we should have a list of secure ciphers and allow an agent setting to switch back to the old list if anyone has problems. We can name it something scary like "allow_insecure_ciphers" and "allow_insecure_tls_versions"

**Comment by jdstrand** [comment]
To add some flavor to this, TLS1.0 and TLS1.1 are effectively EOL as of March 2020 due to their inherent problems:
* https://security.googleblog.com/2018/10/modernizing-transport-security.html
* https://blogs.windows.com/msedgedev/2018/10/15/modernizing-tls-edge-ie11/
* https://webkit.org/blog/8462/deprecation-of-legacy-tls-1-0-and-1-1-versions/
* https://blog.mozilla.org/security/2018/10/15/removing-old-versions-of-tls/

I agree we shouldn't be using them and should enforce TLS1.2 at a minimum by adjusting plugins/common/tls/config.go to set tlsConfig.MinVersion accordingly (this would prevent downgrade attacks. You can use tls.MaxVersion in your unittests to mock things that don't speak TLS1.2 to verify it is working as intended).

I'm new to telegraf (but looking at open security issues across influxdata); who is expected to be talking to the listener or put another way, what client software is expected to connect to telegraf? Adding an allow_insecure_tls_versions (or similar) that defaults to false but when true sets tlsConfig.MinVersion to TLS1.0 would be acceptable IME.

Also, this isn't assigned to anyone; should it be?

**Comment by jdstrand** [comment]
@ssoroka - fyi, I submitted https://github.com/influxdata/telegraf/pull/8959 for this issue.

**Comment by jdstrand** [comment]
I think it is clear that I don't have time to work on this. I would be happy for anyone to pick up my work and run with it. If priorities change, I'll circle back to it, but I don't see that happening in the foreseeable short to mid term future.

**Comment by jdstrand** [comment]
FYI, Golang has since changed the defaults to 1.2 when acting as a client and 1.0 when acting as a server: https://cs.opensource.google/go/go/+/refs/tags/go1.18.4:src/crypto/tls/common.go;l=685:
```
	// MinVersion contains the minimum TLS version that is acceptable.
	//
	// By default, TLS 1.2 is currently used as the minimum when acting as a
	// client, and TLS 1.0 when acting as a server. TLS 1.0 is the minimum
	// supported by this package, both as a client and as a server.
	//
	// The client-side default can temporarily be reverted to TLS 1.0 by
	// including the value "x509sha1=1" in the GODEBUG environment variable.
	// Note that this option will be removed in Go 1.19 (but it will still be
	// possible to set this field to VersionTLS10 explicitly).
	MinVersion uint16
```

As a result, nearly all plugins are now using 1.2, but listener plugins will continue to default to 1.0 as a min version. This change was added late last year in https://cs.opensource.google/go/go/+/035963c7f5d82b5bf1501f407919031f815bd038

**Comment by jdstrand** [comment]
Thanks for picking this up @srebhan! :)
