### ISSUE TITLE
What is the max PPS for the gNMI input plugin and what is the suggested method to achieve redundancy?

### ISSUE THREAD

**Issue by raider111111** [influxdata/telegraf#8174]
## Feature Request

Opening a feature request kicks off a discussion.

I guess my question relates to reliability. 
Using the MDT plugin we can place several Telegraf server containers behind a load balancer. 
This ensures that over loading is avoided and that there's always an available Telegraf server. 
Once I had that infrastructure stood up we noticed that the Telegraf community appeared to be embracing the gNMI plugin. 

Since gNMI appears to be vendor agnostic I went ahead and began researching it and the associated design. 
The way the gNMI appears to work is in reverse of MDT with Telegraf dialing out to the network device as opposed to MDT which streams the data from the switch to Telegraf. 
With this being the case, what are the suggested best practices for achieving similar reliability as you would receive with the MDT plugin. 

Additionally, has this plugin been load tested, and if so what is the recommended maximum PPS that it can reliability operate?
This post was suggested by Samantha Wang at InfluxData.
She asked me to tag the original author @sbyx for comment.

**Comment by sspaink** [comment]
Hello, sorry for such a late response but it looks like your question wasn't ever answered. Unfortunately there isn't a best practice the maintainers of this project can give you as we don't actively use this MDT plugin. There aren't any automatic tests that load test plugins although that would be nice to have in the future. I'm going to close this issue as I don't think anyone will be able to give you an answer. If you have figured a solution since opening this issue I recommend opening a PR to update the MDT plugins documentation with what you found. Thanks!
