### ISSUE TITLE
SNMP_trap add community string

### ISSUE THREAD

**Issue by gomazu** [influxdata/telegraf#8182]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
add community string configuration that is currently available in snmp (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/snmp) to snmp_trap
### Current behavior:
Traps sent to plugin that have a community string set, are disregarded. 
### Desired behavior:
Add community string to configuration
### Use case: 
medium to large organizations will use v2c community string to cut down on unauthorized snmp traps. IN some cases, systems such as Aruba AP do not allow snmp trap configuration without a community string set.

**Comment by reimda** [comment]
> add community string configuration that is currently available in snmp to snmp_trap

The snmp input has a community string setting because it makes snmp requests.  The snmp agent that receives the request won't respond if the community string in the request isn't correct.

It doesn't make sense to add a community string setting to snmp_trap because the community string isn't necessary to receive a trap.  If a trap receiver such as the snmp_trap input has a community string setting, it can only be used to compare with the community string from the trap, say for instance if you wanted to discard traps that didn't have the correct community string.  It doesn't sound like that's the behavior you're asking for.

> Traps sent to plugin that have a community string set, are disregarded

The snmp_trap input accepts v1 and v2c traps with or without community string.  A trap is not disregarded just because it has a community string set.

> systems such as Aruba AP do not allow snmp trap configuration without a community string set

On these systems you can set the community string to whatever you want and its traps should be received by telegraf.

**Comment by gomazu** [comment]
> > add community string configuration that is currently available in snmp to snmp_trap
> 
> The snmp input has a community string setting because it makes snmp requests. The snmp agent that receives the request won't respond if the community string in the request isn't correct.
> 
> It doesn't make sense to add a community string setting to snmp_trap because the community string isn't necessary to receive a trap. If a trap receiver such as the snmp_trap input has a community string setting, it can only be used to compare with the community string from the trap, say for instance if you wanted to discard traps that didn't have the correct community string. It doesn't sound like that's the behavior you're asking for.
> 
> > Traps sent to plugin that have a community string set, are disregarded
> 
> The snmp_trap input accepts v1 and v2c traps with or without community string. A trap is not disregarded just because it has a community string set.
> 
> > systems such as Aruba AP do not allow snmp trap configuration without a community string set
> 
> On these systems you can set the community string to whatever you want and its traps should be received by telegraf.

I suspect my description was poorly written. You are spot: " it can only be used to compare with the community string from the trap, say for instance if you wanted to discard traps that didn't have the correct community string."   we would like the community string to discard traps that did not have the correct community string.

**Comment by gomazu** [comment]
I tested "The snmp_trap input accepts v1 and v2c traps with or without community string. A trap is not disregarded just because it has a community string set."  this evening using both Aruba AP and Pfsense.  Setting community "public" for v2 traps on both the Aruba and PFsense, telegraf was not sending traps to InfluxDB.  Removing community string from trap sink on Pfsense, traps were sent to InfluxDB.
