### ISSUE TITLE
input.smart gives error message that I need help interpreting

### ISSUE THREAD

**Issue by DevinCampbell** [influxdata/telegraf#8217]
I have Telegraf 1.15.3 installed on a Ubuntu LTS 18.04 host. I enabled input.smart in the config file and told it to use sudo when running. I also have the requisite lines from the documentation in my sudoers file.

When I run the command systemctl status telegraf I get the following message:
```
Oct 02 18:29:00 subchromat telegraf[6284]: 2020-10-02T18:29:00Z E! [inputs.smart] Error in plugin: f
Oct 02 18:29:00 subchromat postfix/sendmail[6339]: fatal: open /etc/postfix/main.cf: No such file or
```

There is also no data being written to my InfluxDB for the smart input. I'm not sure what to look for since the message doesn't really tell me anything.

I also don't use postfix on this machine and I didn't enable any inputs to monitor postfix, so I'm not sure why that line is appearing either.

**Comment by p-zak** [comment]
@DevinCampbell 
It seems that each of your status line is truncated to first 100 characters, please run `systemctl status --no-pager --full telegraf` to see full lines in log, because current log does not say much.

Have you installed `Telegraf 1.15.3` or fresher version from sources or maybe any nightly version?
