### ISSUE TITLE
Add support for Windows Event Counters

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#8249]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add support for Windows Event Counters

### Use case:
From Microsoft Blog - [Introducing diagnostics improvements in .NET Core 3.0](https://devblogs.microsoft.com/dotnet/introducing-diagnostics-improvements-in-net-core-3-0/):

**Unlike the .NET Framework on Windows, .NET Core doesn’t emit perf counters.** Instead, we had introduced a new way of emitting metrics in .NET Core via the [EventCounter API](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Diagnostics/Tracing/EventCounter.cs).

EventCounters offer an **improvement over Windows perf counters as these are now usable on all OSes where .NET Core is supported**. Additionally, unlike perf counters, they are also **usable in low privilege environments (like xcopy deployments)**

**Comment by perzizzle** [comment]
I believe we were the origin of this request. If there's any interest in hearing our use case let us know.

**Comment by sjwang90** [comment]
@perzizzle Can you share the use case on this issue? Thanks.

**Comment by perzizzle** [comment]
We are in the middle of re-writing .net framework applications (on windows) with performance counters to use .net core (on linux). In our application deployment automation, we had a process that allowed the application to define what performance counters were relevant and render a telegraf configuration to grab this data. It would be nice to add EventCounter support to telegraf so that the application could simply emit these metrics and telegraf could handle sending them to influx.  The alternative is updating our application to use the http telegraf api directly to write metrics.

**Comment by sjwang90** [comment]
@perzizzle Is there an existing plugin you think we could add this capability to?

**Comment by srebhan** [comment]
@perzizzle is this issue still relevant?

**Comment by perzizzle** [comment]
I don't know of an existing telegraf input plugin that can handle this data so I think so?

**Comment by srebhan** [comment]
OK, thanks! Do you know of an easy way to produce those counters or an easy source @perzizzle? So I could be kick-started... ;-)
