### ISSUE TITLE
Build fails for v1.16.0

### ISSUE THREAD

**Issue by ogarcia** [influxdata/telegraf#8310]
I'm trying to build [v1.16.0][1] from source with this command:
```
export CGO_CPPFLAGS="${CPPFLAGS}"
export CGO_CFLAGS="${CFLAGS}"
export CGO_CXXFLAGS="${CXXFLAGS}"
export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
_LDFLAGS="-X main.version=1.16.0 -X main.branch=tag-1.16.0 -X main.commit=tag-1.16.0 -extldflags ${LDFLAGS}"
go build -o build -ldflags="${_LDFLAGS}" "./..."
```

And I got this error:
```
# github.com/influxdata/telegraf/plugins/inputs/execd/shim/example/cmd
.rela: function main is undeclared in the main package
runtime.main_main·f: function main is undeclared in the main package
```

With all previous versions I don't have problems.

[1]: https://github.com/influxdata/telegraf/archive/v1.16.0.tar.gz

**Comment by p-zak** [comment]
@ogarcia 

From which directory do you call `go build ...`? 

You should call it from Telegraf's root directory (and I think that you do it from `plugins/inputs/execd/shim/example/cmd/`).

**Comment by ogarcia** [comment]
@p-zak from Telegraf's root directory

You can see the full process in [the PKGBUILD][1], but it do:
1. Download v1.16.0
2. Uncompress in `${pkgname}-${pkgver}` directory
3. cd to `${pkgname}-${pkgver}` directory
4. go build -o build -ldflags="${_LDFLAGS}" "./..."

[1]: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=telegraf

**Comment by p-zak** [comment]
Got it, I asked because I got the same output when I called `go build` from `plugins/inputs/execd/shim/example/cmd/`.

I think that it will work when you change 
`go build -o build -ldflags="${_LDFLAGS}" "./..."` 
to 
`go build -o build -ldflags="${_LDFLAGS}" "./cmd/telegraf"`.

This is the same approach which you can see in `Makefile`:
```
# Telegraf build per platform.  This improves package performance by sharing
# the bin between deb/rpm/tar packages over building directly into the package
# directory.
$(buildbin):
	@mkdir -pv $(dir $@)
	go build -o $(dir $@) -ldflags "$(LDFLAGS)" ./cmd/telegraf
```

I think that https://github.com/influxdata/telegraf/commit/080e0dbbfad24ca71bee9e8aba74f07adbc7ca88 broke your approach. After mentioned commit in source tree there is `package main` without `main` function.

**Comment by ogarcia** [comment]
Yes! It works :wink:  At least I can [update the package][1]. Thanks @p-zak !

[1]: https://aur.archlinux.org/packages/telegraf/

**Comment by ssoroka** [comment]
p-zak got it right. Closing the issue.
