### ISSUE TITLE
Build failed on ppc64le

### ISSUE THREAD

**Issue by shaba** [influxdata/telegraf#8311]
After PR #8293 (input plugin for RAS) telegraf can't build on ppc64le. Because modernc.org/libc not ready for ppc64le.
How disable one RAS plugin for build?

**Comment by zak-pawel** [comment]
https://github.com/influxdata/telegraf/pull/8317 fixes this issue.

It wasn't found before, because CI doesn't check/build for these platforms: `mips64`, `mips64le`, `ppc64`, `ppc64le`, `riscv64`.

Mentioned fix will unblock building process for `mips64`, `mips64le`, `ppc64le`, `riscv64`. 
Building is still not supported for `ppc64` because of lack of support for this platform in `shirou/gopsutil` used in few plugins. They have had issue opened since 2017 about that: https://github.com/shirou/gopsutil/issues/301

**Comment by reimda** [comment]
#8317 disabled the RAS input plugin on ppc64le so this should be fixed
