### ISSUE TITLE
system time in system input plugin

### ISSUE THREAD

**Issue by arindamchoudhury** [influxdata/telegraf#8334]
### Proposal:
Include system time in system input plugin

### Current behavior:
currently system input plugin reports following meterics:

system,host=influxdb load1=3.96,load15=3.44,load5=3.38,n_cpus=26i,n_users=2i 1603965488000000000
system,host=influxdb uptime=1319467i 1603965488000000000
system,host=influxdb uptime_format="15 days,  6:31" 1603965488000000000

### Desired behavior:
system input plugin will report:
system,host=influxdb load1=3.96,load15=3.44,load5=3.38,n_cpus=26i,n_users=2i 1603965488000000000
system,host=influxdb system_time_utc="2020-10-29T09:58:08Z",uptime=1319467i 1603965488000000000
system,host=influxdb uptime_format="15 days,  6:31" 1603965488000000000

### Use case: 
It will help to check if the system time is incorrect.

I have changes ready. I can do a pull request.

**Comment by ssoroka** [comment]
The timestamp at the end is actually the system time as an integer, number of nanoseconds since 1970. The round-to-second feature is controlled by the config's `precision` setting. This value will never be different than the timestamp you have in your "desired behavior" example, except that it's in a different format. The overall problem here is you don't have anything to compare it to. It's difficult to tell the difference between system clock drift and a metric that is delayed in delivery to the db.
