### ISSUE TITLE
Fips compliance

### ISSUE THREAD

**Issue by abhi12363** [influxdata/telegraf#8363]
does telegraf supports FIPS ? if it supports then, is there any configuration needed to monitor Fips Enabled Applications and Fips enabled OS ?

**Comment by reimda** [comment]
The project hasn't gone through any FIPS certification and it is not on the project roadmap.  If you're interested in collecting FIPS-specific metrics for applications or OS using telegraf you could submit an issue proposing a new input plugin and we would be happy to review and help plan for a community contributed PR.

**Comment by abhi12363** [comment]
Thanks for clarification. i have one more question, does telegraf work on fips enabled OS and collect metrics related to OS ?

**Comment by abhi12363** [comment]
Kindly help to find answer

**Comment by reimda** [comment]
I don't have much experience running fips mode.  I understand it ensures only approved crypto algorithms will be used but otherwise the OS acts normally.  I expect telegraf would run fine on an os in fips mode.  Telegraf itself would not change its behavior though.  It may use crypto algorithms that are not approved by fips in this case.
