### ISSUE TITLE
Disable test configuration

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [influxdata/telegraf#8442]
## Feature Request

At the moment, when telegraf is installed/updated from the package manager in ubuntu, there is a default configuration that saves cpu, disk, mem, ... stats into the database. In our case we are not interested in this and we comment them out and write custom conf files in the telegraf.d folder which are read every startup. Anyway, the package update can overwrite the main config file reenabling the unnecessary metrics.

### Proposal:

Comment out the default host metrics in the main configuration file

### Current behavior:

The configuration file has some metrics enabled

### Desired behavior:

Those metrics should be commented out by default

### Use case: 

We do not need them; we write custom conf files for all our needs in the telegraf.d folder and we need to comment out the default metrics every time the default config file gets updated in the package.

**Comment by powersj** [comment]
next steps: verify that a package update will overwrite an updated config. If not, close this, otherwise, add this to the potential changes to the deb/rpm config.

**Comment by powersj** [comment]
Been a while since this was filed, so I wanted to verify the current behavior. On fresh install of v1.24.1 puts down the following files:

```s
root@j1:/etc/telegraf# ls -l
total 776
-rw-r--r-- 1 root root 395352 Sep 29 20:03 telegraf.conf
-rw-r--r-- 1 root root 395352 Sep 19 19:05 telegraf.conf.sample
drwxr-xr-x 1 root root      0 Sep 19 19:05 telegraf.d
```

Now I update the telegraf.conf file to only include `inputs.mem` and `outputs.file`:

```
root@j1:/etc/telegraf# cat telegraf.conf
[[inputs.mem]]
[[outputs.file]]
root@j1:/etc/telegraf# ls -l
total 392
-rw-r--r-- 1 root root     32 Sep 29 20:05 telegraf.conf
-rw-r--r-- 1 root root 395352 Sep 19 19:05 telegraf.conf.sample
drwxr-xr-x 1 root root      0 Sep 19 19:05 telegraf.d
```

Finally, update the package to a [nightly build](https://github.com/influxdata/telegraf/blob/master/docs/NIGHTLIES.md):

```
root@j1:~# dpkg -i telegraf_nightly_amd64.deb 
(Reading database ... 33972 files and directories currently installed.)
Preparing to unpack telegraf_nightly_amd64.deb ...
Unpacking telegraf (1.25.0-0) over (1.24.1-1) ...
Setting up telegraf (1.25.0-0) ...
Installing new version of config file /etc/telegraf/telegraf.conf.sample ...
root@j1:~# cd /etc/telegraf/
root@j1:/etc/telegraf# ls -l
total 392
-rw-r--r-- 1 root root     32 Sep 29 20:05 telegraf.conf
-rw-r--r-- 1 root root 395113 Sep 29 07:25 telegraf.conf.sample
drwxr-xr-x 1 root root      0 Sep 19 19:05 telegraf.d
```

The config file was not replaced. The same occurs if the file is an empty file.

This is because the [post-install](https://github.com/influxdata/telegraf/blob/master/scripts/deb/post-install.sh#L46) script will only copy the sample config over to `telegraf.conf` if the file does not exist.

For users who want to use their own config file, then the current behavior avoids replacing users customizations. For users who want to use a directory of config files and ignore this file, then the solution is to replace `telegraf.conf` with an empty file and it will not be touched on updates to telegraf.

I don't think there is anything for us to do here, so I am going to close this issue for now. If I have missed something please do feel free to follow-up.
