### ISSUE TITLE
Add configuration option to elasticsearch input to collect only the most recent fields

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#8517]
## Feature Request

Opening a feature request kicks off a discussion.

### Current behavior:
The plugin currently gathers all historical data, which creates too much data and increases cardinality. Customer would like to filter on a specific time frame, like last 24 hours.

### Desired behavior:
New configuration option: If my indices are datestamped - I'll get X of the newest datestamps depending on what I configure

### Use case: 

Customer using the elasticsearch input plugin and only wants the following fields:
`indexing_index_failed `(float)

He only wanted it for last 24 hours, not all historical data. Add this feature to this specific plugin so it just matches a daily pattern, and ignores everything that’s old.

**Comment by Jagularr** [comment]
Want to run by you a proposed solution for this: we'd add some config value (let's call it X) that specifies the number of prior index instances to report from, in descending order by the date at the end of the index name. So if someone configures `indices_include = ["example"]` and `X = 1,` and we find indices called example_2020_10_25 and example_2020_10_26, then we use fields only from index "example_2020_10_26". 

I guess the only requirement here would be that the user knows and configures the 'base' names of the indices that they want, instead of using `_all`, so that we can know where the date will be in the index name.
