### ISSUE TITLE
[inputs.sqlserver] exclude a bd

### ISSUE THREAD

**Issue by ortiga88** [influxdata/telegraf#8581]
How could you exclude a database from the telegraphy configuration? Is it necessary to delete the data directly from influxdb ???

**Comment by helenosheaa** [comment]
Could you provide the relevant telegraf.conf? From what I understand you want to exclude certain databases from the sqlserver inputs but without seeing your config it's hard to assist. 

For support questions rather than reproducible errors we encourage you to direct questions to our [Community Page](https://community.influxdata.com/) or our [Community Slack Channel](https://influxcommunity.slack.com/archives/CH99HUH8V) where you will get a faster response.
