### ISSUE TITLE
Prometheus Input fails with metric_version = 2

### ISSUE THREAD

**Issue by johnseekins** [influxdata/telegraf#8617]
### Relevant telegraf.conf:

```toml
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"
[agent]
  interval = "30s"
  round_interval = false
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "2s"
  flush_interval = "10s"
  flush_jitter = "5s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false
```

```toml
[[inputs.prometheus]]
  ## An array of urls to scrape metrics from.
  urls = ["http://localhost:9000/minio/prometheus/metrics"]
  metric_version = 2
  name_override = "minio"
  tagexclude = ["url"]
```

### System info:

```
$ lsb_release -rc
Release:	10
Codename:	buster

$ dpkg -l | grep telegraf
ii  telegraf                             1.17.0-1                              amd64        Plugin-driven server agent for reporting metrics into InfluxDB.

$ minio -v
minio version RELEASE.2020-12-12T08-39-07Z
```

### Steps to reproduce:

1. Install telegraf and minio on a host
2. Attempt to scrape prometheus stats from minio using telegraf with `metric_version = 2`.
```
$ sudo -u telegraf telegraf --test --config-directory /etc/telegraf/telegraf.d/ --input-filter prometheus
2020-12-24T17:51:35Z I! Starting Telegraf 1.17.0
2020-12-24T17:51:35Z I! Using config file: /etc/telegraf/telegraf.conf
2020-12-24T17:51:35Z E! [inputs.prometheus] Error in plugin: error reading metrics for http://localhost:9000/minio/prometheus/metrics: reading text format failed: text format parsing error in line 1: expected float as value, got ""
2020-12-24T17:51:35Z E! [telegraf] Error running agent: input plugins recorded 1 errors
```
3. Switch to `metric_version = 1` and stats will be collected, although the naming is then messed up.

### Expected behavior:

1. When scraping stats from minio's prometheus status page, telegraf fails to parse the output values
2. If I set `metric_version = 1` in the prometheus input, the stats are collected.
3. This wasn't the case before 1.17.0. `metric_version = 2` has been working well for quite some time.

### Actual behavior:

Described above.

### Additional info:

This is also occurring with other prometheus client endpoints (traefik, for example) on another Debian 10 system.

Example minio stats pulled from the host:

```
$ curl -Ss localhost:9000/minio/prometheus/metrics | head
# HELP disk_storage_available Total available space left on the disk
# TYPE disk_storage_available gauge
disk_storage_available{disk="/data/Blobstore"} 1.1720781201408e+13
# HELP disk_storage_total Total space on the disk
# TYPE disk_storage_total gauge
disk_storage_total{disk="/data/Blobstore"} 1.6001493008384e+13
# HELP disk_storage_used Total disk storage used on the disk
# TYPE disk_storage_used gauge
disk_storage_used{disk="/data/Blobstore"} 4.280711806976e+12
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
```

It seems clear to me those are valid prometheus stats. What's happening here?

**Comment by johnseekins** [comment]
Stats in Grafana for Minio clearly stopping with the 1.17 release:
![Screenshot from 2020-12-24 11-04-21](https://user-images.githubusercontent.com/5665929/103102136-d9d78f00-45d7-11eb-8894-aca4c068e1d5.png)

**Comment by johnseekins** [comment]
Interesting: Dumping the minio stats to a file and reading them using the prometheus parser:
```toml
[[inputs.file]]
  files = ["/tmp/metrics.txt"]
  name_override = "minio"
  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ##   https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "prometheus"
```
Works!

```
$ sudo -u telegraf telegraf --test --config-directory /etc/telegraf/telegraf.d/ --input-filter file
2020-12-24T18:08:15Z I! Starting Telegraf 1.17.0
2020-12-24T18:08:15Z I! Using config file: /etc/telegraf/telegraf.conf
> minio,host=robit go_memstats_heap_sys_bytes=65732608 1608833296000000000
> minio,commit=48191dd748d228336f04d55e1b5ee0979f601c39,host=robit,version=2020-12-12T08:39:07Z minio_version_info=1 1608833296000000000
> minio,host=robit process_start_time_seconds=1607880157.04 1608833296000000000
> minio,host=robit go_gc_duration_seconds_count=7952,go_gc_duration_seconds_sum=0.78407002 1608833296000000000
> minio,host=robit,quantile=0 go_gc_duration_seconds=0.000052359 1608833296000000000
> minio,host=robit,quantile=0.25 go_gc_duration_seconds=0.000076315 1608833296000000000
> minio,host=robit,quantile=0.5 go_gc_duration_seconds=0.00009054 1608833296000000000
> minio,host=robit,quantile=0.75 go_gc_duration_seconds=0.000106521 1608833296000000000
> minio,host=robit,quantile=1 go_gc_duration_seconds=0.000233852 1608833296000000000
> minio,host=robit internode_rx_bytes_total=0 1608833296000000000
> minio,host=robit process_cpu_seconds_total=521.13 1608833296000000000
> minio,api=completemutipartupload,host=robit s3_requests_current=0 1608833296000000000
```

**Comment by johnseekins** [comment]
Reverting to 1.16.3 fixing this problem immediately.

**Comment by oplehto** [comment]
I'm seeing a similar issue. In my case the reason seems to be that the content negotiation prefers the protobuf format that has been deprecated for a while and is not implemented in metrics_version 2. Some prometheus endpoints respond with protobuf format if it's in the Accept header and the new parser can't handle it. 

https://github.com/influxdata/telegraf/blob/3d30fd85c6cf9dd7a9384abe4c86e9b050690a49/plugins/inputs/prometheus/prometheus.go#L21

Removing the `application/vnd.google.protobuf` works.

**Comment by helenosheaa** [comment]
@johnseekins @oplehto do you still get this error if you run off the current master branch of Telegraf?

I'm not able to reproduce the error when I'm on the master branch and when I go to the latest release of Telegraf 1.17 I'm getting a different error message: 

`reading text format failed: text format parsing error in line 1: invalid metric name`

Which has now been fixed with pr #8545

**Comment by johnseekins** [comment]
@helenosheaa You're right. This was fixed elsewhere. Thanks.

**Comment by oh-jose-vazquez** [comment]
I'm having the same issue, it seems that `metric_version = 2` turns tags into fields, and looses the right field, i.e.:

Prometheus data:
`
# HELP ccloud_metric_sent_records The delta count of records sent. Each sample is the number of records sent since the previous data point. The count is sampled every 60 seconds.
# TYPE ccloud_metric_sent_records gauge
ccloud_metric_sent_records{cluster_id="lkc-r6mp7",kafka_id="lkc-r6mp7",partition="",topic="correction-assets"} 0 1618254480000
`

with `metric_version = 1`,  I have: 
`ccloud_metric_sent_records,cluster_id=lkc-r6mp7,host=telegraf,kafka_id=lkc-r6mp7,topic=ase.correction-assets,url=http://ccloud_exporter:2112/metrics gauge=0 1618261320000000000`

but with `metric_version = 2`, I have:
 `prometheus,cluster_id=lkc-r6mp7,host=telegraf,kafka_id=lkc-r6mp7,topic=dev.priv.ls.location-update,url=http://ccloud_exporter:2112/metrics ccloud_metric_sent_records=0 1618260900000000000`

**Comment by helenosheaa** [comment]
@oh-jose-vazquez sorry you are experiencing problems with prometheus.

I believe what you are describing is in line with how metric v1 and v2 currently works for our Prometheus parser. So the gauge value is still there but the field key gauge is not.

v1 -->
Prometheus metric name = measurement
Labels = Tags
Metric type = Field Key

v2 -->
Plugin name = measurement
Labels = Tags
Prometheus metric name = field key
We don't keep the HELP or TYPE line

There are also some more examples [here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/README.md#metrics)

Could you outline what you are aiming for? We do have options in terms of [starlark](https://github.com/influxdata/telegraf/blob/master/plugins/processors/starlark/README.md) or other renaming processors if you wanted to change the fieldname, tags or measurement name.

**Comment by oh-jose-vazquez** [comment]
@helenosheaa our problem is that we a lot of data and we used V1, but since it's deprecated, we are updating to V2, however, V2 is completely different, and our alerts won't work, we will need to do a lot of changes, so I'm looking for a way to have V2 but have the same way for the metrics

**Comment by helenosheaa** [comment]
@oh-jose-vazquez I would just stick with using V1 as the difference between the metric versions is only the way they are parsed. We currently have no plans to fully deprecate V1 parsing so you are fine to continue using it. I'll also remove the warning log that is currently there as it is suggesting that we are.

**Comment by oh-jose-vazquez** [comment]
Thanks a lot @helenosheaa
