### ISSUE TITLE
inputs.ping failures after updating from 1.17.0 to 1.17.2

### ISSUE THREAD

**Issue by f1sherman** [influxdata/telegraf#8778]
### Relevant telegraf.conf:
```toml
[[inputs.ping]]
  urls = ["cloudflare.com", "example.org", "google.com"]
  method = "native"
```

### System info:

Telegraf 1.17.2
Debian Buster

### Steps to reproduce:

After upgrading to Telegraf 1.17.2 from 1.17.0 last night I'm now seeing errors with the native ping input.

```
 ❯ telegraf -config /etc/telegraf/telegraf.conf --test | grep 'ping,'                                                                                                                            [14:17:38]
2021-01-30T20:17:38Z I! Starting Telegraf 1.17.2
> ping,host=server01,url=google.com result_code=2i 1612037859000000000
> ping,host=server01,url=example.org result_code=2i 1612037859000000000
> ping,host=server01,url=cloudflare.com result_code=2i 1612037859000000000
```

### Expected behavior:

`result_code=0` (previous behavior on 1.17.0)

### Actual behavior:

`result_code=2i`

**Comment by vj-gsr** [comment]
Same here...
```
bash-5.0# telegraf --config /tmp/a --test --debug
2021-01-31T07:41:41Z I! Starting Telegraf 1.17.2
2021-01-31T07:41:41Z D! [agent] Initializing plugins
2021-01-31T07:41:41Z D! [agent] Starting service inputs
2021-01-31T07:41:41Z D! [agent] Stopping service inputs
2021-01-31T07:41:41Z D! [agent] Input channel closed
2021-01-31T07:41:41Z D! [agent] Stopped Successfully
> ping,host=telegraf-standalone-7b54884974-bt4xn,url=1.1.1.1 result_code=2i 1612078901000000000

bash-5.0# cat /tmp/a
[[inputs.ping]]
  urls = ["1.1.1.1"]
  method = "native"
  count = 3
  ping_interval = 1.0
  timeout = 2.0
  deadline = 10
bash-5.0# 

bash-5.0# getpcaps $(ps -A | grep telegraf | cut -d ' ' -f 4)
Capabilities for `42': = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap+eip

bash-5.0# getpcaps telegraf
Capabilities for `telegraf': = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap+eip

bash-5.0# cat /etc/issue 
Welcome to Alpine Linux 3.12
Kernel \r on an \m (\l)
```

**Comment by sspaink** [comment]
Someone else reported a similar problem that was resolved by updating the permissions, maybe the solution will help you as well.
More details: https://github.com/influxdata/telegraf/issues/7892#issuecomment-769887600

**Comment by f1sherman** [comment]
Thanks! `sudo sysctl -w net.ipv4.ping_group_range="0 2147483647"` fixed it!

I'm going to leave this open because it seems like something we might want to document or at least make more clear as a requirement to end users.

Maintainers, feel free to close if that's not the case!

**Comment by Daryes** [comment]
Hello
I would like this issue to be reopened.
The way I understand it, the updated README commit is not a real fix, and also require to add a dedicated configuration under /etc/sysctl.d or sysctl.conf while the documentation already covers everything required.

From https://github.com/go-ping/ping :
you need either : `sysctl -w net.ipv4.ping_group_range`
OR 
`setcap cap_net_raw=+ep /usr/bin/telegraf` AND a call to `pinger.SetPrivileged(true)`

The telegraf documentation already has the information with the CAP_NET_RAW capability through systemd, or using `setcap cap_net_raw` without systemd (or not wanting to deal with it)  

The way the documentation is now written with this patch gives the impression you need both CAP_NET and the sysctl change, which is wrong.  
With the updated go-ping lib, to use CAP_NEW_RAW, the ping.go telegraf input require a global SetPrivileged(true) instead of one [restricted to Windows only](https://github.com/influxdata/telegraf/blob/24a552b90ba06d278cbe0639290a9bee1d7791b6/plugins/inputs/ping/ping.go#L171)

To support this, with telegraf 1.17.2, I had to implement the sysctl change, the native ping wouldn't work otherwise, while the telegraf binary had the capabilities : 
```
$ getcap /usr/bin/telegraf
/usr/bin/telegraf = cap_net_raw+eip
```
In fact, the capability itself has no effect with the new version. You can even remove it, only the sysctl setting works.

I suppose that more people already implemented the cap_net_raw for telegraf through systemd or with the setcap command.
Having SetPrivileged(true) set for any system should cover this without the need of the sysctl config.

**Comment by taylorthurlow** [comment]
Is this something that docker image maintainers are going to have to fix manually? Or is it actually a "problem"? I run telegraf on Unraid and I had to roll back to fix this.

**Comment by Artanicus** [comment]
I agree that the current state is far from fixed since the proposed sysctl command sets socket creation wide open instead of a targeted grant. The systemd `AmbientCapabilities=CAP_NET_RAW` is exactly that method, but now it doesn't work anymore. It should be restored to working order as per @Daryes above. @sspaink can you please re-open?

**Comment by sspaink** [comment]
@Artanicus I won't be re-opening this issue, but instead be addressing it in #8919
