### ISSUE TITLE
inputs.ping reporting 50% packet loss on windows

### ISSUE THREAD

**Issue by sspaink** [influxdata/telegraf#8819]
### System info:

version 1.17.2

### Expected behavior:

No packet loss

### Actual behavior:

@redrumdk reported an issue were using `inputs.ping` with `native` mode causes 50% packet loss to be reported although other tools such as `ping.exe` and `servers alive` don't report any packet loss. Screenshot provided: https://ibb.co/vk9ctVq

more context: #8771

### Additional info:

There was a recent change to go-ping which ignored duplicate packets. this could be related: https://github.com/go-ping/ping/pull/130

**Comment by Jagularr** [comment]
I believe I found the issue here, the 50% packet loss stems from setting a Timeout that is too short. For me, sending a count of 4 packets back and forth took an average of 3 seconds, while the default is timeout is 1 second. I'd just recommend that anyone having this issue try increasing their timeout to around 10 seconds to be safe and seeing what happens.

**Comment by redrumdk** [comment]
Seems all fixed in 17.3, thank you
