### ISSUE TITLE
Make elasticsearch input plugin reported fields integer, not float

### ISSUE THREAD

**Issue by anatolijd** [influxdata/telegraf#8866]
## Feature Request

Most of the fields produced by elasticsearch input plugin are float, even `docs_count` or `size_in_bytes`   are stored as float.
Normally, it is not a problem, until you run large cluster(s) and/or thousands of indicies.

 
### Proposal:

Convert field types to integer.

### Current behavior:

All fields are float

### Desired behavior:

Change field types to integer.
Keep using float type only when necessary.

Alternatively, provide configuration example how to convert all fields in `elasticsearch_indices*` measurements to integer, using telegraf built-in processor/converter. 

### Use case: 

We are running few large ES clusters, one of them running thousands of idices. 
ES influxdb data are collected with 60sec interval and stored to separate database. influxdb database storage used grows 2GB per day (only ES database). This is at least x30 times faster than our 2nd most active database.

**Comment by helenosheaa** [comment]
Changing the types to integer for the input could break backwards compatibility for users so my suggestion would be to use the processor converter to change fields to floats for your use case in your config like so:

```
[[processors.converter]]
  namepass = ["elasticsearch_indices"]
  [processors.converter.fields]
    integer = ["*"]
```

As the measurement name is elasticsearch_indices rather than included in the field using namepass for the metric name and then a * selector for the fields would be the best bet. Unless you want to only change certain fields in which case you'll need to list them out in the integer array.
