### ISSUE TITLE
Missing docker log if the container exit in less than a second.

### ISSUE THREAD

**Issue by lapcchan** [influxdata/telegraf#8881]
telegraf 1.17.2
```
[[inputs.docker_log]]
endpoint = "unix:///var/run/docker.sock"
from_beginning = true
```
i've also try from_beginning = false

if the container exit in less than a second, it will always miss the log to influxdb

we are using influxdb 1.8 if that matters.

**Comment by sspaink** [comment]
Telegraf probably isn't getting enough time to run with the container having such a short lifetime. This is similar to: https://github.com/influxdata/telegraf/issues/8122 and I recommend either adding a `sleep 5m` or run Telegraf with the flag `--once` and have a script wait for Telegraf to finish before exiting the container. Closing this issue because I don't think it is possible to guarantee Telegraf will run completely in less than a second.
