### ISSUE TITLE
[[inputs.ping]] - FreeBSD 12.2 - method = "native" doesn't work with telegraf 1.17.2 and 1.17.3

### ISSUE THREAD

**Issue by zmejuka** [influxdata/telegraf#8919]
### Relevant telegraf.conf:

```toml
[inputs]

  [[inputs.ping]]
    count = 5
    method = "native"
    ping_interval = 1.0
    timeout = 1.0
    urls = ["8.8.8.8", "1.1.1.1"]
```

### System info:

FreeBSD 12.2-RELEASE-p1 GENERIC  amd64
telegraf-1.17.2
telegraf-1.17.3
Telegraf installed from FreeBSD repo: url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest"
### Steps to reproduce:

1. Create config in /usr/local/etc/telegraf.d/ping.conf

2. Test it.

### Expected behavior:

1.17.0
```
# telegraf --config ping.conf --test             
2021-03-01T12:34:01Z I! Starting Telegraf 1.17.0
> ping,host=icmp-mon1,url=1.1.1.1 average_response_ms=1.664081,maximum_response_ms=1.683979,minimum_response_ms=1.64032,packets_received=5i,packets_transmitted=5i,percent_packet_loss=0,result_code=0i,standard_deviation_ms=0.015999,ttl=58i 1614602046000000000
> ping,host=icmp-mon1,url=8.8.8.8 average_response_ms=10.356897,maximum_response_ms=10.425363,minimum_response_ms=10.285378,packets_received=5i,packets_transmitted=5i,percent_packet_loss=0,result_code=0i,standard_deviation_ms=0.049354,ttl=113i 1614602046000000000
```
### Actual behavior:

1.17.2:
```
# telegraf --config ping.conf --test       
2021-03-01T12:04:43Z I! Starting Telegraf 1.17.2
> ping,host=icmp-mon1,url=8.8.8.8 result_code=2i 1614600284000000000
> ping,host=icmp-mon1,url=1.1.1.1 result_code=2i 1614600284000000000
```
1.17.3
```
# telegraf --config ping.conf --test
2021-03-01T12:11:37Z I! Starting Telegraf 1.17.3
> ping,host=icmp-mon1,url=1.1.1.1 result_code=2i 1614600697000000000
> ping,host=icmp-mon1,url=8.8.8.8 result_code=2i 1614600697000000000
```
### Additional info:

Running Telegraf as root to use raw sockets.

**Comment by Daryes** [comment]
You can find the answer to why it doesn't work on this issue : #8758 

@sspaink 
could you get a look to said issue, and especially [my comment](https://github.com/influxdata/telegraf/issues/8778#issuecomment-785332171) explaining why the accepted fix is not well suited ?
Main problem being where everybody using the native ping already did the change to handle the cap_net_raw requirement

**Comment by sspaink** [comment]
Hello @Daryes and @zmejuka thank you for opening this issue and the information provided.

So if I understand correctly, the change that needs to happen is this plugin needs to call "SetPrivileged(true)" for non-windows operating systems as well in order to be able to use "setcap" instead of "sysctl" ? I am thinking we would probably want this to be configurable so you can choose between setting privileged to "true" or not, would that work for you?

**Comment by zmejuka** [comment]
Hello @sspaink,

As I mentioned above, I'm running telegraf as user root to be able to use raw sockets. Also I have to remind that I use FreeBSD, not Linux or Windows. So in my opinion the root of this issue is something else. In the version 1.17.0 with the old native ping lib it worked well.

**Comment by Artanicus** [comment]
The same issue is present on Linux but slightly different (as documented more exentisvely in #8778) .. On that side calling `SetPrivileged(true)` sounds like the reasonable fix. i.e. if you don't attempt to use capabilities, they won't help you. The "sysctl fix" example is a bubblegum solution that opens up raw socket calls for anyone and anything and should not be advocated as a fix.

As to configurability, since when done correctly (setcap or systemd `AmbientCapabilities=CAP_NET_RAW`) priviledged access is required, I don't believe it needs to be configurable beyond only triggering when `method=native` and perhaps warn in the docs that native implies attempting to use privileged capabilities.

As to the FreeBSD aspect of this, as far as I understand "root" permissions are much more fine-grained on the BSD side, so it's wholly plausible that the same capabilities / privileges system breakage can cause issues since this stems from an upstream go ping library change. Thus the fix is likely the exact same, i.e. that native mode implies `SetPrivileged(true)` and beyond that it's a problem of granting the capability/privilege at the OS level.
