### ISSUE TITLE
Carbon2 serializer doesn't translate = in metric name

### ISSUE THREAD

**Issue by pmalek-sumo** [influxdata/telegraf#8974]
### Expected behavior:

Serialized metric names shouldn't contain `=` in their names.

### Actual behavior:

Whenever [carbon2 serializer ](https://github.com/influxdata/telegraf/tree/master/plugins/serializers/carbon2) is used and metric with `=` in their name are being serialized then the serializer doesn't translate the `=` characters, just copies them as is.

### Additional info:

Metrics with `=` in their names may confuse many systems that ingest them.

### Suggestion

Replace all `=` in metric name (and perhaps in all fields?) with `_`.

**Comment by perk-sumo** [comment]
Suggestion: wouldn't it be better to replace the `=` with `:` rather than with `_` by default?
The `=` is rather a separator in the meaning of a "namespace".
Given that many times metrics names have `_` to separate words in the name the "namespace" separator would get lost if same character is used.

Example:
If I have the metric called `node_cpu_utilisation=avg1m`
I'd want it as `node_cpu_utilisation:avg1m`
rather than `node_cpu_utilisation_avg1m`

It would be nice to make it configurable ofc.

**Comment by helenosheaa** [comment]
I think it makes sense. If you wanted to submit a PR for this, there is something similar in the wavefront serializer where it sanitizes `=` to `-` and other chars for the metric name. 

@pmalek-sumo do you think it makes most sense to use `_`or `:`?

Just to clarify would this be an example input/output: 

`weather=stats,location=us-midwest,season=summer wind=100 1234567890`

`metric=weather_stats field=wind location=us-midwest season=summer  100 1234567890`

**Comment by pmalek-sumo** [comment]
@helenosheaa I believe we can make this configurable with `:` as the default.

I can take a look at the implementation in wavefront later on but is there a wider character set that we'd like to replace/sanitize other than `=`?

**Comment by helenosheaa** [comment]
@pmalek-sumo yeah I think that makes sense
