### ISSUE TITLE
Arm64 docker alpine version

### ISSUE THREAD

**Issue by zewelor** [influxdata/telegraf#9030]
## Feature Request

Hi

Is it possible to provide arm64 alpine docker ?

**Comment by reimda** [comment]
Hi @zewelor

You could use the amd64 dockerfile at https://github.com/influxdata/influxdata-docker/blob/4c27ddc6edcfcbd4d94bb99d1716c9f4ec2b15df/telegraf/1.18/alpine/Dockerfile as a starting point for building your own arm64 image.  That dockerfile isn't platform independent and hard codes the amd64 .tar.gz.  You would need to modify your copy of the dockerfile to use the arm64 .tar.gz.  Besides that, I think the package prerequisites and other configuration would apply to arm64 and it looks like the base docker image (alpine:3.12) is already build for arm64, so it should work.

We don't have plans to provide an official arm64 docker image because the potential user base is relatively small.
