### ISSUE TITLE
Telegraf output plugin for Azure Data Explorer

### ISSUE THREAD

**Issue by minwal** [influxdata/telegraf#9230]
## Feature Request

Opening a feature request kicks off a discussion.

### Use case:  Lot of large enterprise customers requested for an ADX output plugin so they can ingest data collected using various input plugins directly to ADX. 
Azure Data Explorer is a big data analytics platform, purpose built for logs and telemetry analytics scenarios.

**Comment by tomconte** [comment]
Hi Minnie, just doing some research on this proposal, and I had a couple question you might be able to help me with:

- Could you share (maybe privately) some throughput and/or performance requirements for the plugin?
- Which [ingestion type](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-overview#batching-vs-streaming-ingestion) should this plugin use: batching or streaming?
- Does the Go SDK support both ingestion options?

**Comment by minwal** [comment]
@ssoroka @helenosheaa @Jagularr - Hi All, Can you please help me on the next steps for this request or connect me with the relevant folks? Looking for your feedback on following -
1. Influx requires to sign Contributor License Agreement (CLA). There is a segment where it mentions a Corporate CLA rather than Individual CLA - https://www.influxdata.com/legal/cla/  
Whom to contact to start this process?
2. I will be creating a PR for this plugin soon, is there a way to schedule sometime with this repo's maintainers/experts to review it together and brainstorm few scenarios?

**Comment by tomconte** [comment]
Hi @minwal, regarding 1. I have initiated the internal review process for the CLA. I will forward you the details in DM.

**Comment by minwal** [comment]
Thanks Thomas, please let me know if any action required from my side.
Is your team responsible for all Telegraf contributions integration from process perspective?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by helenosheaa** [comment]
Hi @minwal, 

Our typical process is if you are looking for feedback on ideas/implementation details you can post them on the InfluxDB Community slack channels #telegraf or #telegraf-dev. You can join this slack channel [here](https://influxdata.com/slack).

Then once you're ready with your PR, submit it and you'll get feedback/reviews from the community and engineers on the Telegraf team. There's also some info on the review process [here](https://github.com/influxdata/telegraf/blob/master/docs/developers/REVIEWS.md).

Thanks!

**Comment by minwal** [comment]
> Hi @minwal,
> 
> Our typical process is if you are looking for feedback on ideas/implementation details you can post them on the InfluxDB Community slack channels #telegraf or #telegraf-dev. You can join this slack channel [here](https://influxdata.com/slack).
> 
> Then once you're ready with your PR, submit it and you'll get feedback/reviews from the community and engineers on the Telegraf team. There's also some info on the review process [here](https://github.com/influxdata/telegraf/blob/master/docs/developers/REVIEWS.md).
> 
> Thanks!

Thanks @helenosheaa! Posted question on slack channel, hoping to get a quick response from the community.

**Comment by sjwang90** [comment]
Questions from @minwal about writing the Telegraf ADX output

In the `Write` method, array of `telegraf.Metric` object is received so is there any implicit convention to group metrics into buckets/namespaces within the same inputter? e.g. I am testing ADX outputter with SQL inputter – there are ~900 metrics collected by SQL inputter that are bucketed into following namespaces depending on `database_type`

```
  ## database_type =  AzureSQLDB  by default collects the following queries

  ## - AzureSQLDBWaitStats

  ## - AzureSQLDBResourceStats

  ## - AzureSQLDBResourceGovernance

  ## - AzureSQLDBDatabaseIO

  ## - AzureSQLDBServerProperties

  ## - AzureSQLDBOsWaitstats

  ## - AzureSQLDBMemoryClerks

  ## - AzureSQLDBPerformanceCounters

  ## - AzureSQLDBRequests

  ## - AzureSQLDBSchedulers
```
from: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/sqlserver#configuration

 

This bucketing logic is very specific to SQL inputter, it is already implemented by Azure monitor outputter like this –

https://github.com/influxdata/telegraf/blob/da7f2c7a934b5dc763ab10c7db02fe65b201686e/plugins/outputs/azure_monitor/azure_monitor.go#L420

 

Looking for suggestions if there is a better and generic way that can work for any input plugin:
1. To group relevant metrics into specific buckets/namespaces so data can be persisted as single table for each namespace rather than a table for each metric
2. Also is there a way to identify data is being generated by which inputter?
