### ISSUE TITLE
Graphite serializer should support output templates

### ISSUE THREAD

**Issue by jipperinbham** [influxdata/telegraf#925]
Some inputs throw a lot of tags into the metric and the graphite serializer currently defaults to iterating over every single tag in the metric to build the name. It would be nice for it to also build the name from a list of tags.

**Comment by sparrc** [comment]
I'm going to change the name of the issue because this is something I've thought about before too, we should be able to support graphite _output_ templates in a similar way that we already support graphite _input_ templates.

**Comment by jipperinbham** [comment]
:+1: that would be quite nice, looking over the _input_ template it's quite a bit more complicated than the current graphite _serializer_

**Comment by sparrc** [comment]
yes, but I think the input needs to be quite a bit more complicated because it needs to deal with generic wildcards and mapping them into influx tag key/values. I think for output we just need to deal with explicit tag key names, and then maybe a single tag wildcard to tell it to write all the rest of the tags.

**Comment by jipperinbham** [comment]
just checked out #1001, nice work!
