### ISSUE TITLE
[Homebrew] Confirming 1.18.2 tarball as seeing SHA mismatch (perhaps due to early update?)

### ISSUE THREAD

**Issue by cho-m** [influxdata/telegraf#9260]
Similar to previous #2140, over at Homebrew, we are seeing a SHA mismatch in source tar for v1.18.2.
The `telegraf` formula update was done in Homebrew/homebrew-core#76216

For security reasons, we want to confirm the correctness of Tar and possible reason for SHA mismatch (e.g. was it perhaps due to same reason as previous issue of too early of an update on Homebrew side).

If we are able to confirm the current source tarball SHA is correct, then we can proceed to update the Formula and make sure all Homebrew users are running the actual official release.

It would be good to also confirm `telegraf` release process as Homebrew often checks the GitHub latest release. Let us know if we should instead be monitoring https://influxdata.com/downloads

---

Exact SHA mismatch we are seeing. Expected is what we used in last Homebrew formula update:
```
==> Downloading https://github.com/influxdata/telegraf/archive/v1.18.2.tar.gz
==> Downloading from https://codeload.github.com/influxdata/telegraf/tar.gz/v1.18.2
Error: SHA256 mismatch
Expected: e83eb358416322a0e434381e6a54e4b497b49583092ab3fa41597cde16ef8f69
  Actual: 19856eef5762c0740f3531d5c4d55e25d8a9de34278ee6e1dcef49dfd48942e1
    File: /Users/brew/Library/Caches/Homebrew/downloads/78fd202e3b15973eccc08ebff81e177a1361a8777c5a70f94e69dcb987ecd69b--telegraf-1.18.2.tar.gz
```

**Comment by reimda** [comment]
Hi @cho-m, when I built 1.18.2 there was a makefile bug that caused packages for a few platforms not to be built. I fixed the bug and retagged 1.18.2. This does appear to be the same situation as https://github.com/influxdata/telegraf/issues/2140, so the resolution again is for us not to retag after packages have been published. I'll update our release documentation to highlight this policy.

Having Homebrew monitor https://portal.influxdata.com/downloads/ would not have helped this time since we published there before we noticed the missing packages.

Sorry for the inconvenience, and thanks for your work packaging Telegraf on Homebrew!
