### ISSUE TITLE
[influx 2.0 output plugin] auto-create bucket if not already present in influx 2.0

### ISSUE THREAD

**Issue by RagHarnoor** [influxdata/telegraf#9301]
## Feature Request

We are using telegraf to write data to influx. The behavior of influxdb output plugin for influx v1.x creates the database specified it not already present. The same is not true of buckets in influx v2.0 

### Proposal: 
The buckets mentioned in the output plugin should be created if not created already 

### Current behavior:
The influx v2.0 bucket to which data should be written should already be present 

### Desired behavior:
If the bucket specified is not present, the bucket should be created and data to should be written to that bucket

### Use case: 
1. When moving from influx v1.x where telegraf creates databases if not present, telegraf taking care of creating buckets if not present provides parity 
2. When multiple database have to moved from influx 1.x to 2.x, the buckets would have to be created manually

**Comment by ssoroka** [comment]
would we have to know what retention policy to use? I think that's a property of the bucket.

**Comment by RagHarnoor** [comment]
It can be default autogen retention policy, like it is with databases in 1.x

**Comment by ssoroka** [comment]
This seems like it might cause some other problems with permissions etc. having many buckets is probably an anti-pattern that would make it difficult to do cross-bucket queries. This is something we could do, I'm just not sure it's the right thing to do for InfluxDB v2. I'm curious to know more about your use case.

**Comment by yorch** [comment]
@ssoroka I'm also looking for this feature as well and just came across this thread.

My current use case is that I have multiple inputs in the same telegraf config (ie: docker, system metrics, mqtt consumer), so I'm giving each of these category of sources it's own tag (`category=system`, `category=docker`, `category=mqtt`) and in the influx output, I'm using `category` tag for bucket selection. Would be ideal if these buckets can be driven by configuration instead of having to provision them in a separate step.

Maybe there is a better way to handle this use case?

Additionally, I'm looking to provision buckets based on some rules in MQTT topics. Specifically, I'm looking to create MQTT topics for each of my customers `customers/customer1/#`, and have telegraf subscribe to these topics `customers/#`, auto provision buckets for each of the customers and start sending the data. This way, each customer has full isolation on their data, and it facilitates the customer provision process.

Thank you!
