### ISSUE TITLE
inputs.tail: add an "use_sudo" parameter

### ISSUE THREAD

**Issue by hluaces** [influxdata/telegraf#9522]
### Proposal:

Add a `use_sudo` parameter to the `tail` input plugin.

### Current behavior:

The input does not have this option, so there's no builtin solution to work around permissions issues.

### Desired behavior:

Make telegraf prepend `sudo` to the command used by the input ( `tail -F --line=0`, according to the documentation) whenever the option `use_sudo` is `true`.

### Use case: 

I don't really know if this qualifies as a feature request or if it was talked about in the past, so I apologize if I've missed it.

In some third party environments you find logs with a ownership or permissions configuration that you can't change, as it is delivered and maintained by the vendor "as is".

An example below:

```bash
f: /usr/local/cpanel/logs/spamd_error_log
 dr-xr-xr-x root root  /
 drwxr-xr-x root root  usr
 drwxr-xr-x root root  local
 drwx--x--x root wheel cpanel
 drwx--x--x root root  logs
 -rw------- root root  spamd_error_log
```

As you can see, the actual log is only readable by `root`. The only way to work around this with an unprivileged Telegraf user is to change the actual permissions of the log (which could be deleted depending on how it rotates), create ACLs to make sure that it stays with the permissions that you need or some other system configurations.

This might prove to be tricky or difficult to maintain depending on the configuration provided by your vendor.

By allowing the tail input to run as an elevated user these situations could be worked around easier, as you'd simply configure the sudoers file to allow for such action. 

I think this is the same approach than the one that was undertaken on the [fail to ban input](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/fail2ban/README.md) that already has an `use_sudo` option.

**Comment by reimda** [comment]
The documentation mentions that the plugin acts like `tail -F --line=0` but it doesn't actually run the tail command. The tail functionality is all implemented in the telegraf binary. This makes it impossible to add privileges in the way you propose.

There are also security considerations when adding privileges. I think using ACLs like you mentioned would be a more secure solution. Since there's a secure workaround, I don't see a strong reason to add `use_sudo` even if it was easy.

I'm closing this but if I'm misunderstanding the feature request, feel free to reopen. Thanks!

**Comment by juanposio** [comment]
Very dangerous, however, you could add the telegraf user to the sudo group.
