### ISSUE TITLE
Parsing curl data massive

### ISSUE THREAD

**Issue by poisoh** [influxdata/telegraf#9689]
Hi!
Please, help.
root@influx:~# curl 'http://192.168.1.57:80/cgi-bin/data.cgi?cmd=current&id_first=0&id_last=27'
there is response from device:
0       0.000018
1       0.000004
2       0.102706
3       0.563257
4       35.892357
5       -inf
6       0.003367
7       42.520859
8       -0.000547
9       0.002846
10      0.000121
11      0.000595
12      0.001000
13      0.000418
14      -0.000189
15      0.481448
16      -0.000000
17      0.000000
18      0.000012
19      0.000335
20      0.035877
21      -inf
22      -0.000001
23      20.471596
24      10.929231
25      -4.654011
26      17.809999
27      38.400000
I need all 28 metrics insert in influxdb.
Now "input.http" input data to influxdb with last symbol "38.40"
How can i input all data in influxdb?

```
[[inputs.http]]
   urls = [
     "http://192.168.1.57:80/cgi-bin/data.cgi?cmd=current&id_first=0&id_last=27"
   ]
    method = "GET"
    timeout = "5s"
    data_format = "value"
    data_type = "float"
```

**Comment by srebhan** [comment]
@poisoh the problem is the following: You will add _all_ those 28 values with the same timestamp (i.e. now) and tags. (You can see this when trying with the `--test` option or by using a file output to e.g. stdout.) This means you have the same series (measurement, field names and tag set) **and** the same timestamp which means you will overwrite one entry in the influxdb 27 times and only the last value is visible afterwards.

Your options are the following:

1. Group those metrics to one measurement with 28 fields. This of course only works if the field set is fixed.
2. Modify the timestamp a bit for each measurement e.g. by adding a small milli-/nanosecond fraction to the timestamp. This only makes sense if the values are a timeseries and you do not rely on the _exact_ timestamp.
3. Distinguish the entries by tag e.g. add a tag `index` and fill it with the value of the first column of your example (i.e. the index). This only makes sense if the values represent different "things" at the same timestamp. **Caution** this might result in a high cardinality if the `index` can grow large.

All modifications can maybe be done by the plugin itself or you have to use the `starlark` processor.

Hope that helps?

**Comment by poisoh** [comment]
Thank you. Where i have to read about config input.http for my problem? Cause i didn't find about..

**Comment by srebhan** [comment]
Can you please post the output with your configuration and running telegraf with the `--test` option? This should print all collected metrics to the console... The reason is that I'm not sure if you can solve the problem at all, at least not if the _order_ of the values is important...
You can read about the plugins when navigating to the github page of that plugin, e.g. for [http](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http) and check the `README.md` file.

**Comment by poisoh** [comment]
Mini parser python and cron to start periodically..

`import requests
import mysql.connector

r = requests.get('http://192.168.0.0/currentinfo')

print(r.status_code)
print(r.text)
message =r.text
result = message.replace('\t', ' ')
result = result.replace('\n', ' ')
print(result)
result = result.rstrip ()
print(result)
b=result.split(" ")

mydb = mysql.connector.connect(
  host="127.0.0.1",
  user="py",
  password="py",
  database="grafana"
)

mycursor = mydb.cursor()

sql = "INSERT INTO paragraf (v1, v2, v3, v4, v5, v6, v7, v8, i1, i2, i3, i4, i5, i6, i7, i8, p1, p2, p3, p4, p5, p6, p7, p8, lt, ld, tamb, tdl)  VALUES (%s, %s, %s, %s, %s,%s, %s, %s, %s, %s,%s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
val = (b[1], b[3], b[5], b[7], b[9], b[11], b[13], b[15], b[17], b[19], b[21], b[23], b[25], b[27], b[29], b[31], b[33], b[35], b[37],b[39], b[41], b[43], b[45], b[47], b[49], b[51], b[53], b[57])
print(val)
mycursor.execute(sql, val)

mydb.commit()

print(mycursor.rowcount, "record inserted.")
`

**Comment by srebhan** [comment]
If so you have the generating side under your control, there is hope. The question is what metrics do you expect from the data-output shown above? Can you write it down for maybe the first 3-5 lines? So how do you want the resulting DB look like?
