### ISSUE TITLE
inputs.docker error with "source_tag"

### ISSUE THREAD

**Issue by elbowz** [influxdata/telegraf#9721]
### Relevant telegraf.conf:

```toml
# Set the source tag for the metrics to the container ID hostname, eg first 12 chars
 source_tag = false
```

### System info:

Telegraf run in a docker container with image 1.9 (v1.9.5)

### Steps to reproduce:

1. Start container with the telegraf.conf file

### Actual behavior:

throw error: 
```
[telegraf] Error running agent: Error parsing http://host:8086/api/v2/telegrafs/081858f2eef76000, line 249: field corresponding to `source_tag' is not defined in `*docker.Docker'
```

### Additional info:

I started using InfluxDB since two days, so I hope to haven't miss something.

p.s. `inputs.net` not appear in the `InfluxDB dashboard / Data / Source` (maybe because miss the README.md in the repo?)

**Thanks for this amazing tools!**

**Comment by sspaink** [comment]
Sorry its taken so long for you to get a response, but are you saying that you are using the version `v1.9.5` of Telegraf? Looking at the git logs the `source_tag` option was introduced in v1.13.0 (https://github.com/influxdata/telegraf/commit/a5294fde32ece53726cec33a68a7f0300f0199a5) if that is the Telegraf version you really should be using the latest whenever possible at the moment `v1.21.2` is what you want to be using. 

Closing because it seems updating your version is the solution, but feel free to re-open in case you think there is another issue.
