### ISSUE TITLE
Lightweight Telegraf

### ISSUE THREAD

**Issue by LucasVillarroelR** [influxdata/telegraf#9732]
Hello,
I am trying to compile Telegraf, with only the plugins needed for my project. Because in the case of compiling using all plugins, it would be too heavy to be deployed.
That's why I'm asking if there is a way to make Telegraf compile only the necessary plugins, to make it much lighter.
Thanks!

**Comment by sjwang90** [comment]
@LucasVillarroelR Just curious, what type of device are you trying to download that you're looking for a more lightweight version?

Take a look at the comment in this thread https://github.com/influxdata/telegraf/issues/9556#issuecomment-889402542 and it will give you insight on how to build telegraf with just the plugins you choose

**Comment by LucasVillarroelR** [comment]
I'm using a NanoPi NEO 4, and I'm looking for a lightweight version  because there are many devices on the network with a bandwith restriction.
I use this [repository](https://github.com/rawkode/bring-your-own-telegraf), and got an answer from the owner on how to add plugins other than input/output plugins.

**Comment by onexay** [comment]
While this issue is closed, I do see a need to *NOT* compile the plugins that are needed. I went about doing it by deleting the files and updating few files to remove the code from compilation that's not needed. The result was a 20M binary (statically linked). This is not the most optimal, scalable way to fix but I am thinking to attemp problem again using go build tags.
